CREATE OR REPLACE PROCEDURE  SP_GEN_CONSOLIDAT_SMS_THREAD  is 
  LN_DUMMY NUMBER;
BEGIN    
   
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_CONSOLIDATED_SMS(1,1,100 ); end;',instance=>1);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_CONSOLIDATED_SMS(1, 101,200); end;',instance=>1);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_CONSOLIDATED_SMS(1, 201,300); end;',instance=>1);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_CONSOLIDATED_SMS(1, 301,400); end;',instance=>1);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_CONSOLIDATED_SMS(1 ,401,500); end;',instance=>1);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_CONSOLIDATED_SMS(1, 501,600); end;',instance=>1);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_CONSOLIDATED_SMS(1, 601,700); end;',instance=>1);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_CONSOLIDATED_SMS(1, 701,800); end;',instance=>2);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_CONSOLIDATED_SMS(1, 801,900); end;',instance=>2);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_CONSOLIDATED_SMS(1, 901,1000); end;',instance=>2);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_CONSOLIDATED_SMS(1, 1001,1100); end;',instance=>2);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_CONSOLIDATED_SMS(1, 1101,1200); end;',instance=>2);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_CONSOLIDATED_SMS(1, 1201,1300); end;',instance=>2);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_CONSOLIDATED_SMS(1, 1301,1400); end;',instance=>2);
  commit;
END SP_GEN_CONSOLIDAT_SMS_THREAD;
/
