CREATE OR REPLACE PROCEDURE SP_DBA_SCRIPTS_EXECUTION_LOG
(
P_SCRIPTS_POINT VARCHAR2,
P_SCRIPTS_SQLCODE CLOB
)
IS
PRAGMA AUTONOMOUS_TRANSACTION;

BEGIN
     INSERT INTO DBA_SCRIPTS_LOG
                (SCRIPTS_POINT, SCRIPTS_SQLCODE, SCRIPTS_EXECUTION_TIME
                )
                VALUES
                (P_SCRIPTS_POINT, P_SCRIPTS_SQLCODE, SYSDATE
                );

    COMMIT;
END;
/
