CREATE OR REPLACE PROCEDURE SP_DATA_CLEAR_ACC
( P_TABLE_NAME IN VARCHAR2,
  P_COLUMN_NAME IN VARCHAR2)
IS
W_SQL_CREATE_TABLE VARCHAR2(3000);
W_SQL_INSERT_TABLE VARCHAR2(3000);
W_SQL_ERROR VARCHAR2(1000);
W_USER_NAME VARCHAR2(100);

BEGIN

W_USER_NAME:=FN_DBA_GET_USER;

W_SQL_CREATE_TABLE:= 'CREATE TABLE TEMP_USER.'||P_TABLE_NAME||' AS
SELECT '||P_TABLE_NAME||'.* FROM '||W_USER_NAME||'.'||P_TABLE_NAME||', '||W_USER_NAME||'.ACNTS,  BRANCH_LIST L
WHERE '||P_COLUMN_NAME||'=ACNTS_INTERNAL_ACNUM
AND ACNTS_ENTITY_NUM=1
AND  ACNTS_BRN_CODE=L.BRANCH_CODE';

EXECUTE IMMEDIATE W_SQL_CREATE_TABLE;

SP_DBA_SCRIPTS_EXECUTION_LOG('SP_DATA_CLEAR_ACC', W_SQL_CREATE_TABLE);

EXCEPTION
    WHEN OTHERS THEN
     W_SQL_ERROR:=SQLERRM;
	 DBMS_OUTPUT.PUT_LINE(P_TABLE_NAME || W_SQL_ERROR);
END;
/
