CREATE OR REPLACE PROCEDURE SP_GL_BAL_CORRECTION (P_BRN_CODE    NUMBER,
                                                  P_GL_CODE     VARCHAR2,
                                                  P_CURR_CODE   VARCHAR2)
IS
   V_YEAR_WISE_AC_DEBIT_SUM    NUMBER (18, 3) := 0;
   V_YEAR_WISE_AC_CREDIT_SUM   NUMBER (18, 3) := 0;
   V_YEAR_WISE_BC_DEBIT_SUM    NUMBER (18, 3) := 0;
   V_YEAR_WISE_BC_CREDIT_SUM   NUMBER (18, 3) := 0;

   V_TOTAL_AC_DEBIT_SUM        NUMBER (18, 3) := 0;
   V_TOTAL_AC_CREDIT_SUM       NUMBER (18, 3) := 0;
   V_TOTAL_BC_DEBIT_SUM        NUMBER (18, 3) := 0;
   V_TOTAL_BC_CREDIT_SUM       NUMBER (18, 3) := 0;

   V_SQL                    VARCHAR2 (1000);

   V_CBD                    DATE;
   V_ENTITY_NUM             NUMBER;
   V_CUR_FIN_YEAR           NUMBER;
BEGIN
   V_ENTITY_NUM := 1;
   V_CBD := PKG_PB_GLOBAL.FN_GET_CURR_BUS_DATE (V_ENTITY_NUM);
   V_CUR_FIN_YEAR := TO_NUMBER (TO_CHAR (V_CBD, 'YYYY'));

   FOR V_YEAR IN 2014 .. V_CUR_FIN_YEAR
   LOOP
      UPDATE GLBBAL
         SET GLBBAL_AC_OPNG_DB_SUM = V_TOTAL_AC_DEBIT_SUM,
             GLBBAL_AC_OPNG_CR_SUM = V_TOTAL_AC_CREDIT_SUM,
             GLBBAL_BC_OPNG_DB_SUM = V_TOTAL_BC_DEBIT_SUM,
             GLBBAL_BC_OPNG_CR_SUM = V_TOTAL_BC_CREDIT_SUM
       WHERE     GLBBAL_ENTITY_NUM = 1
             AND GLBBAL_BRANCH_CODE = P_BRN_CODE
             AND GLBBAL_GLACC_CODE = P_GL_CODE
             AND GLBBAL_YEAR = V_YEAR
             AND GLBBAL_CURR_CODE = P_CURR_CODE;

      BEGIN
         V_SQL :=
               'SELECT SUM(CASE WHEN TRAN_DB_CR_FLG = ''C'' THEN TRAN_AMOUNT ELSE 0 END) 
          AC_CREDIT_SUM,
       SUM(CASE WHEN TRAN_DB_CR_FLG = ''D'' THEN TRAN_AMOUNT ELSE 0 END)
          AC_DEBIT_SUM,
          SUM(CASE WHEN TRAN_DB_CR_FLG = ''C'' THEN TRAN_BASE_CURR_EQ_AMT ELSE 0 END) 
          BC_CREDIT_SUM,
       SUM(CASE WHEN TRAN_DB_CR_FLG = ''D'' THEN TRAN_BASE_CURR_EQ_AMT ELSE 0 END)
          BC_DEBIT_SUM
  FROM TRAN'
            || V_YEAR
            || '
 WHERE     TRAN_ENTITY_NUM = 1
       AND TRAN_ACING_BRN_CODE = ' || P_BRN_CODE || '
       AND TRAN_GLACC_CODE = ' || '''' || P_GL_CODE || '''' || '
       AND TRAN_CURR_CODE = ' || '''' || P_CURR_CODE || '''' || '
       AND TRAN_AUTH_BY IS NOT NULL ';

         EXECUTE IMMEDIATE V_SQL
            INTO V_YEAR_WISE_AC_CREDIT_SUM, V_YEAR_WISE_AC_DEBIT_SUM, V_YEAR_WISE_BC_CREDIT_SUM, V_YEAR_WISE_BC_DEBIT_SUM ;
      EXCEPTION
         WHEN NO_DATA_FOUND
         THEN
            V_YEAR_WISE_AC_CREDIT_SUM:= 0; 
            V_YEAR_WISE_AC_DEBIT_SUM:= 0;
            V_YEAR_WISE_BC_CREDIT_SUM := 0 ; 
            V_YEAR_WISE_BC_DEBIT_SUM := 0 ;
      END;

      V_YEAR_WISE_AC_CREDIT_SUM := NVL (V_YEAR_WISE_AC_CREDIT_SUM, 0);
      V_YEAR_WISE_AC_DEBIT_SUM := NVL (V_YEAR_WISE_AC_DEBIT_SUM, 0);
      V_YEAR_WISE_BC_CREDIT_SUM := NVL (V_YEAR_WISE_BC_CREDIT_SUM, 0);
      V_YEAR_WISE_BC_DEBIT_SUM := NVL (V_YEAR_WISE_BC_DEBIT_SUM, 0);

      /*
      GLBBAL_AC_OPNG_DB_SUM, GLBBAL_AC_OPNG_CR_SUM, GLBBAL_BC_OPNG_DB_SUM, GLBBAL_BC_OPNG_CR_SUM, --- Upto that year
      GLBBAL_AC_CUR_DB_SUM, GLBBAL_AC_CUR_CR_SUM, GLBBAL_BC_CUR_DB_SUM, GLBBAL_BC_CUR_CR_SUM -------- Current balance
      */
      V_TOTAL_AC_DEBIT_SUM := V_TOTAL_AC_DEBIT_SUM + V_YEAR_WISE_AC_DEBIT_SUM;
      V_TOTAL_AC_CREDIT_SUM := V_TOTAL_AC_CREDIT_SUM + V_YEAR_WISE_AC_CREDIT_SUM;
      
      V_TOTAL_BC_DEBIT_SUM := V_TOTAL_BC_DEBIT_SUM + V_YEAR_WISE_BC_DEBIT_SUM;
      V_TOTAL_BC_CREDIT_SUM := V_TOTAL_BC_CREDIT_SUM + V_YEAR_WISE_BC_CREDIT_SUM;

      V_YEAR_WISE_AC_CREDIT_SUM := 0;
      V_YEAR_WISE_AC_DEBIT_SUM := 0;
      V_YEAR_WISE_BC_CREDIT_SUM := 0;
      V_YEAR_WISE_BC_DEBIT_SUM := 0;

      UPDATE GLBBAL
         SET GLBBAL_AC_CUR_DB_SUM = V_TOTAL_AC_DEBIT_SUM,
             GLBBAL_AC_CUR_CR_SUM = V_TOTAL_AC_CREDIT_SUM,
             GLBBAL_BC_CUR_DB_SUM = V_TOTAL_BC_DEBIT_SUM,
             GLBBAL_BC_CUR_CR_SUM = V_TOTAL_BC_CREDIT_SUM,
             GLBBAL_AC_BAL = V_TOTAL_AC_CREDIT_SUM - V_TOTAL_AC_DEBIT_SUM ,
             GLBBAL_BC_BAL = V_TOTAL_BC_CREDIT_SUM - V_TOTAL_BC_DEBIT_SUM 
       WHERE     GLBBAL_ENTITY_NUM = 1
             AND GLBBAL_BRANCH_CODE = P_BRN_CODE
             AND GLBBAL_GLACC_CODE = P_GL_CODE
             AND GLBBAL_YEAR = V_YEAR
             AND GLBBAL_CURR_CODE = P_CURR_CODE;
   END LOOP;
END SP_GL_BAL_CORRECTION;
/




