CREATE OR REPLACE PROCEDURE SP_MIG_SEC_REG(P_ERR_MSG OUT VARCHAR2) IS

  V_ROW_NUM NUMBER;
  V_SQL     VARCHAR2(100);

BEGIN

  V_SQL := 'TRUNCATE TABLE MIG_SEC_REGIS';

  EXECUTE IMMEDIATE V_SQL;

  BEGIN
  
    INSERT INTO MIG_SEC_REGIS
      SELECT /*+PARALLEL(16) */ SECRCPT_ENTITY_NUM,
             SECRCPT_SECURITY_NUM,
             SECRCPT_CREATED_BY_BRN,
             SECRCPT_TAKING_CHRG_DATE,
             SECRCPT_CLIENT_NUM,
             SECRCPT_SEC_TYPE,
             SECRCPT_MODE_OF_SEC,
             SECRCPT_TYPE_OF_MORTGAGE,
             SECRCPT_MORTAGER_NAME,
             TO_DATE(SECRCPT_DATE_OF_MORTGAGE, 'DD-MM-YY'),
             SECRCPT_PLACE_OF_MORTGAGE,
             SECRCPT_PLEDGE_EXISTS,
             SECRCPT_PLEDGE_DATE,
             SECRCPT_CONFIRMATION_DATE,
             SECRCPT_CURR_CODE,
             SECRCPT_SEC_DESCN1,
             SECRCPT_SEC_DESCN2,
             SECRCPT_SEC_DESCN3,
             SECRCPT_SEC_DESCN4,
             SECRCPT_SEC_DESCN5,
             SECRCPT_MARGIN_PER,
             SECRCPT_VALUATION_DATE,
             SECRCPT_LIEN_CHGS_DATE,
             SECRCPT_TAX_PAID_UPTO,
             SECRCPT_INSURANCE_REQD,
             SECRCPT_INSURANCE_BY,
             SECRCPT_VALUE_OF_SECURITY,
             SECRCPT_SECURED_VALUE,
             SECRCPT_NUM_OF_CHGS,
             SECRCPT_OUR_PRIORITY_CHGS,
             SECRCPT_TYPE_OF_PROPERTY,
             SECRCPT_ELIGFIN_COLLATERAL,
             SECRCPT_ELIG_CASH_COLLATERAL,
             SECRCPT_CLAIM_CATG,
             SECRCPT_CLAIM_SUB_CATG,
             SECRCPT_REM1,
             SECRCPT_REM2,
             SECRCPT_REM3,
             SECRCPT_REM4,
             SECRCPT_REM5,
             SECRCPT_RELEASED_ON,
             SECRCPT_DETAILS_ENTD,
             SECRCPT_ENTD_BY,
             SECRCPT_ENTD_ON,
             SECRCPT_LAST_MOD_BY,
             SECRCPT_LAST_MOD_ON,
             SECRCPT_AUTH_BY,
             SECRCPT_AUTH_ON,
             SECRCPT_REJ_BY,
             SECRCPT_REJ_ON,
             SECRCPT_UNIQ_ID
        FROM MIG_SEC_REGIS_temp;
    COMMIT;
  BEGIN
    DBMS_STATS.GATHER_TABLE_STATS(USER, 'MIG_SEC_REGIS');
    DBMS_STATS.GATHER_TABLE_STATS(USER, 'TEMP_CLIENT');
  END;
  END;

  EXECUTE IMMEDIATE 'TRUNCATE TABLE SECNUM';

  INSERT INTO SECNUM
    SELECT SECRCPT.SECRCPT_CLIENT_NUM FROM SECRCPT;

  SELECT MIG_LAST_SECURITY_NUM + 1 INTO V_ROW_NUM FROM MIG_SECRCPTNUM;

  BEGIN
  
    INSERT INTO SECRCPT
      SELECT /*+PARALLEL(16) */ 1 SECRCPT_ENTITY_NUM,
             v_row_num + ROWNUM SECRCPT_SECURITY_NUM,
             S.SECRCPT_CREATED_BY_BRN SECRCPT_CREATED_BY_BRN,
             S.SECRCPT_TAKING_CHRG_DATE SECRCPT_TAKING_CHRG_DATE,
             T.NEW_CLCODE SECRCPT_CLIENT_NUM,
             S.SECRCPT_SEC_TYPE SECRCPT_SEC_TYPE,
             S.SECRCPT_MODE_OF_SEC SECRCPT_MODE_OF_SEC,
             S.SECRCPT_TYPE_OF_MORTGAGE SECRCPT_TYPE_OF_MORTGAGE,
             S.SECRCPT_MORTAGER_NAME SECRCPT_MORTAGER_NAME,
             S.SECRCPT_DATE_OF_MORTGAGE SECRCPT_DATE_OF_MORTGAGE,
             S.SECRCPT_PLACE_OF_MORTGAGE SECRCPT_PLACE_OF_MORTGAGE,
             S.SECRCPT_PLEDGE_EXISTS SECRCPT_PLEDGE_EXISTS,
             S.SECRCPT_PLEDGE_DATE SECRCPT_PLEDGE_DATE,
             S.SECRCPT_CONFIRMATION_DATE SECRCPT_CONFIRMATION_DATE,
             S.SECRCPT_CURR_CODE SECRCPT_CURR_CODE,
             S.SECRCPT_SEC_DESCN1 SECRCPT_SEC_DESCN1,
             S.SECRCPT_SEC_DESCN2 SECRCPT_SEC_DESCN2,
             S.SECRCPT_SEC_DESCN3 SECRCPT_SEC_DESCN3,
             S.SECRCPT_SEC_DESCN4 SECRCPT_SEC_DESCN4,
             S.SECRCPT_SEC_DESCN5 SECRCPT_SEC_DESCN5,
             S.SECRCPT_MARGIN_PER SECRCPT_MARGIN_PER,
             S.SECRCPT_VALUATION_DATE SECRCPT_VALUATION_DATE,
             S.SECRCPT_LIEN_CHGS_DATE SECRCPT_LIEN_CHGS_DATE,
             S.SECRCPT_TAX_PAID_UPTO SECRCPT_TAX_PAID_UPTO,
             S.SECRCPT_INSURANCE_REQD SECRCPT_INSURANCE_REQD,
             S.SECRCPT_INSURANCE_BY SECRCPT_INSURANCE_BY,
             S.SECRCPT_VALUE_OF_SECURITY SECRCPT_VALUE_OF_SECURITY,
             S.SECRCPT_SECURED_VALUE SECRCPT_SECURED_VALUE,
             S.SECRCPT_NUM_OF_CHGS SECRCPT_NUM_OF_CHGS,
             S.SECRCPT_OUR_PRIORITY_CHGS SECRCPT_OUR_PRIORITY_CHGS,
             S.SECRCPT_TYPE_OF_PROPERTY SECRCPT_TYPE_OF_PROPERTY,
             S.SECRCPT_ELIGFIN_COLLATERAL SECRCPT_ELIGFIN_COLLATERAL,
             S.SECRCPT_ELIG_CASH_COLLATERAL SECRCPT_ELIG_CASH_COLLATERAL,
             S.SECRCPT_CLAIM_CATG SECRCPT_CLAIM_CATG,
             S.SECRCPT_CLAIM_SUB_CATG SECRCPT_CLAIM_SUB_CATG,
             S.SECRCPT_REM1 SECRCPT_REM1,
             S.SECRCPT_REM2 SECRCPT_REM2,
             S.SECRCPT_REM3 SECRCPT_REM3,
             S.SECRCPT_REM4 SECRCPT_REM4,
             S.SECRCPT_REM5 SECRCPT_REM5,
             S.SECRCPT_RELEASED_ON SECRCPT_RELEASED_ON,
             S.SECRCPT_DETAILS_ENTD SECRCPT_DETAILS_ENTD,
             'MIG' SECRCPT_ENTD_BY,
             SYSDATE SECRCPT_ENTD_ON,
             NULL SECRCPT_LAST_MOD_BY,
             NULL SECRCPT_LAST_MOD_ON,
             'MIG' SECRCPT_AUTH_BY,
             SYSDATE SECRCPT_AUTH_ON,
             NULL SECRCPT_REJ_BY,
             NULL SECRCPT_REJ_ON,
             'MIG_SECREG' || T.NEW_CLCODE SECRCPT_UNIQ_ID
        FROM MIG_SEC_REGIS S, TEMP_CLIENT T
       WHERE S.SECRCPT_CLIENT_NUM = T.OLD_CLCODE
         AND S.SECRCPT_CREATED_BY_BRN = T.BRN_CODE
         AND T.NEW_CLCODE NOT IN (SELECT SEC_NO FROM SECNUM);
  
    COMMIT;
    
  BEGIN
    DBMS_STATS.GATHER_TABLE_STATS(USER, 'SECRCPT');
  END;
  
  END;

  BEGIN
  
    INSERT INTO SECASSIGNMTBAL
      SELECT /*+PARALLEL(16) */ 1 SECAGMTBAL_ENTITY_NUM,
             SS.SECRCPT_SECURITY_NUM SECAGMTBAL_SEC_NUM,
             T.NEW_CLCODE SECAGMTBAL_CLIENT_NUM,
             1 SECAGMTBAL_LIMIT_LINE_NUM,
             100 SECAGMTBAL_ASSIGN_PERC,
             SUM(S.SECRCPT_SECURED_VALUE) SECAGMTBAL_ASSIGN_AMT,
             'P' SECAGMTBAL_SEC_NATURE
        FROM MIG_SEC_REGIS S, TEMP_CLIENT T, SECRCPT SS
       WHERE S.SECRCPT_CREATED_BY_BRN = T.BRN_CODE
         AND S.SECRCPT_CLIENT_NUM = T.OLD_CLCODE
         AND SS.SECRCPT_CLIENT_NUM = T.NEW_CLCODE
         AND T.NEW_CLCODE NOT IN (SELECT SECNUM.SEC_NO FROM SECNUM)
       GROUP BY T.NEW_CLCODE, SS.SECRCPT_SECURITY_NUM;
    COMMIT;
  END;

  BEGIN
    INSERT INTO SECVAL
      SELECT /*+PARALLEL(16) */ 1 SECVAL_ENTITY_NUM,
             SS.SECRCPT_SECURITY_NUM SECVAL_SECURITY_NUM,
             S.SECRCPT_TAKING_CHRG_DATE SECVAL_EFF_DATE,
             S.SECRCPT_TAKING_CHRG_DATE SECVAL_ENTRY_DATE,
             'BDT' SECVAL_CURR_CODE,
             S.SECRCPT_VALUE_OF_SECURITY SECVAL_SECURED_VALUE,
             'MIG' SECVAL_VALUATION_BY,
             S.SECRCPT_TAKING_CHRG_DATE SECVAL_VALUATION_DATE,
             'MIG' SECVAL_REM1,
             'CLIENT ' || T.NEW_CLCODE SECVAL_REM2,
             'SEC TYPE ' || S.SECRCPT_SEC_TYPE SECVAL_REM3,
             'MIGS' SECVAL_ENTD_BY,
             SYSDATE SECVAL_ENTD_ON,
             NULL SECVAL_LAST_MOD_BY,
             NULL SECVAL_LAST_MOD_ON,
             'MIGS' SECVAL_AUTH_BY,
             SYSDATE SECVAL_AUTH_ON,
             NULL SECVAL_REJ_BY,
             NULL SECVAL_REJ_ON
        FROM MIG_SEC_REGIS S, TEMP_CLIENT T, SECRCPT SS
       WHERE S.SECRCPT_CLIENT_NUM = T.OLD_CLCODE
         AND S.SECRCPT_CREATED_BY_BRN = T.BRN_CODE
         AND SS.SECRCPT_CLIENT_NUM = T.NEW_CLCODE
         AND T.NEW_CLCODE NOT IN (SELECT SECNUM.SEC_NO FROM SECNUM);
    COMMIT;
  END;

  BEGIN
    INSERT INTO SECCLIENT
      SELECT /*+PARALLEL(16) */ 1                       SECCLIENT_ENTITY_NUM,
             SS.SECRCPT_SECURITY_NUM SECCLIENT_SECURITY_NUM,
             1                       SECCLIENT_CLIENT_SL,
             T.NEW_CLCODE            SECCLIENT_CLIENT_NUM
        FROM TEMP_CLIENT T, SECRCPT SS
       WHERE SS.SECRCPT_CLIENT_NUM = T.NEW_CLCODE
         AND T.NEW_CLCODE NOT IN (SELECT SECNUM.SEC_NO FROM SECNUM);
    COMMIT;
  END;

  UPDATE MIG_SECRCPTNUM S
     SET S.MIG_LAST_SECURITY_NUM =
         (SELECT MAX(SECRCPT.SECRCPT_SECURITY_NUM) FROM SECRCPT);

  COMMIT;
  EXCEPTION WHEN OTHERS THEN 
  P_ERR_MSG:=SQLERRM;

END;
/
