CREATE OR REPLACE PROCEDURE SP_TRAN_BRANCH_CLEAR
( P_TABLE_NAME IN VARCHAR2)
IS
W_SQL_CREATE_TABLE VARCHAR2(3000);
W_SQL_INSERT_TABLE VARCHAR2(3000);
W_SQL_ERROR VARCHAR2(1000);
W_USER_NAME VARCHAR2(100);

BEGIN

W_USER_NAME:=FN_DBA_GET_USER;

W_SQL_CREATE_TABLE:='CREATE TABLE TEMP_USER.'||P_TABLE_NAME||' AS
                    SELECT T.* FROM '||W_USER_NAME||'.'||P_TABLE_NAME||' T, BRANCH_LIST L
                    WHERE T.TRAN_BRN_CODE = L.BRANCH_CODE';

EXECUTE IMMEDIATE W_SQL_CREATE_TABLE;

SP_DBA_SCRIPTS_EXECUTION_LOG('SP_TRAN_BRANCH_CLEAR', W_SQL_CREATE_TABLE);


W_SQL_CREATE_TABLE:='INSERT INTO TEMP_USER.'||P_TABLE_NAME||'
                    SELECT T.* FROM '||W_USER_NAME||'.'||P_TABLE_NAME||' T, BRANCH_LIST L
                    WHERE T.TRAN_ACING_BRN_CODE = L.BRANCH_CODE
                    AND T.TRAN_BRN_CODE <> L.BRANCH_CODE';

EXECUTE IMMEDIATE W_SQL_CREATE_TABLE;

SP_DBA_SCRIPTS_EXECUTION_LOG('SP_TRAN_BRANCH_CLEAR 2', W_SQL_CREATE_TABLE);


EXECUTE IMMEDIATE 'DELETE FROM TEMP_USER.'||P_TABLE_NAME||'
WHERE ROWID IN (SELECT DEL_ROW FROM(
SELECT TRAN_ENTITY_NUM, TRAN_BRN_CODE, TRAN_DATE_OF_TRAN, TRAN_BATCH_NUMBER, TRAN_BATCH_SL_NUM, MIN(ROWID) DEL_ROW
FROM TEMP_USER.'||P_TABLE_NAME||'
GROUP BY TRAN_ENTITY_NUM, TRAN_BRN_CODE, TRAN_DATE_OF_TRAN, TRAN_BATCH_NUMBER, TRAN_BATCH_SL_NUM
HAVING COUNT(*)>1))';

W_SQL_CREATE_TABLE:='CREATE TABLE TEMP_USER.'||REPLACE(P_TABLE_NAME,'TRAN','TRANBAT')||' AS
SELECT B.* FROM
(SELECT DISTINCT TRAN_ENTITY_NUM, TRAN_BRN_CODE, TRAN_DATE_OF_TRAN, TRAN_BATCH_NUMBER
FROM '||W_USER_NAME||'.'||P_TABLE_NAME||') T, '||W_USER_NAME||'.'||REPLACE(P_TABLE_NAME,'TRAN','TRANBAT')||' B
WHERE T.TRAN_ENTITY_NUM=B.TRANBAT_ENTITY_NUM
AND T.TRAN_BRN_CODE=B.TRANBAT_BRN_CODE
AND T.TRAN_DATE_OF_TRAN=B.TRANBAT_DATE_OF_TRAN
AND T.TRAN_BATCH_NUMBER=B.TRANBAT_BATCH_NUMBER';

EXECUTE IMMEDIATE W_SQL_CREATE_TABLE;

SP_DBA_SCRIPTS_EXECUTION_LOG('SP_TRAN_BRANCH_CLEAR 3', W_SQL_CREATE_TABLE);

COMMIT;

EXCEPTION
    WHEN OTHERS THEN
     W_SQL_ERROR:=SQLERRM;
	 DBMS_OUTPUT.PUT_LINE(P_TABLE_NAME || W_SQL_ERROR);
END;
/
