CREATE OR REPLACE FUNCTION FN_GET_MOBNUM(P_CLIENT_NUM IN NUMBER)
  RETURN VARCHAR2 IS
 
  W_SQL         VARCHAR2(1500);
  W_CLIENT_TYPE CLIENTS.CLIENTS_TYPE_FLG%TYPE;
  W_MOB         VARCHAR2(1000);
  W_CLIENT      NUMBER(12);
BEGIN
  W_SQL := 'SELECT CLIENTS_TYPE_FLG  FROM CLIENTS WHERE CLIENTS_CODE =:1';
  EXECUTE IMMEDIATE W_SQL
    INTO W_CLIENT_TYPE
    USING P_CLIENT_NUM;
  IF W_CLIENT_TYPE = 'I' THEN
  
    <<GETMOB>>
    BEGIN
      W_SQL := 'SELECT DECODE(TRIM(INDCLIENT_TEL_RES),
                       NULL,
                       DECODE(TRIM(INDCLIENT_TEL_GSM),NULL, ''-'', INDCLIENT_TEL_GSM),
                       DECODE(TRIM(INDCLIENT_TEL_GSM),NULL,INDCLIENT_TEL_RES,TRIM(INDCLIENT_TEL_GSM||'' / ''||INDCLIENT_TEL_RES)))
                FROM INDCLIENTS WHERE INDCLIENT_CODE=:1';
               
      EXECUTE IMMEDIATE W_SQL
        INTO W_MOB
        USING P_CLIENT_NUM;
    EXCEPTION
      WHEN OTHERS THEN
        W_MOB := ' ';
    END GETMOB;
  
  ELSIF W_CLIENT_TYPE = 'J' THEN
    W_SQL := 'SELECT  J.JNTCLDTL_INDIV_CLIENT_CODE FROM JOINTCLIENTSDTL J WHERE J.JNTCLDTL_CLIENT_CODE =:1 AND J.JNTCLDTL_DTL_SL =1';
    EXECUTE IMMEDIATE W_SQL
      INTO W_CLIENT
      USING P_CLIENT_NUM;
    SELECT FN_GET_MOBNUM(W_CLIENT) INTO W_MOB FROM DUAL;
  
  ELSE
    W_MOB := ' ';
  END IF;
  RETURN W_MOB;
END FN_GET_MOBNUM;
/
