CREATE OR REPLACE FUNCTION FN_GET_PIDWITHTYPE (
    P_CLIENT_NUM   IN NUMBER)
    RETURN VARCHAR2
IS
    W_PID           VARCHAR2 (100);
    W_INV           NUMBER (10);
    W_SQL           VARCHAR2 (500);
    W_CLIENT        NUMBER (12);
    W_CLIENT_TYPE   CLIENTS.CLIENTS_TYPE_FLG%TYPE;
BEGIN
    W_SQL := 'SELECT CLIENTS_TYPE_FLG  FROM CLIENTS WHERE CLIENTS_CODE =:1';

    EXECUTE IMMEDIATE W_SQL
        INTO W_CLIENT_TYPE
        USING P_CLIENT_NUM;

    W_PID := ' ';

    IF W_CLIENT_TYPE = 'I'
    THEN
        W_SQL :=
               'SELECT NVL(INDCLIENT_PID_INV_NUM,'
            || CHR (39)
            || 0
            || CHR (39)
            || ')  FROM INDCLIENTS WHERE INDCLIENT_CODE=:1';

        EXECUTE IMMEDIATE W_SQL
            INTO W_INV
            USING P_CLIENT_NUM;
    ELSIF W_CLIENT_TYPE = 'J'
    THEN
        W_SQL :=
            'SELECT  J.JNTCLDTL_INDIV_CLIENT_CODE FROM JOINTCLIENTSDTL J WHERE J.JNTCLDTL_CLIENT_CODE =:1 AND J.JNTCLDTL_DTL_SL =1';

        EXECUTE IMMEDIATE W_SQL
            INTO W_INV
            USING P_CLIENT_NUM;
    END IF;

    IF W_INV <> '0'
    THEN
          SELECT PIDDOCS_PID_TYPE || ' - ' || PIDDOCS_DOCID_NUM     AS PID
            INTO W_PID
            FROM PIDDOCS
           WHERE PIDDOCS_INV_NUM = W_INV AND ROWNUM = 1
        ORDER BY PIDDOCS_DOC_SL;
    END IF;

    RETURN W_PID;
EXCEPTION
    WHEN NO_DATA_FOUND
    THEN
        RETURN 0;
    WHEN OTHERS
    THEN
        RETURN 0;
END FN_GET_PIDWITHTYPE;
/
