CREATE OR REPLACE FUNCTION FN_GETINTRATE(V_ENTITY_NUM IN NUMBER,
                                         W_INT_AC_NO  NUMBER)
  RETURN VARCHAR2 IS

 

  W_PRODUCT_CODE              PRODUCTS.PRODUCT_CODE%TYPE;
  W_AC_TYPE                   ACNTS.ACNTS_AC_TYPE%TYPE;
  W_AC_SUB_TYPE               ACNTS.ACNTS_AC_SUB_TYPE%TYPE;
  W_CURR_CODE                 CURRENCY.CURR_CODE%TYPE;
  W_FACNO                     ACNTS.ACNTS_ACCOUNT_NUMBER%TYPE;
  W_BRNCODE                   MBRN.MBRN_CODE%TYPE;
  W_INTACCNUM                 ACNTS.ACNTS_INTERNAL_ACNUM%TYPE;
  W_LNPRD_INT_CHOICE          LNPRODPM.LNPRD_INT_CHOICE%TYPE;
  W_INTRATE                   LNPRODIR.LNPRODIR_APPL_INT_RATE%TYPE;
  W_LNPRODIR_CYCLE_NUM        LNPRODIR.LNPRODIR_CYCLE_NUM%TYPE;
  W_LNAPP_YEAR                LNAPPL.LNAPPL_YEAR%TYPE;
  W_LNAPP_SL_NO               LNAPPL.LNAPPL_SL_NUM%TYPE;
  W_SD_INT_RATE               NUMBER(8,5);
  W_PRIRBASIS_REFIRT_CODE     PRODIRBASIS.PRIRBASIS_REFIRT_CODE%TYPE;
  W_PRIRBASIS_DIFF_INT_RATE   PRODIRBASIS.PRIRBASIS_DIFF_INT_RATE%TYPE;
  W_ACC_DISB_DATE             ACNTS.ACNTS_OPENING_DATE%TYPE;
  W_ACC_OPEN_DATE             ACNTS.ACNTS_OPENING_DATE%TYPE;

BEGIN

  PKG_ENTITY.SP_SET_ENTITY_CODE(V_ENTITY_NUM);

  <<GETACNUMBER>>
  BEGIN
     W_INTRATE := '';
    IF W_INT_AC_NO IS NOT NULL THEN

      SELECT A.ACNTS_ACCOUNT_NUMBER,
             A.ACNTS_CURR_CODE,
             ACNTS_INTERNAL_ACNUM,
             ACNTS_BRN_CODE,
             ACNTS_PROD_CODE,
             ACNTS_AC_TYPE,
             ACNTS_AC_SUB_TYPE,
             LNAPPLAC_APPL_YEAR,
             LNAPPLAC_APPL_SL,
             LNAPPL_CYCLE_NO,LNACDISB_DISB_ON,ACNTS_OPENING_DATE
        INTO W_FACNO,
             W_CURR_CODE,
             W_INTACCNUM,
             W_BRNCODE,
             W_PRODUCT_CODE,
             W_AC_TYPE,
             W_AC_SUB_TYPE,
             W_LNAPP_YEAR,
             W_LNAPP_SL_NO,W_LNPRODIR_CYCLE_NUM,W_ACC_DISB_DATE,W_ACC_OPEN_DATE
        FROM ACNTS A, LNAPPLACNUM LA,LNAPPL,LNACDISB
       WHERE ACNTS_ENTITY_NUM = PKG_ENTITY.FN_GET_ENTITY_CODE
         AND ACNTS_INTERNAL_ACNUM = W_INT_AC_NO
         AND LNACDISB_ENTITY_NUM=PKG_ENTITY.FN_GET_ENTITY_CODE
        AND LNACDISB_INTERNAL_ACNUM=ACNTS_INTERNAL_ACNUM
        AND LNACDISB_DISB_SL_NUM=(SELECT MAX(LD.LNACDISB_DISB_SL_NUM)FROM LNACDISB LD WHERE
        LD.LNACDISB_ENTITY_NUM=PKG_ENTITY.FN_GET_ENTITY_CODE
        AND LD.LNACDISB_INTERNAL_ACNUM=W_INT_AC_NO)
         AND LNAPPL_ENTITY_NUM=PKG_ENTITY.FN_GET_ENTITY_CODE
        AND LNAPPL_YEAR=LNAPPLAC_APPL_YEAR
        AND LNAPPL_SL_NUM=LNAPPLAC_APPL_SL
         AND LNAPPLAC_ENTITY_NUM = PKG_ENTITY.FN_GET_ENTITY_CODE
         AND LNAPPLAC_INTERNAL_AC_NUM = ACNTS_INTERNAL_ACNUM;

    IF W_ACC_DISB_DATE IS NULL THEN
    W_ACC_DISB_DATE :=W_ACC_OPEN_DATE;
    END IF;
      <<INTERESTCHOICE>>
      BEGIN
        SELECT LP.lnprd_int_choice
          INTO W_LNPRD_INT_CHOICE
          FROM LNPRODPM LP
         WHERE LP.LNPRD_PROD_CODE = W_PRODUCT_CODE;
      EXCEPTION
        WHEN NO_DATA_FOUND THEN
          W_INTRATE := '';
      END INTERESTCHOICE;

      IF W_LNPRD_INT_CHOICE IS NOT NULL THEN

        IF W_LNPRD_INT_CHOICE = '1' THEN

          BEGIN
            SELECT LNPRODIRH_APPL_INT_RATE
              INTO W_INTRATE
              FROM LNPRODIRHIST
             WHERE LNPRODIRH_ENTITY_NUM= PKG_ENTITY.FN_GET_ENTITY_CODE
               AND LNPRODIRH_PROD_CODE = W_PRODUCT_CODE
               AND LNPRODIRH_CURR_CODE = W_CURR_CODE
               AND LNPRODIRH_AC_TYPE = W_AC_TYPE
               AND LNPRODIRH_AC_SUB_TYPE = W_AC_SUB_TYPE
               AND LNPRODIRH_CYCLE_NUM = W_LNPRODIR_CYCLE_NUM
               AND LNPRODIRH_EFF_DATE =(
              SELECT MAX(LNPRODIRH_EFF_DATE)
              FROM LNPRODIRHIST
             WHERE LNPRODIRH_ENTITY_NUM= PKG_ENTITY.FN_GET_ENTITY_CODE
               AND LNPRODIRH_PROD_CODE = W_PRODUCT_CODE
               AND LNPRODIRH_CURR_CODE = W_CURR_CODE
               AND LNPRODIRH_AC_TYPE = W_AC_TYPE
               AND LNPRODIRH_AC_SUB_TYPE = W_AC_SUB_TYPE
               AND LNPRODIRH_CYCLE_NUM = W_LNPRODIR_CYCLE_NUM
               AND LNPRODIRH_EFF_DATE <=W_ACC_DISB_DATE) ;

          EXCEPTION
            WHEN NO_DATA_FOUND THEN

             BEGIN
              SELECT LNPRODIRH_APPL_INT_RATE
                INTO W_INTRATE
                FROM LNPRODIRHIST
               WHERE LNPRODIRH_ENTITY_NUM= PKG_ENTITY.FN_GET_ENTITY_CODE
               AND LNPRODIRH_PROD_CODE = W_PRODUCT_CODE
                 AND LNPRODIRH_CURR_CODE = W_CURR_CODE
                 AND LNPRODIRH_AC_TYPE = ' '
                 AND LNPRODIRH_AC_SUB_TYPE = 0
                 AND LNPRODIRH_CYCLE_NUM = W_LNPRODIR_CYCLE_NUM
                  AND LNPRODIRH_EFF_DATE =(
              SELECT MAX(LNPRODIRH_EFF_DATE)
              FROM LNPRODIRHIST
             WHERE LNPRODIRH_ENTITY_NUM= PKG_ENTITY.FN_GET_ENTITY_CODE
               AND LNPRODIRH_PROD_CODE = W_PRODUCT_CODE
               AND LNPRODIRH_CURR_CODE = W_CURR_CODE
               AND LNPRODIRH_AC_TYPE = ' '
               AND LNPRODIRH_AC_SUB_TYPE = 0
               AND LNPRODIRH_CYCLE_NUM = W_LNPRODIR_CYCLE_NUM
               AND LNPRODIRH_EFF_DATE <=W_ACC_DISB_DATE) ;

            EXCEPTION
              WHEN NO_DATA_FOUND THEN
                BEGIN
                  SELECT PRIRBASH_REFIRT_CODE,PRIRBASH_DIFF_INT_RATE
                  INTO W_PRIRBASIS_REFIRT_CODE, w_prirbasis_diff_int_rate
                  FROM PRODIRBASISHIST WHERE  PRIRBASH_ENTITY_NUM =PKG_ENTITY.FN_GET_ENTITY_CODE
                  AND  PRIRBASH_PROD_CODE=W_PRODUCT_CODE
                  AND PRIRBASH_CURR_CODE=W_CURR_CODE
                  AND PRIRBASH_AC_TYPE=W_AC_TYPE
                  AND  PRIRBASH_AC_SUB_TYPE=W_AC_SUB_TYPE
                  AND PRIRBASH_CLSEG_CODE =W_LNPRODIR_CYCLE_NUM
                  AND PRIRBASH_EFF_DATE=(
                   SELECT MAX( PRIRBASH_EFF_DATE)
                  FROM PRODIRBASISHIST WHERE  PRIRBASH_ENTITY_NUM =PKG_ENTITY.FN_GET_ENTITY_CODE
                  AND  PRIRBASH_PROD_CODE=W_PRODUCT_CODE
                  AND PRIRBASH_CURR_CODE=W_CURR_CODE
                  AND PRIRBASH_AC_TYPE=W_AC_TYPE
                  AND  PRIRBASH_AC_SUB_TYPE=W_AC_SUB_TYPE
                  AND PRIRBASH_CYCLE_NUM =W_LNPRODIR_CYCLE_NUM
                  AND PRIRBASH_EFF_DATE <=W_ACC_DISB_DATE);

                  BEGIN

                    SELECT STDIRH_INT_RATE INTO W_SD_INT_RATE
                    FROM STDIRHIST WHERE STDIRH_ENTITY_NUM =PKG_ENTITY.FN_GET_ENTITY_CODE
                    AND  STDIRH_INT_RATE_TYPE=W_PRIRBASIS_REFIRT_CODE
                    AND STDIRH_CURR_CODE=W_CURR_CODE
                    AND STDIRH_EFF_DATE=
                    (SELECT MAX(STDIRH_EFF_DATE)
                    FROM STDIRHIST WHERE STDIRH_ENTITY_NUM =PKG_ENTITY.FN_GET_ENTITY_CODE
                    AND  STDIRH_INT_RATE_TYPE=W_PRIRBASIS_REFIRT_CODE
                    AND STDIRH_CURR_CODE=W_CURR_CODE
                    AND STDIRH_EFF_DATE<= W_ACC_DISB_DATE
                    );

                    W_INTRATE:=W_SD_INT_RATE+w_prirbasis_diff_int_rate;
                  EXCEPTION
                  WHEN NO_DATA_FOUND THEN
                    W_INTRATE := '0';
                  END;

              EXCEPTION
                WHEN NO_DATA_FOUND THEN
                  BEGIN
                  SELECT PRIRBASH_REFIRT_CODE,PRIRBASH_DIFF_INT_RATE
                  INTO W_PRIRBASIS_REFIRT_CODE, w_prirbasis_diff_int_rate
                  FROM PRODIRBASISHIST WHERE  PRIRBASH_ENTITY_NUM =PKG_ENTITY.FN_GET_ENTITY_CODE
                  AND  PRIRBASH_PROD_CODE=W_PRODUCT_CODE
                  AND PRIRBASH_CURR_CODE=W_CURR_CODE
                  AND PRIRBASH_AC_TYPE=' '
                  AND  PRIRBASH_AC_SUB_TYPE=0
                  AND PRIRBASH_CYCLE_NUM =W_LNPRODIR_CYCLE_NUM
                   AND PRIRBASH_EFF_DATE=(
                   SELECT MAX( PRIRBASH_EFF_DATE)
                  FROM PRODIRBASISHIST WHERE  PRIRBASH_ENTITY_NUM =PKG_ENTITY.FN_GET_ENTITY_CODE
                  AND  PRIRBASH_PROD_CODE=W_PRODUCT_CODE
                  AND PRIRBASH_CURR_CODE=W_CURR_CODE
                  AND PRIRBASH_AC_TYPE=' '
                  AND  PRIRBASH_AC_SUB_TYPE=0
                  AND PRIRBASH_CYCLE_NUM =W_LNPRODIR_CYCLE_NUM
                  AND PRIRBASH_EFF_DATE <=W_ACC_DISB_DATE);

                  BEGIN

                   SELECT STDIRH_INT_RATE INTO W_SD_INT_RATE
                    FROM STDIRHIST WHERE STDIRH_ENTITY_NUM =PKG_ENTITY.FN_GET_ENTITY_CODE
                    AND  STDIRH_INT_RATE_TYPE=W_PRIRBASIS_REFIRT_CODE
                    AND STDIRH_CURR_CODE=W_CURR_CODE
                    AND STDIRH_EFF_DATE=
                    (SELECT MAX(STDIRH_EFF_DATE)
                    FROM STDIRHIST WHERE STDIRH_ENTITY_NUM =PKG_ENTITY.FN_GET_ENTITY_CODE
                    AND  STDIRH_INT_RATE_TYPE=W_PRIRBASIS_REFIRT_CODE
                    AND STDIRH_CURR_CODE=W_CURR_CODE
                    AND STDIRH_EFF_DATE<= W_ACC_DISB_DATE
                    );

                    W_INTRATE:=W_SD_INT_RATE+w_prirbasis_diff_int_rate;
                  EXCEPTION
                  WHEN NO_DATA_FOUND THEN
                    W_INTRATE := '0';
                  END;

              EXCEPTION
                WHEN NO_DATA_FOUND THEN
                  W_INTRATE := '0';
              END;
              END;

            END;
          END;



        ELSIF W_LNPRD_INT_CHOICE = '2' THEN
          BEGIN
                SELECT LNACIRH_APPL_INT_RATE
                INTO W_INTRATE
                FROM LNACIRHIST WHERE  LNACIRH_ENTITY_NUM =PKG_ENTITY.FN_GET_ENTITY_CODE
                AND  LNACIRH_INTERNAL_ACNUM=W_INT_AC_NO AND LNACIRH_EFF_DATE=
                ( SELECT MAX(LNACIRH_EFF_DATE)
                FROM LNACIRHIST WHERE  LNACIRH_ENTITY_NUM =PKG_ENTITY.FN_GET_ENTITY_CODE
                AND  LNACIRH_INTERNAL_ACNUM=W_INT_AC_NO
                AND LNACIRH_EFF_DATE=W_ACC_DISB_DATE);
          EXCEPTION
                WHEN NO_DATA_FOUND THEN
                  BEGIN
                  SELECT PRIRBASH_REFIRT_CODE,PRIRBASH_DIFF_INT_RATE
                  INTO W_PRIRBASIS_REFIRT_CODE, w_prirbasis_diff_int_rate
                  FROM PRODIRBASISHIST WHERE  PRIRBASH_ENTITY_NUM =PKG_ENTITY.FN_GET_ENTITY_CODE
                  AND  PRIRBASH_PROD_CODE=W_PRODUCT_CODE
                  AND PRIRBASH_CURR_CODE=W_CURR_CODE
                  AND PRIRBASH_AC_TYPE=W_AC_TYPE
                  AND  PRIRBASH_AC_SUB_TYPE=W_AC_SUB_TYPE
                  AND PRIRBASH_CYCLE_NUM =W_LNPRODIR_CYCLE_NUM
                   AND PRIRBASH_EFF_DATE=(
                   SELECT MAX( PRIRBASH_EFF_DATE)
                  FROM PRODIRBASISHIST WHERE  PRIRBASH_ENTITY_NUM =PKG_ENTITY.FN_GET_ENTITY_CODE
                  AND  PRIRBASH_PROD_CODE=W_PRODUCT_CODE
                  AND PRIRBASH_CURR_CODE=W_CURR_CODE
                  AND PRIRBASH_AC_TYPE=W_AC_TYPE
                  AND  PRIRBASH_AC_SUB_TYPE=W_AC_SUB_TYPE
                  AND PRIRBASH_CYCLE_NUM =W_LNPRODIR_CYCLE_NUM
                  AND PRIRBASH_EFF_DATE <=W_ACC_DISB_DATE);

                  BEGIN

                    SELECT STDIRH_INT_RATE INTO W_SD_INT_RATE
                    FROM STDIRHIST WHERE STDIRH_ENTITY_NUM =PKG_ENTITY.FN_GET_ENTITY_CODE
                    AND  STDIRH_INT_RATE_TYPE=W_PRIRBASIS_REFIRT_CODE
                    AND STDIRH_CURR_CODE=W_CURR_CODE
                    AND STDIRH_EFF_DATE=
                    (SELECT MAX(STDIRH_EFF_DATE)
                    FROM STDIRHIST WHERE STDIRH_ENTITY_NUM =PKG_ENTITY.FN_GET_ENTITY_CODE
                    AND  STDIRH_INT_RATE_TYPE=W_PRIRBASIS_REFIRT_CODE
                    AND STDIRH_CURR_CODE=W_CURR_CODE
                    AND STDIRH_EFF_DATE<= W_ACC_DISB_DATE
                    );

                    W_INTRATE:=W_SD_INT_RATE+w_prirbasis_diff_int_rate;
                  EXCEPTION
                  WHEN NO_DATA_FOUND THEN
                    W_INTRATE := '0';
                  END;

              EXCEPTION
                WHEN NO_DATA_FOUND THEN
                  BEGIN
                  SELECT PRIRBASH_REFIRT_CODE,PRIRBASH_DIFF_INT_RATE
                  INTO W_PRIRBASIS_REFIRT_CODE, w_prirbasis_diff_int_rate
                  FROM PRODIRBASISHIST WHERE  PRIRBASH_ENTITY_NUM =PKG_ENTITY.FN_GET_ENTITY_CODE
                  AND  PRIRBASH_PROD_CODE=W_PRODUCT_CODE
                  AND PRIRBASH_CURR_CODE=W_CURR_CODE AND PRIRBASH_AC_TYPE=' '
                  AND  PRIRBASH_AC_SUB_TYPE=0
                  AND PRIRBASH_CYCLE_NUM =W_LNPRODIR_CYCLE_NUM
                   AND PRIRBASH_EFF_DATE=(
                   SELECT MAX( PRIRBASH_EFF_DATE)
                  FROM PRODIRBASISHIST WHERE  PRIRBASH_ENTITY_NUM =PKG_ENTITY.FN_GET_ENTITY_CODE
                  AND  PRIRBASH_PROD_CODE=W_PRODUCT_CODE
                  AND PRIRBASH_CURR_CODE=W_CURR_CODE
                  AND PRIRBASH_AC_TYPE=' '
                  AND  PRIRBASH_AC_SUB_TYPE=0
                  AND PRIRBASH_CYCLE_NUM =W_LNPRODIR_CYCLE_NUM
                  AND PRIRBASH_EFF_DATE <=W_ACC_DISB_DATE);

                  BEGIN

                    SELECT STDIRH_INT_RATE INTO W_SD_INT_RATE
                    FROM STDIRHIST WHERE STDIRH_ENTITY_NUM =PKG_ENTITY.FN_GET_ENTITY_CODE
                    AND  STDIRH_INT_RATE_TYPE=W_PRIRBASIS_REFIRT_CODE
                    AND STDIRH_CURR_CODE=W_CURR_CODE
                    AND STDIRH_EFF_DATE=
                    (SELECT MAX(STDIRH_EFF_DATE)
                    FROM STDIRHIST WHERE STDIRH_ENTITY_NUM =PKG_ENTITY.FN_GET_ENTITY_CODE
                    AND  STDIRH_INT_RATE_TYPE=W_PRIRBASIS_REFIRT_CODE
                    AND STDIRH_CURR_CODE=W_CURR_CODE
                    AND STDIRH_EFF_DATE<= W_ACC_DISB_DATE
                    );

                    W_INTRATE:=W_SD_INT_RATE+w_prirbasis_diff_int_rate;
                  EXCEPTION
                  WHEN NO_DATA_FOUND THEN
                    W_INTRATE := '0';
                  END;

              EXCEPTION
                WHEN NO_DATA_FOUND THEN
                  W_INTRATE := '0';
              END;
              END;
          END;

        ELSIF W_LNPRD_INT_CHOICE = '3' THEN
          BEGIN
                SELECT LNACIRH_APPL_INT_RATE
                INTO W_INTRATE
                FROM LNACIRHIST WHERE  LNACIRH_ENTITY_NUM =PKG_ENTITY.FN_GET_ENTITY_CODE
                AND  LNACIRH_INTERNAL_ACNUM=W_INT_AC_NO
                AND LNACIRH_EFF_DATE=
                ( SELECT MAX(LNACIRH_EFF_DATE)
                FROM LNACIRHIST WHERE  LNACIRH_ENTITY_NUM =PKG_ENTITY.FN_GET_ENTITY_CODE
                AND  LNACIRH_INTERNAL_ACNUM=W_INT_AC_NO
                AND LNACIRH_EFF_DATE <= W_ACC_DISB_DATE);
          EXCEPTION
                WHEN NO_DATA_FOUND THEN
                  W_INTRATE := '0';
          END;

        END IF;
      END IF;
    END IF;

  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      W_INTRATE := '';
  END GETACNUMBER;
  RETURN W_INTRATE;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    RETURN W_INTRATE;
END FN_GETINTRATE;
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
/
