CREATE OR REPLACE FUNCTION FN_GET_SECTORTYPE (P_SECTOR VARCHAR2)
   RETURN VARCHAR2
IS
   V_RETURN_SECTYPE   VARCHAR2 (100);
   V_PARENT_SECTYPE   VARCHAR2 (100);
BEGIN
   IF P_SECTOR IN ('1', '2')
   THEN
      RETURN P_SECTOR;
   ELSE
      SELECT SEGMENTS_PARENT_SEC_CODE
        INTO V_PARENT_SECTYPE
        FROM SEGMENTS
       WHERE SEGMENTS_CODE = P_SECTOR;

      V_RETURN_SECTYPE := FN_GET_SECTORTYPE (V_PARENT_SECTYPE);
   END IF;

   RETURN V_RETURN_SECTYPE;
EXCEPTION
   WHEN OTHERS
   THEN
      RETURN NULL;
END FN_GET_SECTORTYPE;
/
