CREATE OR REPLACE FUNCTION FN_GET_SECTORCODE(P_ACC_NUMBER IN VARCHAR2)
  RETURN VARCHAR2 IS

  W_SQL            VARCHAR2(4000);
  W_SECTOR_CODE    CLIENTS.CLIENTS_SEGMENT_CODE%TYPE;
  V_SECTOR_CODE    CLIENTS.CLIENTS_SEGMENT_CODE%TYPE;

BEGIN
  W_SECTOR_CODE := '';
  V_SECTOR_CODE :='';

  W_SQL := 'SELECT CLIENTS_SEGMENT_CODE FROM CLIENTS WHERE CLIENTS_CODE = (SELECT ACNTS_CLIENT_NUM
            FROM ACNTS A WHERE A.ACNTS_ENTITY_NUM = 1 AND A.ACNTS_INTERNAL_ACNUM =:2)';

  EXECUTE IMMEDIATE W_SQL INTO V_SECTOR_CODE USING P_ACC_NUMBER;
  
  W_SECTOR_CODE := V_SECTOR_CODE;

  RETURN W_SECTOR_CODE;
END FN_GET_SECTORCODE;
/
