CREATE OR REPLACE FUNCTION FN_GET_RECOV_AMT(V_BRN_CODE IN NUMBER ,V_INERNAL_ACC_NUM IN NUMBER,W_ACNTS_CLIENT_NUM IN NUMBER ,W_LMTLINE_NUM  IN NUMBER)  
RETURN NUMBER IS
    V_PAYABLE_AMT NUMBER(18, 3);
    V_OS_BALANCE  NUMBER(18, 3);
    V_DISB_AMT    NUMBER(18, 3);
    V_INT_DB_MIG  NUMBER(18, 3);
    V_INT_DB_CBS  NUMBER(18, 3);
    V_CHG_DB_CBS  NUMBER(18, 3);
    V_RECOVERY_AMOUNT  NUMBER(18, 3);
    W_MIG_DATE DATE;
  BEGIN
    V_PAYABLE_AMT := 0;
    V_OS_BALANCE  := 0;
    V_DISB_AMT    := 0;
    V_INT_DB_MIG  := 0;
    V_INT_DB_CBS  := 0;
    V_CHG_DB_CBS  := 0;
    V_RECOVERY_AMOUNT  := 0;
    
    SELECT MIG_END_DATE INTO W_MIG_DATE FROM MIG_DETAIL 
    WHERE BRANCH_CODE = V_BRN_CODE; 
    

    SELECT ABS(SUM(LLACNTOS_LIMIT_CURR_DISB_MADE)),
           SUM(ACNTBAL_AC_BAL)
      INTO V_DISB_AMT, V_OS_BALANCE
      FROM LLACNTOS L, ACNTBAL A
     WHERE L.LLACNTOS_ENTITY_NUM = 1
       AND L.LLACNTOS_CLIENT_CODE = W_ACNTS_CLIENT_NUM
       AND L.LLACNTOS_LIMIT_LINE_NUM = W_LMTLINE_NUM
       AND L.LLACNTOS_CLIENT_ACNUM = V_INERNAL_ACC_NUM
       AND A.ACNTBAL_INTERNAL_ACNUM = L.LLACNTOS_CLIENT_ACNUM;


    SELECT SUM(NVL(L.LNTOTINTDB_TOT_INT_DB_AMT, 0))
      INTO V_INT_DB_MIG
      FROM LNTOTINTDBMIG L
     WHERE L.LNTOTINTDB_ENTITY_NUM = 1
       AND L.LNTOTINTDB_INTERNAL_ACNUM = V_INERNAL_ACC_NUM;

    IF V_INT_DB_MIG IS NULL THEN
      V_INT_DB_MIG := 0;
    END IF;

      SELECT SUM(M.TRANADV_INTRD_BC_AMT), SUM(M.TRANADV_CHARGE_BC_AMT)
        INTO V_INT_DB_CBS, V_CHG_DB_CBS
        FROM MV_LOAN_ACCOUNT_BAL_OD M
       WHERE M.TRAN_INTERNAL_ACNUM = V_INERNAL_ACC_NUM
         AND M.TRAN_DATE_OF_TRAN > W_MIG_DATE
         AND M.TRAN_DB_CR_FLG = 'D';

      IF V_INT_DB_CBS IS NULL THEN
        V_INT_DB_CBS := 0;
      END IF;

      IF V_CHG_DB_CBS IS NULL THEN
        V_CHG_DB_CBS := 0;
      END IF;

      V_RECOVERY_AMOUNT :=(ABS(NVL(V_DISB_AMT,0) + NVL(V_INT_DB_MIG,0) + ABS(V_INT_DB_CBS) + ABS(V_CHG_DB_CBS) - ABS(V_OS_BALANCE)));

      IF V_RECOVERY_AMOUNT < 0 THEN
        V_RECOVERY_AMOUNT := 0;
      END IF;

    RETURN CEIL(V_RECOVERY_AMOUNT);
  END FN_GET_RECOV_AMT;
/
