 SELECT AC.ACNTS_INTERNAL_ACNUM,
       AC.ACNTS_BRN_CODE,
       AC.ACNTS_CLIENT_NUM,
       CL.CLIENTS_TYPE_FLG,
       CL.CLIENTS_ADDR_INV_NUM,
       facno (ac.ACNTS_ENTITY_NUM, ac.ACNTS_INTERNAL_ACNUM),
       (AC.ACNTS_AC_NAME1 || AC.ACNTS_AC_NAME2) AC_NAME,
       PR.PRODUCT_NAME,
       PR.PRODUCT_FOR_DEPOSITS,
       PR.PRODUCT_FOR_LOANS,
       AC.ACNTS_AC_TYPE,
       AC.ACNTS_AC_SUB_TYPE,
       AC.ACNTS_PROD_CODE,
       AC.ACNTS_OPENING_DATE,
       (SELECT ACST.ACSUB_DESCN
          FROM ACSUBTYPES ACST
         WHERE     ACST.ACSUB_SUBTYPE_CODE = AC.ACNTS_AC_SUB_TYPE
               AND ACST.ACSUB_ACTYPE_CODE = AC.ACNTS_AC_TYPE)
          ACSUB_DESCN,
       CL.CLIENTS_PAN_GIR_NUM,
       CL.CLIENTS_VIN_NUM,
       (SELECT ADDR.ADDRDTLS_ADDR1 || ADDR.ADDRDTLS_ADDR2
          FROM ADDRDTLS ADDR
         WHERE     ADDR.ADDRDTLS_INV_NUM = CL.CLIENTS_ADDR_INV_NUM
               AND ADDR.ADDRDTLS_CURR_ADDR = 1)
          AS ADDR_PRESENT_ADDRESS,
       (SELECT ADDR.ADDRDTLS_ADDR1 || ADDR.ADDRDTLS_ADDR2
          FROM ADDRDTLS ADDR
         WHERE     ADDR.ADDRDTLS_INV_NUM = CL.CLIENTS_ADDR_INV_NUM
               AND ADDR.ADDRDTLS_PERM_ADDR = 1)
          AS ADDR_PERMANENT_ADDRESS,
       FN_GET_PID (AC.ACNTS_CLIENT_NUM) ACNTS_PID,
       FN_GET_MOBNUM (AC.ACNTS_CLIENT_NUM) ADDR_PHN_GSM,
       (SELECT TRIM (IND.INDCLIENT_EMAIL_ADDR1)
          FROM INDCLIENTS IND
         WHERE IND.INDCLIENT_CODE = CL.CLIENTS_CODE)
          IND_EMAIL,
       FN_GET_LNACNT_DURATION (ACASLLDTL_CLIENT_NUM,
                               ACASLLDTL_LIMIT_LINE_NUM)
          LNACNT_DURATION,
       (SELECT LMTLINE_LIMIT_EXPIRY_DATE
          FROM limitline L
         WHERE     L.LMTLINE_CLIENT_CODE = AL.ACASLLDTL_CLIENT_NUM
               AND L.LMTLINE_NUM = AL.ACASLLDTL_LIMIT_LINE_NUM
               AND LMTLINE_ENTITY_NUM = 1)
          EXP_DATE,
       (SELECT NVL (LMTLINE_SANCTION_AMT, 0)
          FROM limitline LL
         WHERE     LL.LMTLINE_CLIENT_CODE = AL.ACASLLDTL_CLIENT_NUM
               AND LL.LMTLINE_NUM = AL.ACASLLDTL_LIMIT_LINE_NUM
               AND LL.LMTLINE_ENTITY_NUM = :ENTITY_NUM),
       NULL MATURITY,
       FN_GET_DEPACNT_DURATION (:W_INTERNAL_ACNUM, :W_PROD_CD)
          AS DEPACNT_DURATION,
       PBD.PBDCONT_STD_INT_RATE AS DEP_PRD_INT_RATE,
       PBD.PBDCONT_CLOSURE_DATE AS DEP_PRD_CLOSURE,
       PBD.PBDCONT_BC_DEP_AMT AS PRINCIPAL_AMT,
       PBD.PBDCONT_MAT_DATE AS DEP_PRD_MATURITY
  FROM ACNTS AC,
       ACASLLDTL AL,
       CLIENTS CL,
       PRODUCTS PR,PBDCONTRACT PBD
 WHERE     AC.ACNTS_CLIENT_NUM = CL.CLIENTS_CODE
       AND AC.ACNTS_ENTITY_NUM = :ENTITY_NUM
        AND AC.ACNTS_PROD_CODE = PR.PRODUCT_CODE
       AND AC.ACNTS_INTERNAL_ACNUM = AL.ACASLLDTL_INTERNAL_ACNUM
       AND AC.ACNTS_INTERNAL_ACNUM=PBDCONT_DEP_AC_NUM