CREATE OR REPLACE PACKAGE PKG_DDPO_REPORT IS

    --author : Sabuj
   -- Created :10/12/2017
   --Purpose : DDPO report generate

  TYPE TY_DD IS RECORD(
          REMIT_DESCN VARCHAR2(50),
       ADVICE_DATE DATE,
       ISSUED_BRN NUMBER(6),
       DUP_INST_LEAF_NUM NUMBER(15),
       ADVICE_REC_DATE DATE,
       PAY_CAN_DUP_DATE DATE,
       DD_STATUS CHAR(1),
       REMIT_CODE VARCHAR2(6),
       INST_PFX VARCHAR2(6),
       DDPO_LEAF_NUM VARCHAR2(15) ,
       INST_CURRENCY VARCHAR2(3) ,
       INST_AMT NUMBER(15,3),
       BENEF_NAME1 VARCHAR2(100),
       INST_DATE DATE ,
       ADVICE_NO NUMBER(12));
   TYPE TY_DD_DTL IS TABLE OF TY_DD;

  TYPE TY_PO IS RECORD(
      ENTITY_NUM NUMBER(1),
       REMIT_DESCN VARCHAR2(50),
       ADVICE_DATE DATE,
       ISSUED_BRN NUMBER(6),
       DUP_INST_PFX   VARCHAR2(6),
       DUP_INST_LEAF_NUM NUMBER(15),
       ADVICE_REC_DATE DATE,
       PAY_CAN_DUP_DATE DATE,
       DD_STATUS CHAR(1),
       REMIT_CODE VARCHAR2(6),
       INST_PFX VARCHAR2(6),
       DDPO_LEAF_NUM VARCHAR2(15) ,
       INST_CURRENCY VARCHAR2(3) ,
       INST_AMT NUMBER(15,3),
       BENEF_NAME1 VARCHAR2(100),
       INST_DATE DATE ,
       ADVICE_NO NUMBER(12));
  TYPE TY_PO_DTL IS TABLE OF TY_PO;
  FUNCTION DD_DTL(P_ENTITYNUM  IN NUMBER,
                     P_REMIT_CODE   IN VARCHAR2,
                     P_BRANCH_CODE IN NUMBER,
                     P_ASON_DATE  IN DATE)
                     --RETURN VARCHAR2 ;
                     RETURN TY_DD_DTL
    PIPELINED;

  FUNCTION PO_DTL(P_ENTITYNUM  IN NUMBER,
                  P_REMIT_CODE   IN VARCHAR2,
                  P_BRANCH_CODE IN NUMBER,
                  P_ASON_DATE  IN DATE)
                  --RETURN VARCHAR2 ;
                  RETURN TY_PO_DTL
    PIPELINED;

END PKG_DDPO_REPORT;
/

CREATE OR REPLACE PACKAGE BODY PKG_DDPO_REPORT
IS
   TABLE1        PKG_DDPO_REPORT.TY_DD;
   TABLE2        PKG_DDPO_REPORT.TY_PO;
   W_SQL         VARCHAR2 (4000);

   TYPE R_DD_DTL IS RECORD
   (
      TP_REMIT_DESCN         VARCHAR2 (50),
      TP_ADVICE_DATE         DATE,
      TP_ISSUED_BRN          NUMBER (6),
      --TP_DUP_INST_PFX        VARCHAR2 (6),
      TP_DUP_INST_LEAF_NUM   NUMBER (15),
      TP_ADVICE_REC_DATE     DATE,
      TP_PAY_CAN_DUP_DATE    DATE,
      TP_DD_STATUS           CHAR (1),
      TP_REMIT_CODE          VARCHAR2 (6),
      TP_INST_PFX            VARCHAR2 (6),
      TP_DDPO_LEAF_NUM       VARCHAR2 (15),
      TP_INST_CURRENCY       VARCHAR2 (3),
      TP_INST_AMT            NUMBER (15, 3),
      TP_BENEF_NAME1         VARCHAR2 (100),
      TP_INST_DATE           DATE,
      TP_ADVICE_NO           NUMBER (12)
   );

   TYPE TTY_DD_DTL IS TABLE OF R_DD_DTL
      INDEX BY PLS_INTEGER;

   V_TY_DD_DTL   TTY_DD_DTL;

   TYPE R_PO_DTL IS RECORD
   (
      TM_ENTITY_NUM          NUMBER (1),
      TM_REMIT_DESCN         VARCHAR2 (50),
      TM_ADVICE_DATE         DATE,
      TM_ISSUED_BRN          NUMBER (6),
      TM_DUP_INST_PFX        VARCHAR2 (6),
      TM_DUP_INST_LEAF_NUM   NUMBER (15),
      TM_ADVICE_REC_DATE     DATE,
      TM_PAY_CAN_DUP_DATE    DATE,
      TM_DD_STATUS           CHAR (1),
      TM_REMIT_CODE          VARCHAR2 (6),
      TM_INST_PFX            VARCHAR2 (6),
      TM_DDPO_LEAF_NUM       VARCHAR2 (15),
      TM_INST_CURRENCY       VARCHAR2 (3),
      TM_INST_AMT            NUMBER (15, 3),
      TM_BENEF_NAME1         VARCHAR2 (100),
      TM_INST_DATE           DATE,
      TM_ADVICE_NO           NUMBER (12)
   );

   TYPE TTY_PO_DTL IS TABLE OF R_PO_DTL
      INDEX BY PLS_INTEGER;

   V_TY_PO_DTL   TTY_PO_DTL;


   FUNCTION DD_DTL (P_ENTITYNUM     IN NUMBER,
                    P_REMIT_CODE    IN VARCHAR2,
                    P_BRANCH_CODE   IN NUMBER,
                    P_ASON_DATE     IN DATE)
      RETURN TY_DD_DTL
      PIPELINED
      --RETURN VARCHAR2
   IS
      E_USEREXCEP   EXCEPTION;
      W_ERROR_MSG   VARCHAR2 (60);
   BEGIN
   --PKG_ENTITY.SP_SET_ENTITY_CODE(P_ENTITYNUM);
      W_SQL :=
         'SELECT REMCD_REMIT_DESCN,
       DD.DDPOPAYDB_ADVICE_DATE,
       DD.DDPOPAYDB_ISSUED_BRN,
       (SELECT DDD.DDPOPAYDB_LEAF_NUM FROM DDPOPAYDB DDD WHERE DDD.DDPOPAYDB_ENTITY_NUM = DD.DDPOPAYDB_ENTITY_NUM
       AND DDD.DDPOPAYDB_REMIT_CODE = DD.DDPOPAYDB_REMIT_CODE
       AND DDD.DDPOPAYDB_ISSUED_BRN = DD.DDPOPAYDB_ISSUED_BRN
       AND DDD.DDPOPAYDB_INST_DATE <= DD.DDPOPAYDB_INST_DATE
       AND DDD.DDPOPAYDB_ISSUED_ON_BRN = DD.DDPOPAYDB_ISSUED_ON_BRN
       AND DDD.DDPOPAYDB_DUP_INST_PFX = DD.DDPOPAYDB_INST_PFX
       AND DDD.DDPOPAYDB_DUP_INST_LEAF_NUM = DD.DDPOPAYDB_LEAF_NUM) DDPOPAYDB_DUP_INST_LEAF_NUM,
       DD.DDPOPAYDB_ADVICE_REC_DATE,
       DD.DDPOPAYDB_PAY_CAN_DUP_DATE,
       DD.DDPOPAYDB_STATUS,
       DD.DDPOPAYDB_REMIT_CODE,
       DD.DDPOPAYDB_INST_PFX,
       LPAD (DD.DDPOPAYDB_LEAF_NUM, 7, ''0'') DDPOPAYDB_LEAF_NUM,
       DD.DDPOPAYDB_INST_CURRENCY,
       DD.DDPOPAYDB_INST_AMT,
       DD.DDPOPAYDB_BENEF_NAME1,
       DD.DDPOPAYDB_INST_DATE,
       DD.DDPOPAYDB_ADVICE_NO
  FROM DDPOPAYDB DD,
       (SELECT REMCD_REMIT_DESCN,
               DDPOPAYDB_ADVICE_DATE,
               DDPOPAYDB_ISSUED_BRN,
               DDPOPAYDB_DUP_INST_LEAF_NUM,
               DDPOPAYDB_ENTITY_NUM,
               DDPOPAYDB_ISSUED_ON_BRN,
               DDPOPAYDB_REMIT_CODE,
               DDPOPAYDB_INST_PFX,
               DDPOPAYDB_LEAF_NUM,
               DDPOPAYDB_INST_AMT
          FROM DDPOPAYDB, REMCD
         WHERE     DDPOPAYDB_ENTITY_NUM = :1
               AND DDPOPAYDB_REMIT_CODE = REMCD_REMIT_CODE
               AND DDPOPAYDB_REMIT_CODE =:2
               AND DDPOPAYDB_ISSUED_ON_BRN = :3
               AND NVL (DDPOPAYDB_STATUS, ''#'') NOT IN
                      (''C'', ''R'', ''E'', ''L'',''D'')
               AND DDPOPAYDB_ADVICE_REC_DATE <= :4
        MINUS
        SELECT REMCD_REMIT_DESCN,
               DDPOPAYDB_ADVICE_DATE,
               DDPOPAYDB_ISSUED_BRN,
               DDPOPAYDB_DUP_INST_LEAF_NUM,
               DDPOPAY_ENTITY_NUM,
               DDPOPAY_BRN_CODE,
               DDPOPAY_REMIT_CODE,
               DDPOPAY_INST_PFX,
               DDPOPAY_INST_NUM,
               DDPOPAY_INST_AMT
          FROM DDPOPAY A, DDPOPAYDB B, REMCD
         WHERE     A.DDPOPAY_INST_NUM = B.DDPOPAYDB_LEAF_NUM
               AND DDPOPAYDB_REMIT_CODE = REMCD_REMIT_CODE
               AND A.DDPOPAY_INST_PFX = B.DDPOPAYDB_INST_PFX
               AND A.DDPOPAY_REMIT_CODE = B.DDPOPAYDB_REMIT_CODE
               AND DDPOPAY_REMIT_CODE =:5
               AND DDPOPAYDB_ISSUED_ON_BRN = :6
               AND DDPOPAY_BRN_CODE = :7
               AND NVL (DDPOPAYDB_STATUS, ''#'') NOT IN (''C'', ''R'', ''E'', ''L'',''D'')
               AND DDPOPAY_REJ_ON IS NULL
               AND DDPOPAY_PAY_DATE <= :8) OUTS
 WHERE     OUTS.DDPOPAYDB_ENTITY_NUM = DD.DDPOPAYDB_ENTITY_NUM
       AND OUTS.DDPOPAYDB_REMIT_CODE = DD.DDPOPAYDB_REMIT_CODE
       AND OUTS.DDPOPAYDB_INST_PFX = DD.DDPOPAYDB_INST_PFX
       AND OUTS.DDPOPAYDB_LEAF_NUM = DD.DDPOPAYDB_LEAF_NUM
       AND OUTS.DDPOPAYDB_ISSUED_ON_BRN = DD.DDPOPAYDB_ISSUED_ON_BRN';


      EXECUTE IMMEDIATE W_SQL
         BULK COLLECT INTO V_TY_DD_DTL
         USING P_ENTITYNUM,
               P_REMIT_CODE,
               P_BRANCH_CODE,
               P_ASON_DATE,
               P_REMIT_CODE,
               P_BRANCH_CODE,
               P_BRANCH_CODE,
               P_ASON_DATE;

      IF (V_TY_DD_DTL.FIRST IS NOT NULL)
      THEN
         FOR IDX IN V_TY_DD_DTL.FIRST .. V_TY_DD_DTL.LAST
         LOOP
            TABLE1.REMIT_DESCN := V_TY_DD_DTL (IDX).TP_REMIT_DESCN;
            TABLE1.ADVICE_DATE := V_TY_DD_DTL (IDX).TP_ADVICE_DATE;
            TABLE1.ISSUED_BRN := V_TY_DD_DTL (IDX).TP_ISSUED_BRN;
            TABLE1.DUP_INST_LEAF_NUM := V_TY_DD_DTL (IDX).TP_DUP_INST_LEAF_NUM;
            TABLE1.ADVICE_REC_DATE := V_TY_DD_DTL (IDX).TP_ADVICE_REC_DATE;
            TABLE1.PAY_CAN_DUP_DATE := V_TY_DD_DTL (IDX).TP_PAY_CAN_DUP_DATE;
            TABLE1.DD_STATUS := V_TY_DD_DTL (IDX).TP_DD_STATUS;
            TABLE1.REMIT_CODE := V_TY_DD_DTL (IDX).TP_REMIT_CODE;
            TABLE1.INST_PFX := V_TY_DD_DTL (IDX).TP_INST_PFX;
            TABLE1.DDPO_LEAF_NUM := V_TY_DD_DTL (IDX).TP_DDPO_LEAF_NUM;
            TABLE1.INST_CURRENCY := V_TY_DD_DTL (IDX).TP_INST_CURRENCY;
            TABLE1.INST_AMT := V_TY_DD_DTL (IDX).TP_INST_AMT;
            TABLE1.BENEF_NAME1 := V_TY_DD_DTL (IDX).TP_BENEF_NAME1;
            TABLE1.INST_DATE := V_TY_DD_DTL (IDX).TP_INST_DATE;
            TABLE1.ADVICE_NO := V_TY_DD_DTL (IDX).TP_ADVICE_NO;
            PIPE ROW (TABLE1);
         END LOOP;
      END IF;/*
  EXCEPTION

    WHEN OTHERS THEN
      W_ERROR_MSG := SUBSTR(SQLERRM, 1, 50);   */
   END DD_DTL;


   FUNCTION PO_DTL (P_ENTITYNUM    IN NUMBER,
                    P_REMIT_CODE     IN VARCHAR2,
                    P_BRANCH_CODE   IN NUMBER,
                    P_ASON_DATE    IN DATE)
      RETURN TY_PO_DTL
      PIPELINED
      --RETURN VARCHAR2
   IS
   E_USEREXCEP   EXCEPTION;
      W_ERROR_MSG   VARCHAR2 (60);
   BEGIN
    PKG_ENTITY.SP_SET_ENTITY_CODE(P_ENTITYNUM);
      W_SQL :=
         'WITH PO_DATA AS
(SELECT DDPOPAYDB_ENTITY_NUM, DDPOPAYDB_REMIT_CODE, DDPOPAYDB_INST_PFX, DDPOPAYDB_LEAF_NUM, DDPOPAYDB_ADVICE_DATE,
                (SELECT DDD.DDPOPAYDB_DUP_INST_PFX FROM DDPOPAYDB DDD WHERE DDD.DDPOPAYDB_ENTITY_NUM = DD.DDPOPAYDB_ENTITY_NUM
       AND DDD.DDPOPAYDB_REMIT_CODE = DD.DDPOPAYDB_REMIT_CODE
       AND DDD.DDPOPAYDB_ISSUED_BRN = DD.DDPOPAYDB_ISSUED_BRN
       AND DDD.DDPOPAYDB_INST_DATE <= DD.DDPOPAYDB_INST_DATE
       AND DDD.DDPOPAYDB_ISSUED_ON_BRN = DD.DDPOPAYDB_ISSUED_ON_BRN
       AND DDD.DDPOPAYDB_DUP_INST_PFX = DD.DDPOPAYDB_INST_PFX
       AND DDD.DDPOPAYDB_DUP_INST_LEAF_NUM = DD.DDPOPAYDB_LEAF_NUM) DDPOPAYDB_DUP_INST_PFX,
                (SELECT DDD.DDPOPAYDB_LEAF_NUM FROM DDPOPAYDB DDD WHERE DDD.DDPOPAYDB_ENTITY_NUM = DD.DDPOPAYDB_ENTITY_NUM
       AND DDD.DDPOPAYDB_REMIT_CODE = DD.DDPOPAYDB_REMIT_CODE
       AND DDD.DDPOPAYDB_ISSUED_BRN = DD.DDPOPAYDB_ISSUED_BRN
       AND DDD.DDPOPAYDB_INST_DATE <= DD.DDPOPAYDB_INST_DATE
       AND DDD.DDPOPAYDB_ISSUED_ON_BRN = DD.DDPOPAYDB_ISSUED_ON_BRN
       AND DDD.DDPOPAYDB_DUP_INST_PFX = DD.DDPOPAYDB_INST_PFX
       AND DDD.DDPOPAYDB_DUP_INST_LEAF_NUM = DD.DDPOPAYDB_LEAF_NUM) DDPOPAYDB_DUP_INST_LEAF_NUM , DDPOPAYDB_ADVICE_REC_DATE, DDPOPAYDB_INST_CURRENCY,
                DDPOPAYDB_ADVICE_NO, DDPOPAYDB_ISSUED_BRN, DDPOPAYDB_INST_AMT, DDPOPAYDB_ISSUED_ON_BRN, DDPOPAYDB_BENEF_NAME1, DDPOPAYDB_STATUS,
                DDPOPAYDB_INST_DATE, DDPOPAYDB_PAY_CAN_DUP_DATE
FROM DDPOPAYDB DD
WHERE DDPOPAYDB_ENTITY_NUM=:1
AND DDPOPAYDB_REMIT_CODE=:2
AND DDPOPAYDB_ISSUED_BRN=:3
AND DDPOPAYDB_INST_DATE <=:4
AND DDPOPAYDB_ISSUED_ON_BRN=:5),
DAY_WISE_PO
AS(
SELECT DDPOPAYDB_ENTITY_NUM, DDPOPAYDB_REMIT_CODE, DDPOPAYDB_INST_PFX, DDPOPAYDB_LEAF_NUM
FROM PO_DATA
MINUS
SELECT DDPOPAYDB_ENTITY_NUM, DDPOPAYDB_REMIT_CODE, DDPOPAYDB_INST_PFX, DDPOPAYDB_LEAF_NUM
FROM PO_DATA
WHERE NVL(DDPOPAYDB_STATUS,''#'') IN (''C'',''R'',''E'',''L'', ''P'', ''D'')
AND DDPOPAYDB_PAY_CAN_DUP_DATE<=:6)
SELECT          B.DDPOPAYDB_ENTITY_NUM,
                R.REMCD_REMIT_DESCN,
                B.DDPOPAYDB_ADVICE_DATE,
                B.DDPOPAYDB_ISSUED_BRN,
                B.DDPOPAYDB_DUP_INST_PFX,
                LPAD(B.DDPOPAYDB_DUP_INST_LEAF_NUM,7,''0'') DDPOPAYDB_DUP_INST_LEAF_NUM,
                B.DDPOPAYDB_ADVICE_REC_DATE,
                B.DDPOPAYDB_PAY_CAN_DUP_DATE,
                B.DDPOPAYDB_STATUS,
                B.DDPOPAYDB_REMIT_CODE,
                B.DDPOPAYDB_INST_PFX,
                LPAD(B.DDPOPAYDB_LEAF_NUM,7,''0'') DDPOPAYDB_LEAF_NUM,
                B.DDPOPAYDB_INST_CURRENCY,
                B.DDPOPAYDB_INST_AMT,
                B.DDPOPAYDB_BENEF_NAME1,
                B.DDPOPAYDB_INST_DATE,
                B.DDPOPAYDB_ADVICE_NO FROM DAY_WISE_PO A, PO_DATA B, REMCD R
WHERE A.DDPOPAYDB_ENTITY_NUM=B.DDPOPAYDB_ENTITY_NUM
AND  A.DDPOPAYDB_REMIT_CODE=B.DDPOPAYDB_REMIT_CODE
AND A.DDPOPAYDB_INST_PFX=B.DDPOPAYDB_INST_PFX
AND A.DDPOPAYDB_LEAF_NUM=B.DDPOPAYDB_LEAF_NUM
AND R.REMCD_REMIT_CODE = B.DDPOPAYDB_REMIT_CODE';
--DBMS_OUTPUT.PUT_LINE(W_SQL);

      EXECUTE IMMEDIATE W_SQL
         BULK COLLECT INTO V_TY_PO_DTL
         USING P_ENTITYNUM,
               P_REMIT_CODE,
               P_BRANCH_CODE,
               P_ASON_DATE,
               P_BRANCH_CODE,
               P_ASON_DATE;

      IF (V_TY_PO_DTL.FIRST IS NOT NULL)
      THEN
         FOR IDZ IN V_TY_PO_DTL.FIRST .. V_TY_PO_DTL.LAST
         LOOP
            TABLE2.ENTITY_NUM := V_TY_PO_DTL (IDZ).TM_ENTITY_NUM;
            TABLE2.REMIT_DESCN := V_TY_PO_DTL (IDZ).TM_REMIT_DESCN;
            TABLE2.ADVICE_DATE := V_TY_PO_DTL (IDZ).TM_ADVICE_DATE;
            TABLE2.ISSUED_BRN := V_TY_PO_DTL (IDZ).TM_ISSUED_BRN;
            TABLE2.DUP_INST_PFX := V_TY_PO_DTL (IDZ).TM_DUP_INST_PFX;
            TABLE2.DUP_INST_LEAF_NUM :=
               V_TY_PO_DTL (IDZ).TM_DUP_INST_LEAF_NUM;
            TABLE2.ADVICE_REC_DATE := V_TY_PO_DTL (IDZ).TM_ADVICE_REC_DATE;
            TABLE2.PAY_CAN_DUP_DATE := V_TY_PO_DTL (IDZ).TM_PAY_CAN_DUP_DATE;
            TABLE2.DD_STATUS := V_TY_PO_DTL (IDZ).TM_DD_STATUS;
            TABLE2.REMIT_CODE := V_TY_PO_DTL (IDZ).TM_REMIT_CODE;
            TABLE2.INST_PFX := V_TY_PO_DTL (IDZ).TM_INST_PFX;
            TABLE2.DDPO_LEAF_NUM := V_TY_PO_DTL (IDZ).TM_DDPO_LEAF_NUM;
            TABLE2.INST_CURRENCY := V_TY_PO_DTL (IDZ).TM_INST_CURRENCY;
            TABLE2.INST_AMT := V_TY_PO_DTL (IDZ).TM_INST_AMT;
            TABLE2.BENEF_NAME1 := V_TY_PO_DTL (IDZ).TM_BENEF_NAME1;
            TABLE2.INST_DATE := V_TY_PO_DTL (IDZ).TM_INST_DATE;
            TABLE2.ADVICE_NO := V_TY_PO_DTL (IDZ).TM_ADVICE_NO;
            PIPE ROW (TABLE2);
         END LOOP;
      END IF;

      EXCEPTION

    WHEN OTHERS THEN
      W_ERROR_MSG := SUBSTR(SQLERRM, 1, 50);
   END;
END PKG_DDPO_REPORT;
/
