CREATE OR REPLACE TRIGGER TRG_REF
   BEFORE INSERT ON SWFMT103
   FOR EACH ROW
BEGIN

:NEW.SWFMT103_SEQ_NUM:=SUBSTR(TO_NUMBER('200'||TO_CHAR (SYSDATE, 'YYMMDD') || SUBSTR(LPAD(:NEW.SWFMT103_SEQ_NUM,7,'0'),-7,7)),1,16);

END TRG_REF;
/
