CREATE OR REPLACE TRIGGER TRIG_AML_VERIFY
    AFTER INSERT or update
    ON TBAAUTHDTL
    FOR EACH ROW
BEGIN
    UPDATE AMLVERIFYINFO
       SET AMLVINFO_VERIFY_STATUS = 'RELEASE'
     WHERE  AMLVINFO_VERIFY_STATUS='Pending';
END TRIG_AML_VERIFY;
/
