CREATE OR REPLACE TRIGGER TRIG_ATM_SHADOW
   BEFORE UPDATE OF MN_EOD_IN_PROGRESS
   ON MAINCONT
   FOR EACH ROW
DECLARE
   V_PROGRAM_NAME   VARCHAR2 (1000);
BEGIN
   :NEW.MN_EOD_IN_PROGRESS:=1;

END;
/
