CREATE OR REPLACE TRIGGER TRIG_UPDATE_USERS
BEFORE UPDATE
ON USERS
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
DECLARE
   V_PROGRAM_NAME   VARCHAR2 (1000);
BEGIN
   SELECT PROGRAM
     INTO V_PROGRAM_NAME
     FROM SYS.V_$SESSION
    WHERE AUDSID = USERENV ('SESSIONID')
    AND AUDSID != 0 -- Don't Check SYS Connections
    AND ROWNUM = 1;

   IF V_PROGRAM_NAME <> 'JDBC Thin Client'
      AND :NEW.USER_ID NOT IN ('INTELECT','SPFTL','SPFTL1','SPFTL2','SPFTL3')
   THEN
      RAISE_APPLICATION_ERROR (
         -20000,
         'Update not allowed for user ' || :NEW.USER_ID);
   END IF;
END;
/
