CREATE OR REPLACE TRIGGER TRIG_INSERT_ACNTS_AMLACNTCL
   BEFORE INSERT OR UPDATE OF ACNTS_DORMANT_ACNT,ACNTS_INOP_ACNT ON ACNTS
   FOR EACH ROW
DECLARE
   W_SQLERRM VARCHAR2(1000);
BEGIN
 --ENTITY CODE COMMONLY ADDED - 21-11-2009  - BEG
       PKG_ENTITY.SP_SET_ENTITY_CODE(:NEW.ACNTS_ENTITY_NUM);
 --ENTITY CODE COMMONLY ADDED - 21-11-2009  - END

   IF INSERTING THEN
       <<INSERTAMLACNTCL>>
       BEGIN
         INSERT INTO AMLACNTCL
           (AMLACNTCL_ENTITY_NUM,AMLACNTCL_INTERNAL_ACNUM,
            AMLACNTCL_CLIENT_CODE,
            AMLACNTCL_RISK_CATE,
            AMLACNTCL_TYPE_FLG)
         VALUES
           (PKG_ENTITY.FN_GET_ENTITY_CODE,
            :NEW.ACNTS_INTERNAL_ACNUM,
            :NEW.ACNTS_CLIENT_NUM,
            (SELECT C.CLIENTS_RISK_CATEGORIZATION
               FROM CLIENTS C
              WHERE C.CLIENTS_CODE = :NEW.ACNTS_CLIENT_NUM),
            (SELECT C.CLIENTS_TYPE_FLG
               FROM CLIENTS C
              WHERE C.CLIENTS_CODE = :NEW.ACNTS_CLIENT_NUM));
       EXCEPTION
       WHEN DUP_VAL_ON_INDEX THEN
             UPDATE  AMLACNTCL SET AMLACNTCL_RISK_CATE = (SELECT C.CLIENTS_RISK_CATEGORIZATION
               FROM CLIENTS C
              WHERE C.CLIENTS_CODE = :NEW.ACNTS_CLIENT_NUM), AMLACNTCL_TYPE_FLG =  (SELECT C.CLIENTS_TYPE_FLG
               FROM CLIENTS C
              WHERE C.CLIENTS_CODE = :NEW.ACNTS_CLIENT_NUM) WHERE AMLACNTCL_INTERNAL_ACNUM = :NEW.ACNTS_INTERNAL_ACNUM;
         WHEN OTHERS THEN
         W_SQLERRM:=SQLERRM;
          PKG_PB_GLOBAL.DETAIL_ERRLOG (1,
                                   'E',
                                   'Account '||:NEW.ACNTS_INTERNAL_ACNUM||' Client '||:NEW.ACNTS_CLIENT_NUM||' Error '||W_SQLERRM,
                                   ' ',
                                   :NEW.ACNTS_INTERNAL_ACNUM);
           RAISE_APPLICATION_ERROR(-20999,'Error in Account number risk cat insertion - TRIG_INSERT_ACNTS_AMLACNTCL ' ||W_SQLERRM);
       END INSERTAMLACNTCL;

       <<INSERT_AMLACSOPENSUMM>>
       BEGIN
         INSERT INTO AMLACSOPENSUMM ( AMLACSOP_CLIENT_CODE, AMLACSOP_NUM_ACHOLDER, AMLACSOP_NUM_INTRODUCER)
         VALUES (:NEW.ACNTS_CLIENT_NUM,1,0);

         EXCEPTION
         WHEN DUP_VAL_ON_INDEX THEN
             UPDATE  AMLACSOPENSUMM SET AMLACSOP_NUM_ACHOLDER = AMLACSOP_NUM_ACHOLDER+1 WHERE AMLACSOP_CLIENT_CODE = :NEW.ACNTS_CLIENT_NUM;
         WHEN OTHERS THEN
         W_SQLERRM:=SQLERRM;
          PKG_PB_GLOBAL.DETAIL_ERRLOG (1,
                                   'E',
                                   'Account '||:NEW.ACNTS_INTERNAL_ACNUM||' Client '||:NEW.ACNTS_CLIENT_NUM||' Error '||W_SQLERRM,
                                   ' ',
                                   :NEW.ACNTS_INTERNAL_ACNUM);
             RAISE_APPLICATION_ERROR(-20999,'Error in Account Opening Summary insertion - TRIG_INSERT_ACNTS_AMLACNTCL '||W_SQLERRM);

        END INSERT_AMLACSOPENSUMM;

     ELSIF UPDATING THEN
          <<INSERT_AMLACDORMINOP>>
           BEGIN
               IF :NEW.ACNTS_INOP_ACNT = '0' AND :NEW.ACNTS_DORMANT_ACNT = '0' THEN
                   DELETE FROM AMLACDORMINOP WHERE AMLACDI_ENTITY_NUM = PKG_ENTITY.FN_GET_ENTITY_CODE AND  AMLACDI_INTERNAL_ACNUM = :NEW.ACNTS_INTERNAL_ACNUM;
               ELSE
                   INSERT INTO AMLACDORMINOP (AMLACDI_ENTITY_NUM,AMLACDI_INTERNAL_ACNUM, AMLACDI_DORM_FLG, AMLACDI_INOP_FLG)
                   VALUES (PKG_ENTITY.FN_GET_ENTITY_CODE,:NEW.ACNTS_INTERNAL_ACNUM,:NEW.ACNTS_DORMANT_ACNT,:NEW.ACNTS_INOP_ACNT);
               END IF;

               EXCEPTION
               WHEN DUP_VAL_ON_INDEX THEN
                 UPDATE AMLACDORMINOP SET AMLACDI_DORM_FLG = :NEW.ACNTS_DORMANT_ACNT,AMLACDI_INOP_FLG = :NEW.ACNTS_INOP_ACNT WHERE  AMLACDI_ENTITY_NUM = PKG_ENTITY.FN_GET_ENTITY_CODE AND  AMLACDI_INTERNAL_ACNUM = :NEW.ACNTS_INTERNAL_ACNUM;
               WHEN OTHERS THEN
                W_SQLERRM:=SQLERRM;
          PKG_PB_GLOBAL.DETAIL_ERRLOG (1,
                                   'E',
                                   'Account '||:NEW.ACNTS_INTERNAL_ACNUM||' Client '||:NEW.ACNTS_CLIENT_NUM||' Error '||W_SQLERRM,
                                   ' ',
                                   :NEW.ACNTS_INTERNAL_ACNUM);
                 RAISE_APPLICATION_ERROR(-20999,'Error in AMLACDORMINOP insertion - TRIG_INSERT_ACNTS_AMLACNTCL '||W_SQLERRM);
           END INSERT_AMLACDORMINOP;
   END IF;
 END TRIG_INSERT_ACNTS_AMLACNTCL;
/
