--- ACNTS
CREATE TABLE ACNTS_ACTUAL_AC AS SELECT * FROM ACNTS WHERE ACNTS_ENTITY_NUM = 1
AND  ACNTS_INTERNAL_ACNUM IN (
SELECT IACLINK_INTERNAL_ACNUM FROM ACTUAL_ACCOUNT_UPDATE ) ;


DELETE FROM ACNTS WHERE ACNTS_ENTITY_NUM = 1
AND  ACNTS_INTERNAL_ACNUM IN (
SELECT IACLINK_INTERNAL_ACNUM FROM ACTUAL_ACCOUNT_UPDATE WHERE SL <> 1 ) ;


UPDATE ACNTS
   SET ACNTS_CLOSURE_DATE = NULL
 WHERE     ACNTS_ENTITY_NUM = 1
       AND ACNTS_INTERNAL_ACNUM IN
              (SELECT IACLINK_INTERNAL_ACNUM
                 FROM ACTUAL_ACCOUNT_UPDATE A
                WHERE     A.IACLINK_ACTUAL_ACNUM IN
                             (SELECT IACLINK_ACTUAL_ACNUM
                                FROM ACTUAL_ACCOUNT_UPDATE
                               WHERE ACNTBAL_BC_BAL <> 0)
                      AND A.SL = 1) ;

--- IACLINK


CREATE TABLE IACLINK_ACTUAL_AC AS SELECT * FROM IACLINK WHERE IACLINK_ENTITY_NUM = 1
AND  IACLINK_INTERNAL_ACNUM IN (
SELECT IACLINK_INTERNAL_ACNUM FROM ACTUAL_ACCOUNT_UPDATE ) ;



DELETE FROM IACLINK WHERE IACLINK_ENTITY_NUM = 1
AND  IACLINK_INTERNAL_ACNUM IN (
SELECT IACLINK_INTERNAL_ACNUM FROM ACTUAL_ACCOUNT_UPDATE WHERE SL <> 1 ) ;

--- ACNTMAIL

CREATE TABLE ACNTMAIL_ACTUAL_AC AS SELECT * FROM ACNTMAIL WHERE ACNTMAIL_ENTITY_NUM = 1
AND  ACNTMAIL_INTERNAL_ACNUM IN (
SELECT IACLINK_INTERNAL_ACNUM FROM ACTUAL_ACCOUNT_UPDATE ) ;


 
DELETE FROM ACNTMAIL WHERE ACNTMAIL_ENTITY_NUM = 1
AND  ACNTMAIL_INTERNAL_ACNUM IN (
SELECT IACLINK_INTERNAL_ACNUM FROM ACTUAL_ACCOUNT_UPDATE WHERE SL <> 1 ) ;

-- ECSACMAP

CREATE TABLE ECSACMAP_ACTUAL_AC AS SELECT * FROM ECSACMAP WHERE ECSACMAP_ENTITY_NUM = 1
AND  ECSACMAP_ACTUAL_AC IN (
SELECT IACLINK_INTERNAL_ACNUM FROM ACTUAL_ACCOUNT_UPDATE) ;


DELETE FROM ECSACMAP WHERE ECSACMAP_ENTITY_NUM = 1
AND  ECSACMAP_ACTUAL_AC IN (
SELECT IACLINK_INTERNAL_ACNUM FROM ACTUAL_ACCOUNT_UPDATE WHERE SL <> 1 ) ;

--- ACNTLINK

CREATE TABLE ACNTLINK_ACTUAL_AC AS SELECT * FROM ACNTLINK WHERE ACNTLINK_ENTITY_NUM = 1
AND  ACNTLINK_INTERNAL_ACNUM IN (
SELECT IACLINK_INTERNAL_ACNUM FROM ACTUAL_ACCOUNT_UPDATE ) ;


DELETE FROM ACNTLINK WHERE ACNTLINK_ENTITY_NUM = 1
AND  ACNTLINK_INTERNAL_ACNUM IN (
SELECT IACLINK_INTERNAL_ACNUM FROM ACTUAL_ACCOUNT_UPDATE WHERE SL <> 1 ) ;


--- ACNTFRZ

DECLARE
   V_AC_NUM   NUMBER;
BEGIN
   FOR IDX
      IN (  SELECT * FROM ACTUAL_ACCOUNT_UPDATE)
   LOOP
      IF IDX.SL = 1
      THEN
         V_AC_NUM := IDX.IACLINK_INTERNAL_ACNUM;
      END IF;

      UPDATE ACNTFRZ
         SET ACNTFRZ_INTERNAL_ACNUM = V_AC_NUM
       WHERE     ACNTFRZ_ENTITY_NUM = 1
             AND ACNTFRZ_INTERNAL_ACNUM = IDX.IACLINK_INTERNAL_ACNUM;
   END LOOP;
END; 



---ACNTSTATUS


DECLARE
   V_AC_NUM   NUMBER;
BEGIN
   FOR IDX
      IN (  SELECT * FROM ACTUAL_ACCOUNT_UPDATE)
   LOOP
      IF IDX.SL = 1
      THEN
         V_AC_NUM := IDX.IACLINK_INTERNAL_ACNUM;
      END IF;

      UPDATE ACNTSTATUS
         SET ACNTSTATUS_INTERNAL_ACNUM = V_AC_NUM
       WHERE     ACNTSTATUS_ENTITY_NUM = 1
             AND ACNTSTATUS_INTERNAL_ACNUM = IDX.IACLINK_INTERNAL_ACNUM;
   END LOOP;
END;


--- ACNTLIEN


DECLARE
   V_AC_NUM   NUMBER;
BEGIN
   FOR IDX
      IN (  SELECT * FROM ACTUAL_ACCOUNT_UPDATE)
   LOOP
      IF IDX.SL = 1
      THEN
         V_AC_NUM := IDX.IACLINK_INTERNAL_ACNUM;
      END IF;

      UPDATE ACNTLIEN
         SET ACNTLIEN_INTERNAL_ACNUM = V_AC_NUM
       WHERE     ACNTLIEN_ENTITY_NUM = 1
             AND ACNTLIEN_INTERNAL_ACNUM = IDX.IACLINK_INTERNAL_ACNUM;
   END LOOP;
END;





UPDATE ACNTS
   SET ACNTS_CLOSURE_DATE = NULL
 WHERE     ACNTS_ENTITY_NUM = 1
       AND ACNTS_INTERNAL_ACNUM IN
              (SELECT IACLINK_INTERNAL_ACNUM
                 FROM ACTUAL_ACCOUNT_UPDATE A
                WHERE     A.IACLINK_ACTUAL_ACNUM IN
                             (SELECT IACLINK_ACTUAL_ACNUM
                                FROM ACTUAL_ACCOUNT_UPDATE
                               WHERE ACNTBAL_BC_BAL <> 0)
                      AND A.SL = 1);