WITH OLCOS AS (SELECT OLC_BRN_CODE,
               OLC_LC_TYPE,
               OLC_LC_YEAR,
               OLC_LC_SL,
               SUM(LC_FOREIGN_DEBIT_AMOUNT) - SUM(LC_FOREIGN_CREDIT_AMOUNT) LC_OS,
               SUM(LC_LIABILITY_DEBIT_AMOUNT) -
               SUM(LC_LIABILITY_CREDIT_AMOUNT) LC_OS_BASE
          FROM TABLE(PKG_MARGIN_LIABILITY.GET_MARGIN_LIABILITY_DATA(1,
                                                                    26,
                                                                    NULL,
                                                                    NULL,
                                                                    TRUNC(SYSDATE),
                                                                    NULL,NULL,NULL,NULL,NULL))
         GROUP BY OLC_BRN_CODE, OLC_LC_TYPE, OLC_LC_YEAR, OLC_LC_SL
         ORDER BY OLC_BRN_CODE, OLC_LC_TYPE, OLC_LC_YEAR, OLC_LC_SL)
         

SELECT distinct O.OLC_CUST_NUM "CLIENT CODE",
       (SELECT C.CLIENTS_NAME
          FROM CLIENTS C
         WHERE C.CLIENTS_CODE = O.OLC_CUST_NUM) "CLIENT NAME",
       O.OLC_BRN_CODE "BRANCH CODE",
       (SELECT M.MBRN_NAME
          FROM MBRN M
         WHERE M.MBRN_ENTITY_NUM = 1
           AND M.MBRN_CODE = O.OLC_BRN_CODE) "BRANCH NAME",
       O.OLC_LC_DATE "LC OPENING DATE",
       O.OLC_LC_TYPE "LC CODE",
       TN.TNOMEN_DESCN "LC NAME",
       O.OLC_LC_YEAR "LC YEAR",
       O.OLC_CORR_REF_NUM "LC NUMBER",
       O.OLC_LCAF_NUM "LCAF NUMBER",
       O.OLC_LC_CURR_CODE "LC CURRENCY",
       NN.LC_OS,
       NN.LC_OS_BASE,
       (SELECT  LISTAGG(CM.OLCCOM_ITCHS_CODE, '|') WITHIN GROUP(ORDER BY CM.OLCCOM_ENTITY_NUM, CM.OLCCOM_BRN_CODE, CM.OLCCOM_LC_TYPE, CM.OLCCOM_LC_YEAR, CM.OLCCOM_LC_SL)
          FROM OLCCOMM CM
         WHERE CM.OLCCOM_ENTITY_NUM = O.OLC_ENTITY_NUM
           AND CM.OLCCOM_BRN_CODE = O.OLC_BRN_CODE
           AND CM.OLCCOM_LC_TYPE = O.OLC_LC_TYPE
           AND CM.OLCCOM_LC_YEAR = O.OLC_LC_YEAR
           AND CM.OLCCOM_LC_SL = O.OLC_LC_SL) "HS CODE",
       (SELECT  LISTAGG((SELECT H.HSCODE_DESCN
                         FROM HSCODE H
                        WHERE H.HSCODE_CODE = CM.OLCCOM_ITCHS_CODE),
                       '|') WITHIN GROUP(ORDER BY CM.OLCCOM_ENTITY_NUM, CM.OLCCOM_BRN_CODE, CM.OLCCOM_LC_TYPE, CM.OLCCOM_LC_YEAR, CM.OLCCOM_LC_SL)
          FROM OLCCOMM CM
         WHERE CM.OLCCOM_ENTITY_NUM = O.OLC_ENTITY_NUM
           AND CM.OLCCOM_BRN_CODE = O.OLC_BRN_CODE
           AND CM.OLCCOM_LC_TYPE = O.OLC_LC_TYPE
           AND CM.OLCCOM_LC_YEAR = O.OLC_LC_YEAR
           AND CM.OLCCOM_LC_SL = O.OLC_LC_SL) "HS CODE DESCRIPTION",
       (SELECT  LISTAGG(CM.OLCCOM_COMM_CODE, '|') WITHIN GROUP(ORDER BY CM.OLCCOM_ENTITY_NUM, CM.OLCCOM_BRN_CODE, CM.OLCCOM_LC_TYPE, CM.OLCCOM_LC_YEAR, CM.OLCCOM_LC_SL)
          FROM OLCCOMM CM
         WHERE CM.OLCCOM_ENTITY_NUM = O.OLC_ENTITY_NUM
           AND CM.OLCCOM_BRN_CODE = O.OLC_BRN_CODE
           AND CM.OLCCOM_LC_TYPE = O.OLC_LC_TYPE
           AND CM.OLCCOM_LC_YEAR = O.OLC_LC_YEAR
           AND CM.OLCCOM_LC_SL = O.OLC_LC_SL) "COMMODITY CODE",
       (SELECT  LISTAGG(CM.OLCCOM_IMP_QUANTITY, '|') WITHIN GROUP(ORDER BY CM.OLCCOM_ENTITY_NUM, CM.OLCCOM_BRN_CODE, CM.OLCCOM_LC_TYPE, CM.OLCCOM_LC_YEAR, CM.OLCCOM_LC_SL)
          FROM OLCCOMM CM
         WHERE CM.OLCCOM_ENTITY_NUM = O.OLC_ENTITY_NUM
           AND CM.OLCCOM_BRN_CODE = O.OLC_BRN_CODE
           AND CM.OLCCOM_LC_TYPE = O.OLC_LC_TYPE
           AND CM.OLCCOM_LC_YEAR = O.OLC_LC_YEAR
           AND CM.OLCCOM_LC_SL = O.OLC_LC_SL) "QUANTITY",
       (SELECT  LISTAGG(OLCCOMM_UNIT_PRICE, '|') WITHIN GROUP(ORDER BY CM.OLCCOM_ENTITY_NUM, CM.OLCCOM_BRN_CODE, CM.OLCCOM_LC_TYPE, CM.OLCCOM_LC_YEAR, CM.OLCCOM_LC_SL)
          FROM OLCCOMM CM
         WHERE CM.OLCCOM_ENTITY_NUM = O.OLC_ENTITY_NUM
           AND CM.OLCCOM_BRN_CODE = O.OLC_BRN_CODE
           AND CM.OLCCOM_LC_TYPE = O.OLC_LC_TYPE
           AND CM.OLCCOM_LC_YEAR = O.OLC_LC_YEAR
           AND CM.OLCCOM_LC_SL = O.OLC_LC_SL) "UNIT PRICE",
       (SELECT  LISTAGG(OLCCOM_WEIGHT_SPEC_CODE, '|') WITHIN GROUP(ORDER BY CM.OLCCOM_ENTITY_NUM, CM.OLCCOM_BRN_CODE, CM.OLCCOM_LC_TYPE, CM.OLCCOM_LC_YEAR, CM.OLCCOM_LC_SL)
          FROM OLCCOMM CM
         WHERE CM.OLCCOM_ENTITY_NUM = O.OLC_ENTITY_NUM
           AND CM.OLCCOM_BRN_CODE = O.OLC_BRN_CODE
           AND CM.OLCCOM_LC_TYPE = O.OLC_LC_TYPE
           AND CM.OLCCOM_LC_YEAR = O.OLC_LC_YEAR
           AND CM.OLCCOM_LC_SL = O.OLC_LC_SL) "WT SPEC CODE",
       O.OLC_BENEF_CODE "BENEFICIARY CODE",
       O.OLC_BENEF_NAME "BENEFICIARY NAME",
       O.OLC_BENEF_CNTRY_CODE "BENEFICIARY COUNTRY CODE",
       O.OLC_ADV_THRU_BK "LC ADVISING THROUGH BANK CODE",
       O.OLC_ADV_THRU_BRN "LC ADV THROUGH BRANCH CODE",
       O.OLC_LATEST_DATE_OF_SHPMNT "SHIPMENT DATE",
       O.OLC_LAST_DATE_OF_NEG "EXPIRY DATE",
       O.OLC_LC_TO_BE_CNFRMD_BY_BK "CONFIRMED BY BANK",
       O.OLC_LC_TO_BE_CNFRMD_BY_BRN "CONFIRMED BY BRANCH",
       O.OLC_PRICE_TERMS "TERMS OF PRICE",
       O.OLC_PLACE_OF_EXPIRY "PLACE OF EXPIRY",
       CASE
         WHEN T.OLCT_TENOR_TYPE = 'S' THEN
          'SIGHT'
         WHEN T.OLCT_TENOR_TYPE = 'U' THEN
          'USANCE'
         ELSE
          T.OLCT_TENOR_TYPE
       END "TENOR TYPE",
       T.OLCT_USANCE_PERD "USANCE DAYS",
       T.OLCT_USANCE_FROM "USANCE PERIOD FROM",
       CASE
         WHEN TN.TNOMEN_INLAND_OVERSEAS = 'O' THEN
          'FOREIGN'
         WHEN TN.TNOMEN_INLAND_OVERSEAS = 'I' THEN
          'LOCAL'
       END "LOCAL/FOREIGN TYPE",
       CASE
         WHEN B.BTBBD_BY_ORDER = '1' THEN
          B.BTBBD_BRN_CODE || '|' || B.BTBBD_ORDER_TYPE || '|' ||
          B.BTBBD_ORDER_YEAR || '|' || B.BTBBD_ORDER_SL
         WHEN B.BTBBD_BY_ILC = '1' THEN
          B.BTBBD_BRN_CODE || '|' || B.BTBBD_ILC_TYPE || '|' ||
          B.BTBBD_ILC_YEAR || '|' || B.BTBBD_ILC_SL
       END "EXPORT ORDER / LC (IF BTB)",
       O.OLC_INS_POLICY_NUM "INSURANCE POLICY/CERTIFICATE",
       O.OLC_INS_DATE "INSURANCE ON DATE",
       O.OLC_INS_CURR || ' ' || O.OLC_INS_AMT "INSURED CURRENCY AND AMOUNT ",
       O.OLC_PREMIUM_CURR || ' ' || O.OLC_PREMIUM_AMT "PREMIUM CURRENCY AND AMOUNT ",
       O.OLC_INS_COMPANY "INSURANCE COMPANY",
       O.OLC_COO_ISS_BY "CERT OF ORIGIN TO BE ISSUED BY"

  FROM OLC O
  JOIN OLCTENORS T
    ON (O.OLC_ENTITY_NUM = T.OLCT_ENTITY_NUM AND
       O.OLC_BRN_CODE = T.OLCT_BRN_CODE AND O.OLC_LC_TYPE = T.OLCT_LC_TYPE AND
       O.OLC_LC_YEAR = T.OLCT_LC_YEAR AND O.OLC_LC_SL = T.OLCT_LC_SL)
  JOIN OLCOS NN
    ON (O.OLC_BRN_CODE = NN.OLC_BRN_CODE AND O.OLC_LC_TYPE = NN.OLC_LC_TYPE AND
       O.OLC_LC_YEAR = NN.OLC_LC_YEAR AND O.OLC_LC_SL = NN.OLC_LC_SL)
  JOIN TNOMEN TN
    ON (O.OLC_LC_TYPE = TN.TNOMEN_NOMEN_CODE)
  LEFT JOIN BTBBACKINGDTLS B
    ON (O.OLC_ENTITY_NUM = B.BTBBD_ENTITY_NUM AND
       O.OLC_BRN_CODE = B.BTBBD_BRN_CODE AND O.OLC_LC_TYPE = B.BTBBD_TYPE AND
       O.OLC_LC_YEAR = B.BTBBD_YEAR AND O.OLC_LC_SL = B.BTBBD_SERIAL)
  LEFT JOIN OLCCOMM OM
    ON (O.OLC_ENTITY_NUM = OM.OLCCOM_ENTITY_NUM AND
       O.OLC_BRN_CODE = OM.OLCCOM_BRN_CODE AND
       O.OLC_LC_TYPE = OM.OLCCOM_LC_TYPE AND
       O.OLC_LC_YEAR = OM.OLCCOM_LC_YEAR AND O.OLC_LC_SL = OM.OLCCOM_LC_SL)
 WHERE O.OLC_ENTITY_NUM = 1
   AND O.OLC_LC_DATE <= trunc(sysdate) --ASON DATE
   AND O.OLC_AUTH_ON IS NOT NULL
--AND O.OLC_LC_DATE BETWEEN '01-JAN-2020' AND '19-MAR-2020'
