/* Formatted on 2/18/2019 12:24:26 PM (QP5 v5.227.12220.39754) */
SELECT CLIENT_CODE,FACNO (1, ACNTS_INTERNAL_ACNUM) ACCOUNT_NO,
       ACNTS_AC_NAME1 || ACNTS_AC_NAME2 ACCOUNT_NAME,
       INDCLIENT_FIRST_NAME,
       INDCLIENT_LAST_NAME,
       INDCLIENT_SUR_NAME,
       INDCLIENT_MIDDLE_NAME,GENDER GIVEN_GENDER,INDCLIENT_SEX CBS_GENDER,COUNT (*)
  FROM ACNTS, INDCLIENTS, BR_DEPOSIT_CLIENT
 WHERE     INDCLIENT_CODE = ACNTS_CLIENT_NUM
       AND CLIENT_CODE = INDCLIENT_CODE
       AND CLIENT_CODE = ACNTS_CLIENT_NUM
       and ACNTS_ENTITY_NUM=1
       GROUP BY CLIENT_CODE,FACNO (1, ACNTS_INTERNAL_ACNUM)  ,
       ACNTS_AC_NAME1 || ACNTS_AC_NAME2  ,
       INDCLIENT_FIRST_NAME,
       INDCLIENT_LAST_NAME,
       INDCLIENT_SUR_NAME,
       INDCLIENT_MIDDLE_NAME,GENDER  ,INDCLIENT_SEX  
       HAVING COUNT (*) > 1
       ORDER BY CLIENT_CODE 
       
       AND ACNTS_CLIENT_NUM IN (SELECT CLIENT_CODE
                                  FROM (  SELECT CLIENT_CODE, COUNT (*)
                                            FROM BR_DEPOSIT_CLIENT
                                        GROUP BY CLIENT_CODE
                                          HAVING COUNT (*) > 1))
                                          ORDER BY CLIENT_CODE 