/* Formatted on 5/6/2019 11:51:23 AM (QP5 v5.227.12220.39754) */
BEGIN
   FOR IDX
      IN (SELECT I.IACLINK_INTERNAL_ACNUM,
                 TRIM (ACC5.AC_TYPE) ACC_TYPE,
                 TRIM (ACC5.SUB_TYPE) ACC_SUB_TYPE
            FROM ACC5, IACLINK I
           WHERE     ACC5.ACC_No = I.IACLINK_ACTUAL_ACNUM
                 AND IACLINK_ENTITY_NUM = 1)
   LOOP
      UPDATE ACNTS A
         SET A.ACNTS_AC_TYPE = IDX.ACC_TYPE,
             A.ACNTS_AC_SUB_TYPE = IDX.ACC_SUB_TYPE
       WHERE     A.ACNTS_INTERNAL_ACNUM = IDX.IACLINK_INTERNAL_ACNUM
             AND ACNTS_ENTITY_NUM = 1;
   END LOOP;
END;