/* Formatted on 10/30/2019 12:26:12 PM (QP5 v5.227.12220.39754) */
SELECT ACNTS_BRN_CODE "BRANCH CODE",
       MBRN_NAME "BRANCH NAME",
       FACNO(1,ACTP_ACNT_NUM) "ACCOUNT NUMBER",
       ACNTS_AC_NAME1 || ACNTS_AC_NAME2 "ACCOUNT NAME",
       ACTP_SRC_FUND "SOURCE OF FUND",
       ACTP_NOT_CASHR "NO OF CASH WITHDRAWAL",
       ACTP_CUTOFF_LMT_CASHR "MAXIMIM WIDR 0F A SINGLE TRAN",
       ACTP_MAXAMT_CASHR "CASH TOTAL MONTHLY WITHDRAL",
       ACTP_NOT_NONCASHR "NO OF TRF BY CHEQUE",
       ACTP_CUTOFF_LMT_NONCASHR "MAXIMUM TRF OF A SINGLE TRAN",
       ACTP_MAXAMT_NCASHR "TOTAL MONTHLY TRF",
       ACTP_NOT_TFREMR "NO OF REMITANCE",
       ACTP_CUTOFF_LMT_TFREMR "MAXIMUM REMIT OF A SINGLE TRAN",
       ACTP_MAXAMT_TFREMR "TOTAL MONTHLY REMIT",
       ACTP_NOT_CASHP "NO OF MONTHLY DEPOSIT",
       ACTP_CUTOFF_LMT_CASHP "MAXIMUM AMT OF A SINGLE DEP",
       ACTP_MAXAMT_CASHP "TOTAL MONTHLY DEP",
       ACTP_NOT_NONCASHP "NO OF MONTHLY TRF DEP",
       ACTP_CUTOFF_LMT_NONCASHP "MAXIMUM DEP OF A SINGLE TRF",
       ACTP_MAXAMT_NCASHP "TOTAL MONTHLY TRF DEP",
       ACTP_NOT_TFREMP "NO OF MONTHLY REMIT",
       ACTP_CUTOFF_LMT_TFREMP "MAX AMT DEP OF A SINGLE REMIT",
       ACTP_MAXAMT_TFREMP "TOTAL MONTHLY REMIT DEP"
  FROM MBRN, ACNTRNPR, ACNTS
 WHERE     ACTP_ACNT_NUM = ACNTS_INTERNAL_ACNUM
       AND ACNTS_ENTITY_NUM = 1
       AND ACNTS_BRN_CODE = MBRN_CODE
       AND ACNTS_INTERNAL_ACNUM = 536747784