/* Formatted on 9/16/2021 3:53:07 PM (QP5 v5.149.1003.31008) */
SELECT 'CUMILLA' BOARD_NAME,
       11 BOARD_CODE,
       SRL_NO Z_CODE,
       NID UZ_CODE,
       BANK C_CODE,
       ROUTING_NUMBER EIIN,
       BENEFICIARY_NAME COLLEGE,
       NULL PASSWORD,
       THANA THANA,
       DISTRICT ZILLA,
       ACCOUNT_NUMBER AC_NUMBER,
       'SONALI BANK LIMITED' BANK_NAME,
       NULL ROUTING_NO,
       MOBILE MOBILE_NO,
       SP_GETACNAME (1, IACLINK_INTERNAL_ACNUM) Account_Name,
       IACLINK_BRN_CODE BRNACH_CODE,
       FN_GETBRNNAME (1, IACLINK_BRN_CODE) Branch_Name,
       (SELECT 200 || MBRN_MICR_CODE
          FROM MBRN
         WHERE MBRN_CODE = IACLINK_BRN_CODE)
          Routing_Number
  FROM ACC_FREEDOM_FIGHTER, IACLINK
 WHERE ACCOUNT_NUMBER = IACLINK_ACTUAL_ACNUM AND IACLINK_ENTITY_NUM = 1