DELETE FROM MONTHS_WISE_AC_BALANCE;

EXEC SP_MONTHWISE_DR_CR_SUM;



------------QUERY--------------------------------
 SELECT ACNTBBAL_INTERNAL_ACNUM, ACNTBBAL_YEAR, ACNTBBAL_MONTH,ACNTBBAL_AC_OPNG_CR_SUM-MW_CR_SUM,ACNTBBAL_BC_OPNG_DB_SUM-MW_DR_SUM
  FROM MONTHS_WISE_AC_BALANCE, ACNTBBAL
 WHERE     ACNTBBAL_ENTITY_NUM = 1
       AND INT_AC_NO = ACNTBBAL_INTERNAL_ACNUM
       AND TRANSACTION_MONTHS = ACNTBBAL_MONTH
       AND TRANSACTION_YEAR = ACNTBBAL_YEAR
       AND (ACNTBBAL_AC_OPNG_CR_SUM-MW_CR_SUM<>0 OR ACNTBBAL_BC_OPNG_DB_SUM-MW_DR_SUM<>0)
       ORDER BY ACNTBBAL_INTERNAL_ACNUM, ACNTBBAL_YEAR, ACNTBBAL_MONTH;
       
 --  If mismatch found then execute.

BEGIN
   FOR IDX IN (  SELECT *
                   FROM MONTHS_WISE_AC_BALANCE
               ORDER BY INT_AC_NO, TRANSACTION_YEAR, TRANSACTION_MONTHS)
   LOOP
      UPDATE ACNTBBAL
         SET ACNTBBAL_AC_OPNG_DB_SUM = IDX.MW_DR_SUM,
             ACNTBBAL_AC_OPNG_CR_SUM = IDX.MW_CR_SUM,
             ACNTBBAL_BC_OPNG_DB_SUM = IDX.MW_DR_SUM,
             ACNTBBAL_BC_OPNG_CR_SUM = IDX.MW_CR_SUM
       WHERE     ACNTBBAL_ENTITY_NUM = 1
             AND ACNTBBAL_INTERNAL_ACNUM = IDX.INT_AC_NO
             AND ACNTBBAL_YEAR = IDX.TRANSACTION_YEAR 
             AND ACNTBBAL_MONTH = IDX.TRANSACTION_MONTHS;
   END LOOP;
END;