SELECT * FROM 
(select I.IACLINK_INTERNAL_ACNUM,
      i.IACLINK_ACTUAL_ACNUM,
      I.IACLINK_BRN_CODE
 from iaclink i
where i.IACLINK_ENTITY_NUM = 1
  and (IACLINK_ACTUAL_ACNUM) in
      (SELECT IACLINK_ACTUAL_ACNUM
         FROM IACLINK
        WHERE IACLINK_ENTITY_NUM = 1
        GROUP BY IACLINK_ACTUAL_ACNUM 
       HAVING COUNT(*) > 1)
order by i.IACLINK_ACTUAL_ACNUM
) A,
(select I.IACLINK_INTERNAL_ACNUM,
      i.IACLINK_ACTUAL_ACNUM,
      I.IACLINK_BRN_CODE
 from iaclink i
where i.IACLINK_ENTITY_NUM = 1
  and (IACLINK_ACTUAL_ACNUM) in
      (SELECT IACLINK_ACTUAL_ACNUM
         FROM IACLINK
        WHERE IACLINK_ENTITY_NUM = 1
        GROUP BY IACLINK_ACTUAL_ACNUM 
       HAVING COUNT(*) > 1)
order by i.IACLINK_ACTUAL_ACNUM
) B
WHERE A.IACLINK_ACTUAL_ACNUM = B.IACLINK_ACTUAL_ACNUM
AND A.IACLINK_BRN_CODE <> B.IACLINK_BRN_CODE ;