/* Formatted on 2/20/2019 5:52:48 PM (QP5 v5.227.12220.39754) */
  SELECT :B1 TASK_ID,
         F.FINDING_ID FINDING_ID,
         DECODE (RECINFO.TYPE, NULL, 'Uncategorized', RECINFO.TYPE) REC_TYPE,
         RECINFO.RECCOUNT REC_COUNT,
         F.PERC_ACTIVE_SESS IMPACT_PCT,
         F.MESSAGE MESSAGE,
         TO_DATE (:B3, 'MM-DD-YYYY HH24:MI:SS') START_TIME,
         TO_DATE (:B2, 'MM-DD-YYYY HH24:MI:SS') END_TIME,
         HISTORY.FINDING_COUNT FINDING_COUNT,
         F.FINDING_NAME FINDING_NAME,
         F.ACTIVE_SESSIONS ACTIVE_SESSIONS
    FROM DBA_ADDM_FINDINGS F,
         (  SELECT FINDING_ID, COUNT (R.REC_ID) RECCOUNT, R.TYPE
              FROM DBA_ADVISOR_RECOMMENDATIONS R
             WHERE TASK_ID = :B1
          GROUP BY R.FINDING_ID, R.TYPE) RECINFO,
         (  SELECT COUNT (F_ALL.TASK_ID) FINDING_COUNT, F_CURR.FINDING_NAME
              FROM (SELECT FINDING_NAME
                      FROM DBA_ADVISOR_FINDINGS
                     WHERE TASK_ID = :B1) F_CURR,
                   (SELECT T.TASK_ID,
                           I.LOCAL_TASK_ID,
                           T.END_TIME,
                           T.BEGIN_TIME
                      FROM DBA_ADDM_TASKS T, DBA_ADDM_INSTANCES I
                     WHERE     T.END_TIME > SYSDATE - 1
                           AND T.TASK_ID = I.TASK_ID
                           AND I.INSTANCE_NUMBER =
                                  SYS_CONTEXT ('USERENV', 'INSTANCE')
                           AND T.REQUESTED_ANALYSIS = 'INSTANCE') TASKS,
                   DBA_ADVISOR_FINDINGS F_ALL
             WHERE     F_ALL.TASK_ID = TASKS.TASK_ID
                   AND F_ALL.FINDING_NAME = F_CURR.FINDING_NAME
                   AND F_ALL.TYPE <> 'INFORMATION'
                   AND F_ALL.TYPE <> 'WARNING'
                   AND F_ALL.PARENT = 0
          GROUP BY F_CURR.FINDING_NAME) HISTORY
   WHERE     F.TASK_ID = :B1
         AND F.TYPE <> 'INFORMATION'
         AND F.TYPE <> 'WARNING'
         AND F.FILTERED <> 'Y'
         AND F.PARENT = 0
         AND F.FINDING_ID = RECINFO.FINDING_ID(+)
         AND F.FINDING_NAME = HISTORY.FINDING_NAME
ORDER BY F.FINDING_ID;





/* Formatted on 2/20/2019 5:56:45 PM (QP5 v5.227.12220.39754) */
  SELECT A.CAPTURE_NAME STREAMS_PROCESS_NAME,
         A.STATUS STREAMS_PROCESS_STATUS,
         'CAPTURE' STREAMS_PROCESS_TYPE,
         COUNT (A.ERROR_MESSAGE)
    FROM DBA_CAPTURE A
GROUP BY A.CAPTURE_NAME, A.STATUS
UNION ALL
  SELECT A.PROPAGATION_NAME STREAMS_PROCESS_NAME,
         A.STATUS STREAMS_PROCESS_STATUS,
         'PROPAGATION' STREAMS_PROCESS_TYPE,
         COUNT (A.ERROR_MESSAGE)
    FROM DBA_PROPAGATION A
GROUP BY A.PROPAGATION_NAME, A.STATUS
UNION ALL
  SELECT A.APPLY_NAME STREAMS_PROCESS_NAME,
         A.STATUS STREAMS_PROCESS_STATUS,
         'APPLY' STREAMS_PROCESS_TYPE,
         COUNT (A.ERROR_MESSAGE)
    FROM DBA_APPLY A
GROUP BY A.APPLY_NAME, A.STATUS