--STEP 1
ALTER TABLE BOPAUTHQ ADD BOPAUTHQ_SUBBRN_CODE NUMBER(8);


--STEP 2
BEGIN
   FOR IDX IN (SELECT * FROM MIG_DETAIL)
   LOOP
      UPDATE BOPAUTHQ
         SET BOPAUTHQ_SUBBRN_CODE = 0
       WHERE     BOPAUTHQ_ENTITY_NUM = 1
             AND BOPAUTHQ_TRAN_BRN_CODE = IDX.BRANCH_CODE;

      COMMIT;
   END LOOP;
END;
--AFTER COMPLETE  UPDATE THEN
--STEP 3
ALTER TABLE BOPAUTHQ  MODIFY(BOPAUTHQ_SUBBRN_CODE DEFAULT 0);





---------------limit line

ALTER TABLE LIMITLINE ADD LMTLINE_LOAN_TYPE VARCHAR2(10);
ALTER TABLE LIMITLINE ADD LMTLINE_LOAN_SUB_TYPE VARCHAR2(10);
ALTER TABLE LIMITLINE ADD LMTLINE_SANC_FROM_HO CHAR(1) default 0;
ALTER TABLE LIMITLINE ADD LMTLINE_HO_DIV_CODE VARCHAR2(10);

ALTER TABLE LIMITLINEHIST ADD LIMLNEHIST_LOAN_TYPE VARCHAR2(10);
ALTER TABLE LIMITLINEHIST ADD LIMLNEHIST_LOAN_SUB_TYPE VARCHAR2(10);
ALTER TABLE LIMITLINEHIST ADD LIMLNEHIST_SANC_FROM_HO CHAR(1) default 0;
ALTER TABLE LIMITLINEHIST ADD LIMLNEHIST_HO_DIV_CODE VARCHAR2(10);


BEGIN
   FOR IDX IN (SELECT * FROM MIG_DETAIL)
   LOOP
      UPDATE LIMITLINEHIST
         SET LIMLNEHIST_SANC_FROM_HO = 0
       WHERE     LIMLNEHIST_ENTITY_NUM = 1
       and LIMLNEHIST_SANC_FROM_HO is null
             AND LIMLNEHIST_HOME_BRANCH = IDX.BRANCH_CODE;
      UPDATE LIMITLINE
         SET LMTLINE_SANC_FROM_HO = 0
       WHERE     LMTLINE_ENTITY_NUM = 1
       and LMTLINE_SANC_FROM_HO is null
             AND LMTLINE_HOME_BRANCH = IDX.BRANCH_CODE;

      COMMIT;
   END LOOP;
END;


ALTER TABLE LIMITLINEHIST  MODIFY(LIMLNEHIST_SANC_FROM_HO DEFAULT 0);

ALTER TABLE LIMITLINE  MODIFY(LMTLINE_SANC_FROM_HO DEFAULT 0);


ALTER TABLE LOANACNTS  ADD(LNACNT_LOAN_SUB_TYPE VARCHAR2(10));

, 