--------------banks-----------------

SELECT  A.ACNTS_BRN_CODE, 
             (SELECT B.MBRN_NAME FROM MBRN B
               WHERE B.MBRN_ENTITY_NUM = A.ACNTS_ENTITY_NUM 
                    AND B.MBRN_CODE = A.ACNTS_BRN_CODE )  BRN_NAME,
             FACNO(1, A.ACNTS_INTERNAL_ACNUM) ACNUM, A.ACNTS_AC_NAME1, B.ACBALH_ASON_DATE, B.ACBALH_BC_BAL 
   FROM ACNTS A, ACBALASONHIST B  
WHERE  A.ACNTS_ENTITY_NUM = B.ACBALH_ENTITY_NUM
     AND A.ACNTS_INTERNAL_ACNUM = B.ACBALH_INTERNAL_ACNUM
     AND A.ACNTS_ENTITY_NUM = 1
     AND A.ACNTS_PROD_CODE = 1030
     AND UPPER(A.ACNTS_AC_NAME1) LIKE '%BANK%' 
     AND ACBALH_ASON_DATE BETWEEN '01-NOV-2022' AND '15-NOV-2022'
ORDER BY 1, 3, 5     ;

----------non banks----------------

SELECT  A.ACNTS_BRN_CODE,  
             (SELECT B.MBRN_NAME FROM MBRN B
               WHERE B.MBRN_ENTITY_NUM = A.ACNTS_ENTITY_NUM 
                    AND B.MBRN_CODE = A.ACNTS_BRN_CODE )  BRN_NAME,
             FACNO(1, A.ACNTS_INTERNAL_ACNUM) ACNUM, A.ACNTS_AC_NAME1, B.ACBALH_ASON_DATE, B.ACBALH_BC_BAL 
   FROM ACNTS A, ACBALASONHIST B  
WHERE  A.ACNTS_ENTITY_NUM = B.ACBALH_ENTITY_NUM
     AND A.ACNTS_INTERNAL_ACNUM = B.ACBALH_INTERNAL_ACNUM
     AND A.ACNTS_ENTITY_NUM = 1
     AND A.ACNTS_PROD_CODE = 1030
      AND ACBALH_ASON_DATE BETWEEN '01-NOV-2022' AND '15-NOV-2022'
     AND (
               UPPER(A.ACNTS_AC_NAME1) LIKE '%LANKABANGLA%'
        OR UPPER(A.ACNTS_AC_NAME1) LIKE '%DELTA BRAC%'
        OR UPPER(A.ACNTS_AC_NAME1) LIKE '%IDLC %'
        OR UPPER(A.ACNTS_AC_NAME1) LIKE '%UTTARA FINANCE%'
        OR UPPER(A.ACNTS_AC_NAME1) LIKE '%UNITED LEASING%'  
        OR UPPER(A.ACNTS_AC_NAME1) LIKE '%UNION CAPITAL%'
        OR UPPER(A.ACNTS_AC_NAME1) LIKE '%UAE-BANGLADESH%'
        OR UPPER(A.ACNTS_AC_NAME1) LIKE '%SAUDI-BANGLADESH%'
        OR UPPER(A.ACNTS_AC_NAME1) LIKE '%RELIANCE FINANCE%'
        OR UPPER(A.ACNTS_AC_NAME1) LIKE '%PRIME FINANCE%'
        OR UPPER(A.ACNTS_AC_NAME1) LIKE '%PREMIER LEASING%'
        OR UPPER(A.ACNTS_AC_NAME1) LIKE '%PHOENIX FINANCE%'
        OR UPPER(A.ACNTS_AC_NAME1) LIKE '%PEOPLE''S LEASING%'
        OR UPPER(A.ACNTS_AC_NAME1) LIKE '%NATIONAL HOUSING%'
        OR UPPER(A.ACNTS_AC_NAME1) LIKE '%NATIONAL FINANCE%'
        OR UPPER(A.ACNTS_AC_NAME1) LIKE '%MIDAS%'
        OR UPPER(A.ACNTS_AC_NAME1) LIKE '%ISLAMIC FINANCE%'
        OR UPPER(A.ACNTS_AC_NAME1) LIKE '%INTERNATIONAL LEASING%'
        OR UPPER(A.ACNTS_AC_NAME1) LIKE '%IDCOL%'
        OR UPPER(A.ACNTS_AC_NAME1) LIKE '%IIDFC%'
        OR UPPER(A.ACNTS_AC_NAME1) LIKE '%IPDC%'
        OR UPPER(A.ACNTS_AC_NAME1) LIKE '%HAJJ FINANCE%'
        OR UPPER(A.ACNTS_AC_NAME1) LIKE '%GSP FINANCE%'
        OR UPPER(A.ACNTS_AC_NAME1) LIKE '%FIRST LEASE%'
        OR UPPER(A.ACNTS_AC_NAME1) LIKE '%FAS FINANCE%'
        OR UPPER(A.ACNTS_AC_NAME1) LIKE '%BAY LEASING%'
        OR UPPER(A.ACNTS_AC_NAME1) LIKE '%BIFC%'
        OR UPPER(A.ACNTS_AC_NAME1) LIKE '%BANGLADESH FINANCE%'
        OR UPPER(A.ACNTS_AC_NAME1) LIKE '%ALLIANCE LEASING%'
        OR UPPER(A.ACNTS_AC_NAME1) LIKE '%BANGLADESH INDUSTRIAL FINANCE%'
        OR UPPER(A.ACNTS_AC_NAME1) LIKE '%BANGLADESH INFRASTRUCTURE FINANCE%'
        OR UPPER(A.ACNTS_AC_NAME1) LIKE '%CAPM VENTURE CAPITAL%'
         OR UPPER(A.ACNTS_AC_NAME1) LIKE '%AGRANI SME%'
        )
    AND ACNTS_CLOSURE_DATE is null       
   
