SELECT DISTINCT M.MBRN_NAME,  B.BRNSTATUS_CURR_DATE,B.BRNSTATUS_SIGN_IN,C.CASHCTL_CLOSING_INIT_FLAG
FROM BRNSTATUS B,CASHCTL C,MBRN M
WHERE B.BRNSTATUS_BRN_CODE=C.CASHCTL_BRN_CODE
AND C.CASHCTL_BRN_CODE=M.MBRN_CODE
AND B.BRNSTATUS_BRN_CODE=M.MBRN_CODE
AND B.BRNSTATUS_ENTITY_NUM=1
AND C.CASHCTL_ENTITY_NUM=1
AND M.MBRN_ENTITY_NUM=1
AND BRNSTATUS_STATUS='I'
AND B.BRNSTATUS_CURR_DATE=TO_DATE(SYSDATE)