
Insert into BUDGETCNF
   (BUDGETCNF_ENTITY_NUM, BUDGETCNF_YEAR, BUDGETCNF_BDGT_FROM_MNTH, BUDGETCNF_BDGT_TO_MNTH, BUDGETCNF_BDGT_CURR, 
    BUDGETCNF_BDGT_AMT_UNITS, BUDGETCNF_ENTD_BY, BUDGETCNF_ENTD_ON, BUDGETCNF_LAST_MOD_BY, BUDGETCNF_LAST_MOD_ON, 
    BUDGETCNF_AUTH_BY, BUDGETCNF_AUTH_ON, TBA_MAIN_KEY)
 Values
   (1, 2023, 1, 12, 'BDT', 
    'one', 'M26', TO_DATE('12/01/2022 10:43:03', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    'M26', TO_DATE('12/01/2022 10:43:03', 'MM/DD/YYYY HH24:MI:SS'), NULL);


Insert into BUDGETCD
   (BUDGETCD_CODE, BUDGETCD_DESCN, BUDGETCD_TYPE_INCOME, BUDGETCD_TYPE_EXPENDITURE, BUDGETCD_TYPE_ASSET, 
    BUDGETCD_TYPE_LIABILITY, BUDGETCD_AMT_CHK_REQ, BUDGETCD_ENTD_BY, BUDGETCD_ENTD_ON, BUDGETCD_LAST_MOD_BY, 
    BUDGETCD_LAST_MOD_ON, BUDGETCD_AUTH_BY, BUDGETCD_AUTH_ON, TBA_MAIN_KEY)
 Values
   ('EXPENSE', 'Expense Budget - 01', '0', '1', '0', 
    '0', '1', 'MIG', TO_DATE('02/23/2023 14:10:27', 'MM/DD/YYYY HH24:MI:SS'), NULL, 
    NULL, NULL, NULL, NULL);


Insert into BUDGETICD
   (BUDGETICD_TYPE_CODE, BUDGETICD_ITEM_CODE, BUDGETICD_ITEM_TYPE, BUDGETICD_ITEM_DESCN, BUDGETICD_ENTD_BY, 
    BUDGETICD_ENTD_ON, BUDGETICD_LAST_MOD_BY, BUDGETICD_LAST_MOD_ON, BUDGETICD_AUTH_BY, BUDGETICD_AUTH_ON, 
    TBA_MAIN_KEY)
 Values
   ('EXPENSE', 'ESALAR0001', 'G', 'Salaries', 'MIGMAN', 
    TO_DATE('05/18/2023 10:43:41', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, NULL, NULL, 
    NULL);
Insert into BUDGETICD
   (BUDGETICD_TYPE_CODE, BUDGETICD_ITEM_CODE, BUDGETICD_ITEM_TYPE, BUDGETICD_ITEM_DESCN, BUDGETICD_ENTD_BY, 
    BUDGETICD_ENTD_ON, BUDGETICD_LAST_MOD_BY, BUDGETICD_LAST_MOD_ON, BUDGETICD_AUTH_BY, BUDGETICD_AUTH_ON, 
    TBA_MAIN_KEY)
 Values
   ('EXPENSE', 'ESALAR0002', 'G', 'Medical Allowances', 'MIGMAN', 
    TO_DATE('05/18/2023 10:43:41', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, NULL, NULL, 
    NULL);
Insert into BUDGETICD
   (BUDGETICD_TYPE_CODE, BUDGETICD_ITEM_CODE, BUDGETICD_ITEM_TYPE, BUDGETICD_ITEM_DESCN, BUDGETICD_ENTD_BY, 
    BUDGETICD_ENTD_ON, BUDGETICD_LAST_MOD_BY, BUDGETICD_LAST_MOD_ON, BUDGETICD_AUTH_BY, BUDGETICD_AUTH_ON, 
    TBA_MAIN_KEY)
 Values
   ('EXPENSE', 'ESALAR0003', 'G', 'Transportation Allowances', 'MIGMAN', 
    TO_DATE('05/18/2023 10:43:41', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, NULL, NULL, 
    NULL);
Insert into BUDGETICD
   (BUDGETICD_TYPE_CODE, BUDGETICD_ITEM_CODE, BUDGETICD_ITEM_TYPE, BUDGETICD_ITEM_DESCN, BUDGETICD_ENTD_BY, 
    BUDGETICD_ENTD_ON, BUDGETICD_LAST_MOD_BY, BUDGETICD_LAST_MOD_ON, BUDGETICD_AUTH_BY, BUDGETICD_AUTH_ON, 
    TBA_MAIN_KEY)
 Values
   ('EXPENSE', 'ESALAR0004', 'G', 'House rent Allowances', 'MIGMAN', 
    TO_DATE('05/18/2023 10:43:41', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, NULL, NULL, 
    NULL);
Insert into BUDGETICD
   (BUDGETICD_TYPE_CODE, BUDGETICD_ITEM_CODE, BUDGETICD_ITEM_TYPE, BUDGETICD_ITEM_DESCN, BUDGETICD_ENTD_BY, 
    BUDGETICD_ENTD_ON, BUDGETICD_LAST_MOD_BY, BUDGETICD_LAST_MOD_ON, BUDGETICD_AUTH_BY, BUDGETICD_AUTH_ON, 
    TBA_MAIN_KEY)
 Values
   ('EXPENSE', 'ESALAR0005', 'G', 'Lunch Coupon', 'MIGMAN', 
    TO_DATE('05/18/2023 10:43:41', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, NULL, NULL, 
    NULL);
Insert into BUDGETICD
   (BUDGETICD_TYPE_CODE, BUDGETICD_ITEM_CODE, BUDGETICD_ITEM_TYPE, BUDGETICD_ITEM_DESCN, BUDGETICD_ENTD_BY, 
    BUDGETICD_ENTD_ON, BUDGETICD_LAST_MOD_BY, BUDGETICD_LAST_MOD_ON, BUDGETICD_AUTH_BY, BUDGETICD_AUTH_ON, 
    TBA_MAIN_KEY)
 Values
   ('EXPENSE', 'ESALAR0006', 'G', 'Children Education Allowance', 'MIGMAN', 
    TO_DATE('05/18/2023 10:43:41', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, NULL, NULL, 
    NULL);
Insert into BUDGETICD
   (BUDGETICD_TYPE_CODE, BUDGETICD_ITEM_CODE, BUDGETICD_ITEM_TYPE, BUDGETICD_ITEM_DESCN, BUDGETICD_ENTD_BY, 
    BUDGETICD_ENTD_ON, BUDGETICD_LAST_MOD_BY, BUDGETICD_LAST_MOD_ON, BUDGETICD_AUTH_BY, BUDGETICD_AUTH_ON, 
    TBA_MAIN_KEY)
 Values
   ('EXPENSE', 'ESALAR0007', 'G', 'Contributory Provident Fund', 'MIGMAN', 
    TO_DATE('05/18/2023 10:43:41', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, NULL, NULL, 
    NULL);
Insert into BUDGETICD
   (BUDGETICD_TYPE_CODE, BUDGETICD_ITEM_CODE, BUDGETICD_ITEM_TYPE, BUDGETICD_ITEM_DESCN, BUDGETICD_ENTD_BY, 
    BUDGETICD_ENTD_ON, BUDGETICD_LAST_MOD_BY, BUDGETICD_LAST_MOD_ON, BUDGETICD_AUTH_BY, BUDGETICD_AUTH_ON, 
    TBA_MAIN_KEY)
 Values
   ('EXPENSE', 'ESALAR0008', 'G', 'Pension Fund', 'MIGMAN', 
    TO_DATE('05/18/2023 10:43:41', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, NULL, NULL, 
    NULL);
Insert into BUDGETICD
   (BUDGETICD_TYPE_CODE, BUDGETICD_ITEM_CODE, BUDGETICD_ITEM_TYPE, BUDGETICD_ITEM_DESCN, BUDGETICD_ENTD_BY, 
    BUDGETICD_ENTD_ON, BUDGETICD_LAST_MOD_BY, BUDGETICD_LAST_MOD_ON, BUDGETICD_AUTH_BY, BUDGETICD_AUTH_ON, 
    TBA_MAIN_KEY)
 Values
   ('EXPENSE', 'ESALAR0009', 'G', 'Bonus - Festival', 'MIGMAN', 
    TO_DATE('05/18/2023 10:43:41', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, NULL, NULL, 
    NULL);
Insert into BUDGETICD
   (BUDGETICD_TYPE_CODE, BUDGETICD_ITEM_CODE, BUDGETICD_ITEM_TYPE, BUDGETICD_ITEM_DESCN, BUDGETICD_ENTD_BY, 
    BUDGETICD_ENTD_ON, BUDGETICD_LAST_MOD_BY, BUDGETICD_LAST_MOD_ON, BUDGETICD_AUTH_BY, BUDGETICD_AUTH_ON, 
    TBA_MAIN_KEY)
 Values
   ('EXPENSE', 'ESALAR0010', 'G', 'Nabobarsho Allowance', 'MIGMAN', 
    TO_DATE('05/18/2023 10:43:41', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, NULL, NULL, 
    NULL);
Insert into BUDGETICD
   (BUDGETICD_TYPE_CODE, BUDGETICD_ITEM_CODE, BUDGETICD_ITEM_TYPE, BUDGETICD_ITEM_DESCN, BUDGETICD_ENTD_BY, 
    BUDGETICD_ENTD_ON, BUDGETICD_LAST_MOD_BY, BUDGETICD_LAST_MOD_ON, BUDGETICD_AUTH_BY, BUDGETICD_AUTH_ON, 
    TBA_MAIN_KEY)
 Values
   ('EXPENSE', 'ESALAR0011', 'G', 'Entertainment', 'MIGMAN', 
    TO_DATE('05/18/2023 10:43:41', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, NULL, NULL, 
    NULL);
Insert into BUDGETICD
   (BUDGETICD_TYPE_CODE, BUDGETICD_ITEM_CODE, BUDGETICD_ITEM_TYPE, BUDGETICD_ITEM_DESCN, BUDGETICD_ENTD_BY, 
    BUDGETICD_ENTD_ON, BUDGETICD_LAST_MOD_BY, BUDGETICD_LAST_MOD_ON, BUDGETICD_AUTH_BY, BUDGETICD_AUTH_ON, 
    TBA_MAIN_KEY)
 Values
   ('EXPENSE', 'ESALAR0012', 'G', 'Over Time', 'MIGMAN', 
    TO_DATE('05/18/2023 10:43:41', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, NULL, NULL, 
    NULL);
Insert into BUDGETICD
   (BUDGETICD_TYPE_CODE, BUDGETICD_ITEM_CODE, BUDGETICD_ITEM_TYPE, BUDGETICD_ITEM_DESCN, BUDGETICD_ENTD_BY, 
    BUDGETICD_ENTD_ON, BUDGETICD_LAST_MOD_BY, BUDGETICD_LAST_MOD_ON, BUDGETICD_AUTH_BY, BUDGETICD_AUTH_ON, 
    TBA_MAIN_KEY)
 Values
   ('EXPENSE', 'ESALAR0013', 'G', 'Washing Allowances', 'MIGMAN', 
    TO_DATE('05/18/2023 10:43:41', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, NULL, NULL, 
    NULL);
Insert into BUDGETICD
   (BUDGETICD_TYPE_CODE, BUDGETICD_ITEM_CODE, BUDGETICD_ITEM_TYPE, BUDGETICD_ITEM_DESCN, BUDGETICD_ENTD_BY, 
    BUDGETICD_ENTD_ON, BUDGETICD_LAST_MOD_BY, BUDGETICD_LAST_MOD_ON, BUDGETICD_AUTH_BY, BUDGETICD_AUTH_ON, 
    TBA_MAIN_KEY)
 Values
   ('EXPENSE', 'ESALAR0014', 'G', 'Recreation allowances', 'MIGMAN', 
    TO_DATE('05/18/2023 10:43:41', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, NULL, NULL, 
    NULL);
Insert into BUDGETICD
   (BUDGETICD_TYPE_CODE, BUDGETICD_ITEM_CODE, BUDGETICD_ITEM_TYPE, BUDGETICD_ITEM_DESCN, BUDGETICD_ENTD_BY, 
    BUDGETICD_ENTD_ON, BUDGETICD_LAST_MOD_BY, BUDGETICD_LAST_MOD_ON, BUDGETICD_AUTH_BY, BUDGETICD_AUTH_ON, 
    TBA_MAIN_KEY)
 Values
   ('EXPENSE', 'EOFFIC0001', 'G', 'Stationary', 'MIGMAN', 
    TO_DATE('05/18/2023 10:43:41', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, NULL, NULL, 
    NULL);
Insert into BUDGETICD
   (BUDGETICD_TYPE_CODE, BUDGETICD_ITEM_CODE, BUDGETICD_ITEM_TYPE, BUDGETICD_ITEM_DESCN, BUDGETICD_ENTD_BY, 
    BUDGETICD_ENTD_ON, BUDGETICD_LAST_MOD_BY, BUDGETICD_LAST_MOD_ON, BUDGETICD_AUTH_BY, BUDGETICD_AUTH_ON, 
    TBA_MAIN_KEY)
 Values
   ('EXPENSE', 'EOFFIC0002', 'G', 'Tax', 'MIGMAN', 
    TO_DATE('05/18/2023 10:43:41', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, NULL, NULL, 
    NULL);
Insert into BUDGETICD
   (BUDGETICD_TYPE_CODE, BUDGETICD_ITEM_CODE, BUDGETICD_ITEM_TYPE, BUDGETICD_ITEM_DESCN, BUDGETICD_ENTD_BY, 
    BUDGETICD_ENTD_ON, BUDGETICD_LAST_MOD_BY, BUDGETICD_LAST_MOD_ON, BUDGETICD_AUTH_BY, BUDGETICD_AUTH_ON, 
    TBA_MAIN_KEY)
 Values
   ('EXPENSE', 'EOFFIC0003', 'G', 'Rent (Bank building)', 'MIGMAN', 
    TO_DATE('05/18/2023 10:43:41', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, NULL, NULL, 
    NULL);
Insert into BUDGETICD
   (BUDGETICD_TYPE_CODE, BUDGETICD_ITEM_CODE, BUDGETICD_ITEM_TYPE, BUDGETICD_ITEM_DESCN, BUDGETICD_ENTD_BY, 
    BUDGETICD_ENTD_ON, BUDGETICD_LAST_MOD_BY, BUDGETICD_LAST_MOD_ON, BUDGETICD_AUTH_BY, BUDGETICD_AUTH_ON, 
    TBA_MAIN_KEY)
 Values
   ('EXPENSE', 'EOFFIC0004', 'G', 'Clothing', 'MIGMAN', 
    TO_DATE('05/18/2023 10:43:41', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, NULL, NULL, 
    NULL);
Insert into BUDGETICD
   (BUDGETICD_TYPE_CODE, BUDGETICD_ITEM_CODE, BUDGETICD_ITEM_TYPE, BUDGETICD_ITEM_DESCN, BUDGETICD_ENTD_BY, 
    BUDGETICD_ENTD_ON, BUDGETICD_LAST_MOD_BY, BUDGETICD_LAST_MOD_ON, BUDGETICD_AUTH_BY, BUDGETICD_AUTH_ON, 
    TBA_MAIN_KEY)
 Values
   ('EXPENSE', 'EOFFIC0005', 'G', 'Telephone (Office)', 'MIGMAN', 
    TO_DATE('05/18/2023 10:43:41', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, NULL, NULL, 
    NULL);
Insert into BUDGETICD
   (BUDGETICD_TYPE_CODE, BUDGETICD_ITEM_CODE, BUDGETICD_ITEM_TYPE, BUDGETICD_ITEM_DESCN, BUDGETICD_ENTD_BY, 
    BUDGETICD_ENTD_ON, BUDGETICD_LAST_MOD_BY, BUDGETICD_LAST_MOD_ON, BUDGETICD_AUTH_BY, BUDGETICD_AUTH_ON, 
    TBA_MAIN_KEY)
 Values
   ('EXPENSE', 'EOFFIC0006', 'G', 'Residential', 'MIGMAN', 
    TO_DATE('05/18/2023 10:43:41', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, NULL, NULL, 
    NULL);
Insert into BUDGETICD
   (BUDGETICD_TYPE_CODE, BUDGETICD_ITEM_CODE, BUDGETICD_ITEM_TYPE, BUDGETICD_ITEM_DESCN, BUDGETICD_ENTD_BY, 
    BUDGETICD_ENTD_ON, BUDGETICD_LAST_MOD_BY, BUDGETICD_LAST_MOD_ON, BUDGETICD_AUTH_BY, BUDGETICD_AUTH_ON, 
    TBA_MAIN_KEY)
 Values
   ('EXPENSE', 'EOFFIC0007', 'G', 'Postage', 'MIGMAN', 
    TO_DATE('05/18/2023 10:43:41', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, NULL, NULL, 
    NULL);
Insert into BUDGETICD
   (BUDGETICD_TYPE_CODE, BUDGETICD_ITEM_CODE, BUDGETICD_ITEM_TYPE, BUDGETICD_ITEM_DESCN, BUDGETICD_ENTD_BY, 
    BUDGETICD_ENTD_ON, BUDGETICD_LAST_MOD_BY, BUDGETICD_LAST_MOD_ON, BUDGETICD_AUTH_BY, BUDGETICD_AUTH_ON, 
    TBA_MAIN_KEY)
 Values
   ('EXPENSE', 'EOFFIC0008', 'G', 'Travelling Expenses', 'MIGMAN', 
    TO_DATE('05/18/2023 10:43:41', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, NULL, NULL, 
    NULL);
Insert into BUDGETICD
   (BUDGETICD_TYPE_CODE, BUDGETICD_ITEM_CODE, BUDGETICD_ITEM_TYPE, BUDGETICD_ITEM_DESCN, BUDGETICD_ENTD_BY, 
    BUDGETICD_ENTD_ON, BUDGETICD_LAST_MOD_BY, BUDGETICD_LAST_MOD_ON, BUDGETICD_AUTH_BY, BUDGETICD_AUTH_ON, 
    TBA_MAIN_KEY)
 Values
   ('EXPENSE', 'EOFFIC0009', 'G', 'Petrol/Mobil', 'MIGMAN', 
    TO_DATE('05/18/2023 10:43:41', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, NULL, NULL, 
    NULL);
Insert into BUDGETICD
   (BUDGETICD_TYPE_CODE, BUDGETICD_ITEM_CODE, BUDGETICD_ITEM_TYPE, BUDGETICD_ITEM_DESCN, BUDGETICD_ENTD_BY, 
    BUDGETICD_ENTD_ON, BUDGETICD_LAST_MOD_BY, BUDGETICD_LAST_MOD_ON, BUDGETICD_AUTH_BY, BUDGETICD_AUTH_ON, 
    TBA_MAIN_KEY)
 Values
   ('EXPENSE', 'EOFFIC0010', 'G', 'Books', 'MIGMAN', 
    TO_DATE('05/18/2023 10:43:41', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, NULL, NULL, 
    NULL);
Insert into BUDGETICD
   (BUDGETICD_TYPE_CODE, BUDGETICD_ITEM_CODE, BUDGETICD_ITEM_TYPE, BUDGETICD_ITEM_DESCN, BUDGETICD_ENTD_BY, 
    BUDGETICD_ENTD_ON, BUDGETICD_LAST_MOD_BY, BUDGETICD_LAST_MOD_ON, BUDGETICD_AUTH_BY, BUDGETICD_AUTH_ON, 
    TBA_MAIN_KEY)
 Values
   ('EXPENSE', 'EOFFIC0011', 'G', 'Honorarium', 'MIGMAN', 
    TO_DATE('05/18/2023 10:43:41', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, NULL, NULL, 
    NULL);
Insert into BUDGETICD
   (BUDGETICD_TYPE_CODE, BUDGETICD_ITEM_CODE, BUDGETICD_ITEM_TYPE, BUDGETICD_ITEM_DESCN, BUDGETICD_ENTD_BY, 
    BUDGETICD_ENTD_ON, BUDGETICD_LAST_MOD_BY, BUDGETICD_LAST_MOD_ON, BUDGETICD_AUTH_BY, BUDGETICD_AUTH_ON, 
    TBA_MAIN_KEY)
 Values
   ('EXPENSE', 'EOFFIC0012', 'G', 'Lighting', 'MIGMAN', 
    TO_DATE('05/18/2023 10:43:41', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, NULL, NULL, 
    NULL);
Insert into BUDGETICD
   (BUDGETICD_TYPE_CODE, BUDGETICD_ITEM_CODE, BUDGETICD_ITEM_TYPE, BUDGETICD_ITEM_DESCN, BUDGETICD_ENTD_BY, 
    BUDGETICD_ENTD_ON, BUDGETICD_LAST_MOD_BY, BUDGETICD_LAST_MOD_ON, BUDGETICD_AUTH_BY, BUDGETICD_AUTH_ON, 
    TBA_MAIN_KEY)
 Values
   ('EXPENSE', 'EOFFIC0013', 'G', 'Law consultant Fee', 'MIGMAN', 
    TO_DATE('05/18/2023 10:43:41', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, NULL, NULL, 
    NULL);
Insert into BUDGETICD
   (BUDGETICD_TYPE_CODE, BUDGETICD_ITEM_CODE, BUDGETICD_ITEM_TYPE, BUDGETICD_ITEM_DESCN, BUDGETICD_ENTD_BY, 
    BUDGETICD_ENTD_ON, BUDGETICD_LAST_MOD_BY, BUDGETICD_LAST_MOD_ON, BUDGETICD_AUTH_BY, BUDGETICD_AUTH_ON, 
    TBA_MAIN_KEY)
 Values
   ('EXPENSE', 'EOFFIC0014', 'G', 'Generator Maintenance', 'MIGMAN', 
    TO_DATE('05/18/2023 10:43:41', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, NULL, NULL, 
    NULL);
Insert into BUDGETICD
   (BUDGETICD_TYPE_CODE, BUDGETICD_ITEM_CODE, BUDGETICD_ITEM_TYPE, BUDGETICD_ITEM_DESCN, BUDGETICD_ENTD_BY, 
    BUDGETICD_ENTD_ON, BUDGETICD_LAST_MOD_BY, BUDGETICD_LAST_MOD_ON, BUDGETICD_AUTH_BY, BUDGETICD_AUTH_ON, 
    TBA_MAIN_KEY)
 Values
   ('EXPENSE', 'EOFFIC0015', 'G', 'Police/Ansar Expenses', 'MIGMAN', 
    TO_DATE('05/18/2023 10:43:41', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, NULL, NULL, 
    NULL);
Insert into BUDGETICD
   (BUDGETICD_TYPE_CODE, BUDGETICD_ITEM_CODE, BUDGETICD_ITEM_TYPE, BUDGETICD_ITEM_DESCN, BUDGETICD_ENTD_BY, 
    BUDGETICD_ENTD_ON, BUDGETICD_LAST_MOD_BY, BUDGETICD_LAST_MOD_ON, BUDGETICD_AUTH_BY, BUDGETICD_AUTH_ON, 
    TBA_MAIN_KEY)
 Values
   ('EXPENSE', 'EREPAI0001', 'G', 'Transport', 'MIGMAN', 
    TO_DATE('05/18/2023 10:43:41', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, NULL, NULL, 
    NULL);
Insert into BUDGETICD
   (BUDGETICD_TYPE_CODE, BUDGETICD_ITEM_CODE, BUDGETICD_ITEM_TYPE, BUDGETICD_ITEM_DESCN, BUDGETICD_ENTD_BY, 
    BUDGETICD_ENTD_ON, BUDGETICD_LAST_MOD_BY, BUDGETICD_LAST_MOD_ON, BUDGETICD_AUTH_BY, BUDGETICD_AUTH_ON, 
    TBA_MAIN_KEY)
 Values
   ('EXPENSE', 'EREPAI0002', 'G', 'Office Equipment', 'MIGMAN', 
    TO_DATE('05/18/2023 10:43:41', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, NULL, NULL, 
    NULL);
Insert into BUDGETICD
   (BUDGETICD_TYPE_CODE, BUDGETICD_ITEM_CODE, BUDGETICD_ITEM_TYPE, BUDGETICD_ITEM_DESCN, BUDGETICD_ENTD_BY, 
    BUDGETICD_ENTD_ON, BUDGETICD_LAST_MOD_BY, BUDGETICD_LAST_MOD_ON, BUDGETICD_AUTH_BY, BUDGETICD_AUTH_ON, 
    TBA_MAIN_KEY)
 Values
   ('EXPENSE', 'EREPAI0003', 'G', 'Electric Equipment', 'MIGMAN', 
    TO_DATE('05/18/2023 10:43:41', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, NULL, NULL, 
    NULL);
Insert into BUDGETICD
   (BUDGETICD_TYPE_CODE, BUDGETICD_ITEM_CODE, BUDGETICD_ITEM_TYPE, BUDGETICD_ITEM_DESCN, BUDGETICD_ENTD_BY, 
    BUDGETICD_ENTD_ON, BUDGETICD_LAST_MOD_BY, BUDGETICD_LAST_MOD_ON, BUDGETICD_AUTH_BY, BUDGETICD_AUTH_ON, 
    TBA_MAIN_KEY)
 Values
   ('EXPENSE', 'EREPAI0004', 'G', 'Furniture', 'MIGMAN', 
    TO_DATE('05/18/2023 10:43:41', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, NULL, NULL, 
    NULL);
Insert into BUDGETICD
   (BUDGETICD_TYPE_CODE, BUDGETICD_ITEM_CODE, BUDGETICD_ITEM_TYPE, BUDGETICD_ITEM_DESCN, BUDGETICD_ENTD_BY, 
    BUDGETICD_ENTD_ON, BUDGETICD_LAST_MOD_BY, BUDGETICD_LAST_MOD_ON, BUDGETICD_AUTH_BY, BUDGETICD_AUTH_ON, 
    TBA_MAIN_KEY)
 Values
   ('EXPENSE', 'EREPAI0005', 'G', 'Computer Hardware', 'MIGMAN', 
    TO_DATE('05/18/2023 10:43:41', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, NULL, NULL, 
    NULL);
Insert into BUDGETICD
   (BUDGETICD_TYPE_CODE, BUDGETICD_ITEM_CODE, BUDGETICD_ITEM_TYPE, BUDGETICD_ITEM_DESCN, BUDGETICD_ENTD_BY, 
    BUDGETICD_ENTD_ON, BUDGETICD_LAST_MOD_BY, BUDGETICD_LAST_MOD_ON, BUDGETICD_AUTH_BY, BUDGETICD_AUTH_ON, 
    TBA_MAIN_KEY)
 Values
   ('EXPENSE', 'EREPAI0006', 'G', 'Rent Of connectivity/CCTV/Internet', 'MIGMAN', 
    TO_DATE('05/18/2023 10:43:41', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, NULL, NULL, 
    NULL);
Insert into BUDGETICD
   (BUDGETICD_TYPE_CODE, BUDGETICD_ITEM_CODE, BUDGETICD_ITEM_TYPE, BUDGETICD_ITEM_DESCN, BUDGETICD_ENTD_BY, 
    BUDGETICD_ENTD_ON, BUDGETICD_LAST_MOD_BY, BUDGETICD_LAST_MOD_ON, BUDGETICD_AUTH_BY, BUDGETICD_AUTH_ON, 
    TBA_MAIN_KEY)
 Values
   ('EXPENSE', 'EOTHER0001', 'G', 'Insurance', 'MIGMAN', 
    TO_DATE('05/18/2023 10:43:41', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, NULL, NULL, 
    NULL);
Insert into BUDGETICD
   (BUDGETICD_TYPE_CODE, BUDGETICD_ITEM_CODE, BUDGETICD_ITEM_TYPE, BUDGETICD_ITEM_DESCN, BUDGETICD_ENTD_BY, 
    BUDGETICD_ENTD_ON, BUDGETICD_LAST_MOD_BY, BUDGETICD_LAST_MOD_ON, BUDGETICD_AUTH_BY, BUDGETICD_AUTH_ON, 
    TBA_MAIN_KEY)
 Values
   ('EXPENSE', 'EOTHER0002', 'G', 'Interest On SBG', 'MIGMAN', 
    TO_DATE('05/18/2023 10:43:41', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, NULL, NULL, 
    NULL);
Insert into BUDGETICD
   (BUDGETICD_TYPE_CODE, BUDGETICD_ITEM_CODE, BUDGETICD_ITEM_TYPE, BUDGETICD_ITEM_DESCN, BUDGETICD_ENTD_BY, 
    BUDGETICD_ENTD_ON, BUDGETICD_LAST_MOD_BY, BUDGETICD_LAST_MOD_ON, BUDGETICD_AUTH_BY, BUDGETICD_AUTH_ON, 
    TBA_MAIN_KEY)
 Values
   ('EXPENSE', 'EOTHER0003', 'G', 'Transportation Fare', 'MIGMAN', 
    TO_DATE('05/18/2023 10:43:41', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, NULL, NULL, 
    NULL);
Insert into BUDGETICD
   (BUDGETICD_TYPE_CODE, BUDGETICD_ITEM_CODE, BUDGETICD_ITEM_TYPE, BUDGETICD_ITEM_DESCN, BUDGETICD_ENTD_BY, 
    BUDGETICD_ENTD_ON, BUDGETICD_LAST_MOD_BY, BUDGETICD_LAST_MOD_ON, BUDGETICD_AUTH_BY, BUDGETICD_AUTH_ON, 
    TBA_MAIN_KEY)
 Values
   ('EXPENSE', 'EOTHER0004', 'G', 'Trainning Expenses', 'MIGMAN', 
    TO_DATE('05/18/2023 10:43:41', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, NULL, NULL, 
    NULL);
Insert into BUDGETICD
   (BUDGETICD_TYPE_CODE, BUDGETICD_ITEM_CODE, BUDGETICD_ITEM_TYPE, BUDGETICD_ITEM_DESCN, BUDGETICD_ENTD_BY, 
    BUDGETICD_ENTD_ON, BUDGETICD_LAST_MOD_BY, BUDGETICD_LAST_MOD_ON, BUDGETICD_AUTH_BY, BUDGETICD_AUTH_ON, 
    TBA_MAIN_KEY)
 Values
   ('EXPENSE', 'EOTHER0005', 'G', 'Office Contingency', 'MIGMAN', 
    TO_DATE('05/18/2023 10:43:41', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, NULL, NULL, 
    NULL);


Insert into BDGTITEMDTL
   (BDGTITEMDTL_ENTITY_NUM, BDGTITEMDTL_TYPE_CODE, BDGTITEMDTL_ITEM_CODE, BDGTITEMDTL_EFF_DATE, BDGTITEMDTL_ENTD_ON, 
    BDGTITEMDTL_ENTD_BY, BDGTITEMDTL_MOD_ON, BDGTITEMDTL_MOD_BY, BDGTITEMDTL_AUTH_ON, BDGTITEMDTL_AUTH_BY, 
    TBA_MAIN_KEY)
 Values
   (1, 'EXPENSE', 'ESALAR0001', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/18/2023 10:44:46', 'MM/DD/YYYY HH24:MI:SS'), 
    'MIGMAN', NULL, NULL, NULL, NULL, 
    NULL);
Insert into BDGTITEMDTL
   (BDGTITEMDTL_ENTITY_NUM, BDGTITEMDTL_TYPE_CODE, BDGTITEMDTL_ITEM_CODE, BDGTITEMDTL_EFF_DATE, BDGTITEMDTL_ENTD_ON, 
    BDGTITEMDTL_ENTD_BY, BDGTITEMDTL_MOD_ON, BDGTITEMDTL_MOD_BY, BDGTITEMDTL_AUTH_ON, BDGTITEMDTL_AUTH_BY, 
    TBA_MAIN_KEY)
 Values
   (1, 'EXPENSE', 'ESALAR0002', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/18/2023 10:44:46', 'MM/DD/YYYY HH24:MI:SS'), 
    'MIGMAN', NULL, NULL, NULL, NULL, 
    NULL);
Insert into BDGTITEMDTL
   (BDGTITEMDTL_ENTITY_NUM, BDGTITEMDTL_TYPE_CODE, BDGTITEMDTL_ITEM_CODE, BDGTITEMDTL_EFF_DATE, BDGTITEMDTL_ENTD_ON, 
    BDGTITEMDTL_ENTD_BY, BDGTITEMDTL_MOD_ON, BDGTITEMDTL_MOD_BY, BDGTITEMDTL_AUTH_ON, BDGTITEMDTL_AUTH_BY, 
    TBA_MAIN_KEY)
 Values
   (1, 'EXPENSE', 'ESALAR0003', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/18/2023 10:44:46', 'MM/DD/YYYY HH24:MI:SS'), 
    'MIGMAN', NULL, NULL, NULL, NULL, 
    NULL);
Insert into BDGTITEMDTL
   (BDGTITEMDTL_ENTITY_NUM, BDGTITEMDTL_TYPE_CODE, BDGTITEMDTL_ITEM_CODE, BDGTITEMDTL_EFF_DATE, BDGTITEMDTL_ENTD_ON, 
    BDGTITEMDTL_ENTD_BY, BDGTITEMDTL_MOD_ON, BDGTITEMDTL_MOD_BY, BDGTITEMDTL_AUTH_ON, BDGTITEMDTL_AUTH_BY, 
    TBA_MAIN_KEY)
 Values
   (1, 'EXPENSE', 'ESALAR0004', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/18/2023 10:44:46', 'MM/DD/YYYY HH24:MI:SS'), 
    'MIGMAN', NULL, NULL, NULL, NULL, 
    NULL);
Insert into BDGTITEMDTL
   (BDGTITEMDTL_ENTITY_NUM, BDGTITEMDTL_TYPE_CODE, BDGTITEMDTL_ITEM_CODE, BDGTITEMDTL_EFF_DATE, BDGTITEMDTL_ENTD_ON, 
    BDGTITEMDTL_ENTD_BY, BDGTITEMDTL_MOD_ON, BDGTITEMDTL_MOD_BY, BDGTITEMDTL_AUTH_ON, BDGTITEMDTL_AUTH_BY, 
    TBA_MAIN_KEY)
 Values
   (1, 'EXPENSE', 'ESALAR0005', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/18/2023 10:44:46', 'MM/DD/YYYY HH24:MI:SS'), 
    'MIGMAN', NULL, NULL, NULL, NULL, 
    NULL);
Insert into BDGTITEMDTL
   (BDGTITEMDTL_ENTITY_NUM, BDGTITEMDTL_TYPE_CODE, BDGTITEMDTL_ITEM_CODE, BDGTITEMDTL_EFF_DATE, BDGTITEMDTL_ENTD_ON, 
    BDGTITEMDTL_ENTD_BY, BDGTITEMDTL_MOD_ON, BDGTITEMDTL_MOD_BY, BDGTITEMDTL_AUTH_ON, BDGTITEMDTL_AUTH_BY, 
    TBA_MAIN_KEY)
 Values
   (1, 'EXPENSE', 'ESALAR0006', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/18/2023 10:44:46', 'MM/DD/YYYY HH24:MI:SS'), 
    'MIGMAN', NULL, NULL, NULL, NULL, 
    NULL);
Insert into BDGTITEMDTL
   (BDGTITEMDTL_ENTITY_NUM, BDGTITEMDTL_TYPE_CODE, BDGTITEMDTL_ITEM_CODE, BDGTITEMDTL_EFF_DATE, BDGTITEMDTL_ENTD_ON, 
    BDGTITEMDTL_ENTD_BY, BDGTITEMDTL_MOD_ON, BDGTITEMDTL_MOD_BY, BDGTITEMDTL_AUTH_ON, BDGTITEMDTL_AUTH_BY, 
    TBA_MAIN_KEY)
 Values
   (1, 'EXPENSE', 'ESALAR0007', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/18/2023 10:44:46', 'MM/DD/YYYY HH24:MI:SS'), 
    'MIGMAN', NULL, NULL, NULL, NULL, 
    NULL);
Insert into BDGTITEMDTL
   (BDGTITEMDTL_ENTITY_NUM, BDGTITEMDTL_TYPE_CODE, BDGTITEMDTL_ITEM_CODE, BDGTITEMDTL_EFF_DATE, BDGTITEMDTL_ENTD_ON, 
    BDGTITEMDTL_ENTD_BY, BDGTITEMDTL_MOD_ON, BDGTITEMDTL_MOD_BY, BDGTITEMDTL_AUTH_ON, BDGTITEMDTL_AUTH_BY, 
    TBA_MAIN_KEY)
 Values
   (1, 'EXPENSE', 'ESALAR0008', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/18/2023 10:44:46', 'MM/DD/YYYY HH24:MI:SS'), 
    'MIGMAN', NULL, NULL, NULL, NULL, 
    NULL);
Insert into BDGTITEMDTL
   (BDGTITEMDTL_ENTITY_NUM, BDGTITEMDTL_TYPE_CODE, BDGTITEMDTL_ITEM_CODE, BDGTITEMDTL_EFF_DATE, BDGTITEMDTL_ENTD_ON, 
    BDGTITEMDTL_ENTD_BY, BDGTITEMDTL_MOD_ON, BDGTITEMDTL_MOD_BY, BDGTITEMDTL_AUTH_ON, BDGTITEMDTL_AUTH_BY, 
    TBA_MAIN_KEY)
 Values
   (1, 'EXPENSE', 'ESALAR0009', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/18/2023 10:44:46', 'MM/DD/YYYY HH24:MI:SS'), 
    'MIGMAN', NULL, NULL, NULL, NULL, 
    NULL);
Insert into BDGTITEMDTL
   (BDGTITEMDTL_ENTITY_NUM, BDGTITEMDTL_TYPE_CODE, BDGTITEMDTL_ITEM_CODE, BDGTITEMDTL_EFF_DATE, BDGTITEMDTL_ENTD_ON, 
    BDGTITEMDTL_ENTD_BY, BDGTITEMDTL_MOD_ON, BDGTITEMDTL_MOD_BY, BDGTITEMDTL_AUTH_ON, BDGTITEMDTL_AUTH_BY, 
    TBA_MAIN_KEY)
 Values
   (1, 'EXPENSE', 'ESALAR0010', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/18/2023 10:44:46', 'MM/DD/YYYY HH24:MI:SS'), 
    'MIGMAN', NULL, NULL, NULL, NULL, 
    NULL);
Insert into BDGTITEMDTL
   (BDGTITEMDTL_ENTITY_NUM, BDGTITEMDTL_TYPE_CODE, BDGTITEMDTL_ITEM_CODE, BDGTITEMDTL_EFF_DATE, BDGTITEMDTL_ENTD_ON, 
    BDGTITEMDTL_ENTD_BY, BDGTITEMDTL_MOD_ON, BDGTITEMDTL_MOD_BY, BDGTITEMDTL_AUTH_ON, BDGTITEMDTL_AUTH_BY, 
    TBA_MAIN_KEY)
 Values
   (1, 'EXPENSE', 'ESALAR0011', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/18/2023 10:44:46', 'MM/DD/YYYY HH24:MI:SS'), 
    'MIGMAN', NULL, NULL, NULL, NULL, 
    NULL);
Insert into BDGTITEMDTL
   (BDGTITEMDTL_ENTITY_NUM, BDGTITEMDTL_TYPE_CODE, BDGTITEMDTL_ITEM_CODE, BDGTITEMDTL_EFF_DATE, BDGTITEMDTL_ENTD_ON, 
    BDGTITEMDTL_ENTD_BY, BDGTITEMDTL_MOD_ON, BDGTITEMDTL_MOD_BY, BDGTITEMDTL_AUTH_ON, BDGTITEMDTL_AUTH_BY, 
    TBA_MAIN_KEY)
 Values
   (1, 'EXPENSE', 'ESALAR0012', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/18/2023 10:44:46', 'MM/DD/YYYY HH24:MI:SS'), 
    'MIGMAN', NULL, NULL, NULL, NULL, 
    NULL);
Insert into BDGTITEMDTL
   (BDGTITEMDTL_ENTITY_NUM, BDGTITEMDTL_TYPE_CODE, BDGTITEMDTL_ITEM_CODE, BDGTITEMDTL_EFF_DATE, BDGTITEMDTL_ENTD_ON, 
    BDGTITEMDTL_ENTD_BY, BDGTITEMDTL_MOD_ON, BDGTITEMDTL_MOD_BY, BDGTITEMDTL_AUTH_ON, BDGTITEMDTL_AUTH_BY, 
    TBA_MAIN_KEY)
 Values
   (1, 'EXPENSE', 'ESALAR0013', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/18/2023 10:44:46', 'MM/DD/YYYY HH24:MI:SS'), 
    'MIGMAN', NULL, NULL, NULL, NULL, 
    NULL);
Insert into BDGTITEMDTL
   (BDGTITEMDTL_ENTITY_NUM, BDGTITEMDTL_TYPE_CODE, BDGTITEMDTL_ITEM_CODE, BDGTITEMDTL_EFF_DATE, BDGTITEMDTL_ENTD_ON, 
    BDGTITEMDTL_ENTD_BY, BDGTITEMDTL_MOD_ON, BDGTITEMDTL_MOD_BY, BDGTITEMDTL_AUTH_ON, BDGTITEMDTL_AUTH_BY, 
    TBA_MAIN_KEY)
 Values
   (1, 'EXPENSE', 'ESALAR0014', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/18/2023 10:44:46', 'MM/DD/YYYY HH24:MI:SS'), 
    'MIGMAN', NULL, NULL, NULL, NULL, 
    NULL);
Insert into BDGTITEMDTL
   (BDGTITEMDTL_ENTITY_NUM, BDGTITEMDTL_TYPE_CODE, BDGTITEMDTL_ITEM_CODE, BDGTITEMDTL_EFF_DATE, BDGTITEMDTL_ENTD_ON, 
    BDGTITEMDTL_ENTD_BY, BDGTITEMDTL_MOD_ON, BDGTITEMDTL_MOD_BY, BDGTITEMDTL_AUTH_ON, BDGTITEMDTL_AUTH_BY, 
    TBA_MAIN_KEY)
 Values
   (1, 'EXPENSE', 'EOFFIC0001', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/18/2023 10:44:46', 'MM/DD/YYYY HH24:MI:SS'), 
    'MIGMAN', NULL, NULL, NULL, NULL, 
    NULL);
Insert into BDGTITEMDTL
   (BDGTITEMDTL_ENTITY_NUM, BDGTITEMDTL_TYPE_CODE, BDGTITEMDTL_ITEM_CODE, BDGTITEMDTL_EFF_DATE, BDGTITEMDTL_ENTD_ON, 
    BDGTITEMDTL_ENTD_BY, BDGTITEMDTL_MOD_ON, BDGTITEMDTL_MOD_BY, BDGTITEMDTL_AUTH_ON, BDGTITEMDTL_AUTH_BY, 
    TBA_MAIN_KEY)
 Values
   (1, 'EXPENSE', 'EOFFIC0002', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/18/2023 10:44:46', 'MM/DD/YYYY HH24:MI:SS'), 
    'MIGMAN', NULL, NULL, NULL, NULL, 
    NULL);
Insert into BDGTITEMDTL
   (BDGTITEMDTL_ENTITY_NUM, BDGTITEMDTL_TYPE_CODE, BDGTITEMDTL_ITEM_CODE, BDGTITEMDTL_EFF_DATE, BDGTITEMDTL_ENTD_ON, 
    BDGTITEMDTL_ENTD_BY, BDGTITEMDTL_MOD_ON, BDGTITEMDTL_MOD_BY, BDGTITEMDTL_AUTH_ON, BDGTITEMDTL_AUTH_BY, 
    TBA_MAIN_KEY)
 Values
   (1, 'EXPENSE', 'EOFFIC0003', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/18/2023 10:44:46', 'MM/DD/YYYY HH24:MI:SS'), 
    'MIGMAN', NULL, NULL, NULL, NULL, 
    NULL);
Insert into BDGTITEMDTL
   (BDGTITEMDTL_ENTITY_NUM, BDGTITEMDTL_TYPE_CODE, BDGTITEMDTL_ITEM_CODE, BDGTITEMDTL_EFF_DATE, BDGTITEMDTL_ENTD_ON, 
    BDGTITEMDTL_ENTD_BY, BDGTITEMDTL_MOD_ON, BDGTITEMDTL_MOD_BY, BDGTITEMDTL_AUTH_ON, BDGTITEMDTL_AUTH_BY, 
    TBA_MAIN_KEY)
 Values
   (1, 'EXPENSE', 'EOFFIC0004', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/18/2023 10:44:46', 'MM/DD/YYYY HH24:MI:SS'), 
    'MIGMAN', NULL, NULL, NULL, NULL, 
    NULL);
Insert into BDGTITEMDTL
   (BDGTITEMDTL_ENTITY_NUM, BDGTITEMDTL_TYPE_CODE, BDGTITEMDTL_ITEM_CODE, BDGTITEMDTL_EFF_DATE, BDGTITEMDTL_ENTD_ON, 
    BDGTITEMDTL_ENTD_BY, BDGTITEMDTL_MOD_ON, BDGTITEMDTL_MOD_BY, BDGTITEMDTL_AUTH_ON, BDGTITEMDTL_AUTH_BY, 
    TBA_MAIN_KEY)
 Values
   (1, 'EXPENSE', 'EOFFIC0005', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/18/2023 10:44:46', 'MM/DD/YYYY HH24:MI:SS'), 
    'MIGMAN', NULL, NULL, NULL, NULL, 
    NULL);
Insert into BDGTITEMDTL
   (BDGTITEMDTL_ENTITY_NUM, BDGTITEMDTL_TYPE_CODE, BDGTITEMDTL_ITEM_CODE, BDGTITEMDTL_EFF_DATE, BDGTITEMDTL_ENTD_ON, 
    BDGTITEMDTL_ENTD_BY, BDGTITEMDTL_MOD_ON, BDGTITEMDTL_MOD_BY, BDGTITEMDTL_AUTH_ON, BDGTITEMDTL_AUTH_BY, 
    TBA_MAIN_KEY)
 Values
   (1, 'EXPENSE', 'EOFFIC0007', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/18/2023 10:44:46', 'MM/DD/YYYY HH24:MI:SS'), 
    'MIGMAN', NULL, NULL, NULL, NULL, 
    NULL);
Insert into BDGTITEMDTL
   (BDGTITEMDTL_ENTITY_NUM, BDGTITEMDTL_TYPE_CODE, BDGTITEMDTL_ITEM_CODE, BDGTITEMDTL_EFF_DATE, BDGTITEMDTL_ENTD_ON, 
    BDGTITEMDTL_ENTD_BY, BDGTITEMDTL_MOD_ON, BDGTITEMDTL_MOD_BY, BDGTITEMDTL_AUTH_ON, BDGTITEMDTL_AUTH_BY, 
    TBA_MAIN_KEY)
 Values
   (1, 'EXPENSE', 'EOFFIC0008', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/18/2023 10:44:46', 'MM/DD/YYYY HH24:MI:SS'), 
    'MIGMAN', NULL, NULL, NULL, NULL, 
    NULL);
Insert into BDGTITEMDTL
   (BDGTITEMDTL_ENTITY_NUM, BDGTITEMDTL_TYPE_CODE, BDGTITEMDTL_ITEM_CODE, BDGTITEMDTL_EFF_DATE, BDGTITEMDTL_ENTD_ON, 
    BDGTITEMDTL_ENTD_BY, BDGTITEMDTL_MOD_ON, BDGTITEMDTL_MOD_BY, BDGTITEMDTL_AUTH_ON, BDGTITEMDTL_AUTH_BY, 
    TBA_MAIN_KEY)
 Values
   (1, 'EXPENSE', 'EOFFIC0009', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/18/2023 10:44:46', 'MM/DD/YYYY HH24:MI:SS'), 
    'MIGMAN', NULL, NULL, NULL, NULL, 
    NULL);
Insert into BDGTITEMDTL
   (BDGTITEMDTL_ENTITY_NUM, BDGTITEMDTL_TYPE_CODE, BDGTITEMDTL_ITEM_CODE, BDGTITEMDTL_EFF_DATE, BDGTITEMDTL_ENTD_ON, 
    BDGTITEMDTL_ENTD_BY, BDGTITEMDTL_MOD_ON, BDGTITEMDTL_MOD_BY, BDGTITEMDTL_AUTH_ON, BDGTITEMDTL_AUTH_BY, 
    TBA_MAIN_KEY)
 Values
   (1, 'EXPENSE', 'EOFFIC0010', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/18/2023 10:44:46', 'MM/DD/YYYY HH24:MI:SS'), 
    'MIGMAN', NULL, NULL, NULL, NULL, 
    NULL);
Insert into BDGTITEMDTL
   (BDGTITEMDTL_ENTITY_NUM, BDGTITEMDTL_TYPE_CODE, BDGTITEMDTL_ITEM_CODE, BDGTITEMDTL_EFF_DATE, BDGTITEMDTL_ENTD_ON, 
    BDGTITEMDTL_ENTD_BY, BDGTITEMDTL_MOD_ON, BDGTITEMDTL_MOD_BY, BDGTITEMDTL_AUTH_ON, BDGTITEMDTL_AUTH_BY, 
    TBA_MAIN_KEY)
 Values
   (1, 'EXPENSE', 'EOFFIC0011', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/18/2023 10:44:46', 'MM/DD/YYYY HH24:MI:SS'), 
    'MIGMAN', NULL, NULL, NULL, NULL, 
    NULL);
Insert into BDGTITEMDTL
   (BDGTITEMDTL_ENTITY_NUM, BDGTITEMDTL_TYPE_CODE, BDGTITEMDTL_ITEM_CODE, BDGTITEMDTL_EFF_DATE, BDGTITEMDTL_ENTD_ON, 
    BDGTITEMDTL_ENTD_BY, BDGTITEMDTL_MOD_ON, BDGTITEMDTL_MOD_BY, BDGTITEMDTL_AUTH_ON, BDGTITEMDTL_AUTH_BY, 
    TBA_MAIN_KEY)
 Values
   (1, 'EXPENSE', 'EOFFIC0012', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/18/2023 10:44:46', 'MM/DD/YYYY HH24:MI:SS'), 
    'MIGMAN', NULL, NULL, NULL, NULL, 
    NULL);
Insert into BDGTITEMDTL
   (BDGTITEMDTL_ENTITY_NUM, BDGTITEMDTL_TYPE_CODE, BDGTITEMDTL_ITEM_CODE, BDGTITEMDTL_EFF_DATE, BDGTITEMDTL_ENTD_ON, 
    BDGTITEMDTL_ENTD_BY, BDGTITEMDTL_MOD_ON, BDGTITEMDTL_MOD_BY, BDGTITEMDTL_AUTH_ON, BDGTITEMDTL_AUTH_BY, 
    TBA_MAIN_KEY)
 Values
   (1, 'EXPENSE', 'EOFFIC0013', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/18/2023 10:44:46', 'MM/DD/YYYY HH24:MI:SS'), 
    'MIGMAN', NULL, NULL, NULL, NULL, 
    NULL);
Insert into BDGTITEMDTL
   (BDGTITEMDTL_ENTITY_NUM, BDGTITEMDTL_TYPE_CODE, BDGTITEMDTL_ITEM_CODE, BDGTITEMDTL_EFF_DATE, BDGTITEMDTL_ENTD_ON, 
    BDGTITEMDTL_ENTD_BY, BDGTITEMDTL_MOD_ON, BDGTITEMDTL_MOD_BY, BDGTITEMDTL_AUTH_ON, BDGTITEMDTL_AUTH_BY, 
    TBA_MAIN_KEY)
 Values
   (1, 'EXPENSE', 'EOFFIC0014', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/18/2023 10:44:46', 'MM/DD/YYYY HH24:MI:SS'), 
    'MIGMAN', NULL, NULL, NULL, NULL, 
    NULL);
Insert into BDGTITEMDTL
   (BDGTITEMDTL_ENTITY_NUM, BDGTITEMDTL_TYPE_CODE, BDGTITEMDTL_ITEM_CODE, BDGTITEMDTL_EFF_DATE, BDGTITEMDTL_ENTD_ON, 
    BDGTITEMDTL_ENTD_BY, BDGTITEMDTL_MOD_ON, BDGTITEMDTL_MOD_BY, BDGTITEMDTL_AUTH_ON, BDGTITEMDTL_AUTH_BY, 
    TBA_MAIN_KEY)
 Values
   (1, 'EXPENSE', 'EOFFIC0015', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/18/2023 10:44:46', 'MM/DD/YYYY HH24:MI:SS'), 
    'MIGMAN', NULL, NULL, NULL, NULL, 
    NULL);
Insert into BDGTITEMDTL
   (BDGTITEMDTL_ENTITY_NUM, BDGTITEMDTL_TYPE_CODE, BDGTITEMDTL_ITEM_CODE, BDGTITEMDTL_EFF_DATE, BDGTITEMDTL_ENTD_ON, 
    BDGTITEMDTL_ENTD_BY, BDGTITEMDTL_MOD_ON, BDGTITEMDTL_MOD_BY, BDGTITEMDTL_AUTH_ON, BDGTITEMDTL_AUTH_BY, 
    TBA_MAIN_KEY)
 Values
   (1, 'EXPENSE', 'EREPAI0001', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/18/2023 10:44:46', 'MM/DD/YYYY HH24:MI:SS'), 
    'MIGMAN', NULL, NULL, NULL, NULL, 
    NULL);
Insert into BDGTITEMDTL
   (BDGTITEMDTL_ENTITY_NUM, BDGTITEMDTL_TYPE_CODE, BDGTITEMDTL_ITEM_CODE, BDGTITEMDTL_EFF_DATE, BDGTITEMDTL_ENTD_ON, 
    BDGTITEMDTL_ENTD_BY, BDGTITEMDTL_MOD_ON, BDGTITEMDTL_MOD_BY, BDGTITEMDTL_AUTH_ON, BDGTITEMDTL_AUTH_BY, 
    TBA_MAIN_KEY)
 Values
   (1, 'EXPENSE', 'EREPAI0002', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/18/2023 10:44:46', 'MM/DD/YYYY HH24:MI:SS'), 
    'MIGMAN', NULL, NULL, NULL, NULL, 
    NULL);
Insert into BDGTITEMDTL
   (BDGTITEMDTL_ENTITY_NUM, BDGTITEMDTL_TYPE_CODE, BDGTITEMDTL_ITEM_CODE, BDGTITEMDTL_EFF_DATE, BDGTITEMDTL_ENTD_ON, 
    BDGTITEMDTL_ENTD_BY, BDGTITEMDTL_MOD_ON, BDGTITEMDTL_MOD_BY, BDGTITEMDTL_AUTH_ON, BDGTITEMDTL_AUTH_BY, 
    TBA_MAIN_KEY)
 Values
   (1, 'EXPENSE', 'EREPAI0003', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/18/2023 10:44:46', 'MM/DD/YYYY HH24:MI:SS'), 
    'MIGMAN', NULL, NULL, NULL, NULL, 
    NULL);
Insert into BDGTITEMDTL
   (BDGTITEMDTL_ENTITY_NUM, BDGTITEMDTL_TYPE_CODE, BDGTITEMDTL_ITEM_CODE, BDGTITEMDTL_EFF_DATE, BDGTITEMDTL_ENTD_ON, 
    BDGTITEMDTL_ENTD_BY, BDGTITEMDTL_MOD_ON, BDGTITEMDTL_MOD_BY, BDGTITEMDTL_AUTH_ON, BDGTITEMDTL_AUTH_BY, 
    TBA_MAIN_KEY)
 Values
   (1, 'EXPENSE', 'EREPAI0004', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/18/2023 10:44:46', 'MM/DD/YYYY HH24:MI:SS'), 
    'MIGMAN', NULL, NULL, NULL, NULL, 
    NULL);
Insert into BDGTITEMDTL
   (BDGTITEMDTL_ENTITY_NUM, BDGTITEMDTL_TYPE_CODE, BDGTITEMDTL_ITEM_CODE, BDGTITEMDTL_EFF_DATE, BDGTITEMDTL_ENTD_ON, 
    BDGTITEMDTL_ENTD_BY, BDGTITEMDTL_MOD_ON, BDGTITEMDTL_MOD_BY, BDGTITEMDTL_AUTH_ON, BDGTITEMDTL_AUTH_BY, 
    TBA_MAIN_KEY)
 Values
   (1, 'EXPENSE', 'EREPAI0005', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/18/2023 10:44:46', 'MM/DD/YYYY HH24:MI:SS'), 
    'MIGMAN', NULL, NULL, NULL, NULL, 
    NULL);
Insert into BDGTITEMDTL
   (BDGTITEMDTL_ENTITY_NUM, BDGTITEMDTL_TYPE_CODE, BDGTITEMDTL_ITEM_CODE, BDGTITEMDTL_EFF_DATE, BDGTITEMDTL_ENTD_ON, 
    BDGTITEMDTL_ENTD_BY, BDGTITEMDTL_MOD_ON, BDGTITEMDTL_MOD_BY, BDGTITEMDTL_AUTH_ON, BDGTITEMDTL_AUTH_BY, 
    TBA_MAIN_KEY)
 Values
   (1, 'EXPENSE', 'EREPAI0006', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/18/2023 10:44:46', 'MM/DD/YYYY HH24:MI:SS'), 
    'MIGMAN', NULL, NULL, NULL, NULL, 
    NULL);
Insert into BDGTITEMDTL
   (BDGTITEMDTL_ENTITY_NUM, BDGTITEMDTL_TYPE_CODE, BDGTITEMDTL_ITEM_CODE, BDGTITEMDTL_EFF_DATE, BDGTITEMDTL_ENTD_ON, 
    BDGTITEMDTL_ENTD_BY, BDGTITEMDTL_MOD_ON, BDGTITEMDTL_MOD_BY, BDGTITEMDTL_AUTH_ON, BDGTITEMDTL_AUTH_BY, 
    TBA_MAIN_KEY)
 Values
   (1, 'EXPENSE', 'EOTHER0001', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/18/2023 10:44:46', 'MM/DD/YYYY HH24:MI:SS'), 
    'MIGMAN', NULL, NULL, NULL, NULL, 
    NULL);
Insert into BDGTITEMDTL
   (BDGTITEMDTL_ENTITY_NUM, BDGTITEMDTL_TYPE_CODE, BDGTITEMDTL_ITEM_CODE, BDGTITEMDTL_EFF_DATE, BDGTITEMDTL_ENTD_ON, 
    BDGTITEMDTL_ENTD_BY, BDGTITEMDTL_MOD_ON, BDGTITEMDTL_MOD_BY, BDGTITEMDTL_AUTH_ON, BDGTITEMDTL_AUTH_BY, 
    TBA_MAIN_KEY)
 Values
   (1, 'EXPENSE', 'EOTHER0002', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/18/2023 10:44:46', 'MM/DD/YYYY HH24:MI:SS'), 
    'MIGMAN', NULL, NULL, NULL, NULL, 
    NULL);
Insert into BDGTITEMDTL
   (BDGTITEMDTL_ENTITY_NUM, BDGTITEMDTL_TYPE_CODE, BDGTITEMDTL_ITEM_CODE, BDGTITEMDTL_EFF_DATE, BDGTITEMDTL_ENTD_ON, 
    BDGTITEMDTL_ENTD_BY, BDGTITEMDTL_MOD_ON, BDGTITEMDTL_MOD_BY, BDGTITEMDTL_AUTH_ON, BDGTITEMDTL_AUTH_BY, 
    TBA_MAIN_KEY)
 Values
   (1, 'EXPENSE', 'EOTHER0003', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/18/2023 10:44:46', 'MM/DD/YYYY HH24:MI:SS'), 
    'MIGMAN', NULL, NULL, NULL, NULL, 
    NULL);
Insert into BDGTITEMDTL
   (BDGTITEMDTL_ENTITY_NUM, BDGTITEMDTL_TYPE_CODE, BDGTITEMDTL_ITEM_CODE, BDGTITEMDTL_EFF_DATE, BDGTITEMDTL_ENTD_ON, 
    BDGTITEMDTL_ENTD_BY, BDGTITEMDTL_MOD_ON, BDGTITEMDTL_MOD_BY, BDGTITEMDTL_AUTH_ON, BDGTITEMDTL_AUTH_BY, 
    TBA_MAIN_KEY)
 Values
   (1, 'EXPENSE', 'EOTHER0004', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/18/2023 10:44:46', 'MM/DD/YYYY HH24:MI:SS'), 
    'MIGMAN', NULL, NULL, NULL, NULL, 
    NULL);
Insert into BDGTITEMDTL
   (BDGTITEMDTL_ENTITY_NUM, BDGTITEMDTL_TYPE_CODE, BDGTITEMDTL_ITEM_CODE, BDGTITEMDTL_EFF_DATE, BDGTITEMDTL_ENTD_ON, 
    BDGTITEMDTL_ENTD_BY, BDGTITEMDTL_MOD_ON, BDGTITEMDTL_MOD_BY, BDGTITEMDTL_AUTH_ON, BDGTITEMDTL_AUTH_BY, 
    TBA_MAIN_KEY)
 Values
   (1, 'EXPENSE', 'EOTHER0005', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/18/2023 10:44:46', 'MM/DD/YYYY HH24:MI:SS'), 
    'MIGMAN', NULL, NULL, NULL, NULL, 
    NULL);


Insert into BDGTGLDTL
   (BDGTGLDTL_ENTITY_NUM, BDGTGLDTL_TYPE_CODE, BDGTGLDTL_ITEM_CODE, BDGTGLDTL_EFF_DATE, BDGTGLDTL_SL_NUM, 
    BDGTGLDTL_GL_CODE, BDGTGLDTL_GL_DESC)
 Values
   (1, 'EXPENSE', 'ESALAR0001', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 1, 
    '400107101', 'Charges Account Salaries');
Insert into BDGTGLDTL
   (BDGTGLDTL_ENTITY_NUM, BDGTGLDTL_TYPE_CODE, BDGTGLDTL_ITEM_CODE, BDGTGLDTL_EFF_DATE, BDGTGLDTL_SL_NUM, 
    BDGTGLDTL_GL_CODE, BDGTGLDTL_GL_DESC)
 Values
   (1, 'EXPENSE', 'ESALAR0002', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 2, 
    '400107116', 'Charges Account Medical attendance');
Insert into BDGTGLDTL
   (BDGTGLDTL_ENTITY_NUM, BDGTGLDTL_TYPE_CODE, BDGTGLDTL_ITEM_CODE, BDGTGLDTL_EFF_DATE, BDGTGLDTL_SL_NUM, 
    BDGTGLDTL_GL_CODE, BDGTGLDTL_GL_DESC)
 Values
   (1, 'EXPENSE', 'ESALAR0003', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 3, 
    '400107160', 'Charges Account Conveyance');
Insert into BDGTGLDTL
   (BDGTGLDTL_ENTITY_NUM, BDGTGLDTL_TYPE_CODE, BDGTGLDTL_ITEM_CODE, BDGTGLDTL_EFF_DATE, BDGTGLDTL_SL_NUM, 
    BDGTGLDTL_GL_CODE, BDGTGLDTL_GL_DESC)
 Values
   (1, 'EXPENSE', 'ESALAR0004', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 4, 
    '400107104', 'Charges Account House Rent');
Insert into BDGTGLDTL
   (BDGTGLDTL_ENTITY_NUM, BDGTGLDTL_TYPE_CODE, BDGTGLDTL_ITEM_CODE, BDGTGLDTL_EFF_DATE, BDGTGLDTL_SL_NUM, 
    BDGTGLDTL_GL_CODE, BDGTGLDTL_GL_DESC)
 Values
   (1, 'EXPENSE', 'ESALAR0005', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 5, 
    '400113119', 'Charges Account Lunch Subsidy');
Insert into BDGTGLDTL
   (BDGTGLDTL_ENTITY_NUM, BDGTGLDTL_TYPE_CODE, BDGTGLDTL_ITEM_CODE, BDGTGLDTL_EFF_DATE, BDGTGLDTL_SL_NUM, 
    BDGTGLDTL_GL_CODE, BDGTGLDTL_GL_DESC)
 Values
   (1, 'EXPENSE', 'ESALAR0005', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 6, 
    '400113338', 'Charges AC Daily light Refreshment (Lunch)');
Insert into BDGTGLDTL
   (BDGTGLDTL_ENTITY_NUM, BDGTGLDTL_TYPE_CODE, BDGTGLDTL_ITEM_CODE, BDGTGLDTL_EFF_DATE, BDGTGLDTL_SL_NUM, 
    BDGTGLDTL_GL_CODE, BDGTGLDTL_GL_DESC)
 Values
   (1, 'EXPENSE', 'ESALAR0006', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 7, 
    '400113134', 'Charges Account Children Education Allowance');
Insert into BDGTGLDTL
   (BDGTGLDTL_ENTITY_NUM, BDGTGLDTL_TYPE_CODE, BDGTGLDTL_ITEM_CODE, BDGTGLDTL_EFF_DATE, BDGTGLDTL_SL_NUM, 
    BDGTGLDTL_GL_CODE, BDGTGLDTL_GL_DESC)
 Values
   (1, 'EXPENSE', 'ESALAR0007', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 8, 
    '400107113', 'Charges Account Provident fund');
Insert into BDGTGLDTL
   (BDGTGLDTL_ENTITY_NUM, BDGTGLDTL_TYPE_CODE, BDGTGLDTL_ITEM_CODE, BDGTGLDTL_EFF_DATE, BDGTGLDTL_SL_NUM, 
    BDGTGLDTL_GL_CODE, BDGTGLDTL_GL_DESC)
 Values
   (1, 'EXPENSE', 'ESALAR0007', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 9, 
    '400101116', 'Interest Paid on SB Employees Provident fund');
Insert into BDGTGLDTL
   (BDGTGLDTL_ENTITY_NUM, BDGTGLDTL_TYPE_CODE, BDGTGLDTL_ITEM_CODE, BDGTGLDTL_EFF_DATE, BDGTGLDTL_SL_NUM, 
    BDGTGLDTL_GL_CODE, BDGTGLDTL_GL_DESC)
 Values
   (1, 'EXPENSE', 'ESALAR0008', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 10, 
    '400107110', 'Charges Account Pension fund');
Insert into BDGTGLDTL
   (BDGTGLDTL_ENTITY_NUM, BDGTGLDTL_TYPE_CODE, BDGTGLDTL_ITEM_CODE, BDGTGLDTL_EFF_DATE, BDGTGLDTL_SL_NUM, 
    BDGTGLDTL_GL_CODE, BDGTGLDTL_GL_DESC)
 Values
   (1, 'EXPENSE', 'ESALAR0009', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 11, 
    '400107119', 'Charges Account Staff Bonus');
Insert into BDGTGLDTL
   (BDGTGLDTL_ENTITY_NUM, BDGTGLDTL_TYPE_CODE, BDGTGLDTL_ITEM_CODE, BDGTGLDTL_EFF_DATE, BDGTGLDTL_SL_NUM, 
    BDGTGLDTL_GL_CODE, BDGTGLDTL_GL_DESC)
 Values
   (1, 'EXPENSE', 'ESALAR0010', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 12, 
    '400107137', 'Charges Account Bangla Nabobarsha Allowance');
Insert into BDGTGLDTL
   (BDGTGLDTL_ENTITY_NUM, BDGTGLDTL_TYPE_CODE, BDGTGLDTL_ITEM_CODE, BDGTGLDTL_EFF_DATE, BDGTGLDTL_SL_NUM, 
    BDGTGLDTL_GL_CODE, BDGTGLDTL_GL_DESC)
 Values
   (1, 'EXPENSE', 'ESALAR0011', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 13, 
    '400113122', 'Charges Account Entertainment');
Insert into BDGTGLDTL
   (BDGTGLDTL_ENTITY_NUM, BDGTGLDTL_TYPE_CODE, BDGTGLDTL_ITEM_CODE, BDGTGLDTL_EFF_DATE, BDGTGLDTL_SL_NUM, 
    BDGTGLDTL_GL_CODE, BDGTGLDTL_GL_DESC)
 Values
   (1, 'EXPENSE', 'ESALAR0012', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 14, 
    '400113125', 'Charges Account Overtime');
Insert into BDGTGLDTL
   (BDGTGLDTL_ENTITY_NUM, BDGTGLDTL_TYPE_CODE, BDGTGLDTL_ITEM_CODE, BDGTGLDTL_EFF_DATE, BDGTGLDTL_SL_NUM, 
    BDGTGLDTL_GL_CODE, BDGTGLDTL_GL_DESC)
 Values
   (1, 'EXPENSE', 'ESALAR0013', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 15, 
    '400107141', 'Charges Account Washing Allowance');
Insert into BDGTGLDTL
   (BDGTGLDTL_ENTITY_NUM, BDGTGLDTL_TYPE_CODE, BDGTGLDTL_ITEM_CODE, BDGTGLDTL_EFF_DATE, BDGTGLDTL_SL_NUM, 
    BDGTGLDTL_GL_CODE, BDGTGLDTL_GL_DESC)
 Values
   (1, 'EXPENSE', 'ESALAR0014', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 16, 
    '400107125', 'Charges Account Recreation Expense');
Insert into BDGTGLDTL
   (BDGTGLDTL_ENTITY_NUM, BDGTGLDTL_TYPE_CODE, BDGTGLDTL_ITEM_CODE, BDGTGLDTL_EFF_DATE, BDGTGLDTL_SL_NUM, 
    BDGTGLDTL_GL_CODE, BDGTGLDTL_GL_DESC)
 Values
   (1, 'EXPENSE', 'EOFFIC0001', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 17, 
    '400113101', 'Charges Account Stationery');
Insert into BDGTGLDTL
   (BDGTGLDTL_ENTITY_NUM, BDGTGLDTL_TYPE_CODE, BDGTGLDTL_ITEM_CODE, BDGTGLDTL_EFF_DATE, BDGTGLDTL_SL_NUM, 
    BDGTGLDTL_GL_CODE, BDGTGLDTL_GL_DESC)
 Values
   (1, 'EXPENSE', 'EOFFIC0002', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 18, 
    '400113380', 'Charges Account Holding Tax for Banks Building');
Insert into BDGTGLDTL
   (BDGTGLDTL_ENTITY_NUM, BDGTGLDTL_TYPE_CODE, BDGTGLDTL_ITEM_CODE, BDGTGLDTL_EFF_DATE, BDGTGLDTL_SL_NUM, 
    BDGTGLDTL_GL_CODE, BDGTGLDTL_GL_DESC)
 Values
   (1, 'EXPENSE', 'EOFFIC0003', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 19, 
    '400110101', 'Charges Account Rent');
Insert into BDGTGLDTL
   (BDGTGLDTL_ENTITY_NUM, BDGTGLDTL_TYPE_CODE, BDGTGLDTL_ITEM_CODE, BDGTGLDTL_EFF_DATE, BDGTGLDTL_SL_NUM, 
    BDGTGLDTL_GL_CODE, BDGTGLDTL_GL_DESC)
 Values
   (1, 'EXPENSE', 'EOFFIC0004', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 20, 
    '400113128', 'Charges Account Liveries to Staff');
Insert into BDGTGLDTL
   (BDGTGLDTL_ENTITY_NUM, BDGTGLDTL_TYPE_CODE, BDGTGLDTL_ITEM_CODE, BDGTGLDTL_EFF_DATE, BDGTGLDTL_SL_NUM, 
    BDGTGLDTL_GL_CODE, BDGTGLDTL_GL_DESC)
 Values
   (1, 'EXPENSE', 'EOFFIC0005', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 21, 
    '400113113', 'Charges Account Telephone');
Insert into BDGTGLDTL
   (BDGTGLDTL_ENTITY_NUM, BDGTGLDTL_TYPE_CODE, BDGTGLDTL_ITEM_CODE, BDGTGLDTL_EFF_DATE, BDGTGLDTL_SL_NUM, 
    BDGTGLDTL_GL_CODE, BDGTGLDTL_GL_DESC)
 Values
   (1, 'EXPENSE', 'EOFFIC0007', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 22, 
    '400113385', 'Charges Account Postage-Government Post Office');
Insert into BDGTGLDTL
   (BDGTGLDTL_ENTITY_NUM, BDGTGLDTL_TYPE_CODE, BDGTGLDTL_ITEM_CODE, BDGTGLDTL_EFF_DATE, BDGTGLDTL_SL_NUM, 
    BDGTGLDTL_GL_CODE, BDGTGLDTL_GL_DESC)
 Values
   (1, 'EXPENSE', 'EOFFIC0007', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 23, 
    '400113388', 'Charges Account Postage-Courier Service Bills');
Insert into BDGTGLDTL
   (BDGTGLDTL_ENTITY_NUM, BDGTGLDTL_TYPE_CODE, BDGTGLDTL_ITEM_CODE, BDGTGLDTL_EFF_DATE, BDGTGLDTL_SL_NUM, 
    BDGTGLDTL_GL_CODE, BDGTGLDTL_GL_DESC)
 Values
   (1, 'EXPENSE', 'EOFFIC0008', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 24, 
    '400113116', 'Charges Account Travelling Expenses');
Insert into BDGTGLDTL
   (BDGTGLDTL_ENTITY_NUM, BDGTGLDTL_TYPE_CODE, BDGTGLDTL_ITEM_CODE, BDGTGLDTL_EFF_DATE, BDGTGLDTL_SL_NUM, 
    BDGTGLDTL_GL_CODE, BDGTGLDTL_GL_DESC)
 Values
   (1, 'EXPENSE', 'EOFFIC0009', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 25, 
    '400113140', 'Charges Account Motor/Running(Petrol/Mobil/Diesel)');
Insert into BDGTGLDTL
   (BDGTGLDTL_ENTITY_NUM, BDGTGLDTL_TYPE_CODE, BDGTGLDTL_ITEM_CODE, BDGTGLDTL_EFF_DATE, BDGTGLDTL_SL_NUM, 
    BDGTGLDTL_GL_CODE, BDGTGLDTL_GL_DESC)
 Values
   (1, 'EXPENSE', 'EOFFIC0010', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 26, 
    '400113104', 'Charges Account Books/Newspapers/Periodicals');
Insert into BDGTGLDTL
   (BDGTGLDTL_ENTITY_NUM, BDGTGLDTL_TYPE_CODE, BDGTGLDTL_ITEM_CODE, BDGTGLDTL_EFF_DATE, BDGTGLDTL_SL_NUM, 
    BDGTGLDTL_GL_CODE, BDGTGLDTL_GL_DESC)
 Values
   (1, 'EXPENSE', 'EOFFIC0011', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 27, 
    '400113182', 'Charges Account Directors & Members Fees  Expenses');
Insert into BDGTGLDTL
   (BDGTGLDTL_ENTITY_NUM, BDGTGLDTL_TYPE_CODE, BDGTGLDTL_ITEM_CODE, BDGTGLDTL_EFF_DATE, BDGTGLDTL_SL_NUM, 
    BDGTGLDTL_GL_CODE, BDGTGLDTL_GL_DESC)
 Values
   (1, 'EXPENSE', 'EOFFIC0011', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 28, 
    '400113131', 'Charges Account Honorarium to Staff');
Insert into BDGTGLDTL
   (BDGTGLDTL_ENTITY_NUM, BDGTGLDTL_TYPE_CODE, BDGTGLDTL_ITEM_CODE, BDGTGLDTL_EFF_DATE, BDGTGLDTL_SL_NUM, 
    BDGTGLDTL_GL_CODE, BDGTGLDTL_GL_DESC)
 Values
   (1, 'EXPENSE', 'EOFFIC0011', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 29, 
    '400113355', 'Charges AC Honorarium for Promotion Committee');
Insert into BDGTGLDTL
   (BDGTGLDTL_ENTITY_NUM, BDGTGLDTL_TYPE_CODE, BDGTGLDTL_ITEM_CODE, BDGTGLDTL_EFF_DATE, BDGTGLDTL_SL_NUM, 
    BDGTGLDTL_GL_CODE, BDGTGLDTL_GL_DESC)
 Values
   (1, 'EXPENSE', 'EOFFIC0011', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 30, 
    '400113351', 'Charges AC Honorarium for Meeting');
Insert into BDGTGLDTL
   (BDGTGLDTL_ENTITY_NUM, BDGTGLDTL_TYPE_CODE, BDGTGLDTL_ITEM_CODE, BDGTGLDTL_EFF_DATE, BDGTGLDTL_SL_NUM, 
    BDGTGLDTL_GL_CODE, BDGTGLDTL_GL_DESC)
 Values
   (1, 'EXPENSE', 'EOFFIC0012', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 31, 
    '400113110', 'Charges Account Lighting');
Insert into BDGTGLDTL
   (BDGTGLDTL_ENTITY_NUM, BDGTGLDTL_TYPE_CODE, BDGTGLDTL_ITEM_CODE, BDGTGLDTL_EFF_DATE, BDGTGLDTL_SL_NUM, 
    BDGTGLDTL_GL_CODE, BDGTGLDTL_GL_DESC)
 Values
   (1, 'EXPENSE', 'EOFFIC0013', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 32, 
    '400113164', 'Charges Account Lawyers Fee');
Insert into BDGTGLDTL
   (BDGTGLDTL_ENTITY_NUM, BDGTGLDTL_TYPE_CODE, BDGTGLDTL_ITEM_CODE, BDGTGLDTL_EFF_DATE, BDGTGLDTL_SL_NUM, 
    BDGTGLDTL_GL_CODE, BDGTGLDTL_GL_DESC)
 Values
   (1, 'EXPENSE', 'EOFFIC0014', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 33, 
    '400113179', 'Charges Account Generator Maintenances');
Insert into BDGTGLDTL
   (BDGTGLDTL_ENTITY_NUM, BDGTGLDTL_TYPE_CODE, BDGTGLDTL_ITEM_CODE, BDGTGLDTL_EFF_DATE, BDGTGLDTL_SL_NUM, 
    BDGTGLDTL_GL_CODE, BDGTGLDTL_GL_DESC)
 Values
   (1, 'EXPENSE', 'EOFFIC0015', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 34, 
    '400107122', 'Charges  Account Pay of police /Ansar/Sec. Guard');
Insert into BDGTGLDTL
   (BDGTGLDTL_ENTITY_NUM, BDGTGLDTL_TYPE_CODE, BDGTGLDTL_ITEM_CODE, BDGTGLDTL_EFF_DATE, BDGTGLDTL_SL_NUM, 
    BDGTGLDTL_GL_CODE, BDGTGLDTL_GL_DESC)
 Values
   (1, 'EXPENSE', 'EOFFIC0015', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 35, 
    '400113346', 'Charges AC Private Security Service');
Insert into BDGTGLDTL
   (BDGTGLDTL_ENTITY_NUM, BDGTGLDTL_TYPE_CODE, BDGTGLDTL_ITEM_CODE, BDGTGLDTL_EFF_DATE, BDGTGLDTL_SL_NUM, 
    BDGTGLDTL_GL_CODE, BDGTGLDTL_GL_DESC)
 Values
   (1, 'EXPENSE', 'EREPAI0001', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 36, 
    '400113143', 'Charges Account Motor Car maintenance/Repairs');
Insert into BDGTGLDTL
   (BDGTGLDTL_ENTITY_NUM, BDGTGLDTL_TYPE_CODE, BDGTGLDTL_ITEM_CODE, BDGTGLDTL_EFF_DATE, BDGTGLDTL_SL_NUM, 
    BDGTGLDTL_GL_CODE, BDGTGLDTL_GL_DESC)
 Values
   (1, 'EXPENSE', 'EREPAI0002', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 37, 
    '400110133', 'Charges AC Repairs to Banks Property (Lift)');
Insert into BDGTGLDTL
   (BDGTGLDTL_ENTITY_NUM, BDGTGLDTL_TYPE_CODE, BDGTGLDTL_ITEM_CODE, BDGTGLDTL_EFF_DATE, BDGTGLDTL_SL_NUM, 
    BDGTGLDTL_GL_CODE, BDGTGLDTL_GL_DESC)
 Values
   (1, 'EXPENSE', 'EREPAI0002', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 38, 
    '400110110', 'Charges Account Repairs to rented premises');
Insert into BDGTGLDTL
   (BDGTGLDTL_ENTITY_NUM, BDGTGLDTL_TYPE_CODE, BDGTGLDTL_ITEM_CODE, BDGTGLDTL_EFF_DATE, BDGTGLDTL_SL_NUM, 
    BDGTGLDTL_GL_CODE, BDGTGLDTL_GL_DESC)
 Values
   (1, 'EXPENSE', 'EREPAI0002', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 39, 
    '400110108', 'Charges Account Repairs to Furniture & Fixtures');
Insert into BDGTGLDTL
   (BDGTGLDTL_ENTITY_NUM, BDGTGLDTL_TYPE_CODE, BDGTGLDTL_ITEM_CODE, BDGTGLDTL_EFF_DATE, BDGTGLDTL_SL_NUM, 
    BDGTGLDTL_GL_CODE, BDGTGLDTL_GL_DESC)
 Values
   (1, 'EXPENSE', 'EREPAI0002', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 40, 
    '400110107', 'Charges Account Repairs to Others');
Insert into BDGTGLDTL
   (BDGTGLDTL_ENTITY_NUM, BDGTGLDTL_TYPE_CODE, BDGTGLDTL_ITEM_CODE, BDGTGLDTL_EFF_DATE, BDGTGLDTL_SL_NUM, 
    BDGTGLDTL_GL_CODE, BDGTGLDTL_GL_DESC)
 Values
   (1, 'EXPENSE', 'EREPAI0003', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 41, 
    '400110127', 'Charges AC Repairs to Banks Property (Electricity)');
Insert into BDGTGLDTL
   (BDGTGLDTL_ENTITY_NUM, BDGTGLDTL_TYPE_CODE, BDGTGLDTL_ITEM_CODE, BDGTGLDTL_EFF_DATE, BDGTGLDTL_SL_NUM, 
    BDGTGLDTL_GL_CODE, BDGTGLDTL_GL_DESC)
 Values
   (1, 'EXPENSE', 'EREPAI0003', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 42, 
    '400110131', 'Charges AC Repairs to Banks Property (AC)');
Insert into BDGTGLDTL
   (BDGTGLDTL_ENTITY_NUM, BDGTGLDTL_TYPE_CODE, BDGTGLDTL_ITEM_CODE, BDGTGLDTL_EFF_DATE, BDGTGLDTL_SL_NUM, 
    BDGTGLDTL_GL_CODE, BDGTGLDTL_GL_DESC)
 Values
   (1, 'EXPENSE', 'EREPAI0003', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 43, 
    '400110129', 'Charges AC Repairs to Banks Property (Civil)');
Insert into BDGTGLDTL
   (BDGTGLDTL_ENTITY_NUM, BDGTGLDTL_TYPE_CODE, BDGTGLDTL_ITEM_CODE, BDGTGLDTL_EFF_DATE, BDGTGLDTL_SL_NUM, 
    BDGTGLDTL_GL_CODE, BDGTGLDTL_GL_DESC)
 Values
   (1, 'EXPENSE', 'EREPAI0004', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 44, 
    '400110108', 'Charges Account Repairs to Furniture & Fixtures');
Insert into BDGTGLDTL
   (BDGTGLDTL_ENTITY_NUM, BDGTGLDTL_TYPE_CODE, BDGTGLDTL_ITEM_CODE, BDGTGLDTL_EFF_DATE, BDGTGLDTL_SL_NUM, 
    BDGTGLDTL_GL_CODE, BDGTGLDTL_GL_DESC)
 Values
   (1, 'EXPENSE', 'EREPAI0005', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 45, 
    '400113291', 'Charges A/C Repairs & Maint. Computer Hardware');
Insert into BDGTGLDTL
   (BDGTGLDTL_ENTITY_NUM, BDGTGLDTL_TYPE_CODE, BDGTGLDTL_ITEM_CODE, BDGTGLDTL_EFF_DATE, BDGTGLDTL_SL_NUM, 
    BDGTGLDTL_GL_CODE, BDGTGLDTL_GL_DESC)
 Values
   (1, 'EXPENSE', 'EREPAI0006', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 46, 
    '400113299', 'Charges A/C Rent of Connectivity/CCTV/Internet etc');
Insert into BDGTGLDTL
   (BDGTGLDTL_ENTITY_NUM, BDGTGLDTL_TYPE_CODE, BDGTGLDTL_ITEM_CODE, BDGTGLDTL_EFF_DATE, BDGTGLDTL_SL_NUM, 
    BDGTGLDTL_GL_CODE, BDGTGLDTL_GL_DESC)
 Values
   (1, 'EXPENSE', 'EOTHER0001', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 47, 
    '400113149', 'Charges Account Insurance');
Insert into BDGTGLDTL
   (BDGTGLDTL_ENTITY_NUM, BDGTGLDTL_TYPE_CODE, BDGTGLDTL_ITEM_CODE, BDGTGLDTL_EFF_DATE, BDGTGLDTL_SL_NUM, 
    BDGTGLDTL_GL_CODE, BDGTGLDTL_GL_DESC)
 Values
   (1, 'EXPENSE', 'EOTHER0002', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 48, 
    '400104101', 'Interest Paid on SBG Account Credit Balance');
Insert into BDGTGLDTL
   (BDGTGLDTL_ENTITY_NUM, BDGTGLDTL_TYPE_CODE, BDGTGLDTL_ITEM_CODE, BDGTGLDTL_EFF_DATE, BDGTGLDTL_SL_NUM, 
    BDGTGLDTL_GL_CODE, BDGTGLDTL_GL_DESC)
 Values
   (1, 'EXPENSE', 'EOTHER0002', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 49, 
    '400104106', 'Interest Paid on SBG (RMS) Account Credit Balance');
Insert into BDGTGLDTL
   (BDGTGLDTL_ENTITY_NUM, BDGTGLDTL_TYPE_CODE, BDGTGLDTL_ITEM_CODE, BDGTGLDTL_EFF_DATE, BDGTGLDTL_SL_NUM, 
    BDGTGLDTL_GL_CODE, BDGTGLDTL_GL_DESC)
 Values
   (1, 'EXPENSE', 'EOTHER0002', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 50, 
    '400104110', 'Interest Paid on SBG(CBS) Account Credit Balance');
Insert into BDGTGLDTL
   (BDGTGLDTL_ENTITY_NUM, BDGTGLDTL_TYPE_CODE, BDGTGLDTL_ITEM_CODE, BDGTGLDTL_EFF_DATE, BDGTGLDTL_SL_NUM, 
    BDGTGLDTL_GL_CODE, BDGTGLDTL_GL_DESC)
 Values
   (1, 'EXPENSE', 'EOTHER0002', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 51, 
    '400104104', 'Interest Paid on MO (OLD) Account Credit Balance');
Insert into BDGTGLDTL
   (BDGTGLDTL_ENTITY_NUM, BDGTGLDTL_TYPE_CODE, BDGTGLDTL_ITEM_CODE, BDGTGLDTL_EFF_DATE, BDGTGLDTL_SL_NUM, 
    BDGTGLDTL_GL_CODE, BDGTGLDTL_GL_DESC)
 Values
   (1, 'EXPENSE', 'EOTHER0002', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 52, 
    '400104108', 'Interest Paid on MO (NEW) Account Credit Balance');
Insert into BDGTGLDTL
   (BDGTGLDTL_ENTITY_NUM, BDGTGLDTL_TYPE_CODE, BDGTGLDTL_ITEM_CODE, BDGTGLDTL_EFF_DATE, BDGTGLDTL_SL_NUM, 
    BDGTGLDTL_GL_CODE, BDGTGLDTL_GL_DESC)
 Values
   (1, 'EXPENSE', 'EOTHER0003', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 53, 
    '400113146', 'Charges Account Hired Transport');
Insert into BDGTGLDTL
   (BDGTGLDTL_ENTITY_NUM, BDGTGLDTL_TYPE_CODE, BDGTGLDTL_ITEM_CODE, BDGTGLDTL_EFF_DATE, BDGTGLDTL_SL_NUM, 
    BDGTGLDTL_GL_CODE, BDGTGLDTL_GL_DESC)
 Values
   (1, 'EXPENSE', 'EOTHER0004', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 54, 
    '400113303', 'Charges Account Training Expenses');
Insert into BDGTGLDTL
   (BDGTGLDTL_ENTITY_NUM, BDGTGLDTL_TYPE_CODE, BDGTGLDTL_ITEM_CODE, BDGTGLDTL_EFF_DATE, BDGTGLDTL_SL_NUM, 
    BDGTGLDTL_GL_CODE, BDGTGLDTL_GL_DESC)
 Values
   (1, 'EXPENSE', 'EOTHER0005', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 55, 
    '400113167', 'Charges Account Sundries');
Insert into BDGTGLDTL
   (BDGTGLDTL_ENTITY_NUM, BDGTGLDTL_TYPE_CODE, BDGTGLDTL_ITEM_CODE, BDGTGLDTL_EFF_DATE, BDGTGLDTL_SL_NUM, 
    BDGTGLDTL_GL_CODE, BDGTGLDTL_GL_DESC)
 Values
   (1, 'EXPENSE', 'EOTHER0005', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 56, 
    '400113363', 'Charges Account Sundries Wasa Bills');
Insert into BDGTGLDTL
   (BDGTGLDTL_ENTITY_NUM, BDGTGLDTL_TYPE_CODE, BDGTGLDTL_ITEM_CODE, BDGTGLDTL_EFF_DATE, BDGTGLDTL_SL_NUM, 
    BDGTGLDTL_GL_CODE, BDGTGLDTL_GL_DESC)
 Values
   (1, 'EXPENSE', 'EOTHER0005', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 57, 
    '400113376', 'Charges Account Sundries-Miscellaneous Expenses');
Insert into BDGTGLDTL
   (BDGTGLDTL_ENTITY_NUM, BDGTGLDTL_TYPE_CODE, BDGTGLDTL_ITEM_CODE, BDGTGLDTL_EFF_DATE, BDGTGLDTL_SL_NUM, 
    BDGTGLDTL_GL_CODE, BDGTGLDTL_GL_DESC)
 Values
   (1, 'EXPENSE', 'EOTHER0005', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 58, 
    '400113382', 'Charges Account Sundries Local Government Tax');
Insert into BDGTGLDTL
   (BDGTGLDTL_ENTITY_NUM, BDGTGLDTL_TYPE_CODE, BDGTGLDTL_ITEM_CODE, BDGTGLDTL_EFF_DATE, BDGTGLDTL_SL_NUM, 
    BDGTGLDTL_GL_CODE, BDGTGLDTL_GL_DESC)
 Values
   (1, 'EXPENSE', 'EOTHER0005', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 59, 
    '400113362', 'Charges Account Sundries EXCISE DUTY');
Insert into BDGTGLDTL
   (BDGTGLDTL_ENTITY_NUM, BDGTGLDTL_TYPE_CODE, BDGTGLDTL_ITEM_CODE, BDGTGLDTL_EFF_DATE, BDGTGLDTL_SL_NUM, 
    BDGTGLDTL_GL_CODE, BDGTGLDTL_GL_DESC)
 Values
   (1, 'EXPENSE', 'EOTHER0005', TO_DATE('01/01/2023 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 60, 
    '400113383', 'Charges Account Sundries Other Taxes');

