/*Creating divisions for the divisionwise operations based on the data given by the customer*/

CREATE TABLE DIV_DATA (
DEPT_CODE	VARCHAR2(3),
DEPT_NAME	VARCHAR2(100),
Short_code VARCHAR2(100));


INSERT INTO BUSDIVN
SELECT DEPT_CODE BUSDIVN_DIVN_CODE,
       DEPT_NAME BUSDIVN_DIVN_NAME,
       SHORT_CODE BUSDIVN_DIVN_CONC_NAME,
       'INTELECT' BUSDIVN_ENTD_BY,
       SYSDATE BUSDIVN_ENTD_ON,
       NULL BUSDIVN_LAST_MOD_BY,
       NULL BUSDIVN_LAST_MOD_ON,
       'INTELECT' BUSDIVN_AUTH_BY,
       SYSDATE BUSDIVN_AUTH_ON,
       NULL TBA_MAIN_KEY
  FROM DIV_DATA ;
  
  
INSERT INTO AUBDIVN
SELECT '01' AUBDIVN_ADMIN_UNIT_CODE,
       '23-NOV-2017' AUBDIVN_EFF_DATE,
       'INTELECT' AUBDIVN_ENTD_BY,
       SYSDATE AUBDIVN_ENTD_ON,
       NULL AUBDIVN_LAST_MOD_BY,
       NULL AUBDIVN_LAST_MOD_ON,
       'INTELECT' AUBDIVN_AUTH_BY,
       SYSDATE AUBDIVN_AUTH_ON,
       NULL TBA_MAIN_KEY
  FROM DUAL;

INSERT INTO AUBDIVNDTL
SELECT '01' AUBDIVNDTL_ADMIN_UNIT_CODE,
       '23-NOV-2017' AUBDIVNDTL_EFF_DATE,
       DEPT_CODE AUBDIVNDTL_BUSDIVN_CODE
  FROM DIV_DATA; 