---UPDATE IN MIG 
--CL_CODE 
SELECT LNMISMAPPM_PRODUCT_CODE, LISTAGG(LNMISMAPPM_CL_CODE, ',') WITHIN GROUP (ORDER BY LNMISMAPPM_CL_CODE) AS LNMISMAPPM_CL_CODE
FROM   LNMISMAPPM 
WHERE LNMISMAPPM_PRODUCT_CODE IN (SELECT ACNTS_PROD_CODE FROM MIG_ACNTS )
GROUP BY LNMISMAPPM_PRODUCT_CODE;

----LNMISMAPPM_SME_NONSME_CODE
SELECT LNMISMAPPM_PRODUCT_CODE, LISTAGG(LNMISMAPPM_SME_NONSME_CODE, ',') WITHIN GROUP (ORDER BY LNMISMAPPM_SME_NONSME_CODE) AS LNMISMAPPM_SME_NONSME_CODE
FROM   LNMISMAPPM 
WHERE LNMISMAPPM_PRODUCT_CODE IN (SELECT ACNTS_PROD_CODE FROM MIG_ACNTS )
GROUP BY LNMISMAPPM_PRODUCT_CODE;

----LNMISMAPPM_SECURITY_CODE
SELECT LNMISMAPPM_PRODUCT_CODE, LISTAGG(LNMISMAPPM_SECURITY_CODE, ',') WITHIN GROUP (ORDER BY LNMISMAPPM_SECURITY_CODE) AS LNMISMAPPM_SECURITY_CODE
FROM   LNMISMAPPM 
WHERE LNMISMAPPM_PRODUCT_CODE IN (SELECT ACNTS_PROD_CODE FROM MIG_ACNTS )
GROUP BY LNMISMAPPM_PRODUCT_CODE;

--UPDATE IN PROD
BEGIN
   FOR IDX
      IN (SELECT I.IACLINK_INTERNAL_ACNUM, ACC2.CL_CODE
            FROM IACLINK I, ACC2
           WHERE     I.IACLINK_ACTUAL_ACNUM = ACC2.ACC_NO
                 AND I.IACLINK_ENTITY_NUM = 1)
   LOOP
      UPDATE LNACMIS L
         SET L.LNACMIS_HO_DEPT_CODE = IDX.CL_CODE
       WHERE L.LNACMIS_INTERNAL_ACNUM = IDX.IACLINK_INTERNAL_ACNUM;

      UPDATE LNACMISHIST H
         SET H.LNACMISH_HO_DEPT_CODE = IDX.CL_CODE
       WHERE H.LNACMISH_INTERNAL_ACNUM = IDX.IACLINK_INTERNAL_ACNUM;
   END LOOP;
END;

=====================================================
--CL CODE MISMACTH
SELECT A.ACNTS_BRN_CODE,
       facno(1, A.ACNTS_INTERNAL_ACNUM),
       A.ACNTS_AC_NAME1,
       A.ACNTS_PROD_CODE,
       A.ACNTS_AC_TYPE,
       L.LNACMIS_HO_DEPT_CODE,
       A1.ASSETCLS_ASSET_CODE,
       L1.LNPRD_SHORT_TERM_LOAN,
       A.ACNTS_ENTD_BY,
       (SELECT DISTINCT L.LNMISMAPPM_CL_CODE
          FROM LNMISMAPPM L
         WHERE L.LNMISMAPPM_PRODUCT_CODE = A.ACNTS_PROD_CODE) MAAPING_CODE
  FROM ACNTS A, LNACMIS L, ASSETCLS A1, LNPRODPM L1
 WHERE A.ACNTS_ENTITY_NUM = 1
   AND L.LNACMIS_ENTITY_NUM = 1
   AND A1.ASSETCLS_ENTITY_NUM = 1
   AND A.ACNTS_PROD_CODE = L1.LNPRD_PROD_CODE
   AND A.ACNTS_INTERNAL_ACNUM = L.LNACMIS_INTERNAL_ACNUM
   AND A.ACNTS_INTERNAL_ACNUM = A1.ASSETCLS_INTERNAL_ACNUM
   AND A.ACNTS_CLOSURE_DATE IS NULL
   AND L.LNACMIS_HO_DEPT_CODE LIKE '%CL5%'
   AND L1.LNPRD_SHORT_TERM_LOAN = 0
======================================================
--CORRECTION 
WITH temp
    AS (SELECT *
          FROM LNMISMAPPM l)
 SELECT DISTINCT LNMISMAPPM_ENTITY_NUM,
                 t.LNMISMAPPM_PRODUCT_CODE,
                 LNMISMAPPM_CLIENT_TYPE,
                 TRIM (REGEXP_SUBSTR (t.LNMISMAPPM_CL_CODE,
                                      '[^|]+',
                                      1,
                                      levels.COLUMN_VALUE))
                    AS LNMISMAPPM_CL_CODE,
                 TRIM (REGEXP_SUBSTR (t.LNMISMAPPM_SME_NONSME_CODE,
                                      '[^|]+',
                                      1,
                                      levels.COLUMN_VALUE))
                    AS LNMISMAPPM_SME_NONSME_CODE,
                 TRIM (REGEXP_SUBSTR (t.LNMISMAPPM_SECURITY_CODE,
                                      '[^|]+',
                                      1,
                                      levels.COLUMN_VALUE))
                    AS LNMISMAPPM_SECURITY_CODE,
                 LNMISMAPPM_ENTD_BY,
                 LNMISMAPPM_ENTD_ON,
                 LNMISMAPPM_LAST_MOD_BY,
                 LNMISMAPPM_LAST_MOD_ON,
                 LNMISMAPPM_AUTH_BY,
                 LNMISMAPPM_AUTH_ON,
                 TBA_MAIN_KEY
   FROM temp t,
        TABLE (
           CAST (
              MULTISET (
                     SELECT LEVEL
                       FROM DUAL
                 CONNECT BY LEVEL <=
                                 LENGTH (
                                    REGEXP_REPLACE (
                                       t.LNMISMAPPM_SME_NONSME_CODE,
                                       '[^|]+'))
                               + 1) AS SYS.OdciNumberList)) levels
ORDER BY LNMISMAPPM_PRODUCT_CODE