---OUTWORD
 EDIT  OCLGBATCH WHERE OCLGBAT_BRN_CODE=1032    -------OCLGBAT_STATUS,OCLGBAT_CLOSED_DATE,OCLGBAT_CLOSED_BY
 --AND OCLGBAT_CLG_BATCH=1
 AND OCLGBAT_CLG_DATE =TRUNC(SYSDATE);
 
 -----INWORD
 EDIT ICLGBATCH  --ICLGBAT_STATUS, ICLGBAT_CLOSED_DATE, ICLGBAT_CLOSED_BY
 WHERE ICLGBAT_BRN_CODE=55343
 AND ICLGBAT_CLG_BATCH=1
 AND ICLGBAT_CLG_DATE =TRUNC(SYSDATE);
 
-- POST_TRAN_BATCH_SL BATCH NA PORLE 0 HOBE 
--batch not tallied:OCLGINST te POST_TRAN_BATCH_SL .. etc number chilo instead of 0, and del row from oclgq 
SELECT * FROM OCLGINST OT WHERE OT.OCLGINST_BRN_CODE=21105 AND 
OT.OCLGINST_CLG_DATE='19-aug-2018' AND 
OT.OCLGINST_CLG_BATCH=1 FOR UPDATE 
-- 
SELECT * FROM OCLGQ OC WHERE OC.OCLGQ_BRN_CODE=55376 AND OC.OCLGQ_CLG_DATE='8-oct-2017' 
AND OC.OCLGQ_CLG_BATCH=1 
FOR UPDATE
 
----Regulization not done
SELECT OCLGBAT_CLG_BATCH
                  FROM OCLGBATCH
                 WHERE     OCLGBAT_ENTITY_NUM = V_ENTITY_NUM
                       AND OCLGBAT_BRN_CODE = P_BRNCODE
                       AND OCLGBAT_CLG_DATE =
                              TO_DATE (P_CURR_DATE, 'DD-MM-YYYY')
                       AND OCLGBAT_STATUS <> 'C'
CLEARING_STATE
CLEARING_TRANSACTION
INWARD_CLEARING_IMAGE
INWARD_CLEARING_ITEM




-----------------------------------------
/* Formatted on 6/8/2023 4:58:01 PM (QP5 v5.388) */
SELECT *
  FROM INWARD_CLEARING_ITEM
 WHERE BRANCH_CODE = 5454 AND CLEARING_DATE = '08-jun-2023';



EDIT  ICLGBATCH      --ICLGBAT_STATUS, ICLGBAT_CLOSED_DATE, ICLGBAT_CLOSED_BY
 WHERE ICLGBAT_STATUS = 'O' AND ICLGBAT_CLG_DATE = TRUNC (SYSDATE)   AND ICLGBAT_BRN_CODE   =5454


EDIT  tran2023 where   TRAN_ENTITY_NUM=1 and TRAN_BRN_CODE=5454     and TRAN_DATE_OF_TRAN='08-jun-2023' and TRAN_BATCH_NUMBER=214;


EDIT  tranBAT2023 where   TRANBAT_ENTITY_NUM=1 and TRANBAT_BRN_CODE=2212     and TRANBAT_DATE_OF_TRAN='08-jun-2023' and TRANBAT_BATCH_NUMBER=167;

EDIT  tranBAT2023 where   TRANBAT_ENTITY_NUM=1 and TRANBAT_BRN_CODE=2881     and TRANBAT_DATE_OF_TRAN='08-jun-2023' and TRANBAT_BATCH_NUMBER=475;


SELECT *
  FROM CLEARING_TRANSACTION
 WHERE BRANCH_CODE = 4416;

EDIT BOPAUTHQ
 WHERE     BOPAUTHQ_ENTITY_NUM = 1
       AND BOPAUTHQ_TRAN_BRN_CODE =2212
       AND BOPAUTHQ_TRAN_DATE_OF_TRAN = '08-JUN-2023'   
       AND BOPAUTHQ_TRAN_BATCH_NUMBER =167;

EDIT tranbat2023 where  TRANBAT_BRN_CODE IN (1156,1313,1321,1404,1537,1644,2808,2881,4416,4481,4887,5751,6049) 
and TRANBAT_ENTITY_NUM=1 and TRANBAT_DATE_OF_TRAN='08-jun-2023'   AND TRANBAT_SOURCE_TABLE='ICLG'
and TRANBAT_BATCH_NUMBER IN( 127,90,32,67,45,50,95,80,462,104,94,70,133,151)




 