BEGIN
   FOR IDX IN (SELECT NEW_CLCODE, BIRTH_DATE
                 FROM acc, temp_client
                WHERE CLIENT_NO = OLD_CLCODE AND BRN_CODE = 10090)
   LOOP
      UPDATE CLIENTS
         SET CLIENTS_BIRTH_DATE = IDX.BIRTH_DATE
       WHERE CLIENTS_CODE = IDX.NEW_CLCODE AND CLIENTS_ENT_NUM = 1;

      UPDATE INDCLIENTS
         SET INDCLIENT_BIRTH_DATE = IDX.BIRTH_DATE
       WHERE INDCLIENT_CODE = IDX.NEW_CLCODE;
   END LOOP;
END;