/* Formatted on 10/12/2020 11:35:47 AM (QP5 v5.227.12220.39754) */
EDIT GRPCLIENTS WHERE GRPCLNT_GROUP_CODE = 'CORP';

--------------------------------------------------------
INSERT INTO GRPCLIENTSDTL
   SELECT 1 GRPCLDTL_ENTITY_NUM,
          'CORP' GRPCLDTL_GROUP_CODE,
          '08-jan-2019' GRPCLDTL_DATE_OF_ENTRY,
          124 + ROWNUM GRPCLDTL_SL,
          acc_no GRPCLDTL_CLIENT_CODE
     FROM acc4;
----------------------------------------------------
INSERT INTO GRPCLIENTSDTLHIST
   SELECT GRPCLDTL_ENTITY_NUM,
          GRPCLDTL_GROUP_CODE,
          GRPCLDTL_DATE_OF_ENTRY,
          GRPCLDTL_SL,
          GRPCLDTL_CLIENT_CODE
     FROM GRPCLIENTSDTL
    WHERE     GRPCLDTL_GROUP_CODE = 'CORP'
          AND GRPCLDTL_CLIENT_CODE IN (SELECT ACC_NO FROM ACC4);