/* Formatted on 10/11/2022 6:19:29 PM (QP5 v5.388) */
BEGIN
    FOR IDX
        IN (SELECT IACLINK_INTERNAL_ACNUM, NON_COM_ACC CL_CODE
              FROM acc5, iaclink
             WHERE IACLINK_ENTITY_NUM = 1 AND IACLINK_ACTUAL_ACNUM = acc_no)
    LOOP
        UPDATE LNACMIS
           SET LNACMIS_LATEST_EFF_DATE = '30-SEP-2022',
               LNACMIS_HO_DEPT_CODE = IDX.CL_CODE
         WHERE     LNACMIS_ENTITY_NUM = 1
               AND LNACMIS_INTERNAL_ACNUM = IDX.IACLINK_INTERNAL_ACNUM;
    END LOOP;

    COMMIT;
END;

INSERT INTO LNACMISHIST
SELECT 1                              LNACMISH_ENTITY_NUM,
       LNACMIS_INTERNAL_ACNUM         LNACMISH_INTERNAL_ACNUM,
       LNACMIS_LATEST_EFF_DATE        LNACMISH_EFF_DATE,
       LNACMIS_SEGMENT_CODE           LNACMISH_SEGMENT_CODE,
       LNACMIS_HO_DEPT_CODE           LNACMISH_HO_DEPT_CODE,
       LNACMIS_INDUS_CODE             LNACMISH_INDUS_CODE,
       LNACMIS_SUB_INDUS_CODE         LNACMISH_SUB_INDUS_CODE,
       LNACMIS_BSR_ACT_OCC_CODE       LNACMISH_BSR_ACT_OCC_CODE,
       LNACMIS_BSR_MAIN_ORG_CODE      LNACMISH_BSR_MAIN_ORG_CODE,
       LNACMIS_BSR_SUB_ORG_CODE       LNACMISH_BSR_SUB_ORG_CODE,
       LNACMIS_BSR_STATE_CODE         LNACMISH_BSR_STATE_CODE,
       LNACMIS_BSR_DISTRICT_CODE      LNACMISH_BSR_DISTRICT_CODE,
       LNACMIS_NATURE_BORROWAL_AC     LNACMISH_NATURE_BORROWAL_AC,
       LNACMIS_POP_GROUP_CODE         LNACMISH_POP_GROUP_CODE,
       '48629'                        LNACMISH_ENTD_BY,
       SYSDATE                        LNACMISH_ENTD_ON,
       NULL                           LNACMISH_LAST_MOD_BY,
       NULL                           LNACMISH_LAST_MOD_ON,
       '48629'                        LNACMISH_AUTH_BY,
       SYSDATE                        LNACMISH_AUTH_ON,
       NULL                           TBA_MAIN_KEY,
       LNACMIS_PURPOSE_CODE           LNACMISH_PURPOSE_CODE,
       LNACMIS_PROD_WITH_ETP          LNACMISH_PROD_WITH_ETP,
       LNACMIS_PROD_WITHOUT_ETP       LNACMISH_PROD_WITHOUT_ETP,
       LNACMIS_CROPCODE               LNACMISH_CROPCODE,
       LNACMIS_SEC_TYPE               LNACMISH_SEC_TYPE
  FROM acc5, iaclink, LNACMIS
 WHERE     IACLINK_ENTITY_NUM = 1
       AND IACLINK_ACTUAL_ACNUM = acc_no
       AND LNACMIS_ENTITY_NUM = 1
       AND LNACMIS_INTERNAL_ACNUM = IACLINK_INTERNAL_ACNUM