select GMO_BRANCH GMO_CODE,
       (SELECT MBRN_NAME
          FROM MBRN
         WHERE MBRN_ENTITY_NUM = 1 AND MBRN_CODE = GMO_BRANCH)
          GMO_NAME,
       PO_BRANCH PO_CODE,
       (SELECT MBRN_NAME
          FROM MBRN
         WHERE MBRN_ENTITY_NUM = 1 AND MBRN_CODE = PO_BRANCH)
          PO_NAME,
       (SELECT MBRN_NAME
          FROM MBRN
         WHERE MBRN_ENTITY_NUM = 1 AND MBRN_CODE = TT.BRANCH_CODE)
          BRANCH_NAME,tt.*

from (SELECT  IACLINK_BRN_CODE BRANCH_CODE,
                 ACC_NO,
                 ACNTS_AC_NAME1 || ACNTS_AC_NAME2 ACCOUNT_NAME,
                 CASE
                    WHEN ACNTS_CLOSURE_DATE IS NULL THEN 'Open'
                    ELSE 'Closed'
                 END
                    ACCOUNT_STATUS,
             --50
       ACBLK_AMT_TRF_BLK_GL,
      ACBLK_AMT_RECOVERED,
      ACBLK_AMT_TRF_BLK_GL - ACBLK_AMT_RECOVERED BLOCK_AMOUNT, -- 100  - 20 =80
      WAIVED_INTEREST_AMOUNT CREDITABLE_AMOUNT,                          --50
      ABS((ACBLK_AMT_TRF_BLK_GL - ACBLK_AMT_RECOVERED) - WAIVED_INTEREST_AMOUNT)
         TO_BE_RECOVERED_AMOUNT                            -- 100-20-50 =
  FROM COVID_SBL_DATA C,
       IACLINK,
       ACBLKCOVID,
       ACNTS
 WHERE     IACLINK_ENTITY_NUM = 1
       AND IACLINK_ACTUAL_ACNUM = ACC_NO
       AND ACBLK_ENTITY_NUM = 1
       AND ACBLK_INTERNAL_ACNUM = IACLINK_INTERNAL_ACNUM
       AND ACBLK_ASSET_TYPE = 'P'
       AND ACNTS_ENTITY_NUM = 1
      -- AND ACNTS_BRN_CODE = 26
       AND ACNTS_INTERNAL_ACNUM = IACLINK_INTERNAL_ACNUM
       AND ACNTS_CLOSURE_DATE <= '03-mar-2021'
       AND ACNTS_INTERNAL_ACNUM NOT IN (SELECT B.ACBLK_INTERNAL_ACNUM
                                          FROM BACKUPTABLE.COVID_DATA_INVALID B)
       AND ACBLK_AMT_TRF_BLK_GL - ACBLK_AMT_RECOVERED = 0
UNION ALL
SELECT  IACLINK_BRN_CODE BRANCH_CODE,
                 ACC_NO,
                 ACNTS_AC_NAME1 || ACNTS_AC_NAME2 ACCOUNT_NAME,
                 
                 CASE
                    WHEN ACNTS_CLOSURE_DATE IS NULL THEN 'Open'
                    ELSE 'Closed'
                 END
                    ACCOUNT_STATUS,
                  --50
        ACBLK_AMT_TRF_BLK_GL,
      ACBLK_AMT_RECOVERED,
      ACBLK_AMT_TRF_BLK_GL - ACBLK_AMT_RECOVERED BLOCK_AMOUNT, -- 100  - 20 =80
      WAIVED_INTEREST_AMOUNT CREDITABLE_AMOUNT,                          --50
      ABS((ACBLK_AMT_TRF_BLK_GL - ACBLK_AMT_RECOVERED) - WAIVED_INTEREST_AMOUNT)
         TO_BE_RECOVERED_AMOUNT                            
  FROM COVID_SBL_DATA C,
       IACLINK,
       ACBLKCOVID,
       ACNTS
 WHERE     IACLINK_ENTITY_NUM = 1
       AND IACLINK_ACTUAL_ACNUM = ACC_NO
       AND ACBLK_ENTITY_NUM = 1
       AND ACBLK_INTERNAL_ACNUM = IACLINK_INTERNAL_ACNUM
       AND ACBLK_ASSET_TYPE = 'N'
       AND ACNTS_ENTITY_NUM = 1
      --  AND ACNTS_BRN_CODE = 26
       AND ACNTS_INTERNAL_ACNUM = IACLINK_INTERNAL_ACNUM
       AND (ACNTS_CLOSURE_DATE IS NULL OR ACNTS_CLOSURE_DATE > '03-mar-2021')
       AND ACNTS_INTERNAL_ACNUM NOT IN (SELECT B.ACBLK_INTERNAL_ACNUM
                                          FROM BACKUPTABLE.COVID_DATA_INVALID B)
       AND ACBLK_AMT_TRF_BLK_GL - ACBLK_AMT_RECOVERED <
              WAIVED_INTEREST_AMOUNT
       AND ACBLK_AMT_TRF_BLK_GL - ACBLK_AMT_RECOVERED <> 0
UNION ALL
SELECT  IACLINK_BRN_CODE BRANCH_CODE,
                 ACC_NO,
                 ACNTS_AC_NAME1 || ACNTS_AC_NAME2 ACCOUNT_NAME,
                 CASE
                    WHEN ACNTS_CLOSURE_DATE IS NULL THEN 'Open'
                    ELSE 'Closed'
                 END
                    ACCOUNT_STATUS,
                       --50
       ACBLK_AMT_TRF_BLK_GL,
      ACBLK_AMT_RECOVERED,
      ACBLK_AMT_TRF_BLK_GL - ACBLK_AMT_RECOVERED BLOCK_AMOUNT, -- 100  - 20 =80
      WAIVED_INTEREST_AMOUNT CREDITABLE_AMOUNT,                          --50
      ABS((ACBLK_AMT_TRF_BLK_GL - ACBLK_AMT_RECOVERED) - WAIVED_INTEREST_AMOUNT)
         TO_BE_RECOVERED_AMOUNT                                    -- 100-20-50 =
  FROM COVID_SBL_DATA C,
       IACLINK,
       ACBLKCOVID,
       ACNTS
 WHERE     IACLINK_ENTITY_NUM = 1
       AND IACLINK_ACTUAL_ACNUM = ACC_NO
       AND ACBLK_ENTITY_NUM = 1
       AND ACBLK_INTERNAL_ACNUM = IACLINK_INTERNAL_ACNUM
       AND ACBLK_ASSET_TYPE = 'N'
       AND ACNTS_ENTITY_NUM = 1
      -- AND ACNTS_BRN_CODE = 26
       AND ACNTS_INTERNAL_ACNUM = IACLINK_INTERNAL_ACNUM
       AND ACNTS_CLOSURE_DATE <= '03-mar-2021'
       AND ACNTS_INTERNAL_ACNUM NOT IN (SELECT B.ACBLK_INTERNAL_ACNUM
                                          FROM BACKUPTABLE.COVID_DATA_INVALID B)
       AND ACBLK_AMT_TRF_BLK_GL - ACBLK_AMT_RECOVERED = 0)TT,
       MBRN_TREE1
 WHERE TT.BRANCH_CODE = BRANCH