CREATE TABLE MOBSMSCONSOLQ
(
  MOBSMSCNSL_BRN_CODE          NUMBER(6),
  MOBSMSCNSL_DATE              DATE,
  MOBSMSCNSL_ACC_NUM           NUMBER(14),
  MOBSMSCNSL_MOB_NUM           VARCHAR2(20 BYTE),
  MOBSMSCNSL_DEPINT_AMT        NUMBER(18,3),
  MOBSMSCNSL_SRCTAX_AMT        NUMBER(18,3),
  MOBSMSCNSL_MNTCHG_AMT        NUMBER(18,3),
  MOBSMSCNSL_EXCISDT_AMT       NUMBER(18,3),
  MOBSMSCNSL_SMSCHG_AMT        NUMBER(18,3),
  MOBSMSCNSL_DRCRD_MNTCHG_AMT  NUMBER(18,3),
  MOBSMSCNSL_VAT_AMT           NUMBER(18,3),
  MOBSMSCNSL_ATMCHG_AMT        NUMBER(18,2),
  MOBSMSCNSL_ATM_VAT_AMT       NUMBER(18,2)
)
TABLESPACE TBFES
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE INDEX IDX_BRN_CODE ON MOBSMSCONSOLQ
(MOBSMSCNSL_BRN_CODE)
LOGGING
TABLESPACE TBFES
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
