/* Formatted on 8/21/2022 1:17:06 PM (QP5 v5.252.13127.32867) */
UPDATE  addrdtls SET ADDRDTLS_PHONE_NUM1=null,ADDRDTLS_PHONE_NUM2=null
 WHERE     TRIM (ADDRDTLS_MOBILE_NUM) = TRIM (ADDRDTLS_PHONE_NUM1)
       AND TRIM (ADDRDTLS_MOBILE_NUM) IS NOT NULL
       AND TRIM (ADDRDTLS_PHONE_NUM1) IS NOT NULL;
       
       
       update  piddocs set PIDDOCS_ISSUE_CNTRY='BD'   where PIDDOCS_PID_TYPE='PP' and trim(PIDDOCS_ISSUE_CNTRY) is null;