/* Formatted on 3/24/2019 11:38:20 AM (QP5 v5.227.12220.39754) */
SELECT *
FROM (SELECT ACNTSTATUS_ENTD_BY,
       USER_NAME ACNTSTATUS_ENTD_BY_NAME,
       FACNO(1,ACNTSTATUS_INTERNAL_ACNUM) ACCOUNT_NUMBER,
       ACNTSTATUS_EFF_DATE,
       CASE
          WHEN ACNTSTATUS_FLG = 'O' THEN 'OPERATIVE'
          WHEN ACNTSTATUS_FLG = 'D' THEN 'DORMENT'
          WHEN ACNTSTATUS_FLG = 'I' THEN 'INOPERATIVE'
          ELSE NULL
       END ACNTSTATUS_FLG,
       ACNTSTATUS_ENTD_ON,
       ACNTSTATUS_LAST_MOD_BY,
       (SELECT USER_NAME
          FROM USERS
         WHERE USER_ID = ACNTSTATUS_LAST_MOD_BY)
          ACNTSTATUS_LAST_MOD_NAME,
       ACNTSTATUS_LAST_MOD_ON,
       ACNTSTATUS_REMARKS1 || ACNTSTATUS_REMARKS2 || ACNTSTATUS_REMARKS3
          REMARKS
  FROM ACNTSTATUS, USERS
 WHERE     ACNTSTATUS_ENTITY_NUM = 1
       AND ACNTSTATUS_ENTD_BY = USER_ID
       AND ACNTSTATUS_ENTD_BY IN ('43200', '30819', '2734')
       AND ACNTSTATUS_EFF_DATE BETWEEN '25-may-2017' AND '03-jan-2019')
       ORDER BY  ACCOUNT_NUMBER