exec sp_macro_ddpo;

select *from errorlog;
select *from mig_errorlog;


DECLARE 
V_ERROR VARCHAR2(100);
BEGIN
SP_MIG_DDPO(23093,V_ERROR);

      UPDATE DDPOISS
         SET DDPOISS_STATUS = 'A'
       WHERE DDPOISS.DDPOISS_REMIT_CODE = 1;


      UPDATE DDPOISSDTLANX
         SET DDPOANX_DUPISS_DAY_SL = '0'
       WHERE DDPOANX_DUPISS_DAY_SL IS NULL;
       
          UPDATE DDPOPAYDB
         SET DDPOPAYDB_ISSUED_ON_BNK = DDPOPAYDB_ISSUED_BANK,
             DDPOPAYDB_ISSUED_ON_BRN = DDPOPAYDB_ISSUED_BRN
       WHERE DDPOPAYDB_REMIT_CODE = 1;                         --FOR PAY ORDER

      --COMMIT;


      UPDATE DDPOPAYDB
         SET DDPOPAYDB_ISSUED_ON_BRN = TO_NUMBER (DDPOPAYDB_ISSUED_ON_BRN);
         commit;
END;

delete DD_FINDING;
------EXPORT DATA FROM PRODUCTION -----------
      SELECT D.DDPOPAYDB_ISSUED_BRN,
             D.DDPOPAYDB_INST_DATE,
             D.DDPOPAYDB_INST_PFX,
             D.DDPOPAYDB_LEAF_NUM,
             D.DDPOPAYDB_INST_AMT
        FROM DDPOPAYDB  D
       WHERE     TO_NUMBER (D.DDPOPAYDB_ISSUED_ON_BRN) = 23093
       and DDPOPAYDB_REMIT_CODE in ('2','9')
             AND D.DDPOPAYDB_ADVICE_REC_DATE IS NULL;  
