/* Formatted on 10/22/2019 4:17:20 PM (QP5 v5.227.12220.39754) */
INSERT INTO DDADVPART
   SELECT 1 DDADVPART_ENTITY_NUM,
          DDPOPAYDB_ISSUED_ON_BRN DDADVPART_BRN_CODE,
          DDPOPAYDB_ADVICE_NO DDADVPART_ADVICE_NO,
          DDPOPAYDB_ADVICE_DATE DDADVPART_ADVICE_DATE,
          DDPOPAYDB_ISSUED_BRN DDADVPART_ISSUE_BRN_CODE,
          DDPOPAYDB_ADVICE_REC_DATE DDADVPART_ADV_REC_DATE,
          DDPOPAYDB_INST_PFX DDADVPART_LEAF_PFX,
          DDPOPAYDB_LEAF_NUM DDADVPART_LEAF_NUMBER,
          NULL DDADVPART_ORG_LEAF_NUMBER,
          NULL DDADVPART_ORG_INST_DATE,
          1 DDADVPART_DAY_SL,
          DDPOPAYDB_INST_AMT DDADVPART_INST_AMT,
          DDPOPAYDB_INST_AMT DDADVPART_TOT_INST_AMT,
          DDPOPAYDB_INST_DATE DDADVPART_INST_DATE,
          DDPOPAYDB_BENEF_NAME1 || DDPOPAYDB_BENEF_NAME2
             DDADVPART_BENIFICARY_NAME,
          DDPOPAYDB_IBR_TRN_CODE DDADVPART_IRB_TRN_CODE,
          'UNPAID' DDADVPART_INST_STATUS,
          POST_TRAN_BRN POST_TRAN_BRN,
          POST_TRAN_DATE POST_TRAN_DATE,
          POST_TRAN_BATCH_NUM POST_TRAN_BATCH_NUM,
          'MIG' DDADVPART_ENTD_BY,
          SYSDATE DDADVPART_ENTD_ON,
          NULL DDADVPART_LAST_MOD_BY,
          NULL DDADVPART_LAST_MOD_ON,
          'MIG' DDADVPART_AUTH_BY,
          SYSDATE DDADVPART_AUTH_ON,
          NULL DDADVPART_REJ_BY,
          NULL DDADVPART_REJ_ON
     FROM ddpopaydb
    WHERE     DDPOPAYDB_ENTITY_NUM = 1
          AND DDPOPAYDB_REMIT_CODE IN ('2', '9')
          AND DDPOPAYDB_ISSUED_on_BRN = 55327
          AND DDPOPAYDB_LEAF_NUM IN
                 (2668501, 2668502, 2668503, 2668504, 2668505);

INSERT INTO DDADVPARTDTL
   SELECT 1 DDADVPARTDTL_ENTITY_NUM,
          DDPOPAYDB_ISSUED_ON_BRN DDADVPARTDTL_BRN_CODE,
          DDPOPAYDB_ADVICE_NO DDADVPARTDTL_ADVICE_NO,
          DDPOPAYDB_ADVICE_DATE DDADVPARTDTL_ADVICE_DATE,
          DDPOPAYDB_ISSUED_BRN DDADVPARTDTL_ISSUE_BRN_CODE,
          DDPOPAYDB_ADVICE_REC_DATE DDADVPARTDTL_ADV_REC_DATE,
          DDPOPAYDB_INST_PFX DDADVPARTDTL_LEAF_PFX,
          DDPOPAYDB_LEAF_NUM DDADVPARTDTL_LEAF_NUMBER,
          NULL DDADVPARTDTL_ORG_LEAF_NUMBER,
          NULL DDADVPARTDTL_ORG_INST_DATE,
          1 DDADVPARTDTL_DAY_SL,
          DDPOPAYDB_INST_AMT DDADVPARTDTL_INST_AMT,
          DDPOPAYDB_INST_DATE DDADVPARTDTL_INST_DATE,
          DDPOPAYDB_BENEF_NAME1 || DDPOPAYDB_BENEF_NAME2
             DDADVPARTDTL_BENIFICARY_NAME,
          DDPOPAYDB_IBR_TRN_CODE DDADVPARTDTL_IRB_TRN_CODE,
          'UNPAID' DDADVPARTDTL_INST_STATUS,
          DDPOPAYDB_REMIT_CODE DDADVPARTDTL_REM_CODE
     FROM DDPOPAYDB
    WHERE     DDPOPAYDB_ENTITY_NUM = 1
          AND DDPOPAYDB_REMIT_CODE IN ('2', '9')
          AND DDPOPAYDB_ISSUED_on_BRN = 55327
          AND DDPOPAYDB_LEAF_NUM IN
                 (2668501, 2668502, 2668503, 2668504, 2668505);