----DD block GL balance
SELECT B.GLBBAL_BRANCH_CODE,M.MBRN_NAME,FN_BIS_GET_ASON_GLBAL_AC (1,B.GLBBAL_BRANCH_CODE, '134101102','BDT','29-NOV-2016','29-NOV-2016')    GLBBAL_BC_BAL
FROM GLBBAL B,MBRN M
 WHERE B.GLBBAL_ENTITY_NUM=1
 AND B.GLBBAL_GLACC_CODE='134101102'
AND B.GLBBAL_YEAR='2016'
AND B.GLBBAL_BC_BAL<>0
AND B.GLBBAL_BRANCH_CODE=M.MBRN_CODE;

------PO block GL balance 
SELECT B.GLBBAL_BRANCH_CODE,M.MBRN_NAME,FN_BIS_GET_ASON_GLBAL_AC (1,B.GLBBAL_BRANCH_CODE, '134104103','BDT','29-NOV-2016','29-NOV-2016') GLBBAL_BC_BAL
FROM GLBBAL B,MBRN M
 WHERE B.GLBBAL_ENTITY_NUM=1
 AND B.GLBBAL_GLACC_CODE='134104103'
AND B.GLBBAL_YEAR='2016'
AND B.GLBBAL_BC_BAL<>0
AND B.GLBBAL_BRANCH_CODE=M.MBRN_CODE;



-----govt dd block GL balance 
SELECT B.GLBBAL_BRANCH_CODE,M.MBRN_NAME,FN_BIS_GET_ASON_GLBAL_AC (1,B.GLBBAL_BRANCH_CODE, '134101105','BDT','29-NOV-2016','29-NOV-2016')    GLBBAL_BC_BAL
FROM GLBBAL B,MBRN M
 WHERE B.GLBBAL_ENTITY_NUM=1
 AND B.GLBBAL_GLACC_CODE='134101105'
AND B.GLBBAL_YEAR='2016'
AND B.GLBBAL_BC_BAL<>0
AND B.GLBBAL_BRANCH_CODE=M.MBRN_CODE;


-----cal ldeposit block GL balance 
SELECT B.GLBBAL_BRANCH_CODE,M.MBRN_NAME,FN_BIS_GET_ASON_GLBAL_AC (1,B.GLBBAL_BRANCH_CODE, '125101102','BDT','29-NOV-2016','29-NOV-2016')    GLBBAL_BC_BAL
FROM GLBBAL B,MBRN M
 WHERE B.GLBBAL_ENTITY_NUM=1
 AND B.GLBBAL_GLACC_CODE='125101102'
AND B.GLBBAL_YEAR='2016'
AND B.GLBBAL_BC_BAL<>0
AND B.GLBBAL_BRANCH_CODE=M.MBRN_CODE;


-----DD EX-ADVICE BLOCK GL balance 
SELECT B.GLBBAL_BRANCH_CODE,M.MBRN_NAME, FN_BIS_GET_ASON_GLBAL_AC (1,B.GLBBAL_BRANCH_CODE, '225107102','BDT','29-NOV-2016','29-NOV-2016')    GLBBAL_BC_BAL 
FROM GLBBAL B,MBRN M
 WHERE B.GLBBAL_ENTITY_NUM=1
 AND B.GLBBAL_GLACC_CODE='225107102'
AND B.GLBBAL_YEAR='2016'
AND B.GLBBAL_BC_BAL<>0
AND B.GLBBAL_BRANCH_CODE=M.MBRN_CODE;

===================BALANCE WITH MIG
SELECT BRANCH_CODE, MBRN_NAME,GL_BAL_ACON_TODAY,GL_BAL_ACON_MIG_DATE  FROM 
(SELECT BRANCH_CODE, FN_BIS_GET_ASON_GLBAL_AC (1,
                                BRANCH_CODE,
                                EXTGL_ACCESS_CODE,
                                'BDT',
                                '29-NOV-2016',
                                '29-NOV-2016') GL_BAL_ACON_TODAY,
                                FN_BIS_GET_ASON_GLBAL_AC (1,
                                BRANCH_CODE,
                                EXTGL_ACCESS_CODE,
                                'BDT',
                                MIG_END_DATE,
                                '29-NOV-2016') GL_BAL_ACON_MIG_DATE fROM EXTGL , MIG_DETAIL
WHERE EXTGL_ACCESS_CODE = '225107102') A , MBRN
WHERE A.GL_BAL_ACON_TODAY <> 0 
AND MBRN_CODE = A.BRANCH_CODE
ORDER BY A.BRANCH_CODE
-----------------------------------------------------------------------------------------------
SELECT ACNTS_BRN_CODE,M.MBRN_NAME, PRODUCT_CODE, PRODUCT_NAME,MIG_END_DATE,ACCOUNT_NUMBER,ACNTS_AC_NAME1,ACNTS_AC_TYPE,ACOUNT_BAL,ACOUNT_BAL_MIG FROM (
SELECT C.ACNTS_BRN_CODE,P.PRODUCT_CODE,P.PRODUCT_NAME,D.MIG_END_DATE,FACNO(1,C.ACNTS_INTERNAL_ACNUM ) ACCOUNT_NUMBER,
C.ACNTS_AC_NAME1,C.ACNTS_AC_TYPE,FN_GET_ASON_ACBAL_AC(1,C.ACNTS_INTERNAL_ACNUM,'BDT','29-NOV-2016','29-NOV-2016') ACOUNT_BAL,
FN_GET_ASON_ACBAL_AC(1,C.ACNTS_INTERNAL_ACNUM,'BDT',D.MIG_END_DATE,'29-NOV-2016') ACOUNT_BAL_MIG
FROM PRODUCTS P,ACNTS C,MIG_DETAIL D
WHERE P.PRODUCT_FOR_DEPOSITS=1
AND C.ACNTS_ENTITY_NUM=1
AND P.PRODUCT_FOR_RUN_ACS=1
AND P.PRODUCT_CODE=C.ACNTS_PROD_CODE
AND C.ACNTS_BRN_CODE=D.BRANCH_CODE
) A,MBRN M
WHERE  ACNTS_BRN_CODE=MBRN_CODE
AND MBRN_ENTITY_NUM=1
AND A.ACOUNT_BAL<0
ORDER BY 1;
----Debit balance on account
SELECT C.ACNTS_BRN_CODE,M.MBRN_NAME,P.PRODUCT_CODE,P.PRODUCT_NAME,D.MIG_END_DATE,FACNO(1,A.ACNTBAL_INTERNAL_ACNUM) ACNTBAL_INTERNAL_ACNUM,A.ACNTBAL_BC_BAL
FROM PRODUCTS P,ACNTBAL A,ACNTS C,MBRN M,MIG_DETAIL D
WHERE P.PRODUCT_FOR_DEPOSITS=1
AND A.ACNTBAL_ENTITY_NUM=1
AND C.ACNTS_ENTITY_NUM=1
AND P.PRODUCT_FOR_RUN_ACS=1
AND P.PRODUCT_CODE=C.ACNTS_PROD_CODE
AND A.ACNTBAL_INTERNAL_ACNUM=C.ACNTS_INTERNAL_ACNUM
AND C.ACNTS_BRN_CODE=M.MBRN_CODE
AND M.MBRN_CODE=D.BRANCH_CODE
AND A.ACNTBAL_BC_BAL<0
--AND C.ACNTS_AC_TYPE<>'CAOD'
ORDER BY 1;

-----DEBIT INTEREST POSTING 
select   TRAN_BRN_CODE,(select MBRN_NAME  from mbrn m where m.MBRN_CODE=TRAN_BRN_CODE) branch_name,  facno(1,TRAN_INTERNAL_ACNUM) acc_number, TRAN_DB_CR_FLG, TRAN_AMOUNT, TRANBAT_NARR_DTL1
from ACNTS,TRAN2017, tranbat2017
where TRAN_ENTITY_NUM=1
and TRAN_ENTITY_NUM= TRANBAT_ENTITY_NUM
and TRAN_INTERNAL_ACNUM=ACNTS_INTERNAL_ACNUM
and ACNTS_PROD_CODE=1030
and TRAN_DB_CR_FLG='D'
and TRAN_BRN_CODE = TRANBAT_BRN_CODE
and TRAN_DATE_OF_TRAN = TRANBAT_DATE_OF_TRAN
and TRAN_BATCH_NUMBER = TRANBAT_BATCH_NUMBER
and TRAN_DATE_OF_TRAN = '30-jun-2017'
 and TRANBAT_NARR_DTL1 = 'Running A/c Interest Settlement'
 order by TRAN_BRN_CODE, facno(1,TRAN_INTERNAL_ACNUM);