INSERT INTO DDPOISSDTL
   SELECT DDPOISS_ENTITY_NUM DDPOISSDTL_ENTITY_NUM,
          DDPOISS_BRN_CODE DDPOISSDTL_BRN_CODE,
          DDPOISS_REMIT_CODE DDPOISSDTL_REMIT_CODE,
          DDPOISS_ISSUE_DATE DDPOISSDTL_ISSUE_DATE,
          DDPOISS_DAY_SL DDPOISSDTL_DAY_SL,
          DDPOISS_DAY_SL DDPOISSDTL_INST_SL,
          200 DDPOISSDTL_INST_BANK,
          DDPOISS_BRN_CODE DDPOISSDTL_INST_BRN,
          DDPOISS_TOT_INST_AMT DDPOISSDTL_INST_AMT,
          DDPOISS_TOT_ACTUAL_COMM DDPOISSDTL_ACTUAL_COMMN,
          DDPOISS_TOT_STAX_AMT DDPOISSDTL_ACTUAL_STAX,
       null   DDPOISSDTL_SYS_CALC_COMMN,
          DDPOISS_TOT_OTHBNK_STAX_AMT DDPOISSDTL_SYS_CALC_STAX,
          NULL DDPOISSDTL_BENEF_CODE,
          ' ' DDPOISSDTL_BENEF_NAME1,
          ' ' DDPOISSDTL_BENEF_NAME2,
          NULL DDPOISSDTL_ON_AC_OF,
          NULL DDPOISSDTL_ISS_TYPE,
          '0' DDPOISSDTL_INST_NUM_PFX,
          0 DDPOISSDTL_INST_NUM,
          DDPOISS_ENTD_BY DDPOISSDTL_LAST_PRNT_BY,
          DDPOISS_ENTD_ON DDPOISSDTL_LAST_PRNT_DATETIME,
          DDPOISS_STATUS DDPOISSDTL_CAN_STATUS,
          DDPOISS_TOT_OTHBNK_COMM DDPOISSDTL_OTHBNK_COMMN,
          NULL DDPOISSDTL_SYS_CALC_OTHBNK,
          DDPOISS_TOT_OTHBNK_STAX_AMT DDPOISSDTL_OTHBNK_STAX,
          NULL DDPOISSDTL_SYS_CALC_OB_STAX,
          NULL DDPOISSDTL_REM1,
          NULL DDPOISSDTL_REM2,
          NULL DDPOISSDTL_REM3,
          NULL DDPOISSDTL_ACTUAL_PT_CHGS,
          NULL DDPOISSDTL_SYS_CALC_PT_CHGS
     FROM ddpoiss
    WHERE     DDPOISS_ENTITY_NUM = 1
          AND DDPOISS_BRN_CODE = 16089
          AND DDPOISS_REMIT_CODE = '1'
          AND DDPOISS_ISSUE_DATE =
                 TO_DATE ('1/1/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS')