 SELECT SUM(DR_AMOUNT),SUM(CR_AMOUNT)
 FROM(SELECT CASE WHEN TRAN_DB_CR_FLG = 'D' THEN TRAN_AMOUNT ELSE 0 END DR_AMOUNT,
       CASE WHEN TRAN_DB_CR_FLG = 'C' THEN TRAN_AMOUNT ELSE 0 END CR_AMOUNT
  FROM TRAN2014
 WHERE     TRAN_ENTITY_NUM = 1
       AND TRAN_ACING_BRN_CODE = 16014
       AND TRAN_GLACC_CODE = '225107101'
       UNION ALL
        SELECT CASE WHEN TRAN_DB_CR_FLG = 'D' THEN TRAN_AMOUNT ELSE 0 END DR_AMOUNT,
       CASE WHEN TRAN_DB_CR_FLG = 'C' THEN TRAN_AMOUNT ELSE 0 END CR_AMOUNT
  FROM TRAN2015
 WHERE     TRAN_ENTITY_NUM = 1
       AND TRAN_ACING_BRN_CODE = 16014
       AND TRAN_GLACC_CODE = '225107101'
       UNION ALL 
        SELECT CASE WHEN TRAN_DB_CR_FLG = 'D' THEN TRAN_AMOUNT ELSE 0 END DR_AMOUNT,
       CASE WHEN TRAN_DB_CR_FLG = 'C' THEN TRAN_AMOUNT ELSE 0 END CR_AMOUNT
  FROM TRAN2016
 WHERE     TRAN_ENTITY_NUM = 1
       AND TRAN_ACING_BRN_CODE = 16014
       AND TRAN_GLACC_CODE = '225107101'
       UNION ALL
        SELECT CASE WHEN TRAN_DB_CR_FLG = 'D' THEN TRAN_AMOUNT ELSE 0 END DR_AMOUNT,
       CASE WHEN TRAN_DB_CR_FLG = 'C' THEN TRAN_AMOUNT ELSE 0 END CR_AMOUNT
  FROM TRAN2017
 WHERE     TRAN_ENTITY_NUM = 1
       AND TRAN_ACING_BRN_CODE = 16014
       AND TRAN_GLACC_CODE = '225107101'
       UNION ALL
        SELECT CASE WHEN TRAN_DB_CR_FLG = 'D' THEN TRAN_AMOUNT ELSE 0 END DR_AMOUNT,
       CASE WHEN TRAN_DB_CR_FLG = 'C' THEN TRAN_AMOUNT ELSE 0 END CR_AMOUNT
  FROM TRAN2018
 WHERE     TRAN_ENTITY_NUM = 1
       AND TRAN_ACING_BRN_CODE = 16014
       AND TRAN_GLACC_CODE = '225107101')