/* Formatted on 7/5/2022 6:17:52 PM (QP5 v5.252.13127.32867) */
SELECT TRAN_BRN_CODE,FACNO(1,TRAN_INTERNAL_ACNUM) ACCOUNT_NO,TRANBAT_NARR_DTL1,TRAN_GLACC_CODE,TRAN_AMOUNT
  FROM TRAN2022, TRANbat2022
 WHERE     TRANBAT_BRN_CODE = TRAN_BRN_CODE
       AND TRANBAT_DATE_OF_TRAN = TRAN_DATE_OF_TRAN
       AND TRANBAT_BATCH_NUMBER = TRAN_BATCH_NUMBER
       AND TRANBAT_ENTITY_NUM = 1
       AND TRAN_ENTITY_NUM = 1
       AND TRAN_DATE_OF_TRAN = '30-JUN-2022'
       AND TRANBAT_NARR_DTL1 = 'Running A/c Interest Settlement'
       AND TRAN_DB_CR_FLG = 'D'
       AND TRAN_INTERNAL_ACNUM <> 0
       AND TRAN_NARR_DTL1||TRAN_NARR_DTL2||TRAN_NARR_DTL3 IS NULL