/* Formatted on 6/18/2019 12:32:48 PM (QP5 v5.227.12220.39754) */
---DELETE ROW FROM SECDEPOSIT 
SELECT *
  FROM SECRCPT, SECASSIGNMTBAL, SECDEPOSIT
 WHERE     SECRCPT_ENTITY_NUM = 1
       AND SECAGMTBAL_ENTITY_NUM = 1
       AND SECDEP_ENTITY_NUM = 1
       AND SECDEP_DEP_INTERNAL_ACNUM = 13615200003164
       --   AND SECDEP_DEP_CONTRACT_NUM =
       AND SECDEP_SECURITY_NUM = SECRCPT_SECURITY_NUM
       AND SECRCPT_RELEASED_ON IS NULL
       AND SECRCPT_AUTH_ON IS NOT NULL
       AND SECAGMTBAL_SEC_NUM = SECDEP_SECURITY_NUM