/* Formatted on 7/24/2022 1:34:55 PM (QP5 v5.252.13127.32867) */
SELECT STATE_CODE,
       STATE_NAME,
       DISTRICT_CODE,
       DISTRICT_NAME,LOCN_CODE, LOCN_NAME
  FROM state, district,location
  where DISTRICT_STATE_CODE=STATE_CODE
   and LOCN_STATE_CODE=STATE_CODE
   and LOCN_DISTRICT_CODE=DISTRICT_CODE
  