INSERT INTO ACNTRNPR (ACTP_ACNT_NUM,
                      ACTP_LATEST_EFF_DATE,
                      ACTP_SRC_FUND,
                      ACTP_NOT_CASHR,
                      ACTP_NOT_NONCASHR,
                      ACTP_NOT_TFREMR,
                      ACTP_NOT_NONTFREMR,
                      ACTP_MAXAMT_CASHR,
                      ACTP_MAXAMT_NCASHR,
                      ACTP_MAXAMT_TFREMR,
                      ACTP_MAXAMT_NONTFREMR,
                      ACTP_CUTOFF_LMT_CASHR,
                      ACTP_CUTOFF_LMT_NONCASHR,
                      ACTP_CUTOFF_LMT_TFREMR,
                      ACTP_CUTOFF_LMT_NONTFREMR,
                      ACTP_NOT_CASHP,
                      ACTP_NOT_NONCASHP,
                      ACTP_NOT_TFREMP,
                      ACTP_NOT_NONTFREMP,
                      ACTP_MAXAMT_CASHP,
                      ACTP_MAXAMT_NCASHP,
                      ACTP_MAXAMT_TFREMP,
                      ACTP_MAXAMT_NONTFREMP,
                      ACTP_TOTAMT_CASHP,
                      ACTP_CUTOFF_LMT_CASHP,
                      ACTP_CUTOFF_LMT_NONCASHP,
                      ACTP_CUTOFF_LMT_TFREMP,
                      ACTP_CUTOFF_LMT_NONTFREMP)
   SELECT IACLINK_INTERNAL_ACNUM ACTP_ACNT_NUM,
          ACNT_OPEN_DATE ACTP_LATEST_EFF_DATE,
          'Simplified eKYC TP' ACTP_SRC_FUND,
          10,
          10,
          0,
          0,
          100000,
          100000,
          0,
          0,
          100000,
          100000,
          0,
          0,
          10,
          10,
          0,
          0,
          100000,
          100000,
          0,
          0,
          0,
          100000,
          100000,
          0,
          0
     FROM API_ACNT_OPEN, IACLINK
    WHERE     ACTUAL_ACNT_NUMBER = IACLINK_ACTUAL_ACNUM
          AND IACLINK_ENTITY_NUM = 1
          and IACLINK_INTERNAL_ACNUM not in (select ACTP_ACNT_NUM from  ACNTRNPR);



INSERT INTO ACNTRNPRHIST (ACTPH_ACNT_NUM,
                          ACTPH_LATEST_EFF_DATE,
                          ACTPH_SRC_FUND,
                          ACTPH_NOT_CASHR,
                          ACTPH_NOT_NONCASHR,
                          ACTPH_NOT_TFREMR,
                          ACTPH_NOT_NONTFREMR,
                          ACTPH_MAXAMT_CASHR,
                          ACTPH_MAXAMT_NCASHR,
                          ACTPH_MAXAMT_TFREMR,
                          ACTPH_MAXAMT_NONTFREMR,
                          ACTPH_CUTOFF_LMT_CASHR,
                          ACTPH_CUTOFF_LMT_NONCASHR,
                          ACTPH_CUTOFF_LMT_TFREMR,
                          ACTPH_CUTOFF_LMT_NONTFREMR,
                          ACTPH_NOT_CASHP,
                          ACTPH_NOT_NONCASHP,
                          ACTPH_NOT_TFREMP,
                          ACTPH_NOT_NONTFREMP,
                          ACTPH_MAXAMT_CASHP,
                          ACTPH_MAXAMT_NCASHP,
                          ACTPH_MAXAMT_TFREMP,
                          ACTPH_MAXAMT_NONTFREMP,
                          ACTPH_ENTD_BY,
                          ACTPH_ENTD_ON,
                          ACTPH_AUTH_BY,
                          ACTPH_AUTH_ON,
                          ACTPH_CUTOFF_LMT_CASHP,
                          ACTPH_CUTOFF_LMT_NONCASHP,
                          ACTPH_CUTOFF_LMT_TFREMP,
                          ACTPH_CUTOFF_LMT_NONTFREMP)
   SELECT IACLINK_INTERNAL_ACNUM ACTPH_ACNT_NUM,
          ACNT_OPEN_DATE ACTP_LATEST_EFF_DATE,
          'Simplified eKYC TP' ACTP_SRC_FUND,
          10,
          10,
          0,
          0,
          100000,
          100000,
          0,
          0,
          100000,
          100000,
          0,
          0,
          10,
          10,
          0,
          0,
          100000,
          100000,
          0,
          0,
          OPENED_BY,
          OPENED_ON,
          OPENED_BY,
          OPENED_ON,
          100000,
          100000,
          0,
          0
     FROM API_ACNT_OPEN, IACLINK
    WHERE     ACTUAL_ACNT_NUMBER = IACLINK_ACTUAL_ACNUM
          AND IACLINK_ENTITY_NUM = 1
           and IACLINK_INTERNAL_ACNUM not in (select ACTPH_ACNT_NUM from  ACNTRNPRHIST);