/*Day-end, Month-End takes a long time. By this SQL, we can monitor the timing for every process and also the time for a particular process. In the last column, we can see the overall time for the whole process.*/
SELECT TO_CHAR(SODEODLOG_DATE, 'DD-MM-YYYY') SODEOD_DATE, AA.ESPROCDTL_PROCESS_NAME PROCESS_NAME, SODEODLOG_RUN_SL RUN_SL,ESPROCDTL_RUN_FREQ RUN_FREQ, 
SODEODLOG_PROCESS_SL PROCESS_SL, AA.TOTAL_BRANCH_COMPLETED TOTAL_BRANCH,
FLOOR ( (NVL(SODEODLOG_END_DATE, SYSDATE)  - SODEODLOG_START_DATE) * 24) HOURS,
       FLOOR(MOD ( ( ( (NVL(SODEODLOG_END_DATE, SYSDATE)  - SODEODLOG_START_DATE) * 24) * 60), 60)) MINUTES,
       MOD ( (MOD ( ( ( (NVL(SODEODLOG_END_DATE, SYSDATE)  - SODEODLOG_START_DATE) * 24) * 60), 60) * 60), 60) SECONDS,
       (SELECT FLOOR ( (B.END_TS - B.START_TS) * 24)
       || ' Hours '
       || FLOOR (MOD ( ( ( (B.END_TS - B.START_TS) * 24) * 60), 60))
       || ' Minutes '
       || ROUND( MOD ( (MOD ( ( ( (B.END_TS - B.START_TS) * 24) * 60), 60) * 60),60), 0)
       || ' Seconds' TOTAL_TIME
  FROM (SELECT SYSDATE END_TS, MIN (SODEODLOG_START_DATE) START_TS
          FROM SODEODLOG
         WHERE   SODEODLOG_ENTITY_NUM = 1 
               AND  SODEODLOG_DATE = (SELECT MN_CURR_BUSINESS_DATE FROM MAINCONT)
               AND SODEODLOG_FLG = 'E'
               AND SODEODLOG_ENTITY_NUM = 1) B) TOTAL_TIME
 FROM SODEODLOG , 
(SELECT ESPROCDTL_PROCESS_NAME,NVL(A.TOTAL_BRANCH, 0) TOTAL_BRANCH_COMPLETED, ESPROCDTL_SEQ_SL, ESPROCDTL_RUN_FREQ FROM EODSODPROCDTL LEFT OUTER JOIN (
SELECT PROC_NAME, COUNT (*) TOTAL_BRANCH
    FROM EODSODPROCBRN
   WHERE     EODSODPROCBRN_ENTITY_NUM = 1
         AND PROC_TYPE = 'E'
         AND PROC_DATE = (SELECT MN_CURR_BUSINESS_DATE FROM MAINCONT)
GROUP BY PROC_NAME)  A
ON (ESPROCDTL_PROCESS_NAME = A.PROC_NAME)
WHERE ESPROCDTL_RUN_STAGE = 'E'
AND ESPROCDTL_ENTITY_NUM = 1
AND ESPROCDTL_DISABLED = '0'
AND ESPROCDTL_RUN_FREQ IN ( 'D', 'M', 'Q', 'H' , 'Y') ) AA 
WHERE SODEODLOG_DATE = (SELECT MN_CURR_BUSINESS_DATE FROM MAINCONT)
AND SODEODLOG_FLG = 'E'
AND SODEODLOG_ENTITY_NUM = 1
AND SODEODLOG_FORM_NAME = AA.ESPROCDTL_PROCESS_NAME
ORDER BY ESPROCDTL_SEQ_SL DESC, SODEODLOG_RUN_SL ASC, SODEODLOG_PROCESS_SL ASC;



SELECT BRANCH_CODE FROM MIG_DETAIL
MINUS
SELECT PROC_BRN_CODE
  FROM EODSODPROCBRN
 WHERE     EODSODPROCBRN_ENTITY_NUM = 1
       AND PROC_TYPE = 'E'
       AND PROC_NAME = 'PKG_DEP_INT_ACCRUAL.START_ACCR_BRNWISE'
       AND PROC_DATE = (SELECT MN_CURR_BUSINESS_DATE FROM MAINCONT);




SELECT SODEODLOG_FORM_NAME, PROCESS_TIME, NUMBER_OF_BRANCH,(CASE WHEN (MINUTES/60)>1 THEN (HOURS+FLOOR(MINUTES/60)) ELSE HOURS END) || ' HOURS '||
 (MINUTES-(60*(FLOOR(MINUTES/60)))+(CASE WHEN (SECS/60)>1 THEN (HOURS+FLOOR(SECS/60)) ELSE MINUTES END)) ||' MINUTES '|| 
(SECS-(60*(FLOOR(SECS/60)))) ||' SECS ' TOTAL_TIME
FROM(
SELECT SODEODLOG_FORM_NAME, FLOOR(((NVL(SODEODLOG_END_DATE,SYSDATE)-SODEODLOG_START_DATE)*24*60*60)/3600)
       || ' HOURS ' ||
       FLOOR((((NVL(SODEODLOG_END_DATE,SYSDATE)-SODEODLOG_START_DATE)*24*60*60) -
       FLOOR(((NVL(SODEODLOG_END_DATE,SYSDATE)-SODEODLOG_START_DATE)*24*60*60)/3600)*3600)/60)
       || ' MINUTES ' ||
       ROUND((((NVL(SODEODLOG_END_DATE,SYSDATE)-SODEODLOG_START_DATE)*24*60*60) -
       FLOOR(((NVL(SODEODLOG_END_DATE,SYSDATE)-SODEODLOG_START_DATE)*24*60*60)/3600)*3600 -
       (FLOOR((((NVL(SODEODLOG_END_DATE,SYSDATE)-SODEODLOG_START_DATE)*24*60*60) -
       FLOOR(((NVL(SODEODLOG_END_DATE,SYSDATE)-SODEODLOG_START_DATE)*24*60*60)/3600)*3600)/60)*60) ))
       || ' SECS ' PROCESS_TIME, (SELECT COUNT(*) 
       FROM EODSODPROCBRN 
       WHERE PROC_NAME =SODEODLOG_FORM_NAME  
       AND PROC_DATE =TRUNC(LAST_DAY(SYSDATE-5))) NUMBER_OF_BRANCH,
       SUM(FLOOR(((NVL(SODEODLOG_END_DATE,SYSDATE)-SODEODLOG_START_DATE)*24*60*60)/3600)) OVER (PARTITION BY 1) HOURS,
       SUM(FLOOR((((NVL(SODEODLOG_END_DATE,SYSDATE)-SODEODLOG_START_DATE)*24*60*60) -
       FLOOR(((NVL(SODEODLOG_END_DATE,SYSDATE)-SODEODLOG_START_DATE)*24*60*60)/3600)*3600)/60)) OVER (PARTITION BY 1) MINUTES,
       SUM(ROUND((((NVL(SODEODLOG_END_DATE,SYSDATE)-SODEODLOG_START_DATE)*24*60*60) -
       FLOOR(((NVL(SODEODLOG_END_DATE,SYSDATE)-SODEODLOG_START_DATE)*24*60*60)/3600)*3600 -
       (FLOOR((((NVL(SODEODLOG_END_DATE,SYSDATE)-SODEODLOG_START_DATE)*24*60*60) -
       FLOOR(((NVL(SODEODLOG_END_DATE,SYSDATE)-SODEODLOG_START_DATE)*24*60*60)/3600)*3600)/60)*60)))) OVER (PARTITION BY 1) SECS
  FROM SODEODLOG
 WHERE TRUNC (NVL(SODEODLOG_END_DATE,SYSDATE)) >= TRUNC(SYSDATE-5) AND SODEODLOG_FLG = 'E'
       AND SODEODLOG_DATE =TRUNC(LAST_DAY(SYSDATE-5))
       AND SODEODLOG_ENTITY_NUM=1
       AND SODEODLOG_FLG='E'
ORDER BY SODEODLOG_END_DATE DESC) ;




SELECT (SELECT MN_CURR_BUSINESS_DATE FROM MAINCONT) CBD, ESPROCDTL_PROCESS_NAME,NVL(A.TOTAL_BRANCH, 0) TOTAL_BRANCH_COMPLETED, ESPROCDTL_SEQ_SL FROM EODSODPROCDTL LEFT OUTER JOIN (
SELECT PROC_NAME, COUNT (*) TOTAL_BRANCH
    FROM EODSODPROCBRN
   WHERE     EODSODPROCBRN_ENTITY_NUM = 1
         AND PROC_TYPE = 'S'
         AND PROC_DATE = (SELECT MN_CURR_BUSINESS_DATE FROM MAINCONT)
GROUP BY PROC_NAME)  A
ON (ESPROCDTL_PROCESS_NAME = A.PROC_NAME)
WHERE ESPROCDTL_RUN_STAGE = 'S'
AND ESPROCDTL_ENTITY_NUM = 1
AND ESPROCDTL_DISABLED = '0'
AND ESPROCDTL_RUN_FREQ IN ( 'D' ) 
ORDER BY ESPROCDTL_SEQ_SL DESC ; 