DECLARE
   P_BRANCH_CODE      NUMBER;
   P_PROCESS_DATE     DATE;
   P_FROM_DATE        DATE;
   P_ERROR_MSG        VARCHAR2 (32767);
   P_DELETE_FORCELY   NUMBER;
   P_INSERT_FORCELY   NUMBER;
   P_ENTITY_NUM       NUMBER;
   P_F42_RPT_CODE     VARCHAR2 (32767);
BEGIN
   FOR IDX
      IN (  SELECT *
              FROM (  SELECT BRANCH_CODE, ROWNUM BRANCH_SL
                        FROM MIG_DETAIL
                    ORDER BY BRANCH_CODE)
             WHERE     BRANCH_SL BETWEEN 1 AND 1300
                   AND BRANCH_CODE NOT IN
                          (SELECT BRANCH_CODE FROM CIB_CONTRACT)
          ORDER BY BRANCH_CODE)
   LOOP
      P_BRANCH_CODE := IDX.BRANCH_CODE;

      P_FROM_DATE := '01-AUG-2018';
      P_PROCESS_DATE := '31-AUG-2018';
      P_ERROR_MSG := NULL;
      P_DELETE_FORCELY := 0;
      P_INSERT_FORCELY := 0;
      P_ENTITY_NUM := 1;
      P_F42_RPT_CODE := NULL;

      SP_CIB_CONTRACT_GEN (P_BRANCH_CODE, P_FROM_DATE, P_PROCESS_DATE);

      COMMIT;
   END LOOP;
END;



DECLARE
   P_BRANCH_CODE      NUMBER;
   P_PROCESS_DATE     DATE;
   P_FROM_DATE        DATE;
   P_ERROR_MSG        VARCHAR2 (32767);
   P_DELETE_FORCELY   NUMBER;
   P_INSERT_FORCELY   NUMBER;
   P_ENTITY_NUM       NUMBER;
   P_F42_RPT_CODE     VARCHAR2 (32767);
BEGIN
   FOR IDX
      IN (  SELECT *
              FROM (  SELECT BRANCH_CODE, ROWNUM BRANCH_SL
                        FROM MIG_DETAIL
                    ORDER BY BRANCH_CODE)
             WHERE     BRANCH_SL BETWEEN 101 AND 300
                   AND BRANCH_CODE NOT IN
                          (SELECT BRANCH_CODE FROM CIB_CONTRACT)
          ORDER BY BRANCH_CODE)
   LOOP
      P_BRANCH_CODE := IDX.BRANCH_CODE;
      P_FROM_DATE := '01-AUG-2018';
      P_PROCESS_DATE := '31-AUG-2018';
      P_ERROR_MSG := NULL;
      P_DELETE_FORCELY := 0;
      P_INSERT_FORCELY := 0;
      P_ENTITY_NUM := 1;
      P_F42_RPT_CODE := NULL;

      SP_CIB_CONTRACT_GEN (P_BRANCH_CODE, P_FROM_DATE, P_PROCESS_DATE);
      COMMIT;
   END LOOP;
END;



DECLARE
   P_BRANCH_CODE      NUMBER;
   P_PROCESS_DATE     DATE;
   P_FROM_DATE        DATE;
   P_ERROR_MSG        VARCHAR2 (32767);
   P_DELETE_FORCELY   NUMBER;
   P_INSERT_FORCELY   NUMBER;
   P_ENTITY_NUM       NUMBER;
   P_F42_RPT_CODE     VARCHAR2 (32767);
BEGIN
   FOR IDX
      IN (  SELECT *
              FROM (  SELECT BRANCH_CODE, ROWNUM BRANCH_SL
                        FROM MIG_DETAIL
                    ORDER BY BRANCH_CODE)
             WHERE     BRANCH_SL BETWEEN 301 AND 600
                   AND BRANCH_CODE NOT IN
                          (SELECT BRANCH_CODE FROM CIB_CONTRACT)
          ORDER BY BRANCH_CODE)
   LOOP
      P_BRANCH_CODE := IDX.BRANCH_CODE;
      P_FROM_DATE := '01-AUG-2018';
      P_PROCESS_DATE := '31-AUG-2018';
      P_ERROR_MSG := NULL;
      P_DELETE_FORCELY := 0;
      P_INSERT_FORCELY := 0;
      P_ENTITY_NUM := 1;
      P_F42_RPT_CODE := NULL;

      SP_CIB_CONTRACT_GEN (P_BRANCH_CODE, P_FROM_DATE, P_PROCESS_DATE);
      COMMIT;
   END LOOP;
END;



DECLARE
   P_BRANCH_CODE      NUMBER;
   P_PROCESS_DATE     DATE;
   P_FROM_DATE        DATE;
   P_ERROR_MSG        VARCHAR2 (32767);
   P_DELETE_FORCELY   NUMBER;
   P_INSERT_FORCELY   NUMBER;
   P_ENTITY_NUM       NUMBER;
   P_F42_RPT_CODE     VARCHAR2 (32767);
BEGIN
   FOR IDX
      IN (  SELECT *
              FROM (  SELECT BRANCH_CODE, ROWNUM BRANCH_SL
                        FROM MIG_DETAIL
                    ORDER BY BRANCH_CODE)
             WHERE     BRANCH_SL BETWEEN 601 AND 800
                   AND BRANCH_CODE NOT IN
                          (SELECT BRANCH_CODE FROM CIB_CONTRACT)
          ORDER BY BRANCH_CODE)
   LOOP
      P_BRANCH_CODE := IDX.BRANCH_CODE;
      P_FROM_DATE := '01-AUG-2018';
      P_PROCESS_DATE := '31-AUG-2018';
      P_ERROR_MSG := NULL;
      P_DELETE_FORCELY := 0;
      P_INSERT_FORCELY := 0;
      P_ENTITY_NUM := 1;
      P_F42_RPT_CODE := NULL;

      SP_CIB_CONTRACT_GEN (P_BRANCH_CODE, P_FROM_DATE, P_PROCESS_DATE);
      COMMIT;
   END LOOP;
END;



DECLARE
   P_BRANCH_CODE      NUMBER;
   P_PROCESS_DATE     DATE;
   P_FROM_DATE        DATE;
   P_ERROR_MSG        VARCHAR2 (32767);
   P_DELETE_FORCELY   NUMBER;
   P_INSERT_FORCELY   NUMBER;
   P_ENTITY_NUM       NUMBER;
   P_F42_RPT_CODE     VARCHAR2 (32767);
BEGIN
   FOR IDX
      IN (  SELECT *
              FROM (  SELECT BRANCH_CODE, ROWNUM BRANCH_SL
                        FROM MIG_DETAIL
                    ORDER BY BRANCH_CODE)
             WHERE     BRANCH_SL BETWEEN 801 AND 1000
                   AND BRANCH_CODE NOT IN
                          (SELECT BRANCH_CODE FROM CIB_CONTRACT)
          ORDER BY BRANCH_CODE)
   LOOP
      P_BRANCH_CODE := IDX.BRANCH_CODE;
      P_FROM_DATE := '01-AUG-2018';
      P_PROCESS_DATE := '31-AUG-2018';
      P_ERROR_MSG := NULL;
      P_DELETE_FORCELY := 0;
      P_INSERT_FORCELY := 0;
      P_ENTITY_NUM := 1;
      P_F42_RPT_CODE := NULL;

      SP_CIB_CONTRACT_GEN (P_BRANCH_CODE, P_FROM_DATE, P_PROCESS_DATE);
      COMMIT;
   END LOOP;
END;



DECLARE
   P_BRANCH_CODE      NUMBER;
   P_PROCESS_DATE     DATE;
   P_FROM_DATE        DATE;
   P_ERROR_MSG        VARCHAR2 (32767);
   P_DELETE_FORCELY   NUMBER;
   P_INSERT_FORCELY   NUMBER;
   P_ENTITY_NUM       NUMBER;
   P_F42_RPT_CODE     VARCHAR2 (32767);
BEGIN
   FOR IDX
      IN (  SELECT *
              FROM (  SELECT BRANCH_CODE, ROWNUM BRANCH_SL
                        FROM MIG_DETAIL
                    ORDER BY BRANCH_CODE)
             WHERE     BRANCH_SL BETWEEN 1001 AND 1300
                   AND BRANCH_CODE NOT IN
                          (SELECT BRANCH_CODE FROM CIB_CONTRACT)
          ORDER BY BRANCH_CODE)
   LOOP
      P_BRANCH_CODE := IDX.BRANCH_CODE;
      P_PROCESS_DATE := '30-APR-2018';
      P_ERROR_MSG := NULL;
      P_DELETE_FORCELY := 0;
      P_INSERT_FORCELY := 0;
      P_ENTITY_NUM := 1;
      P_F42_RPT_CODE := NULL;

      SP_CIB_CONTRACT_GEN (P_BRANCH_CODE, P_FROM_DATE, P_PROCESS_DATE);
      COMMIT;
   END LOOP;
END;


DECLARE
   P_BRANCH_CODE      NUMBER;
   P_PROCESS_DATE     DATE;
   P_FROM_DATE        DATE;
   P_ERROR_MSG        VARCHAR2 (32767);
   P_DELETE_FORCELY   NUMBER;
   P_INSERT_FORCELY   NUMBER;
   P_ENTITY_NUM       NUMBER;
   P_F42_RPT_CODE     VARCHAR2 (32767);
BEGIN
   FOR IDX
      IN (  SELECT *
              FROM (  SELECT BRANCH_CODE, ROWNUM BRANCH_SL
                        FROM MIG_DETAIL
                    ORDER BY BRANCH_CODE)
             WHERE     BRANCH_SL BETWEEN 601 AND 700
                   AND BRANCH_CODE NOT IN
                          (SELECT BRANCH_CODE FROM CIB_CONTRACT)
          ORDER BY BRANCH_CODE)
   LOOP
      P_BRANCH_CODE := IDX.BRANCH_CODE;
      P_FROM_DATE := '01-AUG-2018';
      P_PROCESS_DATE := '31-AUG-2018';
      P_ERROR_MSG := NULL;
      P_DELETE_FORCELY := 0;
      P_INSERT_FORCELY := 0;
      P_ENTITY_NUM := 1;
      P_F42_RPT_CODE := NULL;

      SP_CIB_CONTRACT_GEN (P_BRANCH_CODE, P_FROM_DATE, P_PROCESS_DATE);
      COMMIT;
   END LOOP;
END;



DECLARE
   P_BRANCH_CODE      NUMBER;
   P_PROCESS_DATE     DATE;
   P_FROM_DATE        DATE;
   P_ERROR_MSG        VARCHAR2 (32767);
   P_DELETE_FORCELY   NUMBER;
   P_INSERT_FORCELY   NUMBER;
   P_ENTITY_NUM       NUMBER;
   P_F42_RPT_CODE     VARCHAR2 (32767);
BEGIN
   FOR IDX
      IN (  SELECT *
              FROM (  SELECT BRANCH_CODE, ROWNUM BRANCH_SL
                        FROM MIG_DETAIL
                    ORDER BY BRANCH_CODE)
             WHERE     BRANCH_SL BETWEEN 701 AND 800
                   AND BRANCH_CODE NOT IN
                          (SELECT BRANCH_CODE FROM CIB_CONTRACT)
          ORDER BY BRANCH_CODE)
   LOOP
      P_BRANCH_CODE := IDX.BRANCH_CODE;
      P_FROM_DATE := '01-AUG-2018';
      P_PROCESS_DATE := '31-AUG-2018';
      P_ERROR_MSG := NULL;
      P_DELETE_FORCELY := 0;
      P_INSERT_FORCELY := 0;
      P_ENTITY_NUM := 1;
      P_F42_RPT_CODE := NULL;

      SP_CIB_CONTRACT_GEN (P_BRANCH_CODE, P_FROM_DATE, P_PROCESS_DATE);
      COMMIT;
   END LOOP;
END;



DECLARE
   P_BRANCH_CODE      NUMBER;
   P_PROCESS_DATE     DATE;
   P_FROM_DATE        DATE;
   P_ERROR_MSG        VARCHAR2 (32767);
   P_DELETE_FORCELY   NUMBER;
   P_INSERT_FORCELY   NUMBER;
   P_ENTITY_NUM       NUMBER;
   P_F42_RPT_CODE     VARCHAR2 (32767);
BEGIN
   FOR IDX
      IN (  SELECT *
              FROM (  SELECT BRANCH_CODE, ROWNUM BRANCH_SL
                        FROM MIG_DETAIL
                    ORDER BY BRANCH_CODE)
             WHERE     BRANCH_SL BETWEEN 801 AND 900
                   AND BRANCH_CODE NOT IN
                          (SELECT BRANCH_CODE FROM CIB_CONTRACT)
          ORDER BY BRANCH_CODE)
   LOOP
      P_BRANCH_CODE := IDX.BRANCH_CODE;
      P_FROM_DATE := '01-AUG-2018';
      P_PROCESS_DATE := '31-AUG-2018';
      P_ERROR_MSG := NULL;
      P_DELETE_FORCELY := 0;
      P_INSERT_FORCELY := 0;
      P_ENTITY_NUM := 1;
      P_F42_RPT_CODE := NULL;

      SP_CIB_CONTRACT_GEN (P_BRANCH_CODE, P_FROM_DATE, P_PROCESS_DATE);
      COMMIT;
   END LOOP;
END;



DECLARE
   P_BRANCH_CODE      NUMBER;
   P_PROCESS_DATE     DATE;
   P_FROM_DATE        DATE;
   P_ERROR_MSG        VARCHAR2 (32767);
   P_DELETE_FORCELY   NUMBER;
   P_INSERT_FORCELY   NUMBER;
   P_ENTITY_NUM       NUMBER;
   P_F42_RPT_CODE     VARCHAR2 (32767);
BEGIN
   FOR IDX
      IN (  SELECT *
              FROM (  SELECT BRANCH_CODE, ROWNUM BRANCH_SL
                        FROM MIG_DETAIL
                    ORDER BY BRANCH_CODE)
             WHERE     BRANCH_SL BETWEEN 901 AND 1000
                   AND BRANCH_CODE NOT IN
                          (SELECT BRANCH_CODE FROM CIB_CONTRACT)
          ORDER BY BRANCH_CODE)
   LOOP
      P_BRANCH_CODE := IDX.BRANCH_CODE;
      P_FROM_DATE := '01-AUG-2018';
      P_PROCESS_DATE := '31-AUG-2018';
      P_ERROR_MSG := NULL;
      P_DELETE_FORCELY := 0;
      P_INSERT_FORCELY := 0;
      P_ENTITY_NUM := 1;
      P_F42_RPT_CODE := NULL;

      SP_CIB_CONTRACT_GEN (P_BRANCH_CODE, P_FROM_DATE, P_PROCESS_DATE);
      COMMIT;
   END LOOP;
END;



DECLARE
   P_BRANCH_CODE      NUMBER;
   P_PROCESS_DATE     DATE;
   P_FROM_DATE        DATE;
   P_ERROR_MSG        VARCHAR2 (32767);
   P_DELETE_FORCELY   NUMBER;
   P_INSERT_FORCELY   NUMBER;
   P_ENTITY_NUM       NUMBER;
   P_F42_RPT_CODE     VARCHAR2 (32767);
BEGIN
   FOR IDX
      IN (  SELECT *
              FROM (  SELECT BRANCH_CODE, ROWNUM BRANCH_SL
                        FROM MIG_DETAIL
                    ORDER BY BRANCH_CODE)
             WHERE     BRANCH_SL BETWEEN 1001 AND 1100
                   AND BRANCH_CODE NOT IN
                          (SELECT BRANCH_CODE FROM CIB_CONTRACT)
          ORDER BY BRANCH_CODE)
   LOOP
      P_BRANCH_CODE := IDX.BRANCH_CODE;
      P_FROM_DATE := '01-AUG-2018';
      P_PROCESS_DATE := '31-AUG-2018';
      P_ERROR_MSG := NULL;
      P_DELETE_FORCELY := 0;
      P_INSERT_FORCELY := 0;
      P_ENTITY_NUM := 1;
      P_F42_RPT_CODE := NULL;

      SP_CIB_CONTRACT_GEN (P_BRANCH_CODE, P_FROM_DATE, P_PROCESS_DATE);
      COMMIT;
   END LOOP;
END;


DECLARE
   P_BRANCH_CODE      NUMBER;
   P_PROCESS_DATE     DATE;
   P_FROM_DATE        DATE;
   P_ERROR_MSG        VARCHAR2 (32767);
   P_DELETE_FORCELY   NUMBER;
   P_INSERT_FORCELY   NUMBER;
   P_ENTITY_NUM       NUMBER;
   P_F42_RPT_CODE     VARCHAR2 (32767);
BEGIN
   FOR IDX
      IN (  SELECT *
              FROM (  SELECT BRANCH_CODE, ROWNUM BRANCH_SL
                        FROM MIG_DETAIL
                    ORDER BY BRANCH_CODE)
             WHERE     BRANCH_SL BETWEEN 1101 AND 1300
                   AND BRANCH_CODE NOT IN
                          (SELECT BRANCH_CODE FROM CIB_CONTRACT)
          ORDER BY BRANCH_CODE)
   LOOP
      P_BRANCH_CODE := IDX.BRANCH_CODE;
      P_FROM_DATE := '01-AUG-2018';
      P_PROCESS_DATE := '31-AUG-2018';
      P_ERROR_MSG := NULL;
      P_DELETE_FORCELY := 0;
      P_INSERT_FORCELY := 0;
      P_ENTITY_NUM := 1;
      P_F42_RPT_CODE := NULL;

      SP_CIB_CONTRACT_GEN (P_BRANCH_CODE, P_FROM_DATE, P_PROCESS_DATE);
      COMMIT;
   END LOOP;
END;