/* Formatted on 6/18/2019 10:41:57 AM (QP5 v5.227.12220.39754) */
BEGIN
   FOR IDX
      IN (SELECT REPAY_FROM EXPIRY_DATE,
                 L.ACASLLDTL_CLIENT_NUM,
                 REPAY_AMT ACASLLDTL_LIMIT_LINE_NUM
            FROM IACLINK I, ACASLLDTL L, ACC4
           WHERE     I.IACLINK_ACTUAL_ACNUM = ACC_NO
                 AND IACLINK_ENTITY_NUM = 1
                 AND ACASLLDTL_ENTITY_NUM = 1
                 AND I.IACLINK_INTERNAL_ACNUM = L.ACASLLDTL_INTERNAL_ACNUM)
   LOOP
      UPDATE LIMITLINE LM
         SET LM.LMTLINE_LIMIT_EXPIRY_DATE = IDX.EXPIRY_DATE
       WHERE     LM.LMTLINE_CLIENT_CODE = IDX.ACASLLDTL_CLIENT_NUM
             AND LM.LMTLINE_NUM = IDX.ACASLLDTL_LIMIT_LINE_NUM;

      UPDATE LIMITLINEHIST H
         SET H.LIMLNEHIST_LIMIT_EXPIRY_DATE = IDX.EXPIRY_DATE
       WHERE     H.LIMLNEHIST_CLIENT_CODE = IDX.ACASLLDTL_CLIENT_NUM
             AND H.LIMLNEHIST_LIMIT_LINE_NUM = IDX.ACASLLDTL_LIMIT_LINE_NUM;
   END LOOP;
END;