140143121 L3036    Commission Payable Account for SAB
140143119 and configured it with reporting code L3036
 
300113103   I0246, L2701

300113106 I0246, L2701

210131103 A0968

210131106 A0968
225122301 A0910
225122302   A0910
225122303  A0910
225122305 A0910
140146148  L2101

Insert into SBLPROD.RPTHEADGLDTL_OLD
   (RPTHDGLDTL_CODE, RPTHDGLDTL_GL_ACC_SL, RPTHDGLDTL_GLACC_CODE, RPTHDGLDTL_ACNT_PARTIAL_SEL, RPTHDGLDTL_GLBAL_CRITERIA, RPTHDGLDTL_PROD_CODE, RPTHDGLDTL_RESIDENT_NR_STATUS, RPTHDGLDTL_AC_BAL_CRITERIA, RPTHDGLDTL_GL_REQUIRED, RPTHDGLDTL_SME_NONSME_CODE)
 Values
   ('L3036', 3, '140143121', '0', 'A', 
    0, ' ', ' ', '1', 0);
COMMIT;

Insert into SBLPROD.RPTHEADGLDTL_OLD
   (RPTHDGLDTL_CODE, RPTHDGLDTL_GL_ACC_SL, RPTHDGLDTL_GLACC_CODE, RPTHDGLDTL_ACNT_PARTIAL_SEL, RPTHDGLDTL_GLBAL_CRITERIA, RPTHDGLDTL_PROD_CODE, RPTHDGLDTL_RESIDENT_NR_STATUS, RPTHDGLDTL_AC_BAL_CRITERIA, RPTHDGLDTL_GL_REQUIRED, RPTHDGLDTL_SME_NONSME_CODE)
 Values
   ('L3036', 2, '140143119', '0', 'A', 
    0, ' ', ' ', '1', 0);
COMMIT;

Insert into SBLPROD.RPTHEADGLDTL_OLD
   (RPTHDGLDTL_CODE, RPTHDGLDTL_GL_ACC_SL, RPTHDGLDTL_GLACC_CODE, RPTHDGLDTL_ACNT_PARTIAL_SEL, RPTHDGLDTL_GLBAL_CRITERIA, RPTHDGLDTL_PROD_CODE, RPTHDGLDTL_RESIDENT_NR_STATUS, RPTHDGLDTL_AC_BAL_CRITERIA, RPTHDGLDTL_GL_REQUIRED, RPTHDGLDTL_SME_NONSME_CODE)
 Values
   ('I0246', 3, '300113106', '0', 'C', 
    0, ' ', ' ', '1', 0);
Insert into SBLPROD.RPTHEADGLDTL_OLD
   (RPTHDGLDTL_CODE, RPTHDGLDTL_GL_ACC_SL, RPTHDGLDTL_GLACC_CODE, RPTHDGLDTL_ACNT_PARTIAL_SEL, RPTHDGLDTL_GLBAL_CRITERIA, RPTHDGLDTL_PROD_CODE, RPTHDGLDTL_RESIDENT_NR_STATUS, RPTHDGLDTL_AC_BAL_CRITERIA, RPTHDGLDTL_GL_REQUIRED, RPTHDGLDTL_SME_NONSME_CODE)
 Values
   ('I0246', 2, '300113103', '0', 'C', 
    0, ' ', ' ', '1', 0);
Insert into SBLPROD.RPTHEADGLDTL_OLD
   (RPTHDGLDTL_CODE, RPTHDGLDTL_GL_ACC_SL, RPTHDGLDTL_GLACC_CODE, RPTHDGLDTL_ACNT_PARTIAL_SEL, RPTHDGLDTL_GLBAL_CRITERIA, RPTHDGLDTL_PROD_CODE, RPTHDGLDTL_RESIDENT_NR_STATUS, RPTHDGLDTL_AC_BAL_CRITERIA, RPTHDGLDTL_GL_REQUIRED, RPTHDGLDTL_SME_NONSME_CODE)
 Values
   ('L2701', 691, '300113106', '0', 'A', 
    0, ' ', ' ', '1', 0);
Insert into SBLPROD.RPTHEADGLDTL_OLD
   (RPTHDGLDTL_CODE, RPTHDGLDTL_GL_ACC_SL, RPTHDGLDTL_GLACC_CODE, RPTHDGLDTL_ACNT_PARTIAL_SEL, RPTHDGLDTL_GLBAL_CRITERIA, RPTHDGLDTL_PROD_CODE, RPTHDGLDTL_RESIDENT_NR_STATUS, RPTHDGLDTL_AC_BAL_CRITERIA, RPTHDGLDTL_GL_REQUIRED, RPTHDGLDTL_SME_NONSME_CODE)
 Values
   ('L2701', 692, '300113103', '0', 'A', 
    0, ' ', ' ', '1', 0);
COMMIT;


Insert into SBLPROD.RPTHEADGLDTL_OLD
   (RPTHDGLDTL_CODE, RPTHDGLDTL_GL_ACC_SL, RPTHDGLDTL_GLACC_CODE, RPTHDGLDTL_ACNT_PARTIAL_SEL, RPTHDGLDTL_GLBAL_CRITERIA, RPTHDGLDTL_PROD_CODE, RPTHDGLDTL_RESIDENT_NR_STATUS, RPTHDGLDTL_AC_BAL_CRITERIA, RPTHDGLDTL_GL_REQUIRED, RPTHDGLDTL_SME_NONSME_CODE)
 Values
   ('L2101', 145, '140146148', '0', 'A', 
    0, ' ', ' ', '1', 0);
Insert into SBLPROD.RPTHEADGLDTL_OLD
   (RPTHDGLDTL_CODE, RPTHDGLDTL_GL_ACC_SL, RPTHDGLDTL_GLACC_CODE, RPTHDGLDTL_ACNT_PARTIAL_SEL, RPTHDGLDTL_GLBAL_CRITERIA, RPTHDGLDTL_PROD_CODE, RPTHDGLDTL_RESIDENT_NR_STATUS, RPTHDGLDTL_AC_BAL_CRITERIA, RPTHDGLDTL_GL_REQUIRED, RPTHDGLDTL_SME_NONSME_CODE)
 Values
   ('A0910', 131, '225122301', '0', 'A', 
    0, ' ', ' ', '1', 0);
Insert into SBLPROD.RPTHEADGLDTL_OLD
   (RPTHDGLDTL_CODE, RPTHDGLDTL_GL_ACC_SL, RPTHDGLDTL_GLACC_CODE, RPTHDGLDTL_ACNT_PARTIAL_SEL, RPTHDGLDTL_GLBAL_CRITERIA, RPTHDGLDTL_PROD_CODE, RPTHDGLDTL_RESIDENT_NR_STATUS, RPTHDGLDTL_AC_BAL_CRITERIA, RPTHDGLDTL_GL_REQUIRED, RPTHDGLDTL_SME_NONSME_CODE)
 Values
   ('A0910', 132, '225122302', '0', 'A', 
    0, ' ', ' ', '1', 0);
Insert into SBLPROD.RPTHEADGLDTL_OLD
   (RPTHDGLDTL_CODE, RPTHDGLDTL_GL_ACC_SL, RPTHDGLDTL_GLACC_CODE, RPTHDGLDTL_ACNT_PARTIAL_SEL, RPTHDGLDTL_GLBAL_CRITERIA, RPTHDGLDTL_PROD_CODE, RPTHDGLDTL_RESIDENT_NR_STATUS, RPTHDGLDTL_AC_BAL_CRITERIA, RPTHDGLDTL_GL_REQUIRED, RPTHDGLDTL_SME_NONSME_CODE)
 Values
   ('A0910', 133, '225122303', '0', 'A', 
    0, ' ', ' ', '1', 0);
Insert into SBLPROD.RPTHEADGLDTL_OLD
   (RPTHDGLDTL_CODE, RPTHDGLDTL_GL_ACC_SL, RPTHDGLDTL_GLACC_CODE, RPTHDGLDTL_ACNT_PARTIAL_SEL, RPTHDGLDTL_GLBAL_CRITERIA, RPTHDGLDTL_PROD_CODE, RPTHDGLDTL_RESIDENT_NR_STATUS, RPTHDGLDTL_AC_BAL_CRITERIA, RPTHDGLDTL_GL_REQUIRED, RPTHDGLDTL_SME_NONSME_CODE)
 Values
   ('A0910', 134, '225122305', '0', 'A', 
    0, ' ', ' ', '1', 0);
COMMIT;
