/*Statement of affairs generation process for the Year End*/
CREATE TABLE STATMENTOFAFFAIRS_18_CASH1
AS
   SELECT *
     FROM STATMENTOFAFFAIRS
    WHERE     RPT_ENTRY_DATE = '31-DEC-2018'
          AND CASHTYPE = '1';
          

DELETE FROM STATMENTOFAFFAIRS
    WHERE     RPT_ENTRY_DATE = '31-DEC-2018'
          AND CASHTYPE = '1';

          
          
CREATE TABLE INCOMEEXPENSE_18_CASH1
AS
   SELECT *
     FROM INCOMEEXPENSE
    WHERE     RPT_ENTRY_DATE = '31-DEC-2018'
          AND CASHTYPE = '1';
          

DELETE FROM INCOMEEXPENSE
    WHERE     RPT_ENTRY_DATE = '31-DEC-2018'
          AND CASHTYPE = '1';
          
          
CREATE TABLE RTMPTRIALBAL_DETL_CC_18_CASH1 AS 
SELECT * FROM RTMPTRIALBAL_DETL_CC;

CREATE TABLE RTMPTRIALBAL_SUM_CC_18_CASH1 AS 
SELECT * FROM RTMPTRIALBAL_SUM_CC ;


/*          
DECLARE
   P_BRANCH_CODE      NUMBER;
   P_PROCESS_DATE     DATE;
   P_ERROR_MSG        VARCHAR2 (32767);
   P_DELETE_FORCELY   NUMBER;
   P_INSERT_FORCELY   NUMBER;
   P_ENTITY_NUM       NUMBER;
   P_F42_RPT_CODE     VARCHAR2 (32767);
BEGIN
   FOR IDX IN (SELECT * FROM MIG_DETAIL ORDER BY BRANCH_CODE)
   LOOP
      P_BRANCH_CODE := IDX.BRANCH_CODE;
      P_PROCESS_DATE := '31-DEC-2018';
      P_ERROR_MSG := NULL;
      P_DELETE_FORCELY := 1;
      P_INSERT_FORCELY := 1;
      P_ENTITY_NUM := 1;
      P_F42_RPT_CODE := NULL;

      SP_STATEMENT_OF_AFFAIRS_F12 (P_BRANCH_CODE,
                        P_PROCESS_DATE,
                        P_ERROR_MSG,
                        P_DELETE_FORCELY,
                        P_INSERT_FORCELY,
                        P_ENTITY_NUM,
                        P_F42_RPT_CODE);
      COMMIT;
   END LOOP;
END;
/

*/

EXEC SP_GEN_F12_F42_THREAD ;




UPDATE INCOMEEXPENSE
   SET CASHTYPE = '2'
 WHERE RPT_ENTRY_DATE ='31-DEC-2018'
          AND CASHTYPE = '1';
          
          
INSERT INTO INCOMEEXPENSE SELECT * FROM INCOMEEXPENSE_18_CASH1 ;


UPDATE STATMENTOFAFFAIRS
   SET CASHTYPE = '2'
 WHERE RPT_ENTRY_DATE = '31-DEC-2018'
          AND CASHTYPE = '1';
          
          
INSERT INTO STATMENTOFAFFAIRS SELECT * FROM STATMENTOFAFFAIRS_18_CASH1 ;