/* Formatted on 4/30/2019 12:09:40 PM (QP5 v5.227.12220.39754) */
SELECT wm_concat(PRODUCT_CODE),
       PRODUCT_NAME,
       PRODUCT_GLACC_CODE,
       (SELECT EXTGL_EXT_HEAD_DESCN
          FROM EXTGL
         WHERE EXTGL_ACCESS_CODE = PRODUCT_GLACC_CODE)
          GL_DESC,
       RPTLAYOUTDTL_RPT_CODE,RPTLAYOUTDTL_RPT_HEAD_CODE
  FROM RPTHEADGLDTL, PRODUCTS, RPTLAYOUTDTL
 WHERE     RPTHDGLDTL_GLACC_CODE = PRODUCT_GLACC_CODE
       AND RPTLAYOUTDTL_RPT_HEAD_CODE = RPTHDGLDTL_CODE
       AND RPTLAYOUTDTL_RPT_CODE IN ('F12', 'F42B')
       ORDER BY 1;


 