DROP TABLE SBLPROD.GL_BALANCE CASCADE CONSTRAINTS;

CREATE TABLE  GL_BALANCE
(
  BALANCE_DATE   DATE,
  BRANCH_CODE    NUMBER(6),
  GL_CODE        VARCHAR2(15 BYTE),
  AC_BALANCE     NUMBER(18,3),
  BC_BALANCE     NUMBER(18,3),
  CURRENCY_CODE  VARCHAR2(3 BYTE)
)
TABLESPACE TBFES
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX SBLPROD.IND_GL_BALANCE ON SBLPROD.GL_BALANCE
(BALANCE_DATE, BRANCH_CODE, GL_CODE, CURRENCY_CODE)
LOGGING
TABLESPACE TBFES
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX SBLPROD.IND_GL_BALANCE_02 ON SBLPROD.GL_BALANCE
(BRANCH_CODE, GL_CODE, CURRENCY_CODE)
LOGGING
TABLESPACE TBFES
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;
