/* Formatted on 2/4/2020 3:38:16 PM (QP5 v5.227.12220.39754) */
BEGIN
   FOR IDX
      IN (  SELECT TRAN_BRN_CODE,
                   TRAN_GLACC_CODE,
                   SUM (TRAN_BASE_CURR_EQ_AMT) TRAN_BASE_CURR_EQ_AMT
              FROM TRAN2020
             WHERE     TRAN_ENTITY_NUM = 1
                   AND TRAN_DATE_OF_TRAN ='12-aug-2021'
                   AND TRAN_GLACC_CODE = '217101101 '
                   AND TRAN_BRN_CODE =48058
                   AND TRAN_ENTD_BY = 'INTELECT'
          GROUP BY TRAN_BRN_CODE, TRAN_GLACC_CODE
          ORDER BY TRAN_BASE_CURR_EQ_AMT)
   LOOP
      UPDATE GLBALASONHIST
         SET GLBALH_AC_BAL = GLBALH_AC_BAL - IDX.TRAN_BASE_CURR_EQ_AMT,
             GLBALH_BC_BAL = GLBALH_BC_BAL - IDX.TRAN_BASE_CURR_EQ_AMT
       WHERE     GLBALH_GLACC_CODE = IDX.TRAN_GLACC_CODE
             AND GLBALH_BRN_CODE = IDX.TRAN_BRN_CODE
             AND GLBALH_ASON_DATE = '31-JAN-2020';

      UPDATE GLBALASONHIST
         SET GLBALH_AC_BAL = GLBALH_AC_BAL - IDX.TRAN_BASE_CURR_EQ_AMT,
             GLBALH_BC_BAL = GLBALH_BC_BAL -IDX.TRAN_BASE_CURR_EQ_AMT
       WHERE     GLBALH_GLACC_CODE = IDX.TRAN_GLACC_CODE
             AND GLBALH_BRN_CODE = IDX.TRAN_BRN_CODE
             AND GLBALH_ASON_DATE = '01-FEB-2020';
   END LOOP;
END;

SP_GL_BAL_CORRECTION 

--300107110    225122205