/*
Script to add the primary key on the table GLDIVBAL.
*/

SELECT * FROM GLDIVBAL G WHERE (G.ENTITY_NUM , G.BRN_CODE, G.GLACC_CODE, G.DEPT_CODE, G.CLOSING_DATE, G.CURR_CODE) IN (
SELECT  ENTITY_NUM , BRN_CODE, GLACC_CODE, DEPT_CODE, CLOSING_DATE, CURR_CODE FROM GLDIVBAL GROUP BY ENTITY_NUM , BRN_CODE, GLACC_CODE, DEPT_CODE, CLOSING_DATE, CURR_CODE
HAVING COUNT(*) > 1 )
ORDER BY G.ENTITY_NUM , G.BRN_CODE, G.GLACC_CODE, G.DEPT_CODE, G.CLOSING_DATE, G.CURR_CODE ;



DELETE FROM GLDIVBAL
      WHERE ROWID IN (
               SELECT rid
                 FROM (SELECT ROWID rid,
                              ROW_NUMBER () OVER (PARTITION BY  ENTITY_NUM , BRN_CODE, GLACC_CODE, DEPT_CODE, CLOSING_DATE, CURR_CODE ORDER BY ROWID) rn
                         FROM GLDIVBAL)
                WHERE rn <> 1);


ALTER TABLE GLDIVBAL
 ADD CONSTRAINT PK_GLDIVBAL
  PRIMARY KEY
  (ENTITY_NUM, BRN_CODE, GLACC_CODE, DEPT_CODE, CLOSING_DATE, CURR_CODE)
  ENABLE VALIDATE;