
SELECT BRANCH_GMO GMO_CODE,
       (SELECT MBRN_NAME
          FROM MBRN
         WHERE MBRN_ENTITY_NUM = 1 AND MBRN_CODE = BRANCH_GMO)
          GMO_NAME,
       BRANCH_PO PO_CODE,
       (SELECT MBRN_NAME
          FROM MBRN
         WHERE MBRN_ENTITY_NUM = 1 AND MBRN_CODE = BRANCH_PO)
          PO_NAME,(SELECT MBRN_NAME
          FROM MBRN
         WHERE MBRN_ENTITY_NUM = 1 AND MBRN_CODE = RPT_BRANCH_CODE) mbrn_name,tt.*
  FROM ( select  RPT_BRANCH_CODE
from GOAML_RPT_HISTORY
where RPT_YEAR = 2020
AND RPT_MONTH = 6 ) TT,
       MBRN_TREE2
 WHERE TT.RPT_BRANCH_CODE = BRANCH_CODE
 and BRANCH_PO=44000;

--AND PROCESS_STATUS = 'P'