/* Formatted on 9/25/2022 3:33:22 PM (QP5 v5.388) */
DELETE FROM GOAML_TRAN_CORPORATE
      WHERE SEQ_NO IN (SELECT SEQ_NO
                         FROM GOAML_TRAN_MASTER
                        WHERE RPT_YEAR = 2023 AND RPT_MONTH = 3);

DELETE FROM GOAML_TRAN_INDV
      WHERE SEQ_NO IN (SELECT SEQ_NO
                         FROM GOAML_TRAN_MASTER
                        WHERE RPT_YEAR = 2023 AND RPT_MONTH = 3);

DELETE FROM GOAML_TRAN_MASTER
      WHERE RPT_YEAR = 2023 AND RPT_MONTH = 3;

DELETE FROM GOAML_DATA
      WHERE RPT_YEAR = 2023 AND RPT_MONTH = 3;


DELETE FROM GOAML_TMP_DATA_INV
      WHERE ASON_DATE = '01-mar-2023';


UPDATE GOAML_PROCESS
   SET PROCESS_STATUS = 'P';

COMMIT;