/* Formatted on 10/11/2021 1:41:57 PM (QP5 v5.149.1003.31008) */
-- invalid FATHER_NAME
INSERT INTO  KYC_DATA_CORRECTION AS 
SELECT CLIENTS_HOME_BRN_CODE BRN_CODE,
       FN_GETBRNNAME (1, CLIENTS_HOME_BRN_CODE) BR_NAME,
       INDCLIENT_CODE CLIENTS_CODE,
       INDCLIENT_FATHER_NAME,
       'F' U_TYPE,
       'INDCL' TAB
  FROM INDCLIENTS, CLIENTS
 WHERE (NOT REGEXP_LIKE (INDCLIENT_FATHER_NAME, '[A-Za-z]')
        OR LENGTH (INDCLIENT_FATHER_NAME) < 4)
       AND INDCLIENT_CODE = CLIENTS_CODE
       AND TRIM (INDCLIENT_FATHER_NAME) IS NOT NULL
       AND CLIENTS_HOME_BRN_CODE = 1
UNION ALL
-- invalid MOTHER_NAME

SELECT CLIENTS_HOME_BRN_CODE BRN_CODE,
       FN_GETBRNNAME (1, CLIENTS_HOME_BRN_CODE) BR_NAME,
       CLIENTS_CODE CLIENTS_CODE,
       INDCLIENT_MOTHER_NAME,
       'M' U_TYPE,
       'INDCL' TAB
  FROM INDCLIENTS, CLIENTS
 WHERE (NOT REGEXP_LIKE (INDCLIENT_MOTHER_NAME, '[A-Za-z]')
        OR LENGTH (INDCLIENT_MOTHER_NAME) < 4)
       AND INDCLIENT_CODE = CLIENTS_CODE
       AND TRIM (INDCLIENT_MOTHER_NAME) IS NOT NULL
       AND CLIENTS_HOME_BRN_CODE = 16287
UNION ALL
---Mobile NUMBER VALIDATION
SELECT CLIENTS_HOME_BRN_CODE BRN_CODE,
       FN_GETBRNNAME (1, CLIENTS_HOME_BRN_CODE) BR_NAME,
       INDCLIENT_CODE CLIENTS_CODE,
       INDCLIENT_TEL_GSM,
       'MO' U_TYPE,
       'CL' TAB
  FROM INDCLIENTS, CLIENTS
 WHERE     (NOT REGEXP_LIKE (INDCLIENT_TEL_GSM, '^(01[1-9]\d{8})$'))
       AND INDCLIENT_CODE = CLIENTS_CODE
       AND TRIM (INDCLIENT_TEL_GSM) IS NOT NULL
       AND CLIENTS_HOME_BRN_CODE = 26
UNION ALL
SELECT CLIENTS_HOME_BRN_CODE BRN_CODE,
       FN_GETBRNNAME (1, CLIENTS_HOME_BRN_CODE) BR_NAME,
       CLIENTS_CODE CLIENTS_CODE,
       ADDRDTLS_MOBILE_NUM,
       'MO' U_TYPE,
       'AD' TAB
  FROM ADDRDTLS, CLIENTS
 WHERE     (NOT REGEXP_LIKE (ADDRDTLS_MOBILE_NUM, '^(01[1-9]\d{8})$'))
       AND ADDRDTLS_INV_NUM = CLIENTS_ADDR_INV_NUM
       AND TRIM (ADDRDTLS_MOBILE_NUM) IS NOT NULL
       AND CLIENTS_HOME_BRN_CODE = 26
UNION ALL
---------- --invalid NID--------------------

SELECT CLIENTS_HOME_BRN_CODE BRN_CODE,
       FN_GETBRNNAME (1, CLIENTS_HOME_BRN_CODE) BR_NAME,
       PIDDOCS_INV_NUM CLIENTS_CODE,
       PIDDOCS_DOCID_NUM,
       'NID' U_TYPE,
       'PID' TAB
  FROM PIDDOCS, CLIENTS, indclients
 WHERE     PIDDOCS_PID_TYPE = 'NID'
       AND INDCLIENT_PID_INV_NUM = PIDDOCS_INV_NUM
       AND CLIENTS_HOME_BRN_CODE = 26
       AND (LENGTH (PIDDOCS_DOCID_NUM) NOT IN (10, 14, 13, 17)
            OR REGEXP_LIKE (PIDDOCS_DOCID_NUM, '([0-9]+)\1{5}'))
UNION ALL
-------------------------------------       --INVALID NOMINEE

SELECT ACNTS_BRN_CODE BRN_CODE,
       FN_GETBRNNAME (1, ACNTS_BRN_CODE) BR_NAME,
       CONNP_INV_NUM CLIENTS_CODE,
       CONNP_CLIENT_NAME,
       'NO' U_TYPE,
       'CONN' TAB
  FROM CONNPINFO, ACNTS
 WHERE     ACNTS_ENTITY_NUM = 1
       AND CONNP_CONN_ROLE = 2
       AND ACNTS_CONNP_INV_NUM = CONNP_INV_NUM
       AND CONNP_SHARE_HOLD_PER = 100
       AND (   NOT REGEXP_LIKE (CONNP_CLIENT_NAME, '[A-Za-z]')
            OR LENGTH (CONNP_CLIENT_NAME) < 3
            OR CONNP_CLIENT_NAME IS NULL)
       AND ACNTS_BRN_CODE = 26;
       
       
       
       
 ----------------------------------QUERY-----------------------------------------------------
 /* Formatted on 10/12/2021 12:13:15 PM (QP5 v5.149.1003.31008) */
SELECT *
FROM (SELECT BRN_CODE,
       CLIENTS_CODE,
       INDCLIENT_FATHER_NAME UPDATED_FIELD ,
       U_TYPE,
       TAB
   FROM KYC_DATA_CORRECTION
 WHERE TRIM (U_TYPE) = 'F'
 UNION ALL
 SELECT BRN_CODE,
       CLIENTS_CODE,
       INDCLIENT_FATHER_NAME UPDATED_FIELD ,
       U_TYPE,
       TAB
   FROM KYC_DATA_CORRECTION
 WHERE TRIM (U_TYPE) = 'M'
 UNION ALL
select BRN_CODE,
    CLIENTS_CODE   CLIENTS_CODE,
  INDCLIENT_FATHER_NAME   UPDATED_FIELD,
       U_TYPE,
       TAB
  FROM KYC_DATA_CORRECTION
 WHERE   TRIM (U_TYPE) = 'MO'
 AND trim(TAB)='CL'
 UNION ALL
 select BRN_CODE,
    C.CLIENTS_CODE   CLIENTS_CODE,
   INDCLIENT_FATHER_NAME  UPDATED_FIELD,
       U_TYPE,
       TAB
  FROM KYC_DATA_CORRECTION A,CLIENTS C
             WHERE    A.CLIENTS_CODE = CLIENTS_ADDR_INV_NUM
 AND  TRIM (U_TYPE) = 'MO'
 AND TRIM ( TAB)='AD'
 union all
  select BRN_CODE,
    INDCLIENT_CODE  CLIENTS_CODE,
   a.INDCLIENT_FATHER_NAME  UPDATED_FIELD,
       U_TYPE,
       TAB
  FROM KYC_DATA_CORRECTION A,indclients  C
             WHERE    A.CLIENTS_CODE = INDCLIENT_PID_INV_NUM
 AND trim(U_TYPE)='NID')
 WHERE BRN_CODE  IN ( SELECT BRANCH FROM MBRN_TREE1  WHERE   PO_BRANCH=17004);
 

