EMANHOVERING

/* Formatted on 6/13/2022 4:56:35 PM (QP5 v5.252.13127.32867) */
SELECT GMO_BRANCH GMO_CODE,
       (SELECT MBRN_NAME
          FROM MBRN
         WHERE MBRN_ENTITY_NUM = 1 AND MBRN_CODE = GMO_BRANCH)
          GMO_NAME,
       PO_BRANCH PO_CODE,
       (SELECT MBRN_NAME
          FROM MBRN
         WHERE MBRN_ENTITY_NUM = 1 AND MBRN_CODE = PO_BRANCH)
          PO_NAME,(SELECT MBRN_NAME
          FROM MBRN
         WHERE MBRN_ENTITY_NUM = 1 AND MBRN_CODE = HOVERING_BRN_CODE) BRANCH_NAME,
       tt.*
  FROM (SELECT HOVERING_BRN_CODE,HOVERING_YEAR,
       ACNTS_PROD_CODE,
       ACNTS_AC_TYPE,
       facno (1, ACNTBAL_INTERNAL_ACNUM) account_no,
       ACNTS_AC_NAME1 AC_NAME,
       HOVERING_PENDING_AMT
  FROM hovering, acntbal, acnts
 WHERE     HOVERING_ENTITY_NUM = 1
       AND ACNTS_ENTITY_NUM = 1
       AND ACNTS_INTERNAL_ACNUM = ACNTBAL_INTERNAL_ACNUM
       AND ACNTBAL_ENTITY_NUM = 1
       AND ACNTBAL_INTERNAL_ACNUM = HOVERING_RECOVERY_FROM_ACNT
       AND HOVERING_YEAR = 2020
       AND HOVERING_PENDING_AMT <> 0
       AND ACNTBAL_AC_DB_QUEUE_AMT <> 0
       AND HOVERING_CHG_CODE = 'ED') TT, MBRN_TREE
 WHERE TT.HOVERING_BRN_CODE = BRANCH;
 
 
 SELECT 
         COUNT (ACNTS_INTERNAL_ACNUM) TOTAL_ACCOUNT,
         TRAN_AMOUNT SLAB,
         SUM (TRAN_AMOUNT) EXCISE_AMT                       --22257300  338050
    FROM TRAN2022, ACNTS,TRANBAT2022
   WHERE     TRAN_AMOUNT <> 0
         AND ACNTS_ENTITY_NUM = 1
         AND TRAN_INTERNAL_ACNUM = ACNTS_INTERNAL_ACNUM
         --AND ACNTS_AC_TYPE <> 'SBST'
         AND TRAN_ENTITY_NUM = 1
         AND TRAN_DB_CR_FLG='D'
          AND TRANBAT_ENTITY_NUM=1
         AND TRANBAT_SOURCE_TABLE='HOVEREC'
         AND TRANBAT_BRN_CODE=TRAN_BRN_CODE
        AND  TRANBAT_DATE_OF_TRAN=TRAN_DATE_OF_TRAN
         AND TRANBAT_BATCH_NUMBER=TRAN_BATCH_NUMBER
         AND (TRAN_BRN_CODE, TRAN_DATE_OF_TRAN, TRAN_BATCH_NUMBER) IN (
SELECT TRAN_BRN_CODE, TRAN_DATE_OF_TRAN, TRAN_BATCH_NUMBER
  FROM TRAN2022,TRANBAT2022
 WHERE     TRAN_ENTITY_NUM = 1
       AND TRAN_GLACC_CODE = '140146113'
       AND TRANBAT_SOURCE_TABLE='HOVEREC'
       AND TRANBAT_ENTITY_NUM=1
         AND TRANBAT_BRN_CODE=TRAN_BRN_CODE
        AND  TRANBAT_DATE_OF_TRAN=TRAN_DATE_OF_TRAN
         AND TRANBAT_BATCH_NUMBER=TRAN_BATCH_NUMBER
       AND TRAN_DATE_OF_TRAN BETWEEN '19-MAY-2022' AND  '14-DEC-2022'
       AND TRAN_DB_CR_FLG = 'C')
GROUP BY TRAN_AMOUNT ;



-----SLAB WISE DATA-----------------
SELECT TRANBAT_NARR_DTL1||TRANBAT_NARR_DTL2 ED_YEAR,
         COUNT (ACNTS_INTERNAL_ACNUM) TOTAL_ACCOUNT,
         TRAN_AMOUNT SLAB,
         SUM (TRAN_AMOUNT) EXCISE_AMT                       --22257300  338050
    FROM TRAN2022, ACNTS,TRANBAT2022
   WHERE     TRAN_AMOUNT <> 0
         AND ACNTS_ENTITY_NUM = 1
         AND TRAN_INTERNAL_ACNUM = ACNTS_INTERNAL_ACNUM
        -- AND ACNTS_AC_TYPE <> 'SBST'
         AND TRAN_ENTITY_NUM = 1
         AND TRAN_DB_CR_FLG='D'
          AND TRANBAT_ENTITY_NUM=1
         AND TRANBAT_SOURCE_TABLE='HOVEREC'
           and TRAN_AUTH_BY is not null
             AND TRAN_BASE_CURR_EQ_AMT <> 0
         AND TRANBAT_BRN_CODE=TRAN_BRN_CODE
        AND  TRANBAT_DATE_OF_TRAN=TRAN_DATE_OF_TRAN
         AND TRANBAT_BATCH_NUMBER=TRAN_BATCH_NUMBER
         AND (TRAN_BRN_CODE, TRAN_DATE_OF_TRAN, TRAN_BATCH_NUMBER) IN (
SELECT TRAN_BRN_CODE, TRAN_DATE_OF_TRAN, TRAN_BATCH_NUMBER
  FROM TRAN2022,TRANBAT2022
 WHERE     TRAN_ENTITY_NUM = 1
       AND TRAN_GLACC_CODE = '140146113'
       AND TRANBAT_SOURCE_TABLE='HOVEREC'
       AND TRANBAT_ENTITY_NUM=1
         and TRAN_AUTH_BY is not null
         AND TRANBAT_BRN_CODE=TRAN_BRN_CODE
           AND TRAN_BASE_CURR_EQ_AMT <> 0
        AND  TRANBAT_DATE_OF_TRAN=TRAN_DATE_OF_TRAN
         AND TRANBAT_BATCH_NUMBER=TRAN_BATCH_NUMBER
      -- AND TRAN_DATE_OF_TRAN BETWEEN '01-JUN-2022' AND  '30-JUN-2022'
       AND TRAN_DB_CR_FLG = 'C')
GROUP BY TRAN_AMOUNT, TRANBAT_NARR_DTL1|| TRANBAT_NARR_DTL2;





----------------------BRANCH WISE MANUALLY---------------------------
/* Formatted on 3/15/2023 2:02:06 PM (QP5 v5.388) */
  SELECT TRANBAT_BRN_CODE,
         (SELECT MBRN_NAME
            FROM MBRN
           WHERE MBRN_CODE = TRANBAT_BRN_CODE)     MBRN_NAME,
          COUNT (TRAN_INTERNAL_ACNUM)              TOTAL_ACCOUNT,
         TRAN_AMOUNT                               SLAB,
         SUM (TRAN_AMOUNT)                         EXCISE_AMT --22257300  338050
    FROM TRAN2020, TRANBAT2020
   WHERE     TRAN_AMOUNT <> 0
         -- AND ACNTS_AC_TYPE <> 'SBST'
         AND TRAN_ENTITY_NUM = 1
         AND TRAN_DB_CR_FLG = 'D'
           and TRAN_AUTH_BY is not null
             AND TRAN_BASE_CURR_EQ_AMT <> 0
         AND TRAN_INTERNAL_ACNUM<>0
         AND TRANBAT_ENTITY_NUM = 1
         AND TRANBAT_SOURCE_TABLE = 'HOVEREC'
         AND TRANBAT_BRN_CODE = TRAN_BRN_CODE
         AND TRANBAT_DATE_OF_TRAN = TRAN_DATE_OF_TRAN
         AND TRANBAT_BATCH_NUMBER = TRAN_BATCH_NUMBER
         AND (TRAN_BRN_CODE, TRAN_DATE_OF_TRAN, TRAN_BATCH_NUMBER) IN
                 (SELECT TRAN_BRN_CODE, TRAN_DATE_OF_TRAN, TRAN_BATCH_NUMBER
                   FROM TRAN2020, TRANBAT2020
                  WHERE     TRAN_ENTITY_NUM = 1
                        AND TRAN_GLACC_CODE = '140146113'
                        and TRAN_AUTH_BY is not null
                        AND TRANBAT_SOURCE_TABLE = 'HOVEREC'
                          AND TRAN_BASE_CURR_EQ_AMT <> 0
                        AND TRANBAT_ENTITY_NUM = 1
                        AND TRANBAT_BRN_CODE = TRAN_BRN_CODE
                        AND TRANBAT_DATE_OF_TRAN = TRAN_DATE_OF_TRAN
                        AND TRANBAT_BATCH_NUMBER = TRAN_BATCH_NUMBER
                        -- AND TRAN_DATE_OF_TRAN BETWEEN '01-JUN-2022' AND  '30-JUN-2022'
                        AND TRAN_DB_CR_FLG = 'C')
GROUP BY TRANBAT_BRN_CODE,
         TRAN_AMOUNT
        ;
-----------from tran--------------------
/* Formatted on 6/30/2023 8:44:44 PM (QP5 v5.388) */
  SELECT HOVERING_BRN_CODE,
         HOVERING_YEAR,
         HOVERING_SL_NUM,
         HOVERING_RECOVERY_FROM_ACNT,
         HOVERING_RECOVERY_TO_ACNT,
         HOVERING_RECOVERY_CURR,
         HOVERING_PENDING_AMT,
         HOVERING_RECOVERY_NARR1,
         HOVERING_RECOVERY_NARR2,
         HOVERING_RECOVERY_NARR3,
         HOVERING_GLACC_CODE,
         HOVERING_CHG_CODE,
         HOVERTYPE_PARTIAL_REC_ALLOWED,
         HOVERTYPE_TRAN_CODE
    FROM ACNTS,
         ACNTBAL,
         HOVERING,
         HOVERTYPE
   WHERE     HOVERING_ENTITY_NUM = 1
         AND ACNTBAL_ENTITY_NUM = 1
         AND ACNTS_ENTITY_NUM = 1
         AND HOVERING_START_DATE <= '30-JUN-23'
         AND (HOVERING_END_DATE IS NULL OR HOVERING_END_DATE >= '30-JUN-23')
         AND HOVERING_STATUS <> 'C'
         AND HOVERING_PENDING_AMT > 0
         AND HOVERING_AUTH_ON IS NOT NULL
         AND HOVERING_CANC_ON IS NULL
         AND HOVERING_TYPE = HOVERTYPE_CODE
         AND HOVERING_RECOVERY_FROM_ACNT = ACNTBAL_INTERNAL_ACNUM
         AND HOVERING_RECOVERY_FROM_ACNT = ACNTS_INTERNAL_ACNUM
         AND ACNTS_CLOSURE_DATE IS NULL
         AND ACNTS_DB_FREEZED <> '1'
         AND HOVERING_RECOVERY_CURR = ACNTBAL_CURR_CODE
         AND ACNTBAL_AC_DB_QUEUE_AMT > 0
         AND HOVERING_RECOVERY_FROM_ACNT = 13316700018212
         AND HOVERTYPE_ONLINE = '1'
ORDER BY HOVERING_RECOVERY_FROM_ACNT,
         HOVERTYPE_PRIORITY,
         HOVERING_AUTH_ON,
         HOVERING_ENTITY_NUM,
         HOVERING_BRN_CODE,
         HOVERING_YEAR,
         HOVERING_SL_NUM