SELECT *
  FROM IACLINK I
 WHERE I.IACLINK_ACTUAL_ACNUM IN ('0003434097471');

EDIT  ACNTONLTXLIM A WHERE A.ACNTONL_INTERNAL_ACNUM IN (10003400006054,14410700010095);

INSERT INTO ACNTONLTXLIM 
SELECT IACLINK_ENTITY_NUM ACNTONL_ENTITY_NUM,
       IACLINK_INTERNAL_ACNUM ACNTONL_INTERNAL_ACNUM,
       TRUNC (SYSDATE) ACNTONL_LIMIT_EFF_DATE,
       ACCRUE_AMNT ACNTONL_CASH_DEP_AMT,
       ACCRUE_AMNT ACNTONL_CASH_WDRL_AMT,
       ACCRUE_AMNT ACNTONL_TRF_DEP_AMT,
       ACCRUE_AMNT ACNTONL_TRF_WDRL_AMT,
       0 ACNTONL_BCK_TO_PROD,
       'INTELECT' ACNTONL_ENTD_BY,
       SYSDATE ACNTONL_ENTD_ON,
       NULL ACNTONL_LAST_MOD_BY,
       NULL ACNTONL_LAST_MOD_ON,
       'INTELECT' ACNTONL_AUTH_BY,
       SYSDATE ACNTONL_AUTH_ON,
       NULL TBA_MAIN_KEY
  FROM IACLINK, ACC4
 WHERE IACLINK_ENTITY_NUM = 1 AND IACLINK_ACTUAL_ACNUM = ACC_NO;
       
       