/* Formatted on 9/12/2021 5:14:56 PM (QP5 v5.149.1003.31008) */
SELECT GLSUM_GLACC_CODE,
       'Imprest A/C- Received from B.B against W.E.R A/C' gl_name,
       GLSUM_TRAN_DATE,
       (GLSUM_BC_DB_SUM) TOTAL_INCETIVE_AMOUNT,
       (GLSUM_NUM_DBS) TOTAL_COUNT,
       (GLSUM_BC_CR_SUM) TOTAL_INCENTV_RETURN,
       (GLSUM_NUM_CRS) RETURN_COUNT
  FROM glsum2019
 WHERE GLSUM_GLACC_CODE = '140143216' AND GLSUM_TRAN_DATE >= '01-jul-2019'
UNION ALL
SELECT GLSUM_GLACC_CODE,
       'Imprest A/C- Received from B.B against W.E.R A/C' gl_name,
       GLSUM_TRAN_DATE,
       (GLSUM_BC_DB_SUM) TOTAL_INCETIVE_AMOUNT,
       (GLSUM_NUM_DBS) TOTAL_COUNT,
       (GLSUM_BC_CR_SUM) TOTAL_INCENTV_RETURN,
       (GLSUM_NUM_CRS) RETURN_COUNT
  FROM glsum2020
 WHERE GLSUM_GLACC_CODE = '140143216' AND GLSUM_TRAN_DATE >= '30-jun-2020'