UPDATE ACNTS
   SET ACNTS_DORMANT_ACNT = '0',ACNTS_INOP_ACNT= '0'
 WHERE     ACNTS_ENTITY_NUM = 1
       AND ACNTS_BRN_CODE = 51169
       AND ACNTS_PROD_CODE = 1000
	   AND ACNTS_INTERNAL_ACNUM IN ()
       AND ACNTS_DORMANT_ACNT = '1'
	   AND ACNTS_INOP_ACNT='1';
-----------------------------------------------------------------
INSERT INTO ACNTSTATUS
   SELECT 1 ACNTSTATUS_ENTITY_NUM,
          ACNTS_INTERNAL_ACNUM ACNTSTATUS_INTERNAL_ACNUM,
          TRUNC (SYSDATE) ACNTSTATUS_EFF_DATE, --USER_DATE
          'O' ACNTSTATUS_FLG,
          'Auto Classification' ACNTSTATUS_REMARKS1,
          NULL ACNTSTATUS_REMARKS2,
          NULL ACNTSTATUS_REMARKS3,
          41699 ACNTSTATUS_ENTD_BY, --BRANCH_USER_ID
          SYSDATE ACNTSTATUS_ENTD_ON, --USER_DATE
          NULL ACNTSTATUS_LAST_MOD_BY,
          NULL ACNTSTATUS_LAST_MOD_ON
     FROM ACNTS
    WHERE     ACNTS_ENTITY_NUM = 1
          AND ACNTS_BRN_CODE = 51169
		  AND ACNTS_INTERNAL_ACNUM IN ()
          AND ACNTS_PROD_CODE = 1000
          AND ACNTS_INTERNAL_ACNUM NOT IN
                 (SELECT ACNTSTATUS_INTERNAL_ACNUM
                    FROM ACNTSTATUS
                   WHERE ACNTSTATUS_ENTITY_NUM = 1
AND ACNTSTATUS_INTERNAL_ACNUM like '151169%'
AND ACNTSTATUS_FLG = 'O')