 INSERT INTO LOANACNTS
 SELECT I.IACLINK_ENTITY_NUM LNACNT_ENTITY_NUM,
       I.IACLINK_INTERNAL_ACNUM LNACNT_INTERNAL_ACNUM,
       '9820' LNACNT_PURPOSE_CODE,
       NULL LNACNT_LAST_AOD_GIVEN_ON,
       NULL LNACNT_NEXT_AOD_DUE_ON,
       'S' LNACNT_DISB_TYPE,
       0 LNACNT_SUBSIDY_AVAILABLE,
       0 LNACNT_AUTO_INSTALL_RECOV_REQD,
       NULL LNACNT_RECOV_ACNT_NUM,
       R.LNWRTOFF_WRTOFF_DATE LNACNT_INT_ACCR_UPTO,
       R.LNWRTOFF_WRTOFF_DATE LNACNT_INT_APPLIED_UPTO_DATE,
       R.LNWRTOFF_WRTOFF_DATE LNACNT_PA_ACCR_POSTED_UPTO,
       'MIG' LNACNT_ENTD_BY,
       TRUNC (A.ACNTS_OPENING_DATE) LNACNT_ENTD_ON,
       NULL LNACNT_LAST_MOD_BY,
       NULL LNACNT_LAST_MOD_ON,
       'MIG' LNACNT_AUTH_BY,
       TRUNC (A.ACNTS_OPENING_DATE) LNACNT_AUTH_ON,
       NULL TBA_MAIN_KEY,
       0 LNACNT_MARGIN_PERCEN,
       0 LNACNT_PARENT_ACNUM,
       NULL LNACNT_LC_NUM,
       NULL LNACNT_LC_OPEN_DATE,
       0 LNACNT_LC_AMT,
       NULL LNACNT_BILL_REF_NUM,
       NULL LNACNT_BILL_DATE,
       0 LNACNT_BILL_AMT,
       0 LNACNT_PROJECT_LOAN_ACNUM,
       0 LNACNT_EQUITY_ACNUM,
       0 LNACNT_EQUITY_MARGIN
  FROM MIG_WRITEOFF R, IACLINK I, ACNTS A
 WHERE     R.LNWRTOFF_ACNT_NUM = I.IACLINK_ACTUAL_ACNUM
       AND I.IACLINK_INTERNAL_ACNUM NOT IN
              (SELECT LOANACNTS.LNACNT_INTERNAL_ACNUM FROM LOANACNTS)
       AND A.ACNTS_INTERNAL_ACNUM = I.IACLINK_INTERNAL_ACNUM
       AND ACNTS_ENTITY_NUM=1
       AND IACLINK_ENTITY_NUM=1;
       
--------------------------------------
INSERT INTO ACASLL
SELECT I.IACLINK_ENTITY_NUM ACASLL_ENTITY_NUM,
       A.ACNTS_CLIENT_NUM ACASLL_CLIENT_NUM,
       1 ACASLL_LIMIT_LINE_NUM,
       ACNTS_OPENING_DATE ACASLL_DATE_OF_ASSIGNMENT,
      NULL ACASLL_REM1,
      NULL  ACASLL_REM2,
      NULL  ACASLL_REM3,
       'MIG' ACASLL_ENTD_BY,
       ACNTS_OPENING_DATE ACASLL_ENTD_ON,
       NULL ACASLL_LAST_MOD_BY,
       NULL ACASLL_LAST_MOD_ON,
       'MIG' ACASLL_AUTH_BY,
       NULL ACASLL_AUTH_ON,
        NULL  BA_MAIN_KEY
   FROM MIG_WRITEOFF R, IACLINK I,ACNTS A
 WHERE     R.LNWRTOFF_ACNT_NUM = I.IACLINK_ACTUAL_ACNUM
       AND I.IACLINK_INTERNAL_ACNUM NOT IN
              (SELECT LOANACNTS.LNACNT_INTERNAL_ACNUM FROM LOANACNTS)
              AND A.ACNTS_INTERNAL_ACNUM= I.IACLINK_INTERNAL_ACNUM
			  AND ACNTS_ENTITY_NUM=1
       AND IACLINK_ENTITY_NUM=1;  ;
              
              
 ------------------------------------------             
 INSERT INTO ACASLLDTL             
SELECT I.IACLINK_ENTITY_NUM ACASLLDTL_ENTITY_NUM,
       A.ACNTS_CLIENT_NUM ACASLLDTL_CLIENT_NUM,
       1 ACASLLDTL_LIMIT_LINE_NUM,
       01 ACASLLDTL_ACNT_SL,
       I.IACLINK_INTERNAL_ACNUM ACASLLDTL_INTERNAL_ACNUM
  FROM MIG_WRITEOFF R, IACLINK I, ACNTS A
 WHERE     R.LNWRTOFF_ACNT_NUM = I.IACLINK_ACTUAL_ACNUM
       AND I.IACLINK_INTERNAL_ACNUM NOT IN
              (SELECT LOANACNTS.LNACNT_INTERNAL_ACNUM FROM LOANACNTS)
       AND A.ACNTS_INTERNAL_ACNUM = I.IACLINK_INTERNAL_ACNUM
	   AND ACNTS_ENTITY_NUM=1
       AND IACLINK_ENTITY_NUM=1;  ;
       
-----------------------------
 INSERT INTO LIMITLINE
 SELECT I.IACLINK_ENTITY_NUM LMTLINE_ENTITY_NUM,
       A.ACNTS_CLIENT_NUM LMTLINE_CLIENT_CODE,
       1 LMTLINE_NUM,
       P.PRODUCT_NAME LMTLINE_FACILITY_DESCN,
       A.ACNTS_OPENING_DATE LMTLINE_CREATION_DATE,
       1 LMTLINE_APEX_LEVEL_LIMIT,
       0 LMTLINE_SUB_LIMIT_LINE,
       01 LMTLINE_SAUTH_CODE,
       A.ACNTS_OPENING_DATE LMTLINE_DATE_OF_SANCTION,
       953 LMTLINE_SANCTION_REF_NUM,
       A.ACNTS_OPENING_DATE LMTLINE_LIMIT_EFF_DATE,
       R.LNWRTOFF_WRTOFF_DATE LMTLINE_LIMIT_EXPIRY_DATE,
       0 LMTLINE_REVOLVING_LIMIT,
       0 LMTLINE_ADHOC_FACILITY,
       0 LMTLINE_SHARED_LIMIT_LINE,
       P.PRODUCT_CODE LMTLINE_PROD_CODE,
       0 LMTLINE_FACILITY_GRP_CODE,
       'BDT' LMTLINE_SANCTION_CURR,
       R.LNWRTOFF_WRTOFF_AMT LMTLINE_SANCTION_AMT,
       0 LMTLINE_AUTO_DECREMENT,
       NULL LMTLINE_DECR_FIRST_DATE,
      NULL LMTLINE_DECR_FREQ,
      0 LMTLINE_DECR_AMT,
       NULL LMTLINE_LIMIT_AVL_ON_DATE,
       NULL LMTLINE_SEC_LIMIT_LINE,
       NULL LMTLINE_SEC_MARGIN,
       R.LNWRTOFF_WRTOFF_AMT LMTLINE_SEC_AMT_REQD,
       NULL LMTLINE_SEC_TYPE_SPECIFIED,
       NULL LMTLINE_DP_REQD,
       0 LMTLINE_DP_AMT,
       NULL LMTLINE_DP_VALID_UPTO,
       NULL LMTLINE_DUE_DATE_REVIEW,
       0 LMTLINE_PENAL_EOL_CHARGED,
       0 LMTLINE_PENAL_EXP_CHARGED,
       NULL LMTLINE_PENAL_RECOV_ACNUM,
       'LIMIT MIG' LMTLINE_REM1,
       NULL LMTLINE_REM2,
       NULL LMTLINE_REM3,
       NULL LMTLINE_CANCELLED_DATE,
       NULL LMTLINE_INCR_DECR_UPTO_DATE,
       0 LMTLINE_MARKED_AMT_OUT,
       0 LMTLINE_MARKED_AMT_INTO,
       0 LMTLINE_EARMARK_UNAUTH,
       'MIG' LMTLINE_ENTD_BY,
       TRUNC(SYSDATE) LMTLINE_ENTD_ON,
       NULL LMTLINE_LAST_MOD_BY,
       NULL LMTLINE_LAST_MOD_ON,
       'MIG' LMTLINE_AUTH_BY,
      TRUNC(SYSDATE) LMTLINE_AUTH_ON,
       NULL TBA_MAIN_KEY,
       NULL LMTLINE_LIMIT_REM,
       NULL LMTLINE_LIMIT_REM_EFF_DATE,
       NULL LMTLINE_LIMIT_REM_EXPIRY_DATE,
       0 LMTLINE_GROUP_LEVEL_LIMIT,
       0 LMTLINE_PRINCIPAL_AMT,
       0 LMTLINE_INT_AMT,
       0 LMTLINE_NO_OF_UNIT
  FROM MIG_WRITEOFF R,
       IACLINK I,
       ACNTS A,
       PRODUCTS P
 WHERE     R.LNWRTOFF_ACNT_NUM = I.IACLINK_ACTUAL_ACNUM
       AND I.IACLINK_INTERNAL_ACNUM NOT IN
              (SELECT LOANACNTS.LNACNT_INTERNAL_ACNUM FROM LOANACNTS)
       AND A.ACNTS_INTERNAL_ACNUM = I.IACLINK_INTERNAL_ACNUM
       AND A.ACNTS_PROD_CODE=P.PRODUCT_CODE
       AND ACNTS_ENTITY_NUM=1
       AND IACLINK_ENTITY_NUM=1 ;
       
------------------------
 INSERT INTO LIMITLINEHIST
 SELECT I.IACLINK_ENTITY_NUM LIMLNEHIST_ENTITY_NUM,
       A.ACNTS_CLIENT_NUM LIMLNEHIST_CLIENT_CODE,
       1 LIMLNEHIST_LIMIT_LINE_NUM,
       A.ACNTS_OPENING_DATE LIMLNEHIST_EFF_DATE,
       01 LIMLNEHIST_SAUTH_CODE,
       A.ACNTS_OPENING_DATE LIMLNEHIST_DATE_OF_SANCTION,
       953 LIMLNEHIST_SANCTION_REF_NUM,
       'BDT' LIMLNEHIST_SANCTION_CURR,
       R.LNWRTOFF_WRTOFF_AMT LIMLNEHIST_SANCTION_AMT,
       NULL LIMLNEHIST_LIMIT_AVL_ON_DATE,
       R.LNWRTOFF_WRTOFF_DATE LIMLNEHIST_LIMIT_EXPIRY_DATE,
       'LIMIT MIG' LIMLNEHIST_REM1,
       NULL LIMLNEHIST_REM2,
       NULL LIMLNEHIST_REM3,
       'MIG' LIMLNEHIST_ENTD_BY,
       A.ACNTS_OPENING_DATE LIMLNEHIST_ENTD_ON,
       NULL LIMLNEHIST_LAST_MOD_BY,
       NULL LIMLNEHIST_LAST_MOD_ON,
       'MIG' LIMLNEHIST_AUTH_BY,
       A.ACNTS_OPENING_DATE LIMLNEHIST_AUTH_ON,
       NULL TBA_MAIN_KEY,
       0 LIMLNEHIST_SL_NO,
       0 LIMLNEHIST_LIMIT_REM,
       NULL LIMLNEHIST_LIMIT_REM_EFF_DATE,
       NULL LIMLNEHIST_LIMIT_REM_EXP_DATE,
       01 LIMLNEHIST_GROUP_LEVEL_LIMIT,
       LNWRTOFF_PRIN_WRTOFF_AMT LIMLNEHIST_PRINCIPAL_AMT,
       LNWRTOFF_INT_WRTOFF_AMT LIMLNEHIST_INT_AMT,
       NULL LIMLNEHIST_NO_OF_UNIT,
       NULL LIMLNEHIST_DP_REQD,
       0 LIMLNEHIST_DP_AMT,
       NULL LIMLNEHIST_DP_VALID_UPTO,
       NULL LIMLNEHIST_DUE_DATE_REVIEW
  FROM MIG_WRITEOFF R, IACLINK I, ACNTS A
 WHERE     R.LNWRTOFF_ACNT_NUM = I.IACLINK_ACTUAL_ACNUM
       AND I.IACLINK_INTERNAL_ACNUM NOT IN
              (SELECT LOANACNTS.LNACNT_INTERNAL_ACNUM FROM LOANACNTS)
       AND A.ACNTS_INTERNAL_ACNUM = I.IACLINK_INTERNAL_ACNUM
       AND ACNTS_ENTITY_NUM=1
       AND IACLINK_ENTITY_NUM=1;       