Insert into EODSODPGMLIST
   (ESPGMLIST_PROCESS_NAME, ESPGMLIST_PROCESS_DESCN, ESPGMLIST_DEF_TRANCD, ESPGMLIST_PROC_ACNT_LIMIT)
 Values
   ('PKG_FD_RD_MANUAL_MARK.START_BRNWISE', 'FD Account Closure (No Active Contract) Process', ' ', 0);
COMMIT;
