Insert into EODSODPROCDTL
   (ESPROCDTL_ENTITY_NUM, ESPROCDTL_RUN_STAGE, ESPROCDTL_SEQ_SL, ESPROCDTL_PROCESS_NAME, ESPROCDTL_RUN_FREQ, 
    ESPROCDTL_DISABLED)
 Values
   (1, 'E', 27.1, 'PKG_FD_RD_MANUAL_MARK.START_BRNWISE', 'D', 
    '1');
COMMIT;
