INSERT INTO BRNLIST
    SELECT  1 BRNLIST_ENTITY_NUM,
        LIST_ID  BRNLIST_LIST_NUM,
       BRN_NAME BRNLIST_LIST_DESCN,
       'INTELECT' BRNLIST_ENTD_BY,
       SYSDATE BRNLIST_ENTD_ON,
       NULL BRNLIST_LAST_MOD_BY,
       NULL BRNLIST_LAST_MOD_ON,
       'INTELECT' BRNLIST_AUTH_BY,
       SYSDATE BRNLIST_AUTH_ON,
       NULL TBA_MAIN_KEY FROM (
  SELECT DISTINCT LIST_ID, ADMIN_CODE, ( SELECT MM.MBRN_NAME FROM MBRN MM WHERE  MM.MBRN_CODE = ADMIN_CODE ) BRN_NAME
  FROM BRANCH_ADMIN ORDER BY ADMIN_CODE) ;
  
  
  
INSERT INTO BRNLISTDTL
  SELECT 1 BRNLISTDTL_ENTITY_NUM,
         LIST_ID BRNLISTDTL_LIST_NUM,
         ROW_NUMBER() OVER (PARTITION BY ADMIN_CODE ORDER BY ADMIN_CODE) BRNLISTDTL_DTL_SL,
         BRANCH_CODE BRNLISTDTL_BRN_CODE
    FROM BRANCH_ADMIN
ORDER BY 1;