Insert into SMSSVCMAST
   (SMSMAST_ENTITY_NUM, SMSMAST_CD, SMSMAST_DESC, SMSMAST_SVC_CD, SMSMAST_SHORT_CD, 
    SMSMAST_REG_ALL, SMSMAST_NO_RESP_SEG, SMSMAST_ENTD_BY, SMSMAST_ENTD_ON, SMSMAST_LAST_MOD_BY, 
    SMSMAST_LAST_MOD_ON, SMSMAST_AUTH_BY, SMSMAST_AUTH_ON, NO_OF_DAYS_BEFORE, NO_OF_DAYS_AFTER, 
    CHARGE_CODE, SERVICE_STATUS, SERVICE_TYPE)
 Values
   (1, 'BULKSMS', 'BULKSMS', 'BULKSMS', 'BULKSMS', 
    '2', 1, '10890', TO_DATE('9/14/2022', 'MM/DD/YYYY'), '10890', 
    TO_DATE('9/15/2022', 'MM/DD/YYYY'), '10890', TO_DATE('9/15/2022', 'MM/DD/YYYY'), 0, 0, 
    'BULKSMS', 0, '1');
COMMIT;
