/* Formatted on 17/01/2019 2:53:03 PM (QP5 v5.227.12220.39754) */
SELECT ACNTS_BRN_CODE,
       facno (1, ACNTS_INTERNAL_ACNUM) ACCOUNT_NUMBER,
       ACNTS_AC_NAME1 ACCOUNT_NAME,
       JNTCLDTL_CLIENT_CODE JOINT_CLIENT_CODE,
       (SELECT CLIENTS_NAME
          FROM CLIENTS
         WHERE CLIENTS_CODE = JNTCLDTL_CLIENT_CODE)
          JOINT_CLIENT_NAME,
       JNTCLDTL_INDIV_CLIENT_CODE IND_CLIENT_CODE,
       (SELECT CLIENTS_NAME
          FROM CLIENTS
         WHERE CLIENTS_CODE = JNTCLDTL_INDIV_CLIENT_CODE)
          IND_CLIENTS_NAME,
       (SELECT INDCLIENT_SEX
          FROM INDCLIENTS
         WHERE INDCLIENT_CODE = JNTCLDTL_INDIV_CLIENT_CODE)
          IND_CLIENTS_GENDER
  FROM acnts, JOINTCLIENTSDTL
 WHERE JNTCLDTL_CLIENT_CODE = ACNTS_CLIENT_NUM AND ACNTS_ENTITY_NUM = 1;
 
 
--------------------VERSION 2-------------------------
/* Formatted on 17/01/2019 3:06:45 PM (QP5 v5.227.12220.39754) */
  SELECT ACNTS_BRN_CODE,
         ACNTS_INTERNAL_ACNUM,
         ACNTS_AC_NAME1 ACCOUNT_NAME,
         JNTCLDTL_CLIENT_CODE JOINT_CLIENT_CODE,
         (SELECT CLIENTS_NAME
            FROM CLIENTS
           WHERE CLIENTS_CODE = JNTCLDTL_CLIENT_CODE)
            JOINT_CLIENT_NAME,
        TO_CHAR( wm_concat (JNTCLDTL_INDIV_CLIENT_CODE)) IND_CLIENT_CODE,
        TO_CHAR( wm_concat ( (SELECT CLIENTS_NAME
                        FROM CLIENTS
                       WHERE CLIENTS_CODE = JNTCLDTL_INDIV_CLIENT_CODE)))
            IND_CLIENTS_NAME,
         TO_CHAR(wm_concat ( (SELECT INDCLIENT_SEX
                        FROM INDCLIENTS
                       WHERE INDCLIENT_CODE = JNTCLDTL_INDIV_CLIENT_CODE)))
            IND_CLIENTS_GENDER
    FROM acnts, JOINTCLIENTSDTL
   WHERE JNTCLDTL_CLIENT_CODE = ACNTS_CLIENT_NUM AND ACNTS_ENTITY_NUM = 1
GROUP BY ACNTS_BRN_CODE, ACNTS_INTERNAL_ACNUM, JNTCLDTL_CLIENT_CODE,ACNTS_AC_NAME1