/* Formatted on 2/5/2020 3:08:19 PM (QP5 v5.227.12220.39754) */
SELECT LMTLINE_CLIENT_CODE,
       CLIENTS_NAME,
       LMTLINE_NUM,
       LMTLINE_FACILITY_DESCN,
       LMTLINE_SANCTION_CURR,
       SP_GETFORMAT (1, LMTLINE_SANCTION_CURR, LMTLINE_SANCTION_AMT)
          LMTLINE_SANCTION_AMT,
       TO_CHAR (LMTLINE_LIMIT_EFF_DATE, 'DD-MON-YYYY') LMTLINE_LIMIT_EFF_DATE,
       TO_CHAR (LMTLINE_LIMIT_EXPIRY_DATE, 'DD-MON-YYYY')
          LMTLINE_LIMIT_EXPIRY_DATE,
       LMTLINE_ENTD_BY,
        LMTLINE_ENTD_ON,
       LMTLINE_AUTH_BY
  FROM LIMITLINE, CLIENTS
 WHERE     LMTLINE_ENTITY_NUM = 1
       AND LMTLINE_CLIENT_CODE = CLIENTS_CODE
       AND LMTLINE_CANCELLED_DATE IS NULL
       AND LMTLINE_AUTH_ON IS NOT NULL
       AND CLIENTS_HOME_BRN_CODE=1065
       ORDER BY LMTLINE_CLIENT_CODE ASC,LMTLINE_NUM ASC ,LMTLINE_LIMIT_EFF_DATE DESC