insert into LLACNTOS
SELECT 1 LLACNTOS_ENTITY_NUM,
        ACNTS_CLIENT_NUM LLACNTOS_CLIENT_CODE,
       1  LLACNTOS_LIMIT_LINE_NUM,
        ACNTS_INTERNAL_ACNUM LLACNTOS_CLIENT_ACNUM,
        LNACNT_OUTSTANDING_BALANCE LLACNTOS_LIMIT_CURR_OS_AMT,
        -1*LNACNT_SANCTION_AMT LLACNTOS_LIMIT_CURR_DISB_MADE
  FROM ACNTOTN, acnts,mig_lnacnt
 WHERE     ACNTOTN_ENTITY_NUM = ACNTS_ENTITY_NUM
       AND acntotn.acntotn_internal_acnum = acnts.acnts_internal_acnum
       AND ACNTOTN_ENTITY_NUM = 1
        AND ACNTOTN.ACNTOTN_OLD_ACNT_NUM = LNACNT_ACNUM;

 
UPDATE mig_lnacnt
   SET LNACNT_OUTSTANDING_BALANCE = -1 * LNACNT_OUTSTANDING_BALANCE,
       LNACNT_PRIN_OS = -1 * LNACNT_PRIN_OS,
       LNACNT_INT_OS = -1 * LNACNT_INT_OS,
       LNACNT_CHG_OS = -1 * LNACNT_CHG_OS;

----
/* Formatted on 12/5/2022 7:32:40 PM (QP5 v5.388) */
SELECT 1 BATCH_SL,
       rownum LEG_SL,
     null  TRAN_DATE,
       null VALUE_DATE,
      null  SUPP_TRAN,
      18 BRN_CODE,
     18  ACING_BRN_CODE,
      'D' DR_CR,
       NULL GLACC_CODE,
     ACNTS_INTERNAL_ACNUM  INT_AC_NO,
     NULL  CONT_NO,
     ACNTS_CURR_CODE  CURR_CODE,
     ABS(LNACNT_OUTSTANDING_BALANCE)  AC_AMOUNT,
       ABS(OUTSTANDING_BALANCE_BD)  BC_AMOUNT,
      ABS(LNACNT_PRIN_OS)  PRINCIPAL,
       ABS(LNACNT_INT_OS) INTEREST,
        ABS(LNACNT_CHG_OS) CHARGE,
      NULL INST_PREFIX,
      NULL INST_NUM,
      NULL INST_DATE,
      NULL IBR_GL,
      NULL ORIG_RESP,
      NULL CONT_BRN_CODE,
      NULL ADV_NUM,
      NULL ADV_DATE,
      NULL IBR_CODE,
      NULL CAN_IBR_CODE,
       NULL LEG_NARRATION,
      NULL BATCH_NARRATION,
     '40182'  USER_ID,
      NULL TERMINAL_ID,
      NULL PROCESSED,
      NULL BATCH_NO,
      NULL ERR_MSG,
     99119  DEPT_CODE
  FROM ACNTOTN, acnts, mig_lnacnt
 WHERE     ACNTOTN_ENTITY_NUM = ACNTS_ENTITY_NUM
       AND acntotn.acntotn_internal_acnum = acnts.acnts_internal_acnum
       AND ACNTOTN_ENTITY_NUM = 1
       AND ACNTOTN.ACNTOTN_OLD_ACNT_NUM = LNACNT_ACNUM
       and ACNTS_CURR_CODE<>'BDT'