/* Formatted on 1/8/2020 3:50:24 PM (QP5 v5.227.12220.39754) */
SELECT /*+ PARALLEL( 8) */
      TRANADV_BRN_CODE,
       FACNO (1, TRAN_INTERNAL_ACNUM) ACCCOUNT_NUMBER,
       (SELECT MIN (LNACDSDTLH_DISB_DATE)
          FROM LNACDSDTLHIST
         WHERE     LNACDSDTLH_INTERNAL_ACNUM = TRAN_INTERNAL_ACNUM
               AND LNACDSDTLH_ENTITY_NUM = 1)
          FIRST_DISBURSEMENT_DATE,
       ABS (FN_GET_ASON_ACBAL (1,
                               TRAN_INTERNAL_ACNUM,
                               'BDT',
                               '30-SEP-2019',
                               '08-JAN-2020'))
          PREVIOUS_OUTSTANDING,
       (SELECT MAX (ABS (ACBALH_BC_BAL))
          FROM ACBALASONHIST
         WHERE     ACBALH_ENTITY_NUM = 1
               AND ACBALH_INTERNAL_ACNUM = TRAN_INTERNAL_ACNUM
               AND ACBALH_ASON_DATE BETWEEN '01-OCT-2019' AND '31-DEC-2019')
          HIGHEST_OUT_DURING_QUARTER,
       NVL (
          (SELECT SUM (ABS (LNINTAPPL_ACCR_INT_AMT))
             FROM LNINTAPPL
            WHERE     LNINTAPPL_ENTITY_NUM = 1
                  AND LNINTAPPL_ACNT_NUM = TRAN_INTERNAL_ACNUM
                  AND LNINTAPPL_APPL_DATE = TRAN_DATE_OF_TRAN
                  AND LNINTAPPL_BRN_CODE = TRAN_BRN_CODE),
          0)
          TOTAL_INT_DEBIT,
       NVL (TRANADV_CHARGE_BC_AMT, 0) TOTAL_CHARGE_DEBIT
  FROM PRODUCTS, TRAN2019, TRANADV2019
 WHERE     TRAN_BRN_CODE = TRANADV_BRN_CODE
       AND TRAN_DATE_OF_TRAN = TRANADV_DATE_OF_TRAN
       AND TRAN_BATCH_NUMBER = TRANADV_BATCH_NUMBER
       AND TRAN_BATCH_SL_NUM = TRANADV_BATCH_SL_NUM
       AND TRAN_PROD_CODE = PRODUCT_CODE
       AND PRODUCT_FOR_LOANS = 1
       AND TRAN_PROD_CODE <> 0
       AND TRAN_DATE_OF_TRAN BETWEEN '01-OCT-2019' AND '31-DEC-2019'
       AND TRANADV_ENTITY_NUM = 1
       AND TRAN_ENTITY_NUM = 1
       AND TRAN_AMOUNT <> 0
       -- AND TRANADV_INTRD_BC_AMT <> 0

       AND TRANADV_CHARGE_BC_AMT <> 0
       AND TRAN_DB_CR_FLG = 'D'
       AND TRAN_INTERNAL_ACNUM <> 0
--   and TRAN_INTERNAL_ACNUM=14107900007583