/* Formatted on 8/5/2021 11:19:36 AM (QP5 v5.354) */
UPDATE LNREPAY
   SET LNREPAY_AUTH_BY = LNREPAY_ENTD_BY, LNREPAY_AUTH_ON = LNREPAY_ENTD_ON
 WHERE     LNREPAY_REJ_BY IS NULL
       AND LNREPAY_AUTH_BY IS NULL
       AND LNREPAY_ENTRY_DATE < '11-sep-2021'