-- 1. All continious loan and their expiry date

SELECT ACNTS_BRN_CODE BRANCH_CODE,
         MBRN_NAME BRANCH_NAME,
         IACLINK_ACTUAL_ACNUM ACCOUNT_NUMBER,
         ACNTS_PROD_CODE PRODUCT_CODE,
         PRODUCT_NAME PRODUCT_NAME,
         ACNTS_AC_TYPE ACCOUNT_TYPE,
         TO_CHAR (ACNTS_OPENING_DATE,'DD/MM/YYYY') ACCOUNT_OPENING_DATE,
         TO_CHAR ((SELECT LMTLINE_DATE_OF_SANCTION
            FROM LIMITLINE, ACASLLDTL
           WHERE     LMTLINE_ENTITY_NUM = 1
                 AND LMTLINE_CLIENT_CODE = ACASLLDTL_CLIENT_NUM
                 AND LMTLINE_NUM = ACASLLDTL_LIMIT_LINE_NUM
                 AND ACASLLDTL_INTERNAL_ACNUM = ACNTS_INTERNAL_ACNUM
                 AND ACASLLDTL_ENTITY_NUM = 1),
            'DD/MM/YYYY') SANCTION_DATE,
         TO_CHAR (
            (SELECT LMTLINE_LIMIT_EXPIRY_DATE
               FROM LIMITLINE, ACASLLDTL
              WHERE     LMTLINE_ENTITY_NUM = 1
                    AND LMTLINE_CLIENT_CODE = ACASLLDTL_CLIENT_NUM
                    AND LMTLINE_NUM = ACASLLDTL_LIMIT_LINE_NUM
                    AND ACASLLDTL_INTERNAL_ACNUM = ACNTS_INTERNAL_ACNUM
                    AND ACASLLDTL_ENTITY_NUM = 1),
            'DD/MM/YYYY')
            EXPIRY_DATE,
         (SELECT LMTLINE_SANCTION_AMT
            FROM LIMITLINE, ACASLLDTL
           WHERE     LMTLINE_ENTITY_NUM = 1
                 AND LMTLINE_CLIENT_CODE = ACASLLDTL_CLIENT_NUM
                 AND LMTLINE_NUM = ACASLLDTL_LIMIT_LINE_NUM
                 AND ACASLLDTL_INTERNAL_ACNUM = ACNTS_INTERNAL_ACNUM
                 AND ACASLLDTL_ENTITY_NUM = 1) SANCTION_AMOUNT
    FROM ACNTS,
         PRODUCTS,
         IACLINK,
         MBRN
   WHERE     ACNTS_ENTITY_NUM = 1
         AND ACNTS_PROD_CODE = PRODUCT_CODE
         AND PRODUCT_FOR_LOANS = 1
         AND PRODUCT_FOR_RUN_ACS = 1
         AND IACLINK_ENTITY_NUM = 1
         AND IACLINK_INTERNAL_ACNUM = ACNTS_INTERNAL_ACNUM
         AND ACNTS_CLOSURE_DATE IS NULL
         --AND IACLINK_BRN_CODE = 1206
         AND ACNTS_BRN_CODE = IACLINK_BRN_CODE
         AND MBRN_ENTITY_NUM = 1
         AND MBRN_CODE = ACNTS_BRN_CODE
ORDER BY ACNTS_BRN_CODE, ACNTS_PROD_CODE, IACLINK_ACTUAL_ACNUM;


-- 2. Loan data for Product code 2546.



SELECT IACLINK_BRN_CODE BRANCH_CODE,
         MBRN_NAME BRANCH_NAME,
         IACLINK_ACTUAL_ACNUM ACCOUNT_NUMBER,
         ACNTS_AC_TYPE ACCOUNT_TYPE,
         TO_CHAR (ACNTS_OPENING_DATE, 'DD/MM/YYYY') OPEN_DATE,
         (SELECT LMTLINE_SANCTION_AMT
            FROM LIMITLINE, ACASLLDTL
           WHERE     LMTLINE_ENTITY_NUM = 1
                 AND LMTLINE_CLIENT_CODE = ACASLLDTL_CLIENT_NUM
                 AND LMTLINE_NUM = ACASLLDTL_LIMIT_LINE_NUM
                 AND ACASLLDTL_INTERNAL_ACNUM = ACNTS_INTERNAL_ACNUM
                 AND ACASLLDTL_ENTITY_NUM = 1)
            SANCTION_AMOUNT,
         TO_CHAR (
            (SELECT LMTLINE_DATE_OF_SANCTION
               FROM LIMITLINE, ACASLLDTL
              WHERE     LMTLINE_ENTITY_NUM = 1
                    AND LMTLINE_CLIENT_CODE = ACASLLDTL_CLIENT_NUM
                    AND LMTLINE_NUM = ACASLLDTL_LIMIT_LINE_NUM
                    AND ACASLLDTL_INTERNAL_ACNUM = ACNTS_INTERNAL_ACNUM
                    AND ACASLLDTL_ENTITY_NUM = 1),
            'DD/MM/YYYY')
            SANCTION_DATE,
         TO_CHAR (
            (SELECT LMTLINE_LIMIT_EXPIRY_DATE
               FROM LIMITLINE, ACASLLDTL
              WHERE     LMTLINE_ENTITY_NUM = 1
                    AND LMTLINE_CLIENT_CODE = ACASLLDTL_CLIENT_NUM
                    AND LMTLINE_NUM = ACASLLDTL_LIMIT_LINE_NUM
                    AND ACASLLDTL_INTERNAL_ACNUM = ACNTS_INTERNAL_ACNUM
                    AND ACASLLDTL_ENTITY_NUM = 1),
            'DD/MM/YYYY')
            EXPIRY_DATE,
         FN_GET_TOT_PRINDEBIT (ACNTS_INTERNAL_ACNUM, 1) PRIN_DEBIT
    FROM ACNTS, IACLINK, MBRN
   WHERE     ACNTS_ENTITY_NUM = 1
         AND ACNTS_INTERNAL_ACNUM = IACLINK_INTERNAL_ACNUM
         AND ACNTS_BRN_CODE = IACLINK_BRN_CODE
         AND ACNTS_PROD_CODE = IACLINK_PROD_CODE
         AND IACLINK_ENTITY_NUM = 1
         AND ACNTS_PROD_CODE = 2546
         AND ACNTS_CLOSURE_DATE IS NULL
         AND MBRN_ENTITY_NUM = 1
         AND MBRN_CODE = ACNTS_BRN_CODE
ORDER BY MBRN_CODE, IACLINK_ACTUAL_ACNUM