UPDATE ACNTS AC
   SET AC.ACNTS_MMB_INT_ACCR_UPTO = trunc(sysdate-1),
       AC.ACNTS_INT_ACCR_UPTO =trunc(sysdate-1)
 WHERE     AC.ACNTS_ENTITY_NUM = 1
       AND AC.ACNTS_INTERNAL_ACNUM IN
              (SELECT IACLINK_INTERNAL_ACNUM
                 FROM IACLINK IA
                WHERE     IA.IACLINK_ENTITY_NUM = 1
                      AND IA.IACLINK_ACTUAL_ACNUM IN ('3607935023404' 
));

UPDATE LOANACNTS LON
   SET LON.LNACNT_INT_ACCR_UPTO =  trunc(sysdate-1),
       LON.LNACNT_INT_APPLIED_UPTO_DATE =  trunc(sysdate-1)
 WHERE     LON.LNACNT_ENTITY_NUM = 1
       AND LON.LNACNT_INTERNAL_ACNUM IN
              (SELECT IA.IACLINK_INTERNAL_ACNUM
                 FROM IACLINK IA
                WHERE     IA.IACLINK_ENTITY_NUM = 1
                      AND IA.IACLINK_ACTUAL_ACNUM IN ('3607935023404' 
));


--front end :ELNACIAIPUPD