BEGIN
   FOR IDX
      IN (SELECT I.IACLINK_INTERNAL_ACNUM,
                 ACC4.EFF_DATE,
                 I.IACLINK_CIF_NUMBER
            FROM ACC4, IACLINK I
           WHERE ACC4.ACC_NO = I.IACLINK_ACTUAL_ACNUM)
   LOOP
      UPDATE LNACRSHDTL A
         SET A.LNACRSHDTL_EFF_DATE = IDX.EFF_DATE
       WHERE     A.LNACRSHDTL_INTERNAL_ACNUM = IDX.IACLINK_INTERNAL_ACNUM
             AND A.LNACRSHDTL_ENTITY_NUM = 1;

      UPDATE LNACRSHIST B
         SET B.LNACRSH_EFF_DATE = IDX.EFF_DATE
       WHERE     B.LNACRSH_INTERNAL_ACNUM = IDX.IACLINK_INTERNAL_ACNUM
             AND B.LNACRSH_ENTITY_NUM = 1;

      UPDATE LNACRS C
         SET C.LNACRS_LATEST_EFF_DATE = IDX.EFF_DATE
       WHERE     C.LNACRS_INTERNAL_ACNUM = IDX.IACLINK_INTERNAL_ACNUM
             AND C.LNACRS_ENTITY_NUM = 1;

      UPDATE LNACDISB D
         SET D.LNACDISB_DISB_ON = IDX.EFF_DATE
       WHERE     D.LNACDISB_INTERNAL_ACNUM = IDX.IACLINK_INTERNAL_ACNUM
             AND D.LNACDISB_ENTITY_NUM = 1;

      UPDATE LNACDSDTL E
         SET E.LNACDSDTL_DISB_DATE = IDX.EFF_DATE
       WHERE     E.LNACDSDTL_INTERNAL_ACNUM = IDX.IACLINK_INTERNAL_ACNUM
             AND E.LNACDSDTL_ENTITY_NUM = 1;

      UPDATE LNACDSDTLHIST F
         SET F.LNACDSDTLH_EFF_DATE = IDX.EFF_DATE
       WHERE     F.LNACDSDTLH_INTERNAL_ACNUM = IDX.IACLINK_INTERNAL_ACNUM
             AND F.LNACDSDTLH_ENTITY_NUM = 1;

      UPDATE LIMITLINE G
         SET G.LMTLINE_LIMIT_EFF_DATE = IDX.EFF_DATE,
             G.LMTLINE_DATE_OF_SANCTION = IDX.EFF_DATE
       WHERE     G.LMTLINE_CLIENT_CODE = IDX.IACLINK_CIF_NUMBER
             AND G.LMTLINE_ENTITY_NUM = 1;

      UPDATE LIMITLINEHIST H
         SET H.LIMLNEHIST_EFF_DATE = IDX.EFF_DATE,
             H.LIMLNEHIST_DATE_OF_SANCTION = IDX.EFF_DATE
       WHERE     H.LIMLNEHIST_CLIENT_CODE = IDX.IACLINK_CIF_NUMBER
             AND H.LIMLNEHIST_ENTITY_NUM = 1;

      UPDATE ACNTS S
         SET S.ACNTS_OPENING_DATE = IDX.EFF_DATE
       WHERE     S.ACNTS_INTERNAL_ACNUM = IDX.IACLINK_INTERNAL_ACNUM
             AND S.ACNTS_ENTITY_NUM = 1;
   END LOOP;
END;