SELECT 1 VOUTURE_NUMBER,
    TRANADV_BRN_CODE   BRANCH_CODE,
       0 DEBIT_AC_NUMBER,
      IACLINK_INTERNAL_ACNUM CREDIT_AC_NUMBER,
      'L' PRODUCT_TYPE,
      'P' LOAN_TRAN_ACTION,
      0 DEBIT_GL_NUMBER,
      0 CREDIT_GL_NUMBER,
      0 DEBIT_AMOUNT,
      AMOUNT CREDIT_AMOUNT,
      NULL BATCH_NUMBER,
      '' NARATION
FROM(SELECT A.TRANADV_BRN_CODE,IACLINK_INTERNAL_ACNUM,(ACC3.PRIN_BAL+A.TRANADV_PRIN_AC_AMT)AMOUNT,ACC3.PRIN_BAL,TRANADV_PRIN_AC_AMT
FROM  ACC3,IACLINK I,TRAN2015 T,TRANADV2015 A
WHERE ACC3.ACC_NO=I.IACLINK_ACTUAL_ACNUM
AND I.IACLINK_INTERNAL_ACNUM=T.TRAN_INTERNAL_ACNUM
AND T.TRAN_BRN_CODE=A.TRANADV_BRN_CODE
AND T.TRAN_BATCH_NUMBER=A.TRANADV_BATCH_NUMBER
AND T.TRAN_BATCH_SL_NUM=A.TRANADV_BATCH_SL_NUM
AND T.TRAN_DATE_OF_TRAN='07-MAY-2015' 
AND A.TRANADV_DATE_OF_TRAN='07-MAY-2015'
AND T.TRAN_BRN_CODE=3087
AND A.TRANADV_BRN_CODE=3087
AND I.IACLINK_ENTITY_NUM=1
AND T.TRAN_ENTITY_NUM=1
AND A.TRANADV_ENTITY_NUM=1) T;
================================
SELECT 1 VOUTURE_NUMBER,
    TRANADV_BRN_CODE   BRANCH_CODE,
       IACLINK_INTERNAL_ACNUM DEBIT_AC_NUMBER,
      0 CREDIT_AC_NUMBER,
      'L' PRODUCT_TYPE,
      'I' LOAN_TRAN_ACTION,
      0 DEBIT_GL_NUMBER,
      0 CREDIT_GL_NUMBER,
      AMOUNT DEBIT_AMOUNT,
      0 CREDIT_AMOUNT,
      NULL BATCH_NUMBER,
      '' NARATION
FROM(SELECT A.TRANADV_BRN_CODE,IACLINK_INTERNAL_ACNUM,(ACC3.PRIN_BAL+A.TRANADV_PRIN_AC_AMT)AMOUNT,ACC3.PRIN_BAL,TRANADV_PRIN_AC_AMT
FROM  ACC3,IACLINK I,TRAN2015 T,TRANADV2015 A
WHERE ACC3.ACC_NO=I.IACLINK_ACTUAL_ACNUM
AND I.IACLINK_INTERNAL_ACNUM=T.TRAN_INTERNAL_ACNUM
AND T.TRAN_BRN_CODE=A.TRANADV_BRN_CODE
AND T.TRAN_BATCH_NUMBER=A.TRANADV_BATCH_NUMBER
AND T.TRAN_BATCH_SL_NUM=A.TRANADV_BATCH_SL_NUM
AND T.TRAN_DATE_OF_TRAN='07-MAY-2015'
AND A.TRANADV_DATE_OF_TRAN='07-MAY-2015'
AND T.TRAN_BRN_CODE=3087
AND A.TRANADV_BRN_CODE=3087
AND I.IACLINK_ENTITY_NUM=1
AND T.TRAN_ENTITY_NUM=1
AND A.TRANADV_ENTITY_NUM=1) T;