SELECT A.ACNTS_INTERNAL_ACNUM,
       SUM(L.LNREPAY_AMT_RECOVERED) TOTAL_RECOVERED,
       SUM(L.LNREPAY_PRIN_ACT_RECOV) TOTAL_PRIN_RECOVERED,
       SUM(L.LNREPAY_INT_ACT_RECOV) TOTAL_IN_REOVERED,
       SUM(L.LNREPAY_CHG_ACT_RECOV) TOTAL_CHARGE_RECOVERED
  FROM LNREPAY L, ACNTS A, LNPRODPM LP
 WHERE A.ACNTS_ENTITY_NUM = 1
   AND L.LNREPAY_ENTITY_NUM = 1
   AND A.ACNTS_INTERNAL_ACNUM = L.LNREPAY_INTERNAL_ACNUM
   AND A.ACNTS_PROD_CODE = LP.LNPRD_PROD_CODE
   AND LP.LNPRD_TERM_LOAN = 1
   AND L.LNREPAY_ENTRY_DATE BETWEEN '01-JAN-2018' AND '31-JAN-2018'
  -- AND A.ACNTS_BRN_CODE = 56101
 GROUP BY A.ACNTS_INTERNAL_ACNUM;

-----------------------------------------------------------------------CONTINOUS-----------------------
SELECT  A.ACNTS_INTERNAL_ACNUM,
       SUM(TV.TRANADV_PRIN_BC_AMT) PRIN_AMT,
       SUM(TV.TRANADV_INTRD_BC_AMT) INTEREST_AMT,
       SUM(TV.TRANADV_CHARGE_BC_AMT)
  FROM TRAN2018 T, TRANADV2018 TV, PRODUCTS P, ACNTS A
 WHERE T.TRAN_ENTITY_NUM = 1
   AND TV.TRANADV_ENTITY_NUM = 1
   AND A.ACNTS_ENTITY_NUM = 1
   AND A.ACNTS_INTERNAL_ACNUM = T.TRAN_INTERNAL_ACNUM
   AND T.TRAN_BRN_CODE = TV.TRANADV_BRN_CODE
   AND T.TRAN_DATE_OF_TRAN = TV.TRANADV_DATE_OF_TRAN
   AND T.TRAN_BATCH_NUMBER = TV.TRANADV_BATCH_NUMBER
   AND T.TRAN_BATCH_SL_NUM = TV.TRANADV_BATCH_SL_NUM
   AND T.TRAN_DB_CR_FLG = 'C'
   AND A.ACNTS_PROD_CODE = P.PRODUCT_CODE
   AND P.PRODUCT_FOR_LOANS = 1
   AND P.PRODUCT_FOR_RUN_ACS = 1
   AND A.ACNTS_BRN_CODE = 16121
   AND T.TRAN_DATE_OF_TRAN BETWEEN '01-JAN-2018' AND '31-JAN-2018'
   GROUP BY A.ACNTS_INTERNAL_ACNUM ;