SANC_DT,  ---- LIMITLINE, LIMITLINEHIST
EFFECTIVE_DATE, ---- LIMITLINE, LIMITLINEHIST
SANC_AMT, ---- LIMITLINE, LIMITLINEHIST
EXP_DT, ---- LIMITLINE, LIMITLINEHIST
DISB_DATE, --- LNACDISB, LNACDSDTL, LNACDSDTLHIST
DISBURSE_AMT,  --- LNACDISB, LNACDSDTL, LNACDSDTLHIST , LLACNTOS (Current_disb_maid(last column)) negative amount
NO_INT, ---- LNACRSDTL, LNACRSHDTL
INT_SIZE, ----  LNACRSDTL, LNACRSHDTL
INT_PERIOD, ----  LNACRSDTL, LNACRSHDTL
LNACRSHDTL_TOT_REPAY_AMT =  INT_SIZE * NO_INT --  LNACRSDTL, LNACRSHDTL
LNACRS_REPH_ON_AMT =  INT_SIZE * NO_INT -- LNACRS, LNACRSHIST 
TOTALINTDR_PRE_MIG, -- LNTOTINTDBMIG




BEGIN

DELETE FROM LNACDISB
     WHERE (LNACDISB_INTERNAL_ACNUM, LNACDISB_DISB_ON) IN
              (SELECT LNACDISB_INTERNAL_ACNUM, LNACDISB_DISB_ON
                 FROM BACKUPTABLE.TEMP_LOAN_DATA_UPDATE, IACLINK, LNACDISB L
                WHERE     IACLINK_ACTUAL_ACNUM = ACNO
                      AND IACLINK_ENTITY_NUM = 1
                      AND LNACDISB_INTERNAL_ACNUM = IACLINK_INTERNAL_ACNUM
                      AND LNACDISB_ENTITY_NUM = 1
                      AND LNACDISB_AUTH_BY IS NOT NULL
                     -- AND LNACDISB_INTERNAL_ACNUM = 14422200009659
                     and nvl(DISBURSE_AMT,0)<>0
                      AND LNACDISB_DISB_ON <>
                             (SELECT MIN (LNACDISB_DISB_ON)
                                FROM LNACDISB LL
                               WHERE LL.LNACDISB_INTERNAL_ACNUM =
                                        L.LNACDISB_INTERNAL_ACNUM));
                                        
                                        DELETE FROM LNACDSDTL
     WHERE (LNACDSDTL_INTERNAL_ACNUM, LNACDSDTL_DISB_DATE) IN
              (SELECT LNACDSDTL_INTERNAL_ACNUM, LNACDSDTL_DISB_DATE
                 FROM BACKUPTABLE.TEMP_LOAN_DATA_UPDATE, IACLINK, LNACDSDTL L
                WHERE     IACLINK_ACTUAL_ACNUM = ACNO
                      AND IACLINK_ENTITY_NUM = 1
                      AND LNACDSDTL_INTERNAL_ACNUM = IACLINK_INTERNAL_ACNUM
                      AND LNACDSDTL_ENTITY_NUM = 1
                     -- AND LNACDISB_AUTH_BY IS NOT NULL
                     -- AND LNACDISB_INTERNAL_ACNUM = 14422200009659
                      and nvl(DISBURSE_AMT,0)<>0
                      AND LNACDSDTL_DISB_DATE <>
                             (SELECT MIN (LNACDSDTL_DISB_DATE)
                                FROM LNACDSDTL LL
                               WHERE LL.LNACDSDTL_INTERNAL_ACNUM =
                                        L.LNACDSDTL_INTERNAL_ACNUM));
                                        
                                        DELETE FROM LNACDSDTLHIST
     WHERE (LNACDSDTLH_INTERNAL_ACNUM, LNACDSDTLH_DISB_DATE) IN
              (SELECT LNACDSDTLH_INTERNAL_ACNUM, LNACDSDTLH_DISB_DATE
                 FROM BACKUPTABLE.TEMP_LOAN_DATA_UPDATE, IACLINK, LNACDSDTLHIST L
                WHERE     IACLINK_ACTUAL_ACNUM = ACNO
                      AND IACLINK_ENTITY_NUM = 1
                      AND LNACDSDTLH_INTERNAL_ACNUM = IACLINK_INTERNAL_ACNUM
                      AND LNACDSDTLH_ENTITY_NUM = 1
                       and nvl(DISBURSE_AMT,0)<>0
                     -- AND LNACDISB_AUTH_BY IS NOT NULL
                     -- AND LNACDISB_INTERNAL_ACNUM = 14422200009659
                      AND LNACDSDTLH_DISB_DATE <>
                             (SELECT MIN (LNACDSDTLH_DISB_DATE)
                                FROM LNACDSDTLHIST LL
                               WHERE LL.LNACDSDTLH_INTERNAL_ACNUM =
                                        L.LNACDSDTLH_INTERNAL_ACNUM));
                                        
   FOR IDX
      IN (SELECT ACNTS_INTERNAL_ACNUM,
                 AA.*,
                 LMTLINE_CLIENT_CODE,
                 LMTLINE_NUM,
                 LMTLINE_LIMIT_EFF_DATE
            FROM BACKUPTABLE.TEMP_LOAN_DATA_UPDATE AA,
                 IACLINK,
                 ACNTS,
                 LOANACNTS,
                 ACASLLDTL,
                 LIMITLINE
           WHERE     AA.ACNO = IACLINK_ACTUAL_ACNUM
                 AND IACLINK_INTERNAL_ACNUM = ACNTS_INTERNAL_ACNUM
                 AND ACNTS_INTERNAL_ACNUM = LNACNT_INTERNAL_ACNUM
                 AND ACNTS_INTERNAL_ACNUM = ACASLLDTL_INTERNAL_ACNUM
                 AND ACASLLDTL_CLIENT_NUM = LMTLINE_CLIENT_CODE
                 AND ACASLLDTL_LIMIT_LINE_NUM = LMTLINE_NUM
                  and nvl(DISBURSE_AMT,0)<>0
                 AND ACASLLDTL_ENTITY_NUM = 1
                 AND LNACNT_ENTITY_NUM = 1
                 AND LMTLINE_ENTITY_NUM = 1
                 AND ACNTS_ENTITY_NUM = 1
                 AND IACLINK_ENTITY_NUM = 1)
   LOOP
      --sanction date

      UPDATE LIMITLINE
         SET LMTLINE_DATE_OF_SANCTION = IDX.SANC_DT,
            -- LMTLINE_LIMIT_EFF_DATE = IDX.EFFECTIVE_DATE,
             LMTLINE_SANCTION_AMT = IDX.SANC_AMT,
             LMTLINE_LIMIT_EXPIRY_DATE = IDX.EXP_DT
       WHERE     LMTLINE_NUM = IDX.LMTLINE_NUM
             AND LMTLINE_CLIENT_CODE = IDX.LMTLINE_CLIENT_CODE
             AND LMTLINE_ENTITY_NUM = 1;

      UPDATE LIMITLINEHIST
         SET LIMLNEHIST_DATE_OF_SANCTION = IDX.SANC_DT,
            -- LIMLNEHIST_EFF_DATE = IDX.EFFECTIVE_DATE,
             LIMLNEHIST_SANCTION_AMT = IDX.SANC_AMT,
             LIMLNEHIST_LIMIT_EXPIRY_DATE = IDX.EXP_DT
       WHERE     LIMLNEHIST_ENTITY_NUM = 1
             AND LIMLNEHIST_CLIENT_CODE = IDX.LMTLINE_CLIENT_CODE
             AND LIMLNEHIST_LIMIT_LINE_NUM = IDX.LMTLINE_NUM;

      
      
      UPDATE LLACNTOS 
        SET LLACNTOS_LIMIT_CURR_DISB_MADE= IDX.DISBURSE_AMT * -1
      WHERE LLACNTOS_ENTITY_NUM=1
             AND LLACNTOS_LIMIT_LINE_NUM= IDX.LMTLINE_NUM
             AND LLACNTOS_CLIENT_CODE= IDX.LMTLINE_CLIENT_CODE;
      
      
      --disburse date

      UPDATE LNACDISB
         SET LNACDISB_DISB_ON = IDX.DISB_DATE,
             LNACDISB_DISB_AMT = IDX.DISBURSE_AMT
       WHERE     LNACDISB_ENTITY_NUM = 1
             AND LNACDISB_INTERNAL_ACNUM = IDX.ACNTS_INTERNAL_ACNUM;

      UPDATE LNACDSDTL
         SET LNACDSDTL_DISB_DATE = IDX.DISB_DATE,
             LNACDSDTL_DISB_AMOUNT = IDX.DISBURSE_AMT
       WHERE     LNACDSDTL_ENTITY_NUM = 1
             AND LNACDSDTL_INTERNAL_ACNUM = IDX.ACNTS_INTERNAL_ACNUM;

      UPDATE LNACDSDTLHIST
         SET LNACDSDTLH_DISB_DATE = IDX.DISB_DATE,
             LNACDSDTLH_DISB_AMOUNT = IDX.DISBURSE_AMT
       WHERE     LNACDSDTLH_ENTITY_NUM = 1
             AND LNACDSDTLH_INTERNAL_ACNUM = IDX.ACNTS_INTERNAL_ACNUM;


      --NO_INT

      UPDATE LNACRSDTL
         SET LNACRSDTL_NUM_OF_INSTALLMENT = IDX.NO_INT,
             LNACRSDTL_REPAY_AMT = IDX.INT_SIZE,
             LNACRSDTL_REPAY_FREQ = IDX.INT_PERIOD,
             LNACRSDTL_TOT_REPAY_AMT = IDX.INT_SIZE * IDX.NO_INT
       WHERE     LNACRSDTL_ENTITY_NUM = 1
             AND LNACRSDTL_INTERNAL_ACNUM = IDX.ACNTS_INTERNAL_ACNUM;

      UPDATE LNACRSHDTL
         SET LNACRSHDTL_NUM_OF_INSTALLMENT = IDX.NO_INT,
             LNACRSHDTL_REPAY_AMT = IDX.INT_SIZE,
             LNACRSHDTL_REPAY_FREQ = IDX.INT_PERIOD,
             LNACRSHDTL_TOT_REPAY_AMT = IDX.INT_SIZE * IDX.NO_INT
       WHERE     LNACRSHDTL_ENTITY_NUM = 1
             AND LNACRSHDTL_INTERNAL_ACNUM = IDX.ACNTS_INTERNAL_ACNUM;

      UPDATE LNACRS
         SET LNACRS_REPH_ON_AMT = IDX.INT_SIZE * IDX.NO_INT
       WHERE     LNACRS_ENTITY_NUM = 1
             AND LNACRS_INTERNAL_ACNUM = IDX.ACNTS_INTERNAL_ACNUM;

      UPDATE LNACRSHIST
         SET LNACRSH_REPH_ON_AMT = IDX.INT_SIZE * IDX.NO_INT
       WHERE     LNACRSH_ENTITY_NUM = 1
             AND LNACRSH_INTERNAL_ACNUM = IDX.ACNTS_INTERNAL_ACNUM;

      UPDATE LNTOTINTDBMIG
         SET LNTOTINTDB_TOT_INT_DB_AMT = IDX.TOTALINTDR_PRE_MIG
       WHERE     LNTOTINTDB_ENTITY_NUM = 1
             AND LNTOTINTDB_INTERNAL_ACNUM = IDX.ACNTS_INTERNAL_ACNUM;
   END LOOP;
   
   commit;
END;