 --------LOAN ACCRUAL UPDATE---------------------------
BEGIN
   FOR IDX
      IN (SELECT I.IACLINK_INTERNAL_ACNUM, A.TOTAL_BAL
            FROM IACLINK I, ACC A, ACNTS AA
           WHERE     I.IACLINK_ACTUAL_ACNUM = A.ACC_NO
                 AND I.IACLINK_INTERNAL_ACNUM = AA.ACNTS_INTERNAL_ACNUM
                 AND I.IACLINK_ENTITY_NUM = 1
                 AND AA.ACNTS_ENTITY_NUM = 1
                 AND AA.ACNTS_CLOSURE_DATE IS NULL
                 AND I.IACLINK_INTERNAL_ACNUM NOT IN
                        (SELECT L.LOANIA_ACNT_NUM
                           FROM LOANIA L))
   LOOP
      UPDATE LOANIAMRR
         SET LOANIAMRR_TOTAL_NEW_INT_AMT = IDX.TOTAL_BAL,
             LOANIAMRR_INT_AMT = IDX.TOTAL_BAL,
             LOANIAMRR_INT_AMT_RND = IDX.TOTAL_BAL
       WHERE     LOANIAMRR_ACCRUAL_DATE = '27-OCT-2016' --MIG DATE
             AND LOANIAMRR_VALUE_DATE = '27-OCT-2016'
             AND LOANIAMRR_BRN_CODE = 35014 ----BRANCH CODE
             AND LOANIAMRR_ACNT_NUM = IDX.IACLINK_INTERNAL_ACNUM;


      UPDATE LOANIAMRRDTL
         SET LOANIAMRRDTL_UPTO_AMT = IDX.TOTAL_BAL,
             LOANIAMRRDTL_INT_AMT = IDX.TOTAL_BAL,
             LOANIAMRRDTL_INT_AMT_RND = IDX.TOTAL_BAL
       WHERE     LOANIAMRRDTL_ACCRUAL_DATE = '27-OCT-2016' ---MIG DATE
             AND LOANIAMRRDTL_VALUE_DATE = '27-OCT-2016' ---MIG DATE
             AND LOANIAMRRDTL_BRN_CODE = 35014 ----BRANCH CODE
             AND LOANIAMRRDTL_ACNT_NUM = IDX.IACLINK_INTERNAL_ACNUM;
   END LOOP;
END;
-------------------VOUCHER PREPARATION------------------------------
INSERT INTO MANUAL_TRAN
  SELECT  1 SERIAL_NUMBER,
         ACNTS_BRN_CODE BRANCH_CODE,
         NULL PRODUCT_CODE,
         0 DEBIT_AC_NUMBER,
         0 CREDIT_AC_NUMBER,
         P.LNPRDAC_INT_ACCR_GL DEBIT_GL_NUMBER,
         P.LNPRDAC_INT_INCOME_GL CREDIT_GL_NUMBER,
         SUM (ABS (T.CURR_PROVI-T.ACCTUAL_PROVI)) DEBIT_AMOUNT,
         SUM (ABS (T.CURR_PROVI-T.ACCTUAL_PROVI)) CREDIT_AMOUNT,
         NULL BATCH_NUMBER,
         NULL ACNTS_CLOSER_DATE,
         'Migration data correction|Mail: July 25, 2017 11:50AM' NARATION,
         NULL CONTRACT_NUMBER,
         NULL INT_CHECK_PREF,
         NULL INT_CHECK_NUM,
         NULL INST_DATE,
         NULL BASE_CURR_CODE,
         NULL BASE_CURR_CONV_RATE,
         NULL TRAN_BASE_CURR_EQ_AMT
    FROM ACC4 T,
         IACLINK I,
         ASSETCLSHIST,
         lnprodacpm p,
         acnts aa
   WHERE     I.IACLINK_ACTUAL_ACNUM = T.ACC_NO
         AND IACLINK_INTERNAL_ACNUM = ASSETCLSH_INTERNAL_ACNUM
         AND ASSETCLSH_AUTH_BY = 'MIG'
         AND ASSETCLSH_ENTITY_NUM = 1
         AND AA.ACNTS_PROD_CODE = P.LNPRDAC_PROD_CODE
         AND ASSETCLSH_ASSET_CODE IN ('UC', 'SM')
         AND AA.ACNTS_ENTITY_NUM = 1
         AND AA.ACNTS_CLOSURE_DATE IS NULL
         AND I.IACLINK_INTERNAL_ACNUM = AA.ACNTS_INTERNAL_ACNUM
         AND I.IACLINK_INTERNAL_ACNUM NOT IN (SELECT L.LOANIA_ACNT_NUM
                                                FROM loania l)
GROUP BY AA.ACNTS_PROD_CODE,
         P.LNPRDAC_INT_ACCR_GL,
         P.LNPRDAC_INT_INCOME_GL,
         ACNTS_BRN_CODE

-------------- ACCROUAL INSERT ---------------------

CREATE TABLE TEMP_LOANIA
(
  LOANIA_BRN_CODE              NUMBER(6),
  LOANIA_ACNT_NUM              VARCHAR2(15 BYTE),
  LOANIA_VALUE_DATE            DATE,
  LOANIA_ACCRUAL_DATE          DATE,
  LOANIA_ACNT_CURR             VARCHAR2(3 BYTE),
  LOANIA_ACNT_BAL              NUMBER(18,3)     DEFAULT 0,
  LOANIA_INT_ON_AMT            NUMBER(18,3)     DEFAULT 0,
  LOANIA_TOTAL_NEW_OD_INT_AMT  NUMBER(18,9)     DEFAULT 0,
  LOANIA_INT_RATE              NUMBER(8,5)      DEFAULT 0,
  LOANIA_OD_INT_RATE           NUMBER(8,5)      DEFAULT 0,
  LOANIA_LIMIT                 NUMBER(18,3)     DEFAULT 0,
  LOANIA_DP                    NUMBER(18,3)     DEFAULT 0,
  LOANIA_NPA_STATUS            NUMBER(1)        DEFAULT 0,
  LOANIA_NPA_AMT               NUMBER(18,3)     DEFAULT 0
)
-------LOAN ACCRUAL INSERT STATEMENT ----------------------------------------
INSERT INTO LOANIAMRR
SELECT 1 LOANIA_ENTITY_NUM,
       T.LOANIA_BRN_CODE LOANIA_BRN_CODE,
       I.IACLINK_INTERNAL_ACNUM LOANIA_ACNT_NUM,
       T.LOANIA_VALUE_DATE LOANIA_VALUE_DATE,
       T.LOANIA_ACCRUAL_DATE LOANIA_ACCRUAL_DATE,
       NULL LOANIA_PREV_ACCR_DATE,
       T.LOANIA_ACNT_CURR LOANIA_ACNT_CURR,
       NULL LOANIA_ACNT_BAL,
       (-1) * ABS (T.LOANIA_INT_ON_AMT) LOANIA_TOTAL_NEW_INT_AMT,
       0.000 LOANIA_INT_ON_AMT,
       0.000 LOANIA_OD_PORTION,
       0 LOANIA_TOTAL_NEW_OD_INT_AMT,
       T.LOANIA_INT_RATE LOANIA_INT_RATE,
       0 LOANIA_SLAB_AMT,
       0 LOANIA_OD_INT_RATE,
       0 LOANIA_LIMIT,
       0 LOANIA_DP,
       (-1) * ABS (T.LOANIA_INT_ON_AMT) LOANIA_INT_AMT,
       (-1) * ABS (T.LOANIA_INT_ON_AMT) LOANIA_INT_AMT_RND,
       0 LOANIA_OD_INT_AMT,
       0 LOANIA_OD_INT_AMT_RND,
       CASE
          WHEN ASSETCLSH_ASSET_CODE = 'UC' THEN 0
          WHEN ASSETCLSH_ASSET_CODE = 'SM' THEN 0
          ELSE 1
       END
          LOANIA_NPA_STATUS,
       0 LOANIA_NPA_AMT,
       0 LOANIA_NPA_INT_POSTED_AMT,
       0 LOANIA_ARR_INT_AMT
  FROM TEMP_LOANIA T, IACLINK I, ASSETCLSHIST
 WHERE     I.IACLINK_ACTUAL_ACNUM = T.LOANIA_ACNT_NUM
       AND IACLINK_INTERNAL_ACNUM = ASSETCLSH_INTERNAL_ACNUM
       AND ASSETCLSH_AUTH_BY = 'MIG'
       AND ASSETCLSH_ENTITY_NUM = 1;
------------------------------------------------------------- 
 INSERT INTO LOANIAMRRDTL 
 SELECT 1 LOANIADTL_ENTITY_NUM,
       T.LOANIA_BRN_CODE LOANIADTL_BRN_CODE,
       I.IACLINK_INTERNAL_ACNUM LOANIADTL_ACNT_NUM,
       T.LOANIA_VALUE_DATE LOANIADTL_VALUE_DATE,
       T.LOANIA_ACCRUAL_DATE LOANIADTL_ACCRUAL_DATE,
       1 LOANIADTL_SL_NUM,
       T.LOANIA_INT_RATE LOANIADTL_INT_RATE,
       (-1) * ABS (T.LOANIA_INT_ON_AMT) LOANIADTL_UPTO_AMT,
       (-1) * ABS (T.LOANIA_INT_ON_AMT) LOANIADTL_INT_AMT,
       (-1) * ABS (T.LOANIA_INT_ON_AMT) LOANIADTL_INT_AMT_RND
  FROM TEMP_LOANIA T, IACLINK I
 WHERE I.IACLINK_ACTUAL_ACNUM = T.LOANIA_ACNT_NUM;
  

-------VOUCHER PREPARATION------------------------
   INSERT INTO MANUAL_TRAN
  SELECT 1 SERIAL_NUMBER,
         ACNTS_BRN_CODE BRANCH_CODE,
         NULL PRODUCT_CODE,
         0 DEBIT_AC_NUMBER,
         0 CREDIT_AC_NUMBER,
         P.LNPRDAC_INT_ACCR_GL DEBIT_GL_NUMBER,
         P.LNPRDAC_INT_INCOME_GL CREDIT_GL_NUMBER,
         SUM (ABS (LOANIA_INT_ON_AMT)) DEBIT_AMOUNT,
         SUM (ABS (LOANIA_INT_ON_AMT)) CREDIT_AMOUNT,
         NULL BATCH_NUMBER,
         NULL ACNTS_CLOSER_DATE,
         '' NARATION,
         NULL CONTRACT_NUMBER,
         NULL INT_CHECK_PREF,
         NULL INT_CHECK_NUM,
         NULL INST_DATE,
         NULL BASE_CURR_CODE,
         NULL BASE_CURR_CONV_RATE,
         NULL TRAN_BASE_CURR_EQ_AMT
    FROM TEMP_LOANIA T,
         IACLINK I,
         ASSETCLSHIST,
         lnprodacpm p,
         acnts aa
   WHERE     I.IACLINK_ACTUAL_ACNUM = T.LOANIA_ACNT_NUM
         AND IACLINK_INTERNAL_ACNUM = ASSETCLSH_INTERNAL_ACNUM
         AND ASSETCLSH_AUTH_BY = 'MIG'
         AND ASSETCLSH_ENTITY_NUM = 1
         AND AA.ACNTS_PROD_CODE = P.LNPRDAC_PROD_CODE
         AND ASSETCLSH_ASSET_CODE IN ('UC', 'SM')
         AND AA.ACNTS_ENTITY_NUM = 1
         AND AA.ACNTS_CLOSURE_DATE IS NULL
         AND I.IACLINK_INTERNAL_ACNUM = AA.ACNTS_INTERNAL_ACNUM
         AND I.IACLINK_INTERNAL_ACNUM NOT IN (SELECT L.LOANIA_ACNT_NUM
                                                FROM loania l)
GROUP BY AA.ACNTS_PROD_CODE,
         P.LNPRDAC_INT_ACCR_GL,
         P.LNPRDAC_INT_INCOME_GL,
         ACNTS_BRN_CODE
