----interest reverse from mirror------------------
     ----INSERT DATA ON INTRATE_UPDATE------------------

BEGIN
   FOR IDX IN (SELECT T.ACCNUMBER ACCOUNT_NUMBER, T.EFFECTIVE_DATE, INT_RATE
                 FROM INTRATE_UPDATE T)
   LOOP
      SP_LOAN_DATA_CORRECTION_MANUAL (1,
                                      IDX.ACCOUNT_NUMBER,
                                      idx.INT_RATE,                ---INT RATE
                                      IDX.EFFECTIVE_DATE);
   END LOOP;
END;

--------FOR VOUCHER -------------

DELETE FROM AUTOPOST_TRAN_TEMP;

INSERT INTO AUTOPOST_TRAN_TEMP
     SELECT /*+ PARALLEL( 8) */
           1 BATCH_SL,
            1 LEG_SL,
            NULL TRAN_DATE,
            NULL VALUE_DATE,
            NULL SUPP_TRAN,
            IACLINK_BRN_CODE BRN_CODE,
            IACLINK_BRN_CODE ACING_BRN_CODE,
            'D' DR_CR,
            LNPRDAC_INT_INCOME_GL GLACC_CODE,
            NULL INT_AC_NO,
            NULL CONT_NO,
            'BDT' CURR_CODE,
            SUM (ABS (LOANIAMRR_INT_AMT_RND)) AC_AMOUNT,
            :NARRATION,null,null,null
       FROM INTRATE_UPDATE T,
            IACLINK I,
            LOANIAMRR,
            LNPRODACPM P
      WHERE     I.IACLINK_ACTUAL_ACNUM = T.ACCNUMBER
            AND LOANIAMRR_ENTITY_NUM = 1
            AND IACLINK_ENTITY_NUM = 1
            AND I.IACLINK_PROD_CODE = P.LNPRDAC_PROD_CODE
            AND LOANIAMRR_BRN_CODE = IACLINK_BRN_CODE
            AND LOANIAMRR_ACNT_NUM = IACLINK_INTERNAL_ACNUM
             AND LOANIAMRR_NPA_STATUS = 0
            AND LOANIAMRR_VALUE_DATE >= EFFECTIVE_DATE
   GROUP BY IACLINK_BRN_CODE, P.LNPRDAC_INT_INCOME_GL
   UNION ALL
     SELECT /*+ PARALLEL( 8) */
           1 BATCH_SL,
            1 LEG_SL,
            NULL TRAN_DATE,
            NULL VALUE_DATE,
            NULL SUPP_TRAN,
            IACLINK_BRN_CODE BRN_CODE,
            IACLINK_BRN_CODE ACING_BRN_CODE,
            'C' DR_CR,
            LNPRDAC_INT_ACCR_GL GLACC_CODE,
            NULL INT_AC_NO,
            NULL CONT_NO,
            'BDT' CURR_CODE,
            SUM (ABS (LOANIAMRR_INT_AMT_RND)) AC_AMOUNT,
            :NARRATION,null,null,null
       FROM INTRATE_UPDATE T,
            IACLINK I,
            LOANIAMRR,
            LNPRODACPM P
      WHERE     I.IACLINK_ACTUAL_ACNUM = T.ACCNUMBER
            AND LOANIAMRR_ENTITY_NUM = 1
            AND IACLINK_ENTITY_NUM = 1
            AND I.IACLINK_PROD_CODE = P.LNPRDAC_PROD_CODE
            AND LOANIAMRR_BRN_CODE = IACLINK_BRN_CODE
            AND LOANIAMRR_ACNT_NUM = IACLINK_INTERNAL_ACNUM
            AND LOANIAMRR_NPA_STATUS = 0
            AND LOANIAMRR_VALUE_DATE >= EFFECTIVE_DATE
   GROUP BY IACLINK_BRN_CODE, P.LNPRDAC_INT_ACCR_GL;



---------------------------------FOR VOUCHER---------------------------------------------------

DELETE FROM AUTOPOST_TRAN;

INSERT INTO AUTOPOST_TRAN
   SELECT DENSE_RANK () OVER (ORDER BY BRN_CODE) BATCH_SL,
          ROW_NUMBER () OVER (PARTITION BY BRN_CODE ORDER BY BRN_CODE) LEG_SL,
          NULL TRAN_DATE,
          NULL VALUE_DATE,
          NULL SUPP_TRAN,
          BRN_CODE,
          ACING_BRN_CODE,
          DR_CR,
          GLACC_CODE,
          INT_AC_NO,
          CONT_NO,
          CURR_CODE,
          AC_AMOUNT,
          AC_AMOUNT BC_AMOUNT,
          NULL PRINCIPAL,
          NULL INTEREST,
          NULL CHARGE,
          NULL INST_PREFIX,
          NULL INST_NUM,
          NULL INST_DATE,
          NULL IBR_GL,
          NULL ORIG_RESP,
          NULL CONT_BRN_CODE,
          NULL ADV_NUM,
          NULL ADV_DATE,
          NULL IBR_CODE,
          NULL CAN_IBR_CODE,
          NARRATION LEG_NARRATION,
          NARRATION BATCH_NARRATION,
          'INTELECT' USER_ID,
          NULL TERMINAL_ID,
          NULL PROCESSED,
          NULL BATCH_NO,
          NULL ERR_MSG,
          NULL DEPT_CODE
     FROM AUTOPOST_TRAN_TEMP TT;

     EXEC SP_AUTO_SCRIPT_TRAN;

--------FOR ACCRUAL/MIRROR DELETE--------------

BEGIN
   FOR IDX
      IN (SELECT IACLINK_INTERNAL_ACNUM, T.EFFECTIVE_DATE
            FROM INTRATE_UPDATE T, IACLINK I
           WHERE     IACLINK_ENTITY_NUM = 1
                 AND I.IACLINK_ACTUAL_ACNUM = T.ACCNUMBER)
   LOOP
      UPDATE LOANACNTS
         SET LNACNT_RTMP_ACCURED_UPTO = NULL, LNACNT_RTMP_PROCESS_DATE = NULL
       WHERE     LNACNT_ENTITY_NUM = 1
             AND LNACNT_INTERNAL_ACNUM = IDX.IACLINK_INTERNAL_ACNUM;

      DELETE FROM LOANIADLY
            WHERE RTMPLNIA_ACNT_NUM = IDX.IACLINK_INTERNAL_ACNUM;

      DELETE FROM LOANIAMRR
            WHERE     LOANIAMRR_VALUE_DATE >= IDX.EFFECTIVE_DATE
                  AND LOANIAMRR_ENTITY_NUM = 1
                  AND LOANIAMRR_ACNT_NUM = IDX.IACLINK_INTERNAL_ACNUM;

      DELETE FROM LOANIAMRRDTL
            WHERE     LOANIAMRRDTL_VALUE_DATE >= IDX.EFFECTIVE_DATE
                  AND LOANIAMRRDTL_ENTITY_NUM = 1
                  AND LOANIAMRRDTL_ACNT_NUM = IDX.IACLINK_INTERNAL_ACNUM;
   END LOOP;
END;


-------------------accrual reverse from apply---------
/* Formatted on 6/19/2023 1:49:56 PM (QP5 v5.388) */
SELECT /*+ PARALLEL( 8) */
       LOANIAMRR_BRN_CODE,
       FACNO(1,LOANIAMRR_ACNT_NUM) ACCOUNT_NO,
       SUM (ABS (LOANIAMRR_INT_AMT_RND))     LOANIAMRR_INT_AMT_RND
  FROM INTRATE_UPDATE@dr  T,
       IACLINK@dr         I,
       LOANIAMRR@dr,
       LNPRODACPM@dr      P
 WHERE     I.IACLINK_ACTUAL_ACNUM = T.ACCNUMBER
       AND LOANIAMRR_ENTITY_NUM = 1
       AND IACLINK_ENTITY_NUM = 1
       AND I.IACLINK_PROD_CODE = P.LNPRDAC_PROD_CODE
       AND LOANIAMRR_BRN_CODE = IACLINK_BRN_CODE
       AND LOANIAMRR_ACNT_NUM = IACLINK_INTERNAL_ACNUM
       AND LOANIAMRR_NPA_STATUS = 0
        AND LOANIAMRR_VALUE_DATE > :EFFECTIVE_DATE
       GROUP BY LOANIAMRR_BRN_CODE,
       LOANIAMRR_ACNT_NUM
       ORDER BY LOANIAMRR_BRN_CODE,
       LOANIAMRR_ACNT_NUM;



  SELECT /*+ PARALLEL( 8) */
         LOANIA_BRN_CODE,
         facno (1, LOANIA_ACNT_NUM) ACCOUNT_NO,
         SUM (ABS (LOANIA_INT_AMT_RND))     LOANIA_INT_AMT_RND
    FROM INTRATE_UPDATE@dr T,
         IACLINK@dr       I,
         LOANIA@dr,
         LNPRODACPM@dr    P
   WHERE     I.IACLINK_ACTUAL_ACNUM = T.ACCNUMBER
         AND LOANIA_ENTITY_NUM = 1
         AND IACLINK_ENTITY_NUM = 1
         AND I.IACLINK_PROD_CODE = P.LNPRDAC_PROD_CODE
         AND LOANIA_BRN_CODE = IACLINK_BRN_CODE
         AND LOANIA_ACNT_NUM = IACLINK_INTERNAL_ACNUM
         AND LOANIA_VALUE_DATE BETWEEN '01-JAN-2023' AND '31-MAR-2023'
         AND LOANIA_NPA_STATUS = 0
         AND LOANIA_INT_AMT_RND <> 0
GROUP BY LOANIA_BRN_CODE, LOANIA_ACNT_NUM
ORDER BY LOANIA_ACNT_NUM;