1. SP_SAVINGS_CLIENT_CODE_CHANGE FOR SAVING
2. SP_LOAN_CLIENT_CODE_CHANGE FOR LOAN
---INSERT DATA INTO LOAN_CLIENT_CODE_CHANGE TABLE 

--RUN THE FOLLOWING SCRIPT
/* Formatted on 7/21/2019 1:16:21 PM (QP5 v5.227.12220.39754) */
BEGIN
   FOR IDX
      IN (SELECT ACTUAL_LOAN_AC_NUM,
                 IACLINK_CIF_NUMBER CURRENT_CLIENT_CODE,
                 NEW_CLIENT_CODE,
                 PRODUCT_FOR_LOANS
            FROM LOAN_CLIENT_CODE_CHANGE, IACLINK, PRODUCTS
           WHERE     IACLINK_ENTITY_NUM = '1'
                   AND PRODUCT_CODE = IACLINK_PROD_CODE
                 AND STATUS IS NULL
                 AND ACTUAL_LOAN_AC_NUM = IACLINK_ACTUAL_ACNUM)
   LOOP
      IF IDX.PRODUCT_FOR_LOANS = '1'
      THEN
         SP_LOAN_CLIENT_CODE_CHANGE (IDX.ACTUAL_LOAN_AC_NUM,
                                     IDX.CURRENT_CLIENT_CODE,
                                     IDX.NEW_CLIENT_CODE);
      ELSE
         SP_SAVINGS_CLIENT_CODE_CHANGE (IDX.ACTUAL_LOAN_AC_NUM,
                                        IDX.CURRENT_CLIENT_CODE,
                                        IDX.NEW_CLIENT_CODE);
      END IF;
   END LOOP;

   UPDATE LOAN_CLIENT_CODE_CHANGE
      SET STATUS = '1'
    WHERE STATUS IS NULL;
END;