INSERT INTO LOANIAMRR
SELECT distinct 1 LOANIA_ENTITY_NUM,
       T.BRANCH_CODE LOANIA_BRN_CODE,
       I.IACLINK_INTERNAL_ACNUM LOANIA_ACNT_NUM,
       nvl(T.ACCRU_DATE,NPA_DATE) LOANIA_VALUE_DATE,
       nvl(T.ACCRU_DATE,NPA_DATE) LOANIA_ACCRUAL_DATE,
       NULL LOANIA_PREV_ACCR_DATE,
       'BDT' LOANIA_ACNT_CURR,
       NULL LOANIA_ACNT_BAL,
       (-1) * ABS (NVL(T.ACCRU_AMNT,0)) LOANIA_TOTAL_NEW_INT_AMT,
       0.000 LOANIA_INT_ON_AMT,
       0.000 LOANIA_OD_PORTION,
       0 LOANIA_TOTAL_NEW_OD_INT_AMT,
       T.INT_RATE LOANIA_INT_RATE,
       0 LOANIA_SLAB_AMT,
       0 LOANIA_OD_INT_RATE,
       0 LOANIA_LIMIT,
       0 LOANIA_DP,
       (-1) * ABS (NVL(T.ACCRU_AMNT,0)) LOANIA_INT_AMT,
       (-1) * ABS (NVL(T.ACCRU_AMNT,0)) LOANIA_INT_AMT_RND,
       0 LOANIA_OD_INT_AMT,
       0 LOANIA_OD_INT_AMT_RND,
       CASE
          WHEN ASSETCLSH_ASSET_CODE = 'UC' THEN 0
          WHEN ASSETCLSH_ASSET_CODE = 'SM' THEN 0
          ELSE 1
       END
          LOANIA_NPA_STATUS,
       0 LOANIA_NPA_AMT,
       0 LOANIA_NPA_INT_POSTED_AMT,
       0 LOANIA_ARR_INT_AMT
  FROM BACKUPTABLE.ACC7 T, IACLINK I, ASSETCLSHIST
 WHERE     I.IACLINK_ACTUAL_ACNUM = T.ACC_NO
       AND IACLINK_INTERNAL_ACNUM = ASSETCLSH_INTERNAL_ACNUM
      -- AND ASSETCLSH_AUTH_BY = 'MIG'
       AND ASSETCLSH_ENTITY_NUM = 1 and IACLINK_ENTITY_NUM=1
       and  IACLINK_INTERNAL_ACNUM not  in(SELECT LOANIAMRR_ACNT_NUM
  FROM LOANIAMRR
 WHERE     LOANIAMRR_ENTITY_NUM = 1
       AND LOANIAMRR_BRN_CODE = 36137
       AND LOANIAMRR_VALUE_DATE =
              TO_DATE ('01/20/2018 00:00:00', 'MM/DD/YYYY HH24:MI:SS')
       AND LOANIAMRR_ACNT_NUM IN
              (SELECT IACLINK_INTERNAL_ACNUM
                 FROM BACKUPTABLE.ACC7 T, IACLINK I, acnts
                WHERE     I.IACLINK_ACTUAL_ACNUM = T.ACC_NO
                      AND IACLINK_INTERNAL_ACNUM = ACNTS_INTERNAL_ACNUM
                      AND ACNTS_ENTITY_NUM = 1
                      AND IACLINK_ENTITY_NUM = 1))
                      
                      
          
       
       
       
       
       
       ------ 
 INSERT INTO LOANIAMRRDTL 
 SELECT 1 LOANIADTL_ENTITY_NUM,
       T.BRANCH_CODE LOANIADTL_BRN_CODE,
       I.IACLINK_INTERNAL_ACNUM LOANIADTL_ACNT_NUM,
       nvl(T.ACCRU_DATE,NPA_DATE) LOANIADTL_VALUE_DATE,
       nvl(T.ACCRU_DATE,NPA_DATE) LOANIADTL_ACCRUAL_DATE,
       1 LOANIADTL_SL_NUM,
       T.INT_RATE LOANIADTL_INT_RATE,
       (-1) * ABS (NVL(T.ACCRU_AMNT,0)) LOANIADTL_UPTO_AMT,
       (-1) * ABS (NVL(T.ACCRU_AMNT,0)) LOANIADTL_INT_AMT,
       (-1) * ABS (NVL(T.ACCRU_AMNT,0)) LOANIADTL_INT_AMT_RND
  FROM BACKUPTABLE.ACC7 T, IACLINK I
 WHERE I.IACLINK_ACTUAL_ACNUM = T.ACC_NO and IACLINK_ENTITY_NUM=1;
  
 
 
 
 ------------------------------------------
 BEGIN
   FOR idx
      IN (SELECT IACLINK_INTERNAL_ACNUM,
                 UPPER (CL_STATUS) CL_STATUS,
                 NPA_DATE,
                 NVL (t.NPA_DATE, ACNTS_OPENING_DATE) EFF_DATE
            FROM BACKUPTABLE.ACC7 T, IACLINK I, acnts
           WHERE     I.IACLINK_ACTUAL_ACNUM = T.ACC_NO
                 AND IACLINK_INTERNAL_ACNUM = ACNTS_INTERNAL_ACNUM
                 AND ACNTS_ENTITY_NUM = 1
                 AND IACLINK_ENTITY_NUM = 1)
   LOOP
      UPDATE ASSETCLS
         SET ASSETCLS_LATEST_EFF_DATE = idx.EFF_DATE,
             ASSETCLS_ASSET_CODE = idx.CL_STATUS,
             ASSETCLS_NPA_DATE = idx.NPA_DATE
       WHERE ASSETCLS_INTERNAL_ACNUM = idx.IACLINK_INTERNAL_ACNUM
       and ASSETCLS_ENTITY_NUM=1;
   END LOOP;
END;

 
SELECT 1 ASSETCLSH_ENTITY_NUM,
               ASSETCLS_INTERNAL_ACNUM ASSETCLSH_INTERNAL_ACNUM,
               ASSETCLS_LATEST_EFF_DATE ASSETCLSH_EFF_DATE,
               ASSETCLS_ASSET_CODE ASSETCLSH_ASSET_CODE,
               ASSETCLS_NPA_DATE ASSETCLSH_NPA_DATE,
               ASSETCLS_AUTO_MAN_FLG ASSETCLSH_AUTO_MAN_FLG,
               ASSETCLS_REMARKS ASSETCLSH_REMARKS,
               'MIG' ASSETCLSH_ENTD_BY,
               ASSETCLS_LATEST_EFF_DATE ASSETCLSH_ENTD_ON,
               NULL ASSETCLSH_LAST_MOD_BY,
               NULL ASSETCLSH_LAST_MOD_ON,
               'MIG' ASSETCLSH_AUTH_BY,
               ASSETCLS_LATEST_EFF_DATE ASSETCLSH_AUTH_ON,
               NULL TBA_MAIN_KEY,
               NULL ASSETCLSH_PURPOSE_FLAG,
               NULL ASSETCLSH_EXEMPT_END_DATE
          FROM BACKUPTABLE.ACC7 T,
               IACLINK I,
               acnts,
               ASSETCLS
         WHERE     I.IACLINK_ACTUAL_ACNUM = T.ACC_NO
               AND IACLINK_INTERNAL_ACNUM = ACNTS_INTERNAL_ACNUM
               AND ASSETCLS_INTERNAL_ACNUM = IACLINK_INTERNAL_ACNUM
               AND ASSETCLS_ASSET_CODE = 'UC'
               AND ACNTS_ENTITY_NUM = 1
               AND IACLINK_ENTITY_NUM = 1
               AND ASSETCLS_ENTITY_NUM = 1
               
               ------------------------------
               

-------VOUCHER PREPARATION------------------------
   INSERT INTO MANUAL_TRAN
  SELECT 1 SERIAL_NUMBER,
         ACNTS_BRN_CODE BRANCH_CODE,
         NULL PRODUCT_CODE,
         0 DEBIT_AC_NUMBER,
         0 CREDIT_AC_NUMBER,
         P.LNPRDAC_INT_ACCR_GL DEBIT_GL_NUMBER,
         P.LNPRDAC_INT_INCOME_GL CREDIT_GL_NUMBER,
         SUM (ABS (ACCRU_AMNT)) DEBIT_AMOUNT,
         SUM (ABS (ACCRU_AMNT)) CREDIT_AMOUNT,
         NULL BATCH_NUMBER,
         NULL ACNTS_CLOSER_DATE,
         '' NARATION,
         NULL CONTRACT_NUMBER,
         NULL INT_CHECK_PREF,
         NULL INT_CHECK_NUM,
         NULL INST_DATE,
         NULL BASE_CURR_CODE,
         NULL BASE_CURR_CONV_RATE,
         NULL TRAN_BASE_CURR_EQ_AMT
    FROM BACKUPTABLE.ACC7 T,
         IACLINK I,
         ASSETCLSHIST,
         LNPRODACPM P,
         ACNTS AA
   WHERE     I.IACLINK_ACTUAL_ACNUM = T.ACC_NO
         AND IACLINK_INTERNAL_ACNUM = ASSETCLSH_INTERNAL_ACNUM
         --AND ASSETCLSH_AUTH_BY = 'MIG'
         AND ASSETCLSH_ENTITY_NUM = 1
         AND AA.ACNTS_PROD_CODE = P.LNPRDAC_PROD_CODE
         AND ASSETCLSH_ASSET_CODE IN ('UC', 'SM')
         AND AA.ACNTS_ENTITY_NUM = 1
         AND AA.ACNTS_CLOSURE_DATE IS NULL
         AND I.IACLINK_INTERNAL_ACNUM = AA.ACNTS_INTERNAL_ACNUM
         AND I.IACLINK_INTERNAL_ACNUM NOT IN (SELECT L.LOANIA_ACNT_NUM
                                                FROM LOANIA L)
GROUP BY AA.ACNTS_PROD_CODE,
         P.LNPRDAC_INT_ACCR_GL,
         P.LNPRDAC_INT_INCOME_GL,
         ACNTS_BRN_CODE