/* Formatted on 10/14/2019 12:27:48 PM (QP5 v5.227.12220.39754) */
BEGIN
   FOR IDX
      IN (SELECT IACLINK_INTERNAL_ACNUM,
                 PERIODICAL_INT,
                 MATURITY_VALUE,
                 CONT_NUM,
                 INT_RATE
            FROM ACC5, IACLINK
           WHERE ACC_NO = IACLINK_ACTUAL_ACNUM AND IACLINK_ENTITY_NUM = 1)
   LOOP
      UPDATE PBDCONTRACT
         SET PBDCONT_STD_INT_RATE = IDX.INT_RATE,
             PBDCONT_ACTUAL_INT_RATE = IDX.INT_RATE,
             PBDCONT_MAT_VALUE = IDX.MATURITY_VALUE,
             PBDCONT_PERIODICAL_INT_AMT = IDX.PERIODICAL_INT
       WHERE     PBDCONT_ENTITY_NUM = 1
             AND PBDCONT_CONT_NUM = IDX.CONT_NUM
             AND PBDCONT_DEP_AC_NUM = IDX.IACLINK_INTERNAL_ACNUM;
   END LOOP;
END;