/* Formatted on 9/18/2023 3:48:14 PM (QP5 v5.388) */

--step1
CREATE TABLE DATACTRCONF_BKP
AS
    SELECT * FROM DATACTRCONF;


--step2
drop table DATACTRCONF ;
 

---step3
CREATE TABLE DATACTRCONF
(
    DATACTRCONF_ID             VARCHAR2 (10 BYTE),
    DATACTRCONF_DESC           VARCHAR2 (50 BYTE),
    DATACTRCONF_COND           VARCHAR2 (300 BYTE),
    DATACTRCONF_C_DTYP         VARCHAR2 (20 BYTE),
    DATACTRCONF_RLVDATA        VARCHAR2 (300 BYTE),
    DATACTRCONF_RLVQRY         VARCHAR2 (1250 BYTE),
    DATACTRCONF_UPDDATA        VARCHAR2 (300 BYTE),
    DATACTRCONF_UPDQRY         VARCHAR2 (1250 BYTE),
    DATACTRCONF_DTTYPE         VARCHAR2 (20 BYTE),
    DATACTRCONF_MANDOPT        VARCHAR2 (20 BYTE),
    DATACTRCONF_BRN_QRY        VARCHAR2 (1250 BYTE),
    DATACTRCONF_BRNQ_DTP       VARCHAR2 (20 BYTE),
    DATACTRCONF_ACTIVE         CHAR (1 BYTE),
    DATACTRCONF_VAL            VARCHAR2 (3000 BYTE),
    DATACTRCONF_BRNLIST_NUM    NUMBER (6)
)
TABLESPACE TBFES
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 64 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE;

--step4
drop index PK_DATACTRCONF;


---step5
CREATE UNIQUE INDEX PK_DATACTRCONF
    ON DATACTRCONF (DATACTRCONF_ID)
    LOGGING
    TABLESPACE TBFES
    PCTFREE 10
    INITRANS 2
    MAXTRANS 255
    STORAGE (INITIAL 64 K
             NEXT 1 M
             MINEXTENTS 1
             MAXEXTENTS UNLIMITED
             PCTINCREASE 0
             BUFFER_POOL DEFAULT);
             
             
---step6
ALTER TABLE DATACTRCONF
    ADD (
        CONSTRAINT PK_DATACTRCONF PRIMARY KEY (DATACTRCONF_ID)
            USING INDEX PK_DATACTRCONF ENABLE VALIDATE);



---step7
INSERT INTO DATACTRCONF
    SELECT DATACTRCONF_ID,
           DATACTRCONF_DESC,
           DATACTRCONF_COND,
           DATACTRCONF_C_DTYP,
           DATACTRCONF_RLVDATA,
           DATACTRCONF_RLVQRY,
           DATACTRCONF_UPDDATA,
           DATACTRCONF_UPDQRY,
           DATACTRCONF_DTTYPE,
           DATACTRCONF_MANDOPT,
           DATACTRCONF_BRN_QRY,
           DATACTRCONF_BRNQ_DTP,
           DATACTRCONF_ACTIVE,
           NULL     DATACTRCONF_VAL,
           DATACTRCONF_BRNLIST_NUM
      FROM DATACTRCONF_bkp;

COMMIT;
