/* Formatted on 1/9/2023 3:23:55 PM (QP5 v5.388) */
BEGIN
    FOR IDX
        IN (SELECT IACLINK_INTERNAL_ACNUM, REPAY_FREQ
              FROM ACC4, IACLINK
             WHERE IACLINK_ENTITY_NUM = 1 AND IACLINK_ACTUAL_ACNUM = ACC_NO)
    LOOP
        UPDATE LNACMIS
           SET LNACMIS_HO_DEPT_CODE = IDX.REPAY_FREQ ---, LNACMIS_NATURE_BORROWAL_AC = 99
         WHERE LNACMIS_INTERNAL_ACNUM = IDX.IACLINK_INTERNAL_ACNUM;

        UPDATE LNACMISHIST
           SET LNACMISH_HO_DEPT_CODE = IDX.REPAY_FREQ
         WHERE     LNACMISH_ENTITY_NUM = 1
               AND LNACMISH_INTERNAL_ACNUM = IDX.IACLINK_INTERNAL_ACNUM
               AND LNACMISH_EFF_DATE =
                   (SELECT MAX (LNACMISH_EFF_DATE)
                     FROM LNACMISHIST
                    WHERE     LNACMISH_ENTITY_NUM = 1
                          AND LNACMISH_INTERNAL_ACNUM =
                              IDX.IACLINK_INTERNAL_ACNUM);
    END LOOP;
END;