INSERT INTO BACKUPTABLE.MOBILE_GP
SELECT ROWNUM + 3197295 ROW_NO, MOBILE_NUMBER
  FROM MOBILEREG
 WHERE     (MOBILE_NUMBER LIKE '017%' OR MOBILE_NUMBER LIKE '013%')
       AND MOBILE_NUMBER NOT IN (SELECT MOBILE_NUMBER
                                   FROM BACKUPTABLE.MOBILE_GP)
       AND ENTITY_NUM = 1;
       

INSERT INTO BACKUPTABLE.MOBILE_BLINK
SELECT ROWNUM + 698777 ROW_NO, MOBILE_NUMBER
  FROM MOBILEREG
 WHERE     (MOBILE_NUMBER LIKE '019%' OR MOBILE_NUMBER LIKE '014%')
       AND MOBILE_NUMBER NOT IN (SELECT MOBILE_NUMBER
                                   FROM BACKUPTABLE.MOBILE_BLINK)
       AND ENTITY_NUM = 1;
       

INSERT INTO BACKUPTABLE.MOBILE_ROBI_AIRTEL
SELECT ROWNUM + 724390 ROW_NO, MOBILE_NUMBER
  FROM MOBILEREG
 WHERE     (MOBILE_NUMBER LIKE '018%' OR MOBILE_NUMBER LIKE '016%')
       AND MOBILE_NUMBER NOT IN (SELECT MOBILE_NUMBER
                                   FROM BACKUPTABLE.MOBILE_ROBI_AIRTEL)
       AND ENTITY_NUM = 1;
       
       
       
INSERT INTO BACKUPTABLE.MOBILE_TELETALK
SELECT ROWNUM + 77915 ROW_NO, MOBILE_NUMBER
  FROM MOBILEREG
 WHERE     (MOBILE_NUMBER LIKE '015%')
       AND MOBILE_NUMBER NOT IN (SELECT MOBILE_NUMBER
                                   FROM BACKUPTABLE.MOBILE_TELETALK)
       AND ENTITY_NUM = 1;
        