BEGIN
   FOR IDX IN (SELECT * FROM ACC4)
   LOOP
      UPDATE INDCLIENTS
         SET INDCLIENT_TEL_GSM = IDX.ACC_TYPE
       WHERE INDCLIENT_CODE = IDX.ACCOUNT_NUMBER;

      UPDATE ADDRDTLS
         SET ADDRDTLS_MOBILE_NUM = IDX.ACC_TYPE
       WHERE ADDRDTLS_SOURCE_KEY = IDX.ACCOUNT_NUMBER;
   END LOOP;
END;