
BEGIN
   FOR IDX
      IN (SELECT T.NEW_CLCODE, ACC4.MOBILE_NUMBER
            FROM ACC4, TEMP_CLIENT T
           WHERE     ACC4.BRANCH_CODE = T.BRN_CODE
                 AND ACC4.CLIENT_CODE = T.OLD_CLCODE)
   LOOP
      UPDATE INDCLIENTS I
         SET I.INDCLIENT_TEL_GSM = IDX.MOBILE_NUMBER
       WHERE I.INDCLIENT_CODE = IDX.NEW_CLCODE;

      UPDATE ADDRDTLS A
         SET A.ADDRDTLS_MOBILE_NUM = IDX.MOBILE_NUMBER
       WHERE A.ADDRDTLS_SOURCE_KEY = IDX.NEW_CLCODE;
   END LOOP;
END;