/*Few manual tasks after the Half-yearend of June 2020.*/

CREATE OR REPLACE PROCEDURE SBLPROD.SP_TESTLOAN_INT_REV_COVID(P_BRN_CODE NUMBER ) IS
P_BATCH_NUM  VARCHAR2(1000);
P_ERRMSG     VARCHAR2(1000);
 BEGIN
   -- DBMS_DEBUG_JDWP.CONNECT_TCP( '10.10.25.20', 4000 );
   PKG_EODSOD_FLAGS.PV_PROCESS_NAME      := 'PKG_LNINTREVERSE_COVID.START_BRNWISE';
   PKG_EODSOD_FLAGS.PV_USER_ID           := '42894';
   PKG_EODSOD_FLAGS.PV_CALLED_BY_EOD_SOD := 1;
   PKG_EODSOD_FLAGS.PV_EODSODFLAG        := 'E';
   pkg_eodsod_flags.PV_PREVIOUS_DATE     := '29-JUN-2020';
   PKG_EODSOD_FLAGS.PV_CURRENT_DATE      := '30-JUN-2020';
   PKG_LNINTREVERSE_COVID.START_BRNWISE(1,P_BRN_CODE); 

  DBMS_OUTPUT.PUT_LINE(PKG_EODSOD_FLAGS.PV_ERROR_MSG);
 END SP_TESTLOAN_INT_REV_COVID;
/

CREATE OR REPLACE PROCEDURE SBLPROD.SP_GEN_REVERSAL_COVID (
   P_FROM_BRN    NUMBER,
   P_TO_BRN      NUMBER)
IS
   V_CBD           DATE;
   P_ERROR_MSG     VARCHAR2 (1000);
   V_DUMMY_COUNT   NUMBER;
   V_ASON_DATE     DATE;
BEGIN
   V_ASON_DATE := TRUNC (SYSDATE)-1 ;

 -- V_ASON_DATE := '09-APR-2020';

   FOR IDX IN (  SELECT *
                   FROM (  SELECT BRANCH_CODE, ROWNUM BRANCH_SL
                             FROM MIG_DETAIL
                         ORDER BY BRANCH_CODE)
                  WHERE BRANCH_SL BETWEEN P_FROM_BRN AND P_TO_BRN
               ORDER BY BRANCH_CODE)
   LOOP
       

      SP_TESTLOAN_INT_REV_COVID (IDX.BRANCH_CODE );
      COMMIT ;
   END LOOP;

 
END SP_GEN_REVERSAL_COVID;
/


CREATE OR REPLACE PROCEDURE SBLPROD.SP_GEN_REVERSAL_COVID_THREAD AS
  LN_DUMMY NUMBER;
BEGIN
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_REVERSAL_COVID(1,100); end;',instance=>1);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_REVERSAL_COVID(101,200); end;',instance=>1);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_REVERSAL_COVID(201,300); end;',instance=>1);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_REVERSAL_COVID(301,400); end;',instance=>1);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_REVERSAL_COVID(401,500); end;',instance=>1);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_REVERSAL_COVID(501,600); end;',instance=>1);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_REVERSAL_COVID(601,700); end;',instance=>2);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_REVERSAL_COVID(701,800); end;',instance=>2);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_REVERSAL_COVID(801,900); end;',instance=>2);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_REVERSAL_COVID(901,1000); end;',instance=>2);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_REVERSAL_COVID(1001,1100); end;',instance=>2);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_REVERSAL_COVID(1101,1200); end;',instance=>2);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_REVERSAL_COVID(1201,1300); end;',instance=>2); 
  COMMIT;
END SP_GEN_REVERSAL_COVID_THREAD;
/



CREATE OR REPLACE PROCEDURE SBLPROD.SP_TESTLOAN_INT_REV_COVID_ST(P_BRN_CODE NUMBER ) IS
P_BATCH_NUM  VARCHAR2(1000);
P_ERRMSG     VARCHAR2(1000);
 BEGIN
   -- DBMS_DEBUG_JDWP.CONNECT_TCP( '10.10.25.20', 4000 );
   PKG_EODSOD_FLAGS.PV_PROCESS_NAME      := 'PKG_LNINTREVERSE_COVID_ST.START_BRNWISE';
   PKG_EODSOD_FLAGS.PV_USER_ID           := '42894';
   PKG_EODSOD_FLAGS.PV_CALLED_BY_EOD_SOD := 1;
   PKG_EODSOD_FLAGS.PV_EODSODFLAG        := 'E';
   pkg_eodsod_flags.PV_PREVIOUS_DATE     := '29-JUN-2020';
   PKG_EODSOD_FLAGS.PV_CURRENT_DATE      := '30-JUN-2020';
   PKG_LNINTREVERSE_COVID_ST.START_BRNWISE(1,P_BRN_CODE); 

  DBMS_OUTPUT.PUT_LINE(PKG_EODSOD_FLAGS.PV_ERROR_MSG);
 END SP_TESTLOAN_INT_REV_COVID_ST;
/

CREATE OR REPLACE PROCEDURE SBLPROD.SP_GEN_REVERSAL_COVID_ST (
   P_FROM_BRN    NUMBER,
   P_TO_BRN      NUMBER)
IS
   V_CBD           DATE;
   P_ERROR_MSG     VARCHAR2 (1000);
   V_DUMMY_COUNT   NUMBER;
   V_ASON_DATE     DATE;
BEGIN
   V_ASON_DATE := TRUNC (SYSDATE)-1 ;

 -- V_ASON_DATE := '09-APR-2020';

   FOR IDX IN (  SELECT *
                   FROM (  SELECT BRANCH_CODE, ROWNUM BRANCH_SL
                             FROM MIG_DETAIL
                         ORDER BY BRANCH_CODE)
                  WHERE BRANCH_SL BETWEEN P_FROM_BRN AND P_TO_BRN
               ORDER BY BRANCH_CODE)
   LOOP
       

      SP_TESTLOAN_INT_REV_COVID_ST (IDX.BRANCH_CODE );
      COMMIT ;
   END LOOP;

 
END SP_GEN_REVERSAL_COVID_ST;
/



CREATE OR REPLACE PROCEDURE SBLPROD.SP_GEN_REV_COVID_ST_THREAD AS
  LN_DUMMY NUMBER;
BEGIN
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_REVERSAL_COVID_ST(1,100); end;',instance=>1);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_REVERSAL_COVID_ST(101,200); end;',instance=>1);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_REVERSAL_COVID_ST(201,300); end;',instance=>1);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_REVERSAL_COVID_ST(301,400); end;',instance=>1);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_REVERSAL_COVID_ST(401,500); end;',instance=>1);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_REVERSAL_COVID_ST(501,600); end;',instance=>1);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_REVERSAL_COVID_ST(601,700); end;',instance=>2);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_REVERSAL_COVID_ST(701,800); end;',instance=>2);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_REVERSAL_COVID_ST(801,900); end;',instance=>2);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_REVERSAL_COVID_ST(901,1000); end;',instance=>2);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_REVERSAL_COVID_ST(1001,1100); end;',instance=>2);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_REVERSAL_COVID_ST(1101,1200); end;',instance=>2);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_REVERSAL_COVID_ST(1201,1300); end;',instance=>2); 
  COMMIT;
END SP_GEN_REV_COVID_ST_THREAD;
/






CREATE OR REPLACE PROCEDURE SP_TESTLOAN_LOAN_ACBAL_CALC IS
P_BATCH_NUM  VARCHAR2(1000);
P_ERRMSG     VARCHAR2(1000);
 BEGIN
   -- DBMS_DEBUG_JDWP.CONNECT_TCP( '10.10.25.20', 4000 );
   PKG_EODSOD_FLAGS.PV_PROCESS_NAME      := 'PKG_LOAN_ACBAL_CALC.SP_START_PROCESS2';
   PKG_EODSOD_FLAGS.PV_USER_ID           := '42894';
   PKG_EODSOD_FLAGS.PV_CALLED_BY_EOD_SOD := 1;
   PKG_EODSOD_FLAGS.PV_EODSODFLAG        := 'E';
   pkg_eodsod_flags.PV_PREVIOUS_DATE     := '29-JUN-2020';
   PKG_EODSOD_FLAGS.PV_CURRENT_DATE      := '30-JUN-2020';
   PKG_LOAN_ACBAL_CALC.SP_START_PROCESS(1,0); 

  DBMS_OUTPUT.PUT_LINE(PKG_EODSOD_FLAGS.PV_ERROR_MSG);
 END SP_TESTLOAN_LOAN_ACBAL_CALC;
/




CREATE OR REPLACE PROCEDURE SP_TESTLOAN_LNPROVCAL(P_BRN_CODE NUMBER ) IS
P_BATCH_NUM  VARCHAR2(1000);
P_ERRMSG     VARCHAR2(1000);
 BEGIN
   -- DBMS_DEBUG_JDWP.CONNECT_TCP( '10.10.25.20', 4000 );
   PKG_EODSOD_FLAGS.PV_PROCESS_NAME      := 'PKG_LNPROVCAL.START_BRNWISE_PROCESS2';
   PKG_EODSOD_FLAGS.PV_USER_ID           := '42894';
   PKG_EODSOD_FLAGS.PV_CALLED_BY_EOD_SOD := 1;
   PKG_EODSOD_FLAGS.PV_EODSODFLAG        := 'E';
   pkg_eodsod_flags.PV_PREVIOUS_DATE     := '29-JUN-2020';
   PKG_EODSOD_FLAGS.PV_CURRENT_DATE      := '30-JUN-2020';
   PKG_LNPROVCAL.START_BRNWISE_PROCESS(1,P_BRN_CODE); 

  DBMS_OUTPUT.PUT_LINE(PKG_EODSOD_FLAGS.PV_ERROR_MSG);
 END SP_TESTLOAN_LNPROVCAL;
/




CREATE OR REPLACE PROCEDURE SP_GEN_LNPROVCAL (
   P_FROM_BRN    NUMBER,
   P_TO_BRN      NUMBER)
IS
   V_CBD           DATE;
   P_ERROR_MSG     VARCHAR2 (1000);
   V_DUMMY_COUNT   NUMBER;
   V_ASON_DATE     DATE;
BEGIN
   V_ASON_DATE := TRUNC (SYSDATE)-1 ;

 -- V_ASON_DATE := '09-APR-2020';

   FOR IDX IN (  SELECT *
                   FROM (  SELECT BRANCH_CODE, ROWNUM BRANCH_SL
                             FROM MIG_DETAIL
                         ORDER BY BRANCH_CODE)
                  WHERE BRANCH_SL BETWEEN P_FROM_BRN AND P_TO_BRN
               ORDER BY BRANCH_CODE)
   LOOP
       

      SP_TESTLOAN_LNPROVCAL (IDX.BRANCH_CODE );
      COMMIT ;
   END LOOP;

 
END SP_GEN_LNPROVCAL;
/




CREATE OR REPLACE PROCEDURE SP_GEN_SP_GEN_LNPROVCAL_THREAD AS
  LN_DUMMY NUMBER;
BEGIN
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_TESTLOAN_LNPROVCAL(1,100); end;',instance=>1);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_TESTLOAN_LNPROVCAL(101,200); end;',instance=>1);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_TESTLOAN_LNPROVCAL(201,300); end;',instance=>1);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_TESTLOAN_LNPROVCAL(301,400); end;',instance=>1);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_TESTLOAN_LNPROVCAL(401,500); end;',instance=>1);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_TESTLOAN_LNPROVCAL(501,600); end;',instance=>1);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_TESTLOAN_LNPROVCAL(601,700); end;',instance=>2);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_TESTLOAN_LNPROVCAL(701,800); end;',instance=>2);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_TESTLOAN_LNPROVCAL(801,900); end;',instance=>2);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_TESTLOAN_LNPROVCAL(901,1000); end;',instance=>2);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_TESTLOAN_LNPROVCAL(1001,1100); end;',instance=>2);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_TESTLOAN_LNPROVCAL(1101,1200); end;',instance=>2);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_TESTLOAN_LNPROVCAL(1201,1300); end;',instance=>2); 
  COMMIT;
END SP_GEN_SP_GEN_LNPROVCAL_THREAD;
/




exec SP_GEN_REVERSAL_COVID_THREAD ;

EXEC SP_GEN_REV_COVID_ST_THREAD ;


EXEC SP_TESTLOAN_LOAN_ACBAL_CALC ;

EXEC SP_GEN_SP_GEN_LNPROVCAL_THREAD ;
