--- 1. Voucher preperation ------------------



INSERT INTO AUTOPOST_TRAN_TEMP
 SELECT 1 BATCH_SL,
       1 LEG_SL,
       (SELECT MN_CURR_BUSINESS_DATE FROM MAINCONT ) TRAN_DATE,
       (SELECT MN_CURR_BUSINESS_DATE FROM MAINCONT ) VALUE_DATE,
       '0' SUPP_TRAN,
       ACNTS_BRN_CODE BRN_CODE,
       ACNTS_BRN_CODE ACING_BRN_CODE,
       'D' DR_CR,
       LNPRDAC_INT_INCOME_GL GLACC_CODE,
       0 INT_AC_NO,
       0 CONT_NO,
       'BDT' CURR_CODE,
       SUM(ABS(L.LOANIAMRR_INT_AMT_RND)) AC_AMOUNT 
     FROM LOANIAMRR L, ACNTS A, LNPRODACPM P , LOANACNTS
 WHERE A.ACNTS_ENTITY_NUM = 1
   AND A.ACNTS_ENTITY_NUM = 1
   AND P.LNPRDAC_PROD_CODE = A.ACNTS_PROD_CODE
   AND A.ACNTS_INTERNAL_ACNUM = L.LOANIAMRR_ACNT_NUM
   AND A.ACNTS_BRN_CODE = L.LOANIAMRR_BRN_CODE
   AND A.ACNTS_PROD_CODE IN (2546, 2547)
   AND L.LOANIAMRR_NPA_STATUS = 0
   AND LNACNT_ENTITY_NUM = 1
   AND L.LOANIAMRR_ENTITY_NUM = 1
   --AND ACNTS_CLOSURE_DATE IS NULL 
   AND LNACNT_INTERNAL_ACNUM = L.LOANIAMRR_ACNT_NUM
   AND L.LOANIAMRR_VALUE_DATE > LNACNT_INT_ACCR_UPTO
 GROUP BY A.ACNTS_BRN_CODE,P.LNPRDAC_INT_INCOME_GL,P.LNPRDAC_INT_ACCR_GL HAVING SUM(ABS(L.LOANIAMRR_INT_AMT_RND)) >0 
 UNION ALL 
SELECT 1 BATCH_SL,
       1 LEG_SL,
       (SELECT MN_CURR_BUSINESS_DATE FROM MAINCONT ) TRAN_DATE,
       (SELECT MN_CURR_BUSINESS_DATE FROM MAINCONT ) VALUE_DATE,
       '0' SUPP_TRAN,
       ACNTS_BRN_CODE BRN_CODE,
       ACNTS_BRN_CODE ACING_BRN_CODE,
       'C' DR_CR,
       LNPRDAC_INT_ACCR_GL GLACC_CODE,
       0 INT_AC_NO,
       0 CONT_NO,
       'BDT' CURR_CODE,
       SUM(ABS(L.LOANIAMRR_INT_AMT_RND)) AC_AMOUNT 
     FROM LOANIAMRR L, ACNTS A, LNPRODACPM P, LOANACNTS
 WHERE A.ACNTS_ENTITY_NUM = 1
   AND A.ACNTS_ENTITY_NUM = 1
   AND P.LNPRDAC_PROD_CODE = A.ACNTS_PROD_CODE
   AND A.ACNTS_INTERNAL_ACNUM = L.LOANIAMRR_ACNT_NUM
   AND A.ACNTS_BRN_CODE = L.LOANIAMRR_BRN_CODE
   AND A.ACNTS_PROD_CODE IN (2546, 2547)
   AND L.LOANIAMRR_NPA_STATUS = 0
   AND LNACNT_ENTITY_NUM = 1
      AND L.LOANIAMRR_ENTITY_NUM = 1
   AND LNACNT_INTERNAL_ACNUM = L.LOANIAMRR_ACNT_NUM
   AND L.LOANIAMRR_VALUE_DATE > LNACNT_INT_ACCR_UPTO
 GROUP BY A.ACNTS_BRN_CODE,P.LNPRDAC_INT_INCOME_GL,P.LNPRDAC_INT_ACCR_GL HAVING SUM(ABS(L.LOANIAMRR_INT_AMT_RND)) >0 
ORDER BY BRN_CODE , DR_CR ;




BEGIN
   FOR IDX
      IN (SELECT ROW_NUMBER () OVER (PARTITION BY BRN_CODE ORDER BY BRN_CODE)
                    LEG_NO,
                 T.*
            FROM AUTOPOST_TRAN_TEMP T)
   LOOP
      UPDATE AUTOPOST_TRAN_TEMP
         SET LEG_SL = IDX.LEG_NO
       WHERE     TRAN_DATE = IDX.TRAN_DATE
             AND VALUE_DATE = IDX.VALUE_DATE
             AND BRN_CODE = IDX.BRN_CODE
             AND DR_CR = IDX.DR_CR
             AND AC_AMOUNT = IDX.AC_AMOUNT
             AND INT_AC_NO =IDX.INT_AC_NO;
   END LOOP;
END;


BEGIN
   FOR idx IN (SELECT ROWNUM r_num, t.*
                 FROM (  SELECT DISTINCT TRAN_DATE, BRN_CODE
                           FROM AUTOPOST_TRAN_TEMP
                       ORDER BY BRN_CODE) t)
   LOOP
      UPDATE AUTOPOST_TRAN_TEMP
         SET BATCH_SL = idx.r_num
       WHERE TRAN_DATE = idx.TRAN_DATE AND BRN_CODE = idx.BRN_CODE;
   END LOOP;
END;




TRUNCATE TABLE AUTOPOST_TRAN ;

INSERT INTO AUTOPOST_TRAN
SELECT T.*,
       T.AC_AMOUNT BC_AMOUNT,
       NULL PRINCIPAL,
       NULL INTEREST,
       NULL CHARGE,
       NULL INST_PREFIX,
       NULL INST_NUM,
       NULL INST_DATE,
       NULL IBR_GL,
       NULL ORIG_RESP,
       NULL CONT_BRN_CODE,
       NULL ADV_NUM,
       NULL ADV_DATE,
       NULL IBR_CODE,
       NULL CAN_IBR_CODE,
       'Accrual After 31-dec-2017 for product 2546,2547' LEG_NARRATION,
       'Accrual reversal for product 2546,2547' BATCH_NARRATION,
       'INTELECT' USER_ID,
       NULL TERMINAL_ID,
       NULL PROCESSED,
       NULL BATCH_NO,
       NULL ERR_MSG
  FROM AUTOPOST_TRAN_TEMP T;
  
  
SELECT * FROM AUTOPOST_TRAN ; 

exec SP_AUTO_SCRIPT_TRAN ;



--- 2. Data delete from LOANIAMRRDTL, LOANIAMRR, LOANIADLY ------------------







DELETE FROM LOANIAMRRDTL WHERE LOANIAMRRDTL_ENTITY_NUM = 1 
AND( LOANIAMRRDTL_BRN_CODE, LOANIAMRRDTL_ACNT_NUM, LOANIAMRRDTL_VALUE_DATE) IN (
SELECT ACNTS_BRN_CODE, L.LOANIAMRR_ACNT_NUM,L.LOANIAMRR_VALUE_DATE  
     FROM LOANIAMRR L, ACNTS A, LNPRODACPM P , LOANACNTS
 WHERE A.ACNTS_ENTITY_NUM = 1
   AND A.ACNTS_ENTITY_NUM = 1
   AND P.LNPRDAC_PROD_CODE = A.ACNTS_PROD_CODE
   AND A.ACNTS_INTERNAL_ACNUM = L.LOANIAMRR_ACNT_NUM
   AND A.ACNTS_BRN_CODE = L.LOANIAMRR_BRN_CODE
   AND A.ACNTS_PROD_CODE IN (2546, 2547)
   AND LNACNT_ENTITY_NUM = 1
   AND LNACNT_INTERNAL_ACNUM = L.LOANIAMRR_ACNT_NUM
   AND L.LOANIAMRR_VALUE_DATE > LNACNT_INT_ACCR_UPTO);
   
   
DELETE FROM LOANIAMRR LL WHERE LL.LOANIAMRR_ENTITY_NUM = 1 
AND( LL.LOANIAMRR_BRN_CODE, LL.LOANIAMRR_ACNT_NUM, LL.LOANIAMRR_VALUE_DATE) IN (
SELECT ACNTS_BRN_CODE, L.LOANIAMRR_ACNT_NUM,L.LOANIAMRR_VALUE_DATE  
     FROM LOANIAMRR L, ACNTS A, LNPRODACPM P , LOANACNTS
 WHERE A.ACNTS_ENTITY_NUM = 1
   AND A.ACNTS_ENTITY_NUM = 1
   AND P.LNPRDAC_PROD_CODE = A.ACNTS_PROD_CODE
   AND A.ACNTS_INTERNAL_ACNUM = L.LOANIAMRR_ACNT_NUM
   AND A.ACNTS_BRN_CODE = L.LOANIAMRR_BRN_CODE
   AND A.ACNTS_PROD_CODE IN (2546, 2547)
   AND LNACNT_ENTITY_NUM = 1
   AND LNACNT_INTERNAL_ACNUM = L.LOANIAMRR_ACNT_NUM
   AND L.LOANIAMRR_VALUE_DATE > LNACNT_INT_ACCR_UPTO); 
   
   
DELETE FROM LOANIADLY LL WHERE (LL.RTMPLNIA_BRN_CODE, LL.RTMPLNIA_ACNT_NUM, LL.RTMPLNIA_VALUE_DATE) IN (
SELECT ACNTS_BRN_CODE, L.RTMPLNIA_ACNT_NUM, L.RTMPLNIA_VALUE_DATE 
     FROM LOANIADLY L, ACNTS A, LNPRODACPM P , LOANACNTS
 WHERE A.ACNTS_ENTITY_NUM = 1
   AND A.ACNTS_ENTITY_NUM = 1
   AND P.LNPRDAC_PROD_CODE = A.ACNTS_PROD_CODE
   AND A.ACNTS_INTERNAL_ACNUM = L.RTMPLNIA_ACNT_NUM
   AND A.ACNTS_BRN_CODE = L.RTMPLNIA_BRN_CODE
   AND A.ACNTS_PROD_CODE IN (2546, 2547)
   AND LNACNT_ENTITY_NUM = 1
   AND LNACNT_INTERNAL_ACNUM = L.RTMPLNIA_ACNT_NUM
   AND L.RTMPLNIA_VALUE_DATE > LNACNT_INT_ACCR_UPTO
);













--- 3. Update LOANACNTS table ----------------------






UPDATE LOANACNTS
   SET LNACNT_RTMP_ACCURED_UPTO = NULL, LNACNT_RTMP_PROCESS_DATE = NULL
 WHERE     LNACNT_ENTITY_NUM = 1
       AND LNACNT_INTERNAL_ACNUM IN
              (SELECT A.ACNTS_INTERNAL_ACNUM
                 FROM ACNTS A
                WHERE     A.ACNTS_ENTITY_NUM = 1
                      AND A.ACNTS_PROD_CODE IN (2546, 2547)
                      AND ACNTS_CLOSURE_DATE IS NULL);
					  
					  

--- 4. Enable product level interest rate -------------------------
					  
					  
UPDATE LNACIRS SET LNACIRS_AC_LEVEL_INT_REQD = 0 WHERE LNACIRS_ENTITY_NUM = 1 AND LNACIRS_INTERNAL_ACNUM IN (                      
SELECT A.ACNTS_INTERNAL_ACNUM
                 FROM ACNTS A
                WHERE     A.ACNTS_ENTITY_NUM = 1
                      AND A.ACNTS_PROD_CODE IN (2546, 2547)
                      AND ACNTS_CLOSURE_DATE IS NULL) ;
                      
                      
UPDATE LNACIRSHIST SET LNACIRSH_AC_LEVEL_INT_REQD = 0 WHERE LNACIRSH_ENTITY_NUM = 1 AND LNACIRSH_INTERNAL_ACNUM IN (                      
SELECT A.ACNTS_INTERNAL_ACNUM
                 FROM ACNTS A
                WHERE     A.ACNTS_ENTITY_NUM = 1
                      AND A.ACNTS_PROD_CODE IN (2546, 2547)
                      AND ACNTS_CLOSURE_DATE IS NULL);
					  
					  
					  
--- Finish ----------------