ACASLL;ACASLLDTL;ACNTBAL;ACNTLINK;ACNTMAIL;ACNTOTN;ACNTOTNNEW;ACNTS;ADDRDTLS;ASSETCLS;ASSETCLSHIST;CLIENTNUM;CLIENTS;CORPCLIENTS;IACLINK;LIMFACCURRLIMITLINE;LIMITLINEAUX;LOANACHIST;LOANACNTS;LIMITLINEHIST;LIMITSERIAL;LLACNTOS;LNACAODHIST;LNACDISB;LNACDSDTL;LNACDSDTLHIST;LNACIR;LNACIRHIST;LNACIRS;LNACIRSHIST;LNACMIS;LNACMISHIST;LOANACHIST;LOANACNTS;TEMP_CLIENT;limitline;LIMFACCURR;NOMREG;NOMREGDTL;



select count(*)  from SPDOCIMAGE;
select count(*) from  CLAMIMAGE;
select count(*) from  	INVSPDOCIMG  ;