/* Formatted on 12/29/2021 5:40:48 PM (QP5 v5.252.13127.32867) */
SELECT CLIENTS_HOME_BRN_CODE,
       MBRN_NAME,
       CLIENTS_CODE,CLIENTS_NAME,
       CLIENTS_TYPE_FLG,
       CLIENTS_EXEMP_IN_TDS,
       CLIENTS_EXEMP_TDS_PER
  FROM CLIENTS, MBRN
 WHERE     CLIENTS_CODE IN (SELECT ACNTS_CLIENT_NUM
                              FROM ACNTS
                             WHERE     ACNTS_ENTITY_NUM = 1
                                   AND ACNTS_AC_TYPE = 'SBST')
       AND NVL (CLIENTS_EXEMP_IN_TDS, 0) = '1'
       AND NVL (CLIENTS_EXEMP_TDS_PER, 0) <> 0
       AND CLIENTS_HOME_BRN_CODE = MBRN_CODE