--1. upload data from xls file to IBR_TRAN_MANUAL  

--2. run the script below to update the IBR_CODE and CONTRA_ACNT_INT_NUM :

--3. EXCEL AMOUNT FEILD SHOULD BE NUMBER;
INSERT INTO AUTOPOST_TRAN
SELECT    DENSE_RANK () OVER (ORDER BY CONT_BRN_CODE) BATCH_SL,
          ROW_NUMBER () OVER (PARTITION BY CONT_BRN_CODE ORDER BY CONT_BRN_CODE) LEG_SL,
            TRAN_DATE,
            VALUE_DATE,
             SUPP_TRAN,
           BRN_CODE,
           ACING_BRN_CODE,
         DR_CR,
           GLACC_CODE,
            INT_AC_NO,
            CONT_NO,
           CURR_CODE,
            AC_AMOUNT,
            BC_AMOUNT,
            PRINCIPAL,
            INTEREST,
            CHARGE,
            INST_PREFIX,
            INST_NUM,
            INST_DATE,
            IBR_GL,
            ORIG_RESP,
            CONT_BRN_CODE,
            ADV_NUM,
            ADV_DATE,
            IBR_CODE,
            CAN_IBR_CODE,
           LEG_NARRATION,
            BATCH_NARRATION,
            USER_ID,
            TERMINAL_ID,
            PROCESSED,
            BATCH_NO,
            ERR_MSG,
            DEPT_CODE
          
 FROM (  SELECT  1 BATCH_SL,
           1 LEG_SL,
          null TRAN_DATE,
          null VALUE_DATE,
          null  SUPP_TRAN,
         TRAN_BRN_CODE BRN_CODE,
         TRAN_BRN_CODE ACING_BRN_CODE,
       'D'  DR_CR,
         CONTRA_GL GLACC_CODE,
         null  INT_AC_NO,
         null  CONT_NO,
        null  CURR_CODE,
          AMOUNT AC_AMOUNT,
          AMOUNT BC_AMOUNT,
          NULL PRINCIPAL,
          NULL INTEREST,
          NULL CHARGE,
          NULL INST_PREFIX,
          NULL INST_NUM,
          NULL INST_DATE,
          NULL IBR_GL,
          NULL ORIG_RESP,
          CONTRA_BRN_CODE CONT_BRN_CODE,
          NULL ADV_NUM,
          NULL ADV_DATE,
          NULL IBR_CODE,
          NULL CAN_IBR_CODE,
         NARRATION LEG_NARRATION,
          NARRATION BATCH_NARRATION,
          'INTELECT' USER_ID,
          NULL TERMINAL_ID,
          NULL PROCESSED,
          NULL BATCH_NO,
          NULL ERR_MSG,
          99184 DEPT_CODE
     FROM IBR_TRAN_MANUAL TT
     UNION ALL
      SELECT  1 BATCH_SL,
            1 LEG_SL,
          null TRAN_DATE,
          null VALUE_DATE,
          null  SUPP_TRAN,
         TRAN_BRN_CODE BRN_CODE,
         TRAN_BRN_CODE ACING_BRN_CODE,
        'C' DR_CR,
         '216101101' GLACC_CODE,
         null  INT_AC_NO,
         null  CONT_NO,
        null  CURR_CODE,
          AMOUNT AC_AMOUNT,
          AMOUNT BC_AMOUNT,
          NULL PRINCIPAL,
          NULL INTEREST,
          NULL CHARGE,
          NULL INST_PREFIX,
          NULL INST_NUM,
          NULL INST_DATE,
          1 IBR_GL,
          ORIG_RESP ORIG_RESP,
          CONTRA_BRN_CODE CONT_BRN_CODE,
          ADVICE_NUM ADV_NUM,
          ADVICE_DATE ADV_DATE,
          IBR_CODE IBR_CODE,
          IBR_CODE CAN_IBR_CODE,
         NARRATION LEG_NARRATION,
          NARRATION BATCH_NARRATION,
          'INTELECT' USER_ID,
          NULL TERMINAL_ID,
          NULL PROCESSED,
          NULL BATCH_NO,
          NULL ERR_MSG,
          99184 DEPT_CODE
     FROM IBR_TRAN_MANUAL TT);


EXEC   	SP_AUTO_SCRIPT_TRAN	;
