INSERT INTO MV_LOAN_ACCOUNT_BAL
SELECT /*+ USE_MERGE(TR,T) PARALLEL(16) */
      A.ACNTS_ENTITY_NUM,
       A.ACNTS_BRN_CODE,
       TRAN_INTERNAL_ACNUM,
       TRAN_AMOUNT,
       TRANADV_INTRD_AC_AMT,
       TRANADV_INTRD_BC_AMT,
       TRANADV_CHARGE_BC_AMT,
       TRAN_DB_CR_FLG,
       TRAN_DATE_OF_TRAN,
       TRAN_VALUE_DATE
  FROM TRANADV2017 T,
       TRAN2017 TR,
       LOANACNTS L,
       ACNTS A
 WHERE     TRANADV_BRN_CODE = TRAN_BRN_CODE
       AND TRAN_DATE_OF_TRAN = TRANADV_DATE_OF_TRAN
       AND TRANADV_BATCH_NUMBER = TRAN_BATCH_NUMBER
       AND TRANADV_BATCH_SL_NUM = TRAN_BATCH_SL_NUM
       --AND ACNTS_GLACC_CODE = TRAN_GLACC_CODE
       AND L.LNACNT_INTERNAL_ACNUM = TR.TRAN_INTERNAL_ACNUM
       AND L.LNACNT_INTERNAL_ACNUM = A.ACNTS_INTERNAL_ACNUM
       AND A.ACNTS_INTERNAL_ACNUM = TR.TRAN_INTERNAL_ACNUM
       AND TR.TRAN_ENTITY_NUM = A.ACNTS_ENTITY_NUM
       AND TRANADV_ENTITY_NUM = A.ACNTS_ENTITY_NUM
       AND L.LNACNT_ENTITY_NUM = A.ACNTS_ENTITY_NUM
       AND TRAN_VALUE_DATE >=
              TRUNC (NVL (L.LNACNT_INT_ACCR_UPTO, A.ACNTS_OPENING_DATE),
                     'MM')
       AND TRAN_AUTH_ON IS NOT NULL
       and tr.tran_entd_by = 'MIG'
       AND A.ACNTS_CLOSURE_DATE IS NULL
