select   USER_ID, USER_NAME,URPGMAR_PGM_ID
from URPGMAR ,users
where trim(URPGMAR_USER_ID)=USER_ID;



select  UROLE_CODE, UROLE_DESCN,URPGMAR_PGM_ID
from URPGMAR ,USERROLES
where trim(UROLE_CODE)=URPGMAR_ROLE_CODE;

URPGMAR  