/* Formatted on 5/27/2021 11:57:03 AM (QP5 v5.252.13127.32867) */
SELECT USER_ID,
       USER_NAME,
       USERLOCKLOG_DATE,
       USERLOCKLOG_LOCK_REASON,
       USERLOCKLOG_IP_ADDRESS,
       USERLOCKLOG_LOCK_BY,
       USERLOCKLOG_LOCK_REL_BY LOCK_RELEASE_BY,
       USERLOCKLOG_LOCK_REL_ON LOCK_RELEASE_ON
  FROM USERLOCKLOG, users
 WHERE USERLOCKLOG_USER_ID = USER_ID AND USERLOCKLOG_USER_ID = '35247'