SELECT TRFSTAFF_USER_ID,
       TRFSTAFF_EFF_DATE,
       CASE TRFSTAFF_TRF_TYPE
          WHEN 'D' THEN 'Deputation'
          WHEN 'P' THEN 'Permanant'
          ELSE '0'
       END
          TRANSFER_TYPE,
       TRFSTAFF_TRF_FROM_BRN FROM_BRN_CODE,
       (SELECT MBRN_NAME
          FROM MBRN
         WHERE MBRN_CODE = TRFSTAFF_TRF_FROM_BRN)
          FROM_BRN_NAME,
       TRFSTAFF_TRF_TO_BRN TO_BRN_CODE,
       (SELECT MBRN_NAME
          FROM MBRN
         WHERE MBRN_CODE = TRFSTAFF_TRF_TO_BRN)
          TO_BRN_NAME,
       TRFSTAFF_REASON1,
       TRFSTAFF_REASON2,
       TRFSTAFF_REASON3,
       TRFSTAFF_ENTD_BY,
       TRFSTAFF_ENTD_ON,
       TRFSTAFF_AUTH_BY,
       TRFSTAFF_AUTH_ON
  FROM TRFSTAFF
 WHERE TRFSTAFF_USER_ID in ('41544')
 ORDER BY TRFSTAFF_EFF_DATE ASC;
 
 ----------------user disable information----------------------
 EDIT  EMPSUSPREL  WHERE  EMPSUSPREL_USER_ID = '41544' ;
 EDIT  EMPSUSPREV  ;