INSERT INTO MANUAL_TRAN_SIN_MULTI
SELECT 1 VOUTURE_NUMBER,
       IACLINK_BRN_CODE BRANCH_CODE,
       IACLINK_INTERNAL_ACNUM DEBIT_AC_NUMBER,
       0 CREDIT_AC_NUMBER,
       'L' PRODUCT_TYPE,
       'P' LOAN_TRAN_ACTION,
       0 DEBIT_GL_NUMBER,
       0 CREDIT_GL_NUMBER,
       DR_AMOUNT DEBIT_AMOUNT,
       0 CREDIT_AMOUNT,
       NULL BATCH_NUMBER,
       'LOAN AC BALANCE CORRECTION |Issue|21033' NARATION,
       NULL ERROR_MESSAGE
  FROM acc4, iaclink
 WHERE DR_ACC_NO = IACLINK_ACTUAL_ACNUM
 AND IACLINK_ENTITY_NUM=1
 UNION ALL
 SELECT 1 VOUTURE_NUMBER,
       IACLINK_BRN_CODE BRANCH_CODE,
       0 DEBIT_AC_NUMBER,
       IACLINK_INTERNAL_ACNUM CREDIT_AC_NUMBER,
       'L' PRODUCT_TYPE,
       'I' LOAN_TRAN_ACTION,
       0 DEBIT_GL_NUMBER,
       0 CREDIT_GL_NUMBER,
       0 DEBIT_AMOUNT,
       CR_AMOUNT CREDIT_AMOUNT,
       NULL BATCH_NUMBER,
       'LOAN AC BALANCE CORRECTION |Issue|21033' NARATION,
       NULL ERROR_MESSAGE
  FROM acc4, iaclink
 WHERE CR_ACC_NO = IACLINK_ACTUAL_ACNUM
 AND IACLINK_ENTITY_NUM=1