/* Formatted on 12/30/2019 1:44:46 PM (QP5 v5.227.12220.39754) */
SELECT ACNTS_BRN_CODE,
       CLCHGWAIVDT_CLIENT_NUM CLIENT_CODE,
       NULL CLIENTS_NAME,
       FACNO (1, ACNTS_INTERNAL_ACNUM) ACCOUNT_NO,
       ACNTS_AC_NAME1 || ACNTS_AC_NAME2 ACCOUNT_NAME,
       CLCHGWAIVDT_CHARGE_CODE CHARGE_CODE,
       CHGCD_CHARGE_DESCN CHARGE_DESCN,
       CLCHGWAIVDT_LATEST_EFF_DATE EFF_DATE,
       CASE
          WHEN CLCHGWAIVDT_WAIVER_TYPE = 'F' THEN 'FULL'
          WHEN CLCHGWAIVDT_WAIVER_TYPE = 'P' THEN 'PARTIAL'
       END
          WAIVER_TYPE,
       CASE
          WHEN CLCHGWAIVDT_WAIVER_TYPE = 'P' THEN CLCHGWAIVDT_DISCOUNT_PER
          ELSE 100
       END
          DISCOUNT_PERTANCE
  FROM CLCHGWAIVEDTL,
       CLCHGWAIVER,
       ACNTS,
       CHGCD
 WHERE                           --CLCHGWAIVDT_CLIENT_NUM=CLCHGWAIV_CLIENT_NUM
      CLCHGWAIVDT_INTERNAL_ACNUM = CLCHGWAIV_INTERNAL_ACNUM
       AND ACNTS_INTERNAL_ACNUM = CLCHGWAIVDT_INTERNAL_ACNUM
       -- AND  ACNTS_CLIENT_NUM=CLCHGWAIVDT_CLIENT_NUM
       AND CHGCD_CHARGE_CODE = CLCHGWAIVDT_CHARGE_CODE
        AND CLCHGWAIV_WAIVE_REQD=1
       AND ACNTS_BRN_CODE = :P_BRN_CODE
       AND ACNTS_ENTITY_NUM = 1
UNION ALL
SELECT CLIENTS_HOME_BRN_CODE ACNTS_BRN_CODE,
       CLIENTS_CODE CLIENT_CODE,
       CLIENTS_NAME,
       NULL ACCOUNT_NO,
       NULL ACCOUNT_NAME,
       CLCHGWAIVDT_CHARGE_CODE CHARGE_CODE,
       CHGCD_CHARGE_DESCN CHARGE_DESCN,
       CLCHGWAIVDT_LATEST_EFF_DATE EFF_DATE,
       CASE
          WHEN CLCHGWAIVDT_WAIVER_TYPE = 'F' THEN 'FULL'
          WHEN CLCHGWAIVDT_WAIVER_TYPE = 'P' THEN 'PARTIAL'
       END
          WAIVER_TYPE,
       CASE
          WHEN CLCHGWAIVDT_WAIVER_TYPE = 'P' THEN CLCHGWAIVDT_DISCOUNT_PER
          ELSE 100
       END
          DISCOUNT_PERTANCE
  FROM CLCHGWAIVEDTL,
       CLCHGWAIVER,
       CLIENTS,
       CHGCD
 WHERE     CLCHGWAIVDT_CLIENT_NUM = CLCHGWAIV_CLIENT_NUM
       -- CLCHGWAIVDT_INTERNAL_ACNUM = CLCHGWAIV_INTERNAL_ACNUM
       -- AND ACNTS_INTERNAL_ACNUM = CLCHGWAIVDT_INTERNAL_ACNUM
       AND CLIENTS_CODE = CLCHGWAIVDT_CLIENT_NUM
       AND CLCHGWAIV_WAIVE_REQD=1
       AND CHGCD_CHARGE_CODE = CLCHGWAIVDT_CHARGE_CODE
       AND CLIENTS_HOME_BRN_CODE = :P_BRN_CODE