BEGIN
   BEGIN
      FOR IND
         IN (SELECT A.ACNTEXCAMT_ENTITY_NUM EXCISE_ENTITY_NUM,
                    A.ACNTEXCAMT_INTERNAL_ACNUM EXCISE_INTERNAL_ACNUM,
                    A.ACNTEXCAMT_BRN_CODE EXCISE_BRN_CODE,
                    A.ACNTEXCAMT_EXCISE_AMT
               FROM ACNTEXCISEAMT A, ACNTEXCISEAMT_RECALC R
              WHERE     ACNTEXCAMT_FIN_YEAR = 2020
                    AND A.ACNTEXCAMT_ENTITY_NUM = R.EXCISE_ENTITY_NUM
                    AND A.ACNTEXCAMT_BRN_CODE = R.EXCISE_BRN_CODE)
      LOOP
         UPDATE ACNTEXCISEAMT_RECALC
            SET ACNTEXCAMT_EXCISE_AMT = IND.ACNTEXCAMT_EXCISE_AMT
          WHERE     EXCISE_ENTITY_NUM = IND.EXCISE_ENTITY_NUM
                AND EXCISE_BRN_CODE = IND.EXCISE_BRN_CODE
                AND EXCISE_INTERNAL_ACNUM = IND.EXCISE_INTERNAL_ACNUM;
      END LOOP;

      COMMIT;
   END;

   SP_EXCISE_AMOUNT_CALCULATE;
   ---SP_EXCISE_DUTY_2020;
END;
/