SELECT COUNT(*) FROM MIG_DETAIL WHERE MIG_END_DATE <= TRUNC(SYSDATE) -1

--> Total Branches:         

SELECT COUNT(CLIENTS_CODE)  FROM CLIENTS  WHERE  ( TRUNC(CLIENTS_AUTH_ON) <= TRUNC(SYSDATE) -1  OR TRUNC(CLIENTS_ENTD_ON) <= TRUNC(SYSDATE) -1  )  

--> No of Clients (C, I, J):  

SELECT COUNT(ACNTS_INTERNAL_ACNUM ) NO_OF_ACCOUNTS_ACTIVE , COUNT(DISTINCT ACNTS_CLIENT_NUM)  NO_OF_CLIENTS 
FROM ACNTS  WHERE ACNTS_CLOSURE_DATE IS NULL  AND
 ( TRUNC(ACNTS_ENTD_ON) <= TRUNC(SYSDATE) -1   OR TRUNC(ACNTS_AUTH_ON) <= TRUNC(SYSDATE) -1 )
 
--> No of Accounts (active): 
--> No of Clients          :  


SELECT  A.ACNTS_PROD_CODE, COUNT(A.ACNTS_INTERNAL_ACNUM)  
 FROM ACNTS A 
WHERE  A.ACNTS_CLOSURE_DATE IS NULL 
AND A.ACNTS_PROD_CODE IN (1000, 1005, 1020, 1030 )
AND A.ACNTS_OPENING_DATE <=  TRUNC(SYSDATE) -1
GROUP BY A.ACNTS_PROD_CODE 
ORDER BY A.ACNTS_PROD_CODE 

1000 :
1005 :
1020 :
1030 : 

SELECT  COUNT(A.ACNTS_ACCOUNT_NUMBER)   SOD_ACC
FROM ACNTS A, PRODUCTS P
WHERE A.ACNTS_PROD_CODE = P.PRODUCT_CODE
     AND A.ACNTS_CLOSURE_DATE IS NULL
     AND P.PRODUCT_FOR_LOANS = '1'
     AND P.PRODUCT_FOR_RUN_ACS = '1'  
     --AND PRODUCT_FOR_DEPOSITS = '1'
     --AND PRODUCT_FOR_RUN_ACS = '0'
     AND A.ACNTS_OPENING_DATE <=  TRUNC(SYSDATE) -1;

SOD_ACC: 


SELECT COUNT(DDPOISSDTL_DAY_SL) FROM DDPOISSDTL  
WHERE   TRUNC(DDPOISSDTL_ISSUE_DATE)  BETWEEN  TO_DATE('01-JAN-2017', 'DD-MON-RRRR')  AND TRUNC(SYSDATE) -1

--> No of DDPO issued:

SELECT   COUNT(TRAN_BATCH_NUMBER) FROM TRAN2017  
 WHERE   TRUNC(TRAN_DATE_OF_TRAN) <=  TRUNC(SYSDATE) -1

--> No of transactions: 

SELECT COUNT(USER_ID )  FROM USERS  WHERE TRIM(USER_SUSP_REL_FLAG) IS NULL  AND --USER_LOCKED_FLAG = 0 AND 
( TRUNC(USER_AUTH_ON) <= TRUNC(SYSDATE)  OR TRUNC(USER_ENTD_ON) <= TRUNC(SYSDATE)  )
 
--> No of registered users: 

SELECT MAX(CONN_USER) FROM 
(
    SELECT  SIGN_EFF_DATE, COUNT(DISTINCT SIGN_USER_ID) CONN_USER
       FROM  SIGNINOUT
    WHERE  SIGN_EFF_DATE   BETWEEN  TO_DATE('24-NOV-2017') AND TO_DATE('28-NOV-2017') 
    GROUP BY SIGN_EFF_DATE
)

-->  Avg. Number of Users logged in daily basis :


SELECT  SODEODLOG_FORM_NAME, SODEODLOG_START_DATE, SODEODLOG_END_DATE, 
               SODEODLOG_PROC_FLG||'   '||SODEODLOG_USER_ID||'   '|| SODEODLOG_ERR_DESCN  FLG_USER_ERR
  FROM SODEODLOG
WHERE SODEODLOG_DATE  = TO_DATE('11/30/2017', 'MM/DD/YYYY')
     AND SODEODLOG_FLG = 'E' 
ORDER BY SODEODLOG_RUN_SL, SODEODLOG_PROCESS_SL ;


SELECT   SODEODLOG_FORM_NAME, SODEODLOG_START_DATE, SODEODLOG_END_DATE, 
               SODEODLOG_PROC_FLG||'   '||SODEODLOG_USER_ID||'   '|| SODEODLOG_ERR_DESCN  FLG_USER_ERR
  FROM SODEODLOG
WHERE SODEODLOG_DATE  = TO_DATE('12/01/2017', 'MM/DD/YYYY')
     AND SODEODLOG_FLG = 'S'
--ORDER BY SODEODLOG_RUN_SL DESC, SODEODLOG_PROCESS_SL DESC  
ORDER BY SODEODLOG_RUN_SL, SODEODLOG_PROCESS_SL ;
 
--> Attached the XL files for EOM, SOM.
