TRUNCATE TABLE TERM_LOAN_DATA;

TRUNCATE TABLE CONTNIOUS_LOAN_DATA ;



EXEC SP_GEN_MIS_DEP_DATA_THREAD ;

EXEC SP_GEN_MIS_DEP_DATA_THREAD_2 ;


SELECT COUNT(DISTINCT SUBSTR(ACNTS_INTERNAL_ACNUM,2,5) ) FROM CONTNIOUS_LOAN_DATA;

SELECT COUNT(DISTINCT SUBSTR(ACNTS_INTERNAL_ACNUM,2,5) ) FROM TERM_LOAN_DATA;



UPDATE CONTNIOUS_LOAN_DATA SET SLAB = 1 WHERE SLAB IS NULL ;

UPDATE TERM_LOAN_DATA SET SLAB = 1 WHERE SLAB IS NULL ;



DELETE FROM CONTNIOUS_LOAN_DATA WHERE SLAB = 6 AND TOTAL_OUTSTANDING = 0;

SELECT DISTINCT FACNO(1,ACNTS_INTERNAL_ACNUM), SANCTION_AMOUNT FROM CONTNIOUS_LOAN_DATA WHERE SLAB = 6 AND SANCTION_AMOUNT >= 5000000000 ;

DELETE FROM CONTNIOUS_LOAN_DATA WHERE SLAB = 6 AND SANCTION_AMOUNT >= 5000000000 ;



  SELECT ACNT_YEAR,
         SLAB,
         COUNT (*),
         ROUND(SUM (SANCTION_AMOUNT)/10000000,2) SANCTION_AMOUNT,
         ROUND(SUM (DISBURSEMENT_AMOUNT)/10000000,2) DISBURSEMENT_AMOUNT,
         ROUND(SUM (PRINCIPAL_OS)/10000000,2) PRINCIPAL_OS,
         ROUND(SUM (INTEREST_OS)/10000000,2) INTEREST_OS,
         ROUND(SUM (CHARGES_AMOUNT)/10000000,2) CHARGES_AMOUNT,
         ROUND(SUM (TOTAL_OUTSTANDING)/10000000,2) TOTAL_OUTSTANDING,
         ROUND(SUM (APPLIED_INTEREST)/10000000,2) APPLIED_INTEREST,
         ROUND(SUM (APPLIED_CHARGES)/10000000,2) APPLIED_CHARGES,
         ROUND(SUM (RECOVERED_PRINCIPAL)/10000000,2) RECOVERED_PRINCIPAL,
         ROUND(SUM (RECOVERED_INTEREST)/10000000,2) RECOVERED_INTEREST,
         ROUND(SUM (RECOVERED_CHARGES)/10000000,2) RECOVERED_CHARGES
    FROM TERM_LOAN_DATA
GROUP BY ACNT_YEAR, SLAB
ORDER BY ACNT_YEAR DESC, SLAB;


  SELECT ACNT_YEAR,
         SLAB,
         COUNT (*),
         ROUND(SUM (SANCTION_AMOUNT)/10000000,2) SANCTION_AMOUNT,
         --SUM(DISBURSEMENT_AMOUNT) DISBURSEMENT_AMOUNT,
         ROUND(SUM (PRINCIPAL_OS)/10000000,2) PRINCIPAL_OS,
         ROUND(SUM (INTEREST_OS)/10000000,2) INTEREST_OS,
         ROUND(SUM (CHARGES_AMOUNT)/10000000,2) CHARGES_AMOUNT,
         ROUND(SUM (TOTAL_OUTSTANDING)/10000000,2) TOTAL_OUTSTANDING,
         ROUND(SUM (APPLIED_INTEREST)/10000000,2) APPLIED_INTEREST,
         ROUND(SUM (APPLIED_CHARGES)/10000000,2) APPLIED_CHARGES,
         ROUND(SUM (RECOVERED_PRINCIPAL)/10000000,2) RECOVERED_PRINCIPAL,
         ROUND(SUM (RECOVERED_INTEREST)/10000000,2) RECOVERED_INTEREST,
         ROUND(SUM (RECOVERED_CHARGES)/10000000,2) RECOVERED_CHARGES,
         SUM (IS_OS_GR_SANC) IS_OS_GR_SANC,
         ROUND(SUM (IS_OS_GR_SANC_OS)/10000000,2) IS_OS_GR_SANC_OS
    FROM CONTNIOUS_LOAN_DATA
GROUP BY ACNT_YEAR, SLAB
ORDER BY ACNT_YEAR DESC, SLAB;